### ISSUE TITLE
Character refresh bug

### ISSUE THREAD

**Issue by zaneroman** [overextended/ox_inventory#1000]
While pressing "R" key, the character is been refreshed. If the inventory is stopped, it's been stopped working. So, kindly do help me to fix this error.

**Comment by thelindat** [comment]
Dude what

**Comment by zaneroman** [comment]
> Dude what

Yes, That's the thing.

**Comment by thelindat** [comment]
> > Dude what
> 
> Yes, That's the thing.

I still don’t know what the thing is, because the original post is an amalgamation of words that individually have great meaning, but fall apart when places in the order you used them.

Try explaining what the actual issue you’re experiencing is so we can all go about our days.

**Comment by zaneroman** [comment]
> > > Dude what
> > 
> > 
> > Yes, That's the thing.
> 
> I still don’t know what the thing is, because the original post is an amalgamation of words that individually have great meaning, but fall apart when placed in the order you used them.
> 
> Try explaining what the actual issue you’re experiencing is so we can all go about our days.

Actually, if we press "R" key, the character is refreshed. If the inventory script is stopped and if we press "R" button, It ain't getting refreshed. So this is the issue!

**Comment by thelindat** [comment]
> if we press "R" key, the character is refreshed

WHAT DOES THIS MEAN?

> If the inventory script is stopped and if we press "R" button, It ain't getting refreshed

So you expect R to "refresh your character" but when you press R it isn't "refreshing your character". Now explain _what the fuck_ is "refreshing"_ in this context, how does that relate to the inventory system.

**Comment by zaneroman** [comment]
> 

I'm not expecting that thing to be happened. And refresh means, the player is getting revived while pressing "R" button. So this is the issue.

**Comment by thelindat** [comment]
Waste of my god damn time.

Go point out the code that "revives your player"; and how does "refresh my character" translate to being revived? Christ.

**Comment by thelindat** [comment]
Ox inventory does not revive, no clip, or whatever other weird shit people want to claim it does. The only thing it will do when reloading is just that - reload your weapon.

If you’re “dead” (but actually not dead) it’ll do it; but no clip or disappearing for a moment is just - huh?
