### ISSUE TITLE
weapon license ox_inventory

### ISSUE THREAD

**Issue by nemaDev** [overextended/ox_inventory#1001]
esx_license has been updated. and licenses are no longer saved in the table when you buy a weapon license
![image](https://user-images.githubusercontent.com/28969108/204654041-f5222bae-4254-4377-a074-0d3b0e6196b4.png)
![image](https://user-images.githubusercontent.com/28969108/204654087-a6e4fea6-c056-4374-9df6-f2391f83a566.png)
![image](https://user-images.githubusercontent.com/28969108/204654130-401d0278-ae3a-4854-88ca-c301abd6022d.png)

https://github.com/esx-framework/esx-legacy/compare/f52f0c1cc085...fc74695c166f

**Comment by thelindat** [comment]
Did you try adding it to the licenses table?

**Comment by nemaDev** [comment]
of course when i manually put the license in the table it works, but when i buy it it doesn't work. i had to go back to the previous version of esx_license after the last one and then it works again.

**Comment by thelindat** [comment]
I'm saying the _licenses_ table, not *user_licenses*.

**Comment by nemaDev** [comment]
no I have not tried

**Comment by nemaDev** [comment]
![image](https://user-images.githubusercontent.com/28969108/204680007-352f88c9-10dd-4e9d-8cb8-c008eb16b2cb.png)
you were absolutely right, I had not added the line in licenses, problem solved thanks bestia

**Comment by thelindat** [comment]
Closing since not really a bug, just lack of a weapon license by default for ESX and the recent update now validates license types.
