### ISSUE TITLE
Stash Issue

### ISSUE THREAD

**Issue by Draco-Fahad** [overextended/ox_inventory#1007]
ACTUALLY I

Sir Iam Using ox inventory for storage
When i save items in esx_property(stash) my item got stored in sql with no problem.. even after server restart

but after sometime in a running server like after 14 hours my items automatically wiped and i checked the sql the Name has changed >> for example : like from property-11 to property-1111 automatically.

**Comment by ilveopensource** [comment]
ox-inventory only supports automatic restarts

**Comment by Draco-Fahad** [comment]
Without Doing Restart Stashes Clear Automatically.  in a running server like after 14 hours my items automatically wiped and i checked the sql the Name has changed >> for example : like from property-11 to property-1111 automatically. Its an Issue With Stash Export
