### ISSUE TITLE
Truck not working

### ISSUE THREAD

**Issue by ilveopensource** [overextended/ox_inventory#1009]
**Describe the bug**
Tried changing hotkey of secondary inventory many times but in any vehicle I cannot open the truck. 

**To Reproduce**
1. Go near a vehicle or inside
2. Click the keybind set in config
3. Nothing happens to me

**Expected behavior**
Checked server console and client console and it's clear no errors no prompt.

**Screenshots**
No screenshot available since I can't see the truck

**Additional context**
.

**Comment by N-fire** [comment]
Check your keybind in your client parameter.

**Comment by ilveopensource** [comment]
> Check your keybind in your client parameter.

I fixed it by changing the name of the addKeybind function. It's not the first time that using a name make keybind not working, maybe I'm not understanding something? or it's a ox_lib issue?

**Comment by N-fire** [comment]
Fivem client keep the first keybind you need yo change it in your client. That's normal behavior, not related to ox_lib. (That's why I stick with default keybind has much as possible)
