### ISSUE TITLE
Crafting options are incorrectly enabled when required items are missing

### ISSUE THREAD

**Issue by edwardexo** [overextended/ox_inventory#1011]
After confiscating an inventory, the crafting options don't become disabled (the UI shows like you still have the required materials).

**Steps to reproduce the behavior:**
1. Set up a crafting bench (have the required ingredient in your inventory).
2. Open the crafting bench.
3. See that the crafting option is correctly enabled (colorful).
4. Confiscate your inventory with `exports.ox_inventory:ConfiscateInventory()`
5. Open the crafting bench again

**Expected behavior**
The crafting option should now be disabled (as you don't have the required item(s) anymore).

![9HH1TBt](https://user-images.githubusercontent.com/118666903/205498372-fc06fc1d-ec9c-47d5-a096-dc7f0f9d8ea9.png)

**Actual behaviour**
The crafting option stays incorrectly enabled, even though you don't have the required ingredients.
![image](https://user-images.githubusercontent.com/118666903/205498407-5a5e89ac-4114-42b6-bd84-f44b2e2ba585.png)

**Note:** You won't be actually able to craft the item, as you'll get the 'You can not perform this action' error.

**Comment by thelindat** [comment]
Are you confiscating the inventory while it's open on the client? I can't imagine a case where you would just randomly be confiscating it but sure we can probably trigger a re-render..

**Comment by edwardexo** [comment]
The issue also occurs when you confiscate it while the inventory is closed.
