### ISSUE TITLE
Player ped refreshes when reloading

### ISSUE THREAD

**Issue by JusTheDomas** [overextended/ox_inventory#1020]
**Describe the bug**
Weird thing happen when I try to reload, my char seems to reload, weapons unequip when I press R button, but when I change my reload keybinding to something else, it reloads just fine.

**To Reproduce**
Press R button

**Expected behavior**
Reload weapon

**Screenshots**
Quick video I made: https://streamable.com/sfoof1

**Additional context**
I'm not sure if this is a bug, or I need to disable something to stop this from happening. 

inventory.cfg I use:
```
# Activate specific event handlers and functions (supported: ox, esx, qb, nd)
setr inventory:framework "esx"

# Load specific language file from data/locales
setr ox:locale "en"

# Number of slots for player inventories
setr inventory:slots 30

# Maximum carry capacity for players, in grams (will be automatically converted to kilograms in-game)
setr inventory:weight 30000

# Weapons will reload after reaching 0 ammo
setr inventory:autoreload true

# Weapons must be aimed before shooting
setr inventory:aimedfiring true

# Blur the screen while accessing the inventory
setr inventory:screenblur true

# Trim whitespace from vehicle plates when checking owned vehicles
setr inventory:trimplate true

# Integrated support for qtarget/ox_target stashes, shops, etc
# Note: qtarget is deprecated, a future update may drop support (ox_target only, or gated features)
setr inventory:target true

# Default hotkeys to access primary and secondary inventories, and hotbar
setr inventory:keys ["F2", "Y", "TAB"]

# Enable control action when inventory is open
setr inventory:enablekeys [249]

# Show a list of all nearby players when giving items
setr inventory:giveplayerlist false

# Jobs with access to police armoury, evidence lockers, etc
setr inventory:police ["police", "aras"]

# The URL to load item images from
setr inventory:imagepath "nui://ox_inventory/web/images"

# Logging via ox_lib (0: Disable, 1: Standard, 2: Include AddItem/RemoveItem, and all shop purchases)
set inventory:loglevel 1

# Item prices fluctuate in shops
set inventory:randomprices true

# Compare current version to latest release on GitHub
set inventory:versioncheck true

# Loot will randomly generate inside unowned vehicles and dumpsters
set inventory:randomloot true

# Minimum job grade to remove items from evidence lockers
set inventory:evidencegrade 3

# Stashes will be wiped after remaining unchanged for the given time
set inventory:clearstashes "6 MONTH"

# Set the contents of randomly generated inventories
# [item name, minimum, maximum, loot chance]
set inventory:vehicleloot [
    ["cola", 1, 1],
    ["water", 1, 1],
    ["garbage", 1, 2, 50],
    ["panties", 1, 1, 5],
    ["money", 1, 50],
    ["money", 200, 400, 5],
    ["bandage", 1, 1]
]

set inventory:dumpsterloot [
    ["bottle", 1, 1],
    ["negyvas_tlf", 1, 1],
    ["metalas", 1, 2],
    ["metalspring", 1, 1],
    ["money", 1, 50],
    ["rubber", 1, 1],
    ["lockpick", 1, 1],
    ["plastic", 1, 1],
    ["elektronika", 1, 1],
    ["mikroschema", 1, 1],
    ["trigger", 1, 1]
]

# Set datadog API key for inventory logging (https://app.datadoghq.com/organization-settings/api-keys)
#set datadog:key ""

# Set server intake (https://docs.datadoghq.com/api/latest/logs/#send-logs)
#set datadog:site "datadoghq.com"

# Set server hostname
#set datadog:hostname "FXServer"
```

**Comment by thelindat** [comment]
See also https://github.com/overextended/ox_inventory/issues/1000 - so the three of you are using _god knows what_ which somehow conflicts with the inventory and causes the player to, as you annoyingly and confusingly put it, "reload".

@zaneroman @jdubstx @JusTheDomas figure out what you're using in common, aside from ox_inventory which isn't directly causing it.

**Comment by JusTheDomas** [comment]
> See also #1000 - so the three of you are using _god knows what_ which somehow conflicts with the inventory and causes the player to, as you annoyingly and confusingly put it, "reload".
> 
> @zaneroman @jdubstx @JusTheDomas figure out what you're using in common, aside from ox_inventory which isn't directly causing it.
> 
> Also a good idea to determine if it's caused by _pressing R_ or by _using ammo_.

When I stop ox_inventory and press R nothing happens like it should.

**Comment by thelindat** [comment]
That's very nice, but you're free to look at what pressing "R" does and there's nothing there to cause what is described; furthermore it's three people out of thousands reporting the problem.

**Comment by thelindat** [comment]
> ```
> RegisterCommand('reload', function()
> 	local ped = PlayerPedId()
> 	local hp  = GetEntityHealth(ped)
> 	ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin, jobSkin)
> 		local isMale = skin.sex == 0
> 		TriggerEvent('skinchanger:loadDefaultModel', isMale, function()
> 			ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
> 				TriggerEvent('skinchanger:loadSkin', skin)
> 				TriggerEvent('esx:restoreLoadout')
> 			end)
> 		end)
> 	end)
> 	SetEntityHealth(ped, hp)
> 	ESX.UI.Menu.CloseAll()
> 	SetNuiFocus(false, false)
> 	ClearPedTasks(ped)
> end, false)
> ```

The reload command used in ox inventory was changed a couple months ago to +reloadweapon so it may have been blocking that other reload command previously. Though you said stopping the script prevented that command from running which is odd.

**Comment by JusTheDomas** [comment]
> > ```
> > RegisterCommand('reload', function()
> > 	local ped = PlayerPedId()
> > 	local hp  = GetEntityHealth(ped)
> > 	ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin, jobSkin)
> > 		local isMale = skin.sex == 0
> > 		TriggerEvent('skinchanger:loadDefaultModel', isMale, function()
> > 			ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
> > 				TriggerEvent('skinchanger:loadSkin', skin)
> > 				TriggerEvent('esx:restoreLoadout')
> > 			end)
> > 		end)
> > 	end)
> > 	SetEntityHealth(ped, hp)
> > 	ESX.UI.Menu.CloseAll()
> > 	SetNuiFocus(false, false)
> > 	ClearPedTasks(ped)
> > end, false)
> > ```
> 
> The reload command used in ox inventory was changed a couple months ago to +reloadweapon so it may have been blocking that other reload command previously. Though you said stopping the script prevented that command from running which is odd.

![vaizdas_2022-12-09_142643783](https://user-images.githubusercontent.com/76823865/206702282-5a874431-a842-495b-9232-db28e0be2e56.png)
