### ISSUE TITLE
Have the choice of the number for craft

### ISSUE THREAD

**Issue by Nasdrov** [overextended/ox_inventory#1023]
Hello , if is possible please add the the possibility to have the choice of the number of items that we want to craft, without using the count = of the data but to be able to choose the exact number you want in craft. Thank you very much for your work.

**Comment by thelindat** [comment]
Let's say you have a recipe that costs `1 scrapmetal` and gives you `3 lockpicks`. How do you expect to craft _just_ 1 lockpick, or 5?
`count` is the amount you will receive from a single craft.

**Comment by Nasdrov** [comment]
with if possible the table in the middle (integer) which also allows you to choose the number of items that you buy or transfer. for example if the player wants to do this 5 repair kit he enters 5 in the middle table or with ox_lib (input) and crafts the 5 kits if he has the right number of items in his inventory (for example 10 scrap metal per kit he he will need 50 scrap). this is only a suggestion for improvement if possible of course. thanks

**Comment by thelindat** [comment]
Guess you missed my point and/or poorly explained what you _actually_ want, which is the ability to craft a recipe x times rather than _choosing how many items to craft_.

**Comment by Nasdrov** [comment]
Yes that's what I meant.
