### ISSUE TITLE
Crafting (esx)

### ISSUE THREAD

**Issue by TrentaSei** [overextended/ox_inventory#1024]

**Comment by N-fire** [comment]
Remove the entries in crafting.lua

**Comment by TrentaSei** [comment]
how? (sorry i don't have much experience in devving)

**Comment by N-fire** [comment]
You must be kidding...
Don't start a fivem server if you can't do something like that.
Ps: github issue are for bug report and suggestion if you want support ask in the discord.

**Comment by TrentaSei** [comment]
anyway how can i remove it?

**Comment by TrentaSei** [comment]
can u send me what i need to remove?
