### ISSUE TITLE
How can I update your scripts to the latest version without losing changes?

### ISSUE THREAD

**Issue by Justin2211** [overextended/ox_inventory#1025]
Good day, first of all a big praise to your ESX scripts, just great, but unfortunately I could not find out until now how to update the scripts without losing things like stores or items.

**Comment by Justin2211** [comment]
Isn't there a simpler solution?
I have some changes.

Is there not for example something like git pull and then that it replaces only the updates?

**Comment by eprimex** [comment]
You could use vscode to do it but it isn't that simple to setup

**Comment by N-fire** [comment]
> Isn't there a simpler solution? I have some changes.
> 
> Is there not for example something like git pull and then that it replaces only the updates?

Yes, clone the repo and pull when you want to update
If you want, but it's not necessery you can use a git client like gitkraken

**Comment by thelindat** [comment]
> Is there not for example something like git pull and then that it replaces only the updates?

you answered your own question
