### ISSUE TITLE
Trunk and glovebox not working

### ISSUE THREAD

**Issue by RAXIC7** [overextended/ox_inventory#1026]
Trunk and glovebox are not working I used the convertinventory command of the inventory but it still doesn't work how can I fix it.

![resim](https://user-images.githubusercontent.com/57269411/206916949-6531f2bd-2f2f-4152-b21f-f75e200b0ddc.png)

**Comment by N-fire** [comment]
Use the secondary inventory key (k by default)
PS: this is not a bug, please ask in the discord if you want support.

**Comment by RAXIC7** [comment]
It worked with the K key thanks.
