### ISSUE TITLE
Logger webhooks 

### ISSUE THREAD

**Issue by XianPT** [overextended/ox_inventory#1030]
**Good Morning.

First of all I would like to congratulate you on the incredible inventory!

My suggestion for improvement is that I believe that many people would like to have this option, to have inventory webhooks for better player control.

I know that there is an option to use datadog but not everyone knows how to work with it and there can't be many people who had the chance to pay for a datadog plan.
Try to think about it when putting up webhooks.**

Webhooks discord

**Comment by thelindat** [comment]
> Webhooks discord

no

> can't be many people who had the chance to pay for a datadog plan

14 day retention for free
or use self-hosted loki + grafana

i'm never supporting discord webhooks again

**Comment by XianPT** [comment]
anyway ok...

Just tell me how to find the player's steam id in the inventory.

**Comment by thelindat** [comment]
why would i store their steam id

**Comment by XianPT** [comment]
to be able to search the players

**Comment by XianPT** [comment]
Exemple 

steam id bought x of coke
