### ISSUE TITLE
Shop marker not working if target is true

### ISSUE THREAD

**Issue by Gregory-Hepicloud** [overextended/ox_inventory#1034]
**Describe the bug**
Create shop wihout target not working if setr inventory:target true in config

**To Reproduce**
1. Go to shop.lua
2. Create shop without option target or model
3. restart
4. See any shop show on map and no marker
5. go to ox config
6. disable setr inventory:target true to false
7. working but lost target stash dumster

Want marker shop for this store remove target list but shop stop working if no target set to false

no error log in client or server side

![image](https://user-images.githubusercontent.com/4592618/207568668-5e802554-67e7-426e-8f27-eceee9143778.png)
![image](https://user-images.githubusercontent.com/4592618/207568759-81077d1a-2a52-4120-9e8c-b1b1765522ad.png)

We use last version of all version of ox (2 day ago)

**Comment by Gregory-Hepicloud** [comment]
> that's how it works, yes

We want a workshop, with a marker system and some with a target system, but if only add locations, the shop does not work or if the target is displayed, but we want to type of shop is not possible ?

**Comment by thelindat** [comment]
Doing some cleaning up and this is a copy of #960, so closing.
