### ISSUE TITLE
CanCarryWeight doesn't exist, though it does in docs

### ISSUE THREAD

**Issue by DetErDugget** [overextended/ox_inventory#1038]
**Describe the bug**
CanCarryWeight function doesn't exist, though it does in docs ( https://overextended.github.io/docs/ox_inventory/Functions/Server/Inventory/CanCarryWeight )

**To Reproduce**
exports.ox_inventory:CanCarryWeight(inv, weight)

**Expected behavior**
A cb with weight :D

**Comment by TankGod726** [comment]
This isn't a bug and this issue can be closed as it most definitely exists https://github.com/overextended/ox_inventory/blob/main/modules/inventory/server.lua#L1062
