### ISSUE TITLE
special ammo

### ISSUE THREAD

**Issue by FozzySf5** [overextended/ox_inventory#1053]
after update, were not able to use the special ammo like hollowpoint and all that.  it wont reload, we use to put the gun away then take it back out to reload it but that dont work nomore. Or if it does work can u tell me how to reload the weapon with the special ammo installed

**Comment by SneakyAF** [comment]
Same issue. None of the special rounds work with custom magazines such as TRACER, INCENDIARY, ARMORPIERCING etc. Unless I'm doing soemthing wrong. Got the names from https://wiki.rage.mp/index.php?title=Weapons_Components#Assault_Rifle

**Comment by thelindat** [comment]
Does it work fine if reverting https://github.com/overextended/ox_inventory/commit/85e536d3549921fe56748eb850a5a541f11b443d?

**Comment by SneakyAF** [comment]
Does not look like it. Still unable to reload with the commit reverted

**Comment by FozzySf5** [comment]
yea, i can at least put the weapon back in my pocket and back out and its loaded
