### ISSUE TITLE
A clothes system to ui of inventory

### ISSUE THREAD

**Issue by Gojaneu** [overextended/ox_inventory#1059]
Would you mind adding something like this, I think it would be quite useful.

Image: ![image](https://user-images.githubusercontent.com/87229379/209358948-68505307-a614-49bf-8c85-fd7c3f054e30.png)

**Comment by Testaross** [comment]
Add it yourself most people don't want this

**Comment by Gojaneu** [comment]
> Add it yourself most people don't want this

it is true that many people want it

**Comment by Testaross** [comment]
Then make it
