### ISSUE TITLE
Crafting issue

### ISSUE THREAD

**Issue by FozzySf5** [overextended/ox_inventory#1069]
![image](https://user-images.githubusercontent.com/121222122/209741657-ef062ead-6ba2-4352-8d6b-ef261ddb6b0b.png)

i was making a repair weapons crafting station. it was working 2 updates ago and now it doesnt work. 

i added the weapon in the ingredients sections, which worked before and it doesnt now. i removed the weapon ingredient and it works just to craft a weapon but not take a weapon thats a item

**Comment by 0tto92** [comment]
remember to capitalize the names of the weapons. Maybe that will work
