### ISSUE TITLE
Automatic holster weapon on drive

### ISSUE THREAD

**Issue by IlMicioLetale** [overextended/ox_inventory#1070]
**Describe the bug**
When i drive and shot, when i finish the ammo on the charger the ped automatic holster the gun, any solution? thank you!

**To Reproduce**
1. Go to drive and shot fire

**Expected behavior**

**Screenshots**
(https://clipchamp.com/watch/zKuX95mNXvj)

**Additional context**

**Comment by thelindat** [comment]
That's default GTA behaviour, and the workaround I use never fails on my system.

**Comment by IlMicioLetale** [comment]
> That's default GTA behaviour, and the workaround I use never fails on my system.

can you tell me how to do?
