### ISSUE TITLE
Item icons config

### ISSUE THREAD

**Issue by TonybynMp4** [overextended/ox_inventory#1072]
**Is your feature request related to a problem? Please describe.**
An item's 'picture' is the image of the same name, wich mean if you have multiple items with the same image you'll have multiple copy of that image (wastes space when you have potentially hundreds of items, feels kinda unecessary)

**Describe the solution you'd like**
A config option of what image to use (as simple as a image = 'phone.png' for example)

**Comment by N-fire** [comment]
It's already possible with metadata.
Also if you use the same image you should probably create only one item with different metadata.

**Comment by TonybynMp4** [comment]
> It's already possible with metadata.

oh i didn't know that my bad lol
