### ISSUE TITLE
Improvements to Trash

### ISSUE THREAD

**Issue by 442516** [overextended/ox_inventory#1074]
I would like to say why we can't use the object to identify whether it is a trash can to search? We don't need to configure the coordinates of the trash can. Because the city is full of trash cans. If you change it to recognize objects. This will be very convenient. I don't need to configure coordinates, just search the bins at will. I can find valuable items inside that I really like to use. ox_inventory because he's awesome and cool. I hope you guys like this advice and take it, I think it's great advice. Supplementary explanation. I mean. Changed shrinking bins from not requiring coordinates to identifying objects. This way we don't need to configure bin coordinates. to search. Because there are too many trash cans in the city. I hope you can take my advice, thank you.

**Comment by thelindat** [comment]
It's already based on objects?

**Comment by 442516** [comment]
He's not object based and still needs to configure coordinates so I'm wondering if this can be improved? It would be great to have it because there are too many trash bins in the city and I need to configure new coordinates so he can search the trash. That would be cumbersome, it would be handy if it were object based. Because players want to be scavengers. This will be great. Hope to improve. I will develop a script that matches ox_inventory called Trash. I will take advantage. The ox_inventory feature allows players to sell items they find. This is great and hopefully can be done by improving the bins to identify objects. This way we won't need to configure new bins. He sounds great, right? I hope you can take my suggestion, thank you.

**Comment by thelindat** [comment]
..........................

> He's not object based

_It_ is based on models.

```lua
Inventory.Dumpsters = {218085040, 666561306, -58485588, -206690185, 1511880420, 682791951}
```

> needs to configure coordinates

No coordinates are set for bins.

**Comment by 442516** [comment]
I mean just make him based on the model without having to configure the coordinates and identify all the bins because the city bins. Everywhere This is cumbersome to configure because it's everywhere. It would be even better if this could be improved, hmm. Able to identify all litter boxes in the city. Now you should understand what I mean, right?

**Comment by thelindat** [comment]
> I mean just make him

_It_, not "him".

> based on the model

For the third time, it _is_ based on models.

> without having to configure the coordinates

Not a single coordinate is defined for a bin anywhere in this resource.
