### ISSUE TITLE
how we use the special ammo after fix

### ISSUE THREAD

**Issue by FozzySf5** [overextended/ox_inventory#1079]
?
 i have it as a item and it doesnt work still the way i had it before

**Comment by SneakyAF** [comment]
Hey, I was having the same issue as you before, however, after the latest update it works just fine. The first time you have to put the weapon away and take it out and after that, I'm able to reload the usual way.

Did the testing with fire ammo.

**Comment by FozzySf5** [comment]
> Hey, I was having the same issue as you before, however, after the latest update it works just fine. The first time you have to put the weapon away and take it out and after that, I'm able to reload the usual way.
> 
> Did the testing with fire ammo.

it showed the ammo being installed? so we put the ammo in like last time, put the gun away then back out?

**Comment by FozzySf5** [comment]
i cant even use the item i made for the ammo. how u get it to work?
