### ISSUE TITLE
SCRIPT ERROR: @esx_addoninventory/server/main.lua:9: No such export RegisterStash in resource ox_inventory

### ISSUE THREAD

**Issue by CrazedslawDev** [overextended/ox_inventory#1080]
**Describe the bug**
Every time the server is booted, Inventory doesnt work due to AddonInventory not being able to find the RegisterStash export. 

**To Reproduce**
1. Start server
2. See error

**Expected behavior**
for it to find the export in the inventory modules server.lua and work as intended from there on out

**Screenshots**
![gamer](https://user-images.githubusercontent.com/65857370/210254755-b31726fe-a616-400c-885d-030bf8a85b3e.PNG)
![gamer2](https://user-images.githubusercontent.com/65857370/210254863-1a1e5b72-b0ad-43c9-83dd-0ae23486fc77.PNG)
![gamer3](https://user-images.githubusercontent.com/65857370/210255009-37868613-0a1f-44a2-95a7-f0b48f94463b.PNG)

**Additional context**
Followed the installation instructions to a T, the order in which each of the scripts is started is correct in the resources.cfg, Ive tried adding the local variable of the exports table to esx_addoninventory to no avail, tried reinstalling all of the scripts to no avail. ox_inventory is untouched, as is ox_lib, oxmysql and ox_target

**Comment by CrazedslawDev** [comment]
i should also add that, in its current state its also breaking the functionality of mx-multicharacter so i feel like that could be the cause but realistically, addoninventory not being able to find RegisterStash in ox_inventory shouldnt really be related to mx-multicharacter

**Comment by thelindat** [comment]
If an export doesn't exist, either the resource doesn't exist, the resource hasn't fully started, the export literally doesn't exist, or something prevented the export from being created (i.e. an error). Not sure how you want me to help you fix something that works everywhere else.
