### ISSUE TITLE
WEAPON_SWEEPERSHOTGUN weapon item can not be equipped as a weapon.

### ISSUE THREAD

**Issue by wobozkyng** [overextended/ox_inventory#1081]
**Describe the bug**
The registered WEAPON_SWEEPERSHOTGUN item in weapon data, can not be equipped as a weapon when it is being used.

**To Reproduce**
1. Give player the item.
2. The item exist, appeared in inventory.
3. Use the item.
4. See the issue

**Expected behavior**
Can equip the weapon as I assumed WEAPON_SWEEPERSHOTGUN = WEAPON_AUTOSHOTGUN.

**Comment by TheFantomas** [comment]
Then create a pr that will rename the shutgun to WEAPON_AUTOSHOTGUN

**Comment by TheFantomas** [comment]
because WEAPON_SWEEPERSHOTGUN doesn´t exist
