### ISSUE TITLE
Crafting ingredients list not ordered according to defined order

### ISSUE THREAD

**Issue by Skryptific** [overextended/ox_inventory#1084]
**Describe the bug**
The list of ingredients is in a different order than defined in the data. This seems to be only happening with larger lists of ingredients.

**To Reproduce**
1. Open up data/crafting.lua and add a new item with around 5-6 ingredients to a crafting bench.
2. Check the item in the crafting bench in-game and check the ingredients.

**Expected behavior**
The list of ingredients ordered according to the defined order.

**Screenshots**
Output when printing ``data`` in ``modules/crafting/client.lua`` inside the ``createCraftingBench`` function.

![image](https://user-images.githubusercontent.com/48567607/210375405-18f21a74-3d41-4726-b3de-c214c4ac4e41.png)

Data defined in ``data/crafting.lua``.

![image](https://user-images.githubusercontent.com/48567607/210375428-e0ac4fa4-ad43-42ca-b8fe-aa8ee110af92.png)

**Additional context**
When creating a crafting brench in ``createCraftingBench`` the data seems to be already defined like in the first screenshot.

**Comment by thelindat** [comment]
Lua tables are unordered.

**Comment by Skryptific** [comment]
Fair point, didn't think of that. Would be nice to define the order in some way as an enhancement, but not a high priority I think.
