### ISSUE TITLE
Search with the policejob

### ISSUE THREAD

**Issue by Yan4nickk** [overextended/ox_inventory#1088]
Hello, since we started using the inventory, the police officers can no longer look into the players' pockets via the job menu. (Error on the screenshot)
Is that the inventory? If yes, can someone please help me

Thanks in advance

![image](https://user-images.githubusercontent.com/106911487/211169601-898bb961-0738-4c3d-af33-cf6161da4082.png)

**Comment by N-fire** [comment]
That's not a bug, you will have to use ox_inventory export for that.
https://overextended.github.io/docs/ox_inventory/Functions/Client/openNearbyInventory
If you need help ask in the discord.
Github issue are for bug report.
