### ISSUE TITLE
Problem when entering the server

### ISSUE THREAD

**Issue by LudiYoutuber65** [overextended/ox_inventory#1089]
![image](https://user-images.githubusercontent.com/67953605/211668683-09bec7cc-fa41-40ce-b19d-f3438b7c2f7f.png)
![image](https://user-images.githubusercontent.com/67953605/211668697-9250de3e-38ec-447b-bd8d-730605979df1.png)
![image](https://user-images.githubusercontent.com/67953605/211668711-ffc80997-b875-44f7-a4f2-6dd7b08656a1.png)
When I enter the server for the first time, it won't open my inventory and shows me these two errors, how to fix it?

**Comment by 96Manuel** [comment]
I too have this exact same problem. I have version 1.9 of esx, analyzing the problem it cannot find the function that we are going to call in es extended, in fact if we print it with a print it writes nil

**Comment by thelindat** [comment]
> ![image](https://user-images.githubusercontent.com/67953605/211668683-09bec7cc-fa41-40ce-b19d-f3438b7c2f7f.png) ![image](https://user-images.githubusercontent.com/67953605/211668697-9250de3e-38ec-447b-bd8d-730605979df1.png) ![image](https://user-images.githubusercontent.com/67953605/211668711-ffc80997-b875-44f7-a4f2-6dd7b08656a1.png) When I enter the server for the first time, it won't open my inventory and shows me these two errors, how to fix it?

I don't even know what version of ESX you're using, considering it's still using the async resource.

> I too have this exact same problem. I have version 1.9 of esx, analyzing the problem it cannot find the function that we are going to call in es extended, in fact if we print it with a print it writes nil

I just ran 1.9 and it works fine. Both of you need to look for errors at server startup rather than when a player joins.
