### ISSUE TITLE
Issues with returnInventory

### ISSUE THREAD

**Issue by humaniti** [overextended/ox_inventory#1091]
**Describe the bug**
Using the latest ESX legacy and OX_Inventory i'm experiencing this issue.
We are no longer getting Saved 1 inventory to DB after ConfiscateInventory on the server console.
In the database we see, that item inventory is saved.

https://i.imgur.com/9njLonK.png

Items are getting removed from the player, but after using ReturnInventory, nothing happens.

As I've tried to debug the issue, it seems the script stucks at

https://i.imgur.com/peRENjq.png

I'm still trying to debug the issue but i cannot figure out whats wrong. The only modification we did to ES_Extended that we are using Steam ID as identifier instead of Rockstar License.

**To Reproduce**
1. ConfiscateInventory
2. use ReturnInventory
3. Player Items are not getting back

**Expected behavior**

1. ConfiscateInventory
2. use ReturnInventory
3. Player are getting the items back.

**Comment by thelindat** [comment]
Confiscating and returning working completely fine.
```
/takeinv me
/returninv me
```
