### ISSUE TITLE
Weapon ammo Bug

### ISSUE THREAD

**Issue by DyroS3** [overextended/ox_inventory#1097]
**Describe the bug**
Weapons remaining bullets can not be synchronized with the last offline, the number of bullets will sometimes be more and sometimes less

**To Reproduce**
1. Emptying weapon bullets
2. Quit the server
3. Re-enter to server
4. After that, weapon bullets will be synchronized with the number of bullets before the last quit server

**Screenshots**
![Emptying](https://user-images.githubusercontent.com/64310374/212768685-13737ae9-73e3-46e1-b95f-c780aad38e18.gif)
[Emptying weapon bullets]

![Re-enter](https://user-images.githubusercontent.com/64310374/212769020-6f99bdcd-f31f-4c2a-ade9-6527d6dba179.gif)
[Re-enter to server]

**Comment by thelindat** [comment]
This is reported every few months with the same steps to reproduce, and is never reproducible.
