### ISSUE TITLE
Manual Eating / Smoking / Drinking via Item Data

### ISSUE THREAD

**Issue by Duderocktv** [overextended/ox_inventory#1099]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A lot of servers use something similar to [Devcore Realistic Needs](https://forum.cfx.re/t/release-devcore-realistic-needs-drinks-shots-food-alcohol/4410983) / [Realistic Smoking](https://forum.cfx.re/t/paid-devcore-realistic-smoking-v2-joint-cigar-cigarett-vape-bong/4623990).

Basically you use the Burger / Water or Cigarette. It goes into your hand.
You can Press E to take a puff, bite or drink, which takes away a % of the item.
You use E a few times to fully consume item.
(Bonus, like Devcore, he has the ability to pass your drink/smoke/water to someone else. His new script has you pouring Drinks into glasses on the table and putting props down for players to pick up -directly- into the eating/drinking anim (Like Red Dead Redemption 2)

**Describe alternatives you've considered**
Using the Devcore Scripts

**Additional context**
I thought it would be really nice to switch to ox inventory. It seems maintained, well written etc. But its a hell of a job to rewrite a bunch of scripts, let alone with old data stemming 1 year to thousands and thousands of players. 
And of course, the obfuscated scripts that wont allow us to actually modify inventory functions.

Really I thought this would be my only barrier to entry, myself, personally.
And with a built in solid feature like this, would definitely drive me to switch!

Cheers!

**Comment by N-fire** [comment]
You can already do that.

**Comment by Duderocktv** [comment]
Wha? You hold the item in your hand and press e to use it? Like holding a
bottle in your hand and press e to take a drink?

**Comment by N-fire** [comment]
It's not built in but you completely do this yourself. Look at how to make item usable.
