### ISSUE TITLE
SCRIPT ERROR: @ox_inventory/client.lua:816: attempt to index a nil value (local 'data') / new additions to the items and weapons lua arent defining

### ISSUE THREAD

**Issue by CrazedslawDev** [overextended/ox_inventory#1100]
**Describe the bug**
Item Data is undefined, despite being defined in the items.lua, Only items upto a certain point in the file work. 

**To Reproduce**
1. Join Server
2. use /giveitem to add any item after the Vehicle Keys in the items.lua to inventory
3. Watch item get added with correct name and icon (if it has one)
4. Open inventory and see its broken and flagging errors in console

**Expected behavior**
For the item data for all of the items to be defined and not break 

**Screenshots**
![20230117122254_1](https://user-images.githubusercontent.com/65857370/212899109-3c16fe6c-c4fa-4dad-9939-ff1f4ec90ec7.jpg)
**Additional context**
Items.lua (format changed to TXT to upload):
[items.txt](https://github.com/overextended/ox_inventory/files/10434967/items.txt)

**Comment by CrazedslawDev** [comment]
I should also mention that i updated to the latest versions of ox_inventory and ox_lib so its not a case of something being outdated

**Comment by thelindat** [comment]
> For the item data for all of the items to be defined and not break

Well needless to say, data for all items is defined just fine for me and everybody else. Your repro is worthless, because you have some _other_ issue.

**Comment by CrazedslawDev** [comment]
> > For the item data for all of the items to be defined and not break
> 
> Well needless to say, data for all items is defined just fine for me and everybody else. Your repro is worthless, because you have some _other_ issue.

Yes well im just following the template and trying to figure out what script is breaking item definition. The line number referenced is just the end of an if statement

**Comment by DokaDoka** [comment]
you are missing the comma after weight for every single item after paint

**Comment by CrazedslawDev** [comment]
> you are missing the comma after weight for every single item after paint

not the issue, added the commas after weight for every single item after pain and it didnt fix it
