### ISSUE TITLE
Can you give an example of export.oxinventory:openInventory....

### ISSUE THREAD

**Issue by daviddd20** [overextended/ox_inventory#1101]
I tried 
exports.ox_inventory:openInventory('shop',{ type = 'YouTool', id = 1 })

and it says 
"You can not open this inventory"

how to fix this?

**Comment by 1489259653** [comment]
> I tried exports.ox_inventory:openInventory('shop',{ type = 'YouTool', id = 1 })
> 
> and it says "You can not open this inventory"
> 
> how to fix this?

did u solve your problem? I also met that notify
