### ISSUE TITLE
Crafting Amount

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_inventory#1104]
We found a bug with the crafting amount. 

Sample:
![image](https://user-images.githubusercontent.com/35350615/213900299-9245a26d-a2fa-430f-bf39-9d4dd684ed20.png)

But in the end, we got only 1 Speakerbox and not 5.

**Comment by thelindat** [comment]
You neglected to include any information whatsoever; the data for speakerbox isn't irrelevant here.
I took an educated guess so it's _probably_ resolved but don't just dump issues without providing information; the craft amount isn't the problem.
