### ISSUE TITLE
mouse bug inside inventory

### ISSUE THREAD

**Issue by ItsTaras** [overextended/ox_inventory#1105]
**Describe the bug**
A user of my server is experiencing a strange bug in the middle of the screen when opening the inventory

https://www.youtube.com/watch?v=E-2Cv7OH66M&ab_channel=T1T0GU1LL

I use legacy 1.8.5

It only happens to two users of my server

**Comment by thelindat** [comment]
Not an inventory bug; rather something with GTA, FiveM, or even Windows interacting with CEF.
Change "Mouse Input Method" from Windows.
