### ISSUE TITLE
Ability to disable weapon use by ox. Ability to use Ace permissions for items.

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [overextended/ox_inventory#1107]
**Is your feature request related to a problem? Please describe.**
• vMenu - can we use ox inventory and still have vMenu weapons?
• Is it possible to still use weapon wheel with ox inventory somehow? (on foot) 

**Describe the solution you'd like**
• Option to disable weapons in ox_inventory.

• Can we assign ACE permissions to an item to prevent someone from buying it in a shop if they do not have the proper perms.
As a relatively standalone server that is not using jobs but rather ace permissions its frustrating that we cannot use the inventory simply because of weapons and furthermore even if not using vMenu weapons or weapon wheel could not even use them in inventory due to using Ace permissions for our weapon perms. Would be amazing if supported.

**Describe alternatives you've considered**
Unfortunately it seems to be either I can use ox inv or not. No inbetween :(

Thank you for your time. If this is something we could make happen, and if needed, had to commission to happen, I would love to make it possible.

**Comment by thelindat** [comment]
> vMenu - can we use ox inventory and still have vMenu weapons?

No, because if you don't equip a weapon through the inventory then you will be disarmed.

> Is it possible to still use weapon wheel with ox inventory somehow? (on foot)

No, because if you don't equip a weapon through the inventory then you will be disarmed.

> Can we assign ACE permissions to an item to prevent someone from buying it in a shop if they do not have the proper perms.
As a relatively standalone server that is not using jobs but rather ace permissions its frustrating that we cannot use the inventory

It's not a fully standalone resource and requires a framework; if you want other features you're free to work on them.

> Unfortunately it seems to be either I can use ox inv or not. No inbetween :(

That is how most things generally work; you either have it or do not.

**Comment by Legacy-TacticalGamingInteractive** [comment]
In this case then, is there somewhere that you could point me to regarding the weapons in particular on the ox inventory side of things. So I could try to add ace permissions to those? I have added it to one item thats from another script so far but that was in that script specifically in their buying code. But as for weapons that come with ox inventorys system I'm not sure where to begin I've tried checking the code but I'm new to lua, doing my best here. If I can figure out how to add ace permissions where the buying code is directly in a forked version of ox inventory I would love to just need a bit of help. I know you're busy.

**Comment by thelindat** [comment]
If you look at the bridge module you can set default functions and framework overrides for them. A set of functions specifically for “standalone” would probably be the best to avoid conflicting with defaults used by other resources.

hasGroup would be the way to look at ace permissions but they aren’t synced to client so you would need another solution there.
