### ISSUE TITLE
Can't use weapon

### ISSUE THREAD

**Issue by Jackpoter135** [overextended/ox_inventory#1109]
hello so i have a qb server and when i try to use any weapon after i draw a weapon the weapon immediately goes into the inventory (equipped weapon and 2 seconds later holstered weapon) PLEASE HELP

**Comment by thelindat** [comment]
Something conflicting - qb-smallresources has some holster stuff iirc.

**Comment by mirrox1337** [comment]
Probably `qb-anticheat:server:HasWeaponInInventory`
