### ISSUE TITLE
Container weight 

### ISSUE THREAD

**Issue by KuMoNDev** [overextended/ox_inventory#1111]
**Is your feature request related to a problem? Please describe.**
Items inside of a container counting towards weight of the inventory

**Describe the solution you'd like**
An option to make it so that items in a container do not add weight to your inventory, doesn’t make much sense to use bags as a container considering that it would add the weight for every item inside the container to your inventory. I think it would make more sense to have an option to make the container give you more weight instead. This way if you have a back pack or a bag or even a box you get additional weight. Just a suggestion.

**Comment by thelindat** [comment]
> An option to make it so that items in a container do not add weight to your inventory

Maybe you haven't noticed but I tend to aim for some level of realism, which does not include a "bag of holding".

> doesn’t make much sense to use bags as a container considering that it would add the weight for every item inside the container to your inventory

Organisation, mostly.

> have an option to make the container give you more weight instead

You can do all that and more using hooks and adjusting the player's inventory max weight.
