### ISSUE TITLE
Datadog limit? or bug?

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_inventory#1113]
Hi we use datadog an we get sometimes this error with 200/300 players 
![image](https://user-images.githubusercontent.com/35350615/215512850-96418944-82a3-4ddd-b0d3-cd1dd9afe5f6.png)

**Comment by thelindat** [comment]
Posting multiple times won't accomplish anything; if I can't have the problem occur then I can't look into the cause and resolve it.
