### ISSUE TITLE
I can't search

### ISSUE THREAD

**Issue by JancsiOfficial** [overextended/ox_inventory#1116]
Hi I can't search nearby player's inventory in fractions. nothing error.

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/blob/61fe3250def5f83141d5d9d94c96940fec54da31/client.lua#L49-L59
https://github.com/overextended/ox_inventory/blob/61fe3250def5f83141d5d9d94c96940fec54da31/client.lua#L145-L147
https://github.com/overextended/ox_inventory/blob/61fe3250def5f83141d5d9d94c96940fec54da31/client.lua#L478-L480

**Comment by AcJochym** [comment]
Anyone know how to add this to qtarget?

**Comment by thelindat** [comment]
> Anyone know how to add this to qtarget?

did you try reading, then putting 2 and 2 together?
