### ISSUE TITLE
Configuration doesn't change

### ISSUE THREAD

**Issue by Van-hoa** [overextended/ox_inventory#1118]
**Describe the bug**
When I try to set a config.cfg to modify locale, file seems to be read but in game, there is no changes.

**To Reproduce**
1. Create a config.cfg (inside my resources/[ox]/ox_inventory/config.cfg
2. "setr inventory:locale "fr""
3. Launch game

**Expected behavior**
Shoud translate inventory from english to french

**Screenshots**
![image](https://user-images.githubusercontent.com/38043639/216280786-64fe75d5-acdc-4c83-9e83-c56da0b222be.png)
![image](https://user-images.githubusercontent.com/38043639/216280865-24b798a5-1de1-41eb-b820-375cd50d707d.png)

**Additional context**
After that, I don't understand how to enable vehicle storage and glovebox ?

Thank you for you replies ! :D

**Comment by lush0n3** [comment]
Use `setr ox:locale en` instead of `setr inventory:locale`
