### ISSUE TITLE
My screen goes black whenever putting this script

### ISSUE THREAD

**Issue by Julezzzz119** [overextended/ox_inventory#1121]
**Describe the bug**
I added the ox_inventory script to my fivem server and now it just puts me into a black screen loop.

If you join the my server western Sydney RP you can see for yourself 

this is what it says in my command prompt 
[citizen-server-impl] Started resource ox_lib
[ c-resources-core] Resource 'ox_inventory' can't run:
[ c-resources-core] 1. server needs to be 6116 or higher
[ citizen-server-impl] Couldn't start resource ox_inventory 
 
i do not know how to fix this help i really want to add this to my server.

**Comment by thelindat** [comment]
cool now learn to read
