### ISSUE TITLE
Weapon ammo syncing bug

### ISSUE THREAD

**Issue by hyprell** [overextended/ox_inventory#1122]
When you shoot all your bullets and empty your ammo magazine to 0, it doesn't update server-side, so when you drop it and pick it back up it has a full magazine.

1. Give yourself some automatic weapon for example WEAPON_MINISMG
2. Fully reload it and drop all of your ammo
3. Shoot until ammo magazine is fully empty
4. Drop it and pick it back up

**Comment by thelindat** [comment]
wow the steps haven't changed since the first time people reporting issues with ammo sync and it still doesn't repro
