### ISSUE TITLE
Giving Items

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_inventory#1129]
**Describe the bug**
When giving a player an item (such as a gun) when the weapon is out it produces an error.

**To Reproduce**
1. Unholster a gun
2. Give the gun to another player
3. Bam error

**Expected behavior**
To give the gun without it erroring

**Error::**
```lua
error during NUI callback giveItem: @ox_inventory/modules/weapon/client.lua:117: attempt to index a nil value (field 'metadata')
^1SCRIPT ERROR: @ox_inventory/modules/weapon/client.lua:117: attempt to index a nil value (field 'metadata')^7
^3> Disarm^7 (^5@ox_inventory/modules/weapon/client.lua^7:117)
^3> updateInventory^7 (^5@ox_inventory/client.lua^7:819)
^3> handler^7 (^5@ox_inventory/client.lua^7:870)

^1SCRIPT ERROR: @ox_inventory/client.lua:1306: attempt to index a nil value (field 'metadata')^7
^3> callback^7 (^5@ox_inventory/client.lua^7:1306)
^3> fn^7 (^5@ox_lib/init.lua^7:122)
```

**Additional Context**
**Artifacts:** Windows - 6248
**Inventory:** 2.23.1

**Comment by EpKouhia** [comment]
We managed to replicate this on my local aswell. For some reason weapon is not disarmed when giving unholstered weapon.
