### ISSUE TITLE
Vocal/multi player on stash/player nearby

### ISSUE THREAD

**Issue by DARKAOFF** [overextended/ox_inventory#1131]
hello I don't know if it's possible but we can't access more than one stash and also if we search an inventory if the person opens his inventory we can't access it.  and voice level if you are in the inventory impossible to speak

**Comment by thelindat** [comment]
> we can't access more than one stash

yes

> if we search an inventory if the person opens his inventory we can't access it

yes

> voice level if you are in the inventory impossible to speak

https://docs.fivem.net/docs/game-references/controls/

```yaml
# Enable control action when inventory is open
setr inventory:enablekeys [249, othercontrols]
```
