### ISSUE TITLE
[Bug] An error occurred while calling export `checkDependency` in resource `ox_lib`

### ISSUE THREAD

**Issue by slamkica** [overextended/ox_inventory#1132]
Hello, so I am not sure how this could be an error on my side because I have followed the documentation and everything was as it is supposed to be. I have not changed anything regarding the scripts required to run ox_inventory, I only edited es_extended but I do not see how that could cause this error. I have used ox_inventory 1-2 months ago and everything worked as intended.

![error](https://user-images.githubusercontent.com/125159001/218281502-8ce29009-eecd-4e21-8c68-01ce016b4687.png)

**Comment by thelindat** [comment]
This is the function to check resource versions.
https://github.com/overextended/ox_lib/blob/master/resource/version/server.lua#L1-L10

All these resources have version defined in fxmanifest, and you're mysteriously the _only one_ with this.
https://github.com/overextended/ox_lib/blob/master/fxmanifest.lua#L11
https://github.com/overextended/ox_target/blob/main/fxmanifest.lua#L10
https://github.com/overextended/ox_inventory/blob/main/fxmanifest.lua#L10

As well as an index error for lib.checkDependency, where again it checks 'version' from fxmanifest (which is again, magically non-existent for you only).
https://github.com/overextended/ox_lib/blob/master/resource/version/shared.lua#L2

Also _not the right place for this issue_.
