### ISSUE TITLE
Temporary Stashes

### ISSUE THREAD

**Issue by davidxd33** [overextended/ox_inventory#1134]
**Is your feature request related to a problem? Please describe.**

Using a stash in a manner such as to make "lootable" entities with dynamically generated stash contents. As it stands, this requires workarounds such as force purging stashes on resource start to wipe them from the database, registering hooks preventing adding items to the stash, and running loops calling an export to add an item to the dynamic stash.

**Describe the solution you'd like**

Either adding two additional parameters to `RegisterStash` that makes it non-persistent and defining a preset list of items that get auto assigned to an available slot or similar logic in a `RegisterTemporaryStash` function. 

**Describe alternatives you've considered**

Wiping the database entries for previously generated temporary stashes on server resource start.

**Additional context**

This is a very useful feature similar to the custom drops. You'll be able to use the inventory to create dynamic "loot" stashes that don't act as a normal storage that persists. There are many other use cases for this.

**Comment by eprimex** [comment]
> Wiping the database entries for previously generated temporary stashes on server resource start.

A stash that is temporary shouldn't even be saved to the database in the first place. The data stays in the server-side cache while the server is running and is then wiped
