### ISSUE TITLE
Vending machines don't working

### ISSUE THREAD

**Issue by P1R4T3development** [overextended/ox_inventory#1138]
First, thx for this wonderful script!
I can't get working my vending machine (ESX framework).
All is up to date, and i've try with and without ox_target mode.
If you've any idea, thank you very much by advance

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/218380474-0fbd4055-f746-4cea-97ff-bab883c62172.png)

Just running default soo

**Comment by P1R4T3development** [comment]
Nothing for me, i've try with key, and target, and no any option appear (with "target false" and "true" in config file, all shops works fini, but vending machine not. U can't take screenshot with target key pressed, but i got no any interaction, on the defined props
![uylligyulkug](https://user-images.githubusercontent.com/124460873/218474969-6be1070c-1a50-4c09-98bf-84dc8e667482.JPG)
![lukgfly](https://user-images.githubusercontent.com/124460873/218474976-7adc488e-92c4-4779-891b-8983db663e98.JPG)
![kyhdgkfjk;](https://user-images.githubusercontent.com/124460873/218474984-9938736c-ad2e-45e4-98e4-3d8772f44f95.JPG)

**Comment by P1R4T3development** [comment]
Hi, i hope you're fine!
Have you any idea? Nothing working for me, and i'm working on a second server, with ox ressources, and vending machines arent working too on this one :(

**Comment by P1R4T3development** [comment]
Why my issue was closed with no reply? I'm allways stuck with the same problem, and no idea or replies :(

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/221760843-0e6ec6f8-a702-451b-99e1-24ec297dd9cf.png)
![image](https://user-images.githubusercontent.com/65407488/221760858-22ce05fa-af2b-4e1c-abea-06f5826be804.png)

What are these nonsense convars you're trying to set? It's `setr inventory:target true`.

**Comment by P1R4T3development** [comment]
> ![image](https://user-images.githubusercontent.com/65407488/221760843-0e6ec6f8-a702-451b-99e1-24ec297dd9cf.png) ![image](https://user-images.githubusercontent.com/65407488/221760858-22ce05fa-af2b-4e1c-abea-06f5826be804.png)
> 
> What are these nonsense convars you're trying to set? It's `setr inventory:target true`.

It was what i've tried first, but not working, i've try some possibilities, "target false", "target true", "false", "true"...

**Comment by thelindat** [comment]
> i've try some possibilities

There's _one_ possibility, and none of what you keep showing is correct - especially not trying to set it as false.
