### ISSUE TITLE
Item count limit (yes, again)

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#1143]
I know this is something annoying, it was PR in the passed and removed a few moments later.
But this is in my opinion really **needed** for rp servers otherwise it makes no sense.

## Is your feature request related to a problem? Please describe.
Not having item limit makes the roleplay not realistic at all.
Having the ability to fill a player inventory with assault rifles or heistbags, makes no sense.
Carrying larges but lightweights objects also need this limitation.

## Describe the solution you'd like
This feature could be pretty complicated to get the necessary flexibility and realism.
For example a limit should be different depending on the inventory type.
A nice solution could be to check if item limit is a number or a table. Where number means a global limit, or table keys are pointing to inv individual inv types.

## Describe alternatives you've considered
Before starting a new server I misunderstood the hook system. I was thinking that it provides a way to add a limit and cancel any situation where an item limit could be hit. But for example buying an item from shops is not cancelable using createItem hook.

## Additional context
Here is more unrealistic situation without this count limit:

<img src="https://user-images.githubusercontent.com/47056777/218443697-d083aed3-868d-445c-a813-5204f97795a0.png" width="600"/>

<img src="https://user-images.githubusercontent.com/47056777/218443697-d083aed3-868d-445c-a813-5204f97795a0.png" width="600"/>

<img src="https://user-images.githubusercontent.com/47056777/218444333-595fc42c-163b-41ba-a97c-260f26af6436.png" width="600"/>

<img src="https://user-images.githubusercontent.com/47056777/218445377-f83e5628-f04e-40e0-9dcf-fd8968bd96d8.png" width="600"/>

<img src="https://user-images.githubusercontent.com/47056777/218447727-9efcfef9-5123-49d9-9410-335132b3d38f.png" width="600"/>

**Comment by thelindat** [comment]
Reduce slots, forcing people to use bags.
Reduce max weight, forcing people to carry less random items.

**Comment by dolutattoo** [comment]
Already tried for sure but sadly this is not enough at all...
I know this is really annoying since it requires a lot of code refactor and probably impacting performances but it's really really a must have
