### ISSUE TITLE
Hook for CloseInventory and Exports

### ISSUE THREAD

**Issue by chaze117** [overextended/ox_inventory#1147]
Hi it is possible to make a hook for CloseInventory? 

I scripting in C# and I can use Exports but the way you use in your sripts I can't. Can you do some improvements? Like use exports like this 
`exports["name"]:function()`
or make events. 
Thank you!

**Comment by chaze117** [comment]
So you do this `exports('displayMetadata', displayMetadata)`  (modules/items/client.lua)
I can yuse this in C# `Exports["esx_progressbar"].Progressbar(...)`
The method you export things the client don't recognise it like exported like this `exports["name"]:function()`

**Comment by thelindat** [comment]
Exports are a cfx implementation, and I don't see what C# syntax has to do with export creation?

These are all the same in Lua.
```lua
exports.ox_inventory:displayMetadata(...)
exports.['ox_inventory']:displayMetadata(...)
exports.["ox_inventory"]:displayMetadata(...)
```
And for JS.
```lua
exports.ox_inventory.displayMetadata(...)
exports.['ox_inventory'].displayMetadata(...)
exports.["ox_inventory"].displayMetadata(...)
```

If C# needs to use string notation like that.. then just do that? Don't know how you expect me to "use exports like that" when `exports('displayMetadata', displayMetadata)` _is the only way to register an export_.

**Comment by chaze117** [comment]
Of course I can add some modifications but this way hard to keep everything up to date.  
My biggest problem is when you do export like this `exports('Search', Inventory.Search)`
The client throws me an error that Inventory is not member of Export.
But maybe there is a way to make some bridge/wrapper to keep thing in one place. I'll try it later.
Or throws this error because my script loads before ox_inventory.
Anyway thanks for your answer.

**Comment by thelindat** [comment]
> Of course I can add some modifications but this way hard to keep everything up to date.

When did I _ever_ mention having to make modifications?

> My biggest problem is when you do export like this exports('Search', Inventory.Search)

Inventory.Search refers to a function. The export is `Exports["ox_inventory"].Search(...)`

> The client throws me an error that Inventory is not member of Export.

Because it's ["ox_inventory"] not ["Inventory"]

**Comment by chaze117** [comment]
Oh God, I think I misundersood how Exports works...
You need to call Expors[resource_name].exported name. Right?
If this is the case then thank you for pointing me to the right direction. And sorry for bothering you.
