### ISSUE TITLE
Registering items

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#1150]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Could be very usefull to be able to create items trough an export function, so we can create items from external resources.

**Additional context**
I would personally love to let admins create new items on my server, without having to send a ticket to devs to create items everyday.
Best addition to this could be to provide something to refresh items, so everything could be done in runtime.
(or even better, only send the new items and/or edited ones to all connected players instead of the full item list)

For sure this is only for external resource purpose, unless the inventory provides something (i.e. modal) with strong validation checks and why not something to preview item image.

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/issues/553

Number of times this gets brought up is more annoying than limit; not as simple as just adding an export and requires rewriting large parts of the code and the UI to properly support it.
