### ISSUE TITLE
image metadata not showing image in the inventory

### ISSUE THREAD

**Issue by Senlar** [overextended/ox_inventory#1153]
**Describe the bug**
For some reason adding the image metadata is not showing the images in the inventory when adding an item.

**To Reproduce**
1. Use the addItem export to add an item to your inventory with metadata.image to a valid URL
2. See no image showing in full inventory.

**Expected behavior**
Items with the image metadata show show the image

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
This show them having the image when being added to my inventory
![image](https://cdn.discordapp.com/attachments/1076920880359297074/1077351665079943168/image.png)

This show no image in full inventory
![image](https://cdn.discordapp.com/attachments/1076920880359297074/1077351716913168505/image.png)

I added the image to display metadata and you can see the image metadata URL is showing on the item.
![image](https://user-images.githubusercontent.com/1503963/220209281-c803e5b8-1c83-49e5-93ce-cf266ece58a5.png)

**Comment by FjamZoo** [comment]
Well the metadata for seting a inventory with a URL is not metadata.image but metadata.imageurl.
