### ISSUE TITLE
inventory stop working

### ISSUE THREAD

**Issue by FozzySf5** [overextended/ox_inventory#1154]
**Describe the bug**
i had mutiple repost of inventory not popping up

**To Reproduce**
people hangin inside ot la fuento ranch with couple people or dieing and reviving couple times.

**Screenshots**
![image](https://user-images.githubusercontent.com/121222122/220516301-bf4e24a5-febd-4d5a-bea5-65941408ceba.png)

**Comment by thelindat** [comment]
That's not how to reproduce it, and it was fixed (4?) days ago.

**Comment by FozzySf5** [comment]
well how was it reproduced? What caused it.

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/commit/6ea3f786b63533a24f9b33494cf54651ecc58cfe
