### ISSUE TITLE
parachute

### ISSUE THREAD

**Issue by JancsiOfficial** [overextended/ox_inventory#1156]
Hello the parachute I can't use it because I can't see a prop and I can't move my character. and I falling down.
![image](https://user-images.githubusercontent.com/123206097/220721478-a5755556-aa19-4d8f-b8b6-c79c4348a48c.png)

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/220976379-7be30a60-62f4-4f79-a558-40277f573039.png)
ok?
