### ISSUE TITLE
Thank you Lindat!

### ISSUE THREAD

**Issue by benzon** [overextended/ox_inventory#116]
Hey The Lindat!

This isn’t a feature request, this is actually just a thank you!

You are doing an amazing job with this inventory, not using it myself, but testing it now and again and keeping track of what happens, and I just wanted to say you are doing a darn great job!

You tried to alter something first, did not feel like it worked, then created a new project written from scratch, a project that you put a darn lot of time in to, just the amount of commits show how dedicated you are working on this project.

So this is just a thank you from me and hopefully the community for the work you are doing! Keep doing what you are doing, it’s an amazing journey to follow!

**Comment by ScaredDonut** [comment]
Totally agree! Thank you so much for putting your free time into this. There are so many paid projects out there and this one is literally the best out of all of them and its free! 

You're awesome!  ♥

**Comment by yolobrandon01** [comment]
I just saw this because I've been skimming through all your resources and looking at all the amazing work you have done, your inventory and all the stuff you have available has helped me with updating esx! Keep up the great work!

**Comment by leixdd** [comment]
Agreed, Thank you so much. You write your code really well and it was really optimized.

**Comment by lush0n3** [comment]
I join in the congratulations, you are doing an incredible job and that makes you a great person.

**Comment by Okkie-NL** [comment]
I agree with these comments. It is a great inventory and the players love it.

**Comment by Senlar** [comment]
If you can, you should by Linden a coffee... seriously.
https://www.buymeacoffee.com/thelindat
