### ISSUE TITLE
SetMaxWeight export - UI issue

### ISSUE THREAD

**Issue by Edward-Bakker** [overextended/ox_inventory#1167]
**Describe the bug**
With the new `SetMaxWeight` export you have to re-open your inventory for your max weight to update in the UI.

**To Reproduce**
1. Open inventory
2. Use the `SetMaxWeight` export to update the max weight.
3. Look at the max weight in the inventory, has not changed.
4. Re-open inventory, it has now properly updated.

**Expected behavior**
Use the `SetMaxWeight` export and the max weight in the inventory UI updates.

**Screenshots**
[Video](https://streamable.com/4zr2if)

**Additional context**
N/A

**Comment by thelindat** [comment]
Will fix it eventually, but one would assumably not have their inventory open when this is being triggered.
