### ISSUE TITLE
depreciated syntax for lib.addCommand

### ISSUE THREAD

**Issue by QuarterMileRP** [overextended/ox_inventory#1169]
**Describe the bug**
Errors in server console after upgrading ox_inventory and ox_lib

**To Reproduce**
Start server and the I get errors about depreciated syntax for lib.addCommand 

**Screenshots**
(https://imgur.com/a/MGzC7j2)

**Additional context**
I've redownloaded both latest releases. Only changes I've made are adding my items, shops and stashes lua's

name 'ox_inventory'
author 'Overextended'
version      '2.24.2'

name         'ox_lib'
author       'Overextended'
version      '3.0.0'
license      'LGPL-3.0-or-later'

Server Artifacts 6230
Server build 2699
ESX Legacy 1.9.1

**Comment by jag3dagster** [comment]
They clearly state they are warnings, not errors.

Regardless work has been done, wait for the next version of ox_inventory to go out. Everything should work fine regardless.

**Comment by Im-Kayun** [comment]
Download the last version of ox_inventory and follow this guide.
https://overextended.github.io/docs/ox_inventory/Guides/inventory_ui

**Comment by Evan-Barbati** [comment]
I did your steps but still the same bug
