### ISSUE TITLE
Cant open inventory

### ISSUE THREAD

**Issue by DarwansDev** [overextended/ox_inventory#1170]
Before i got an error about a third party something. So i reinstalled it ox inventory and ox lib. But now i get that i cant open inventory, i am able to use the inventory for about 1 minute before it says i cant open inventory

**Comment by thelindat** [comment]
> Before i got an error about a third party something.

Not an error..

> So i reinstalled it ox inventory and ox lib.

As is FiveM user tradition..

> But now i get that i cant open inventory, i am able to use the inventory for about 1 minute before it says i cant open inventory

Debug it yourself, looking at https://github.com/overextended/ox_inventory/blob/caf7d3b1624851ab6bfef20dc8e42c1fa220e25e/client.lua#L42-L63
