### ISSUE TITLE
After server restart player inventory disappears 

### ISSUE THREAD

**Issue by MysticStyxxx** [overextended/ox_inventory#1176]
After server restart player inventory disappears.

**Comment by thelindat** [comment]
After server restart player inventory saves.

**Comment by MysticStyxxx** [comment]
It's not saving in database. So where is it saving? It saves stashes and everything but when player joins back after leaving they have nothing in inventory

**Comment by thelindat** [comment]
Well if you use ESX, ESX handles saving the player inventory. If you use anything else, they save _the exact same way stashes do_.

**Comment by MysticStyxxx** [comment]
I'm using Esx.Legacy.  In database I see one stash saved as I'm testing it but player are not in it at all, Please HELP ME OUT.

**Comment by thelindat** [comment]
>  if you use ESX, ESX handles saving the player inventory.

**Comment by MysticStyxxx** [comment]
I get that. WHERE do I go for that?

**Comment by MysticStyxxx** [comment]
Please be more specific

**Comment by thelindat** [comment]
> WHERE do I go for that?

Into es_extended. Which also triggers saves on restart (like ox_inventory). Unless your definition of restart is closing fxserver.exe of course.

I just setup a fresh ESX install and it saves as one would expect.
