### ISSUE TITLE
WEAPON_RAYCARBINE broken after a single shot

### ISSUE THREAD

**Issue by SneakyAF** [overextended/ox_inventory#1180]
**Describe the bug**
WEAPON_RAYCARBINE gets its durability set to 0 after a single shot. Not sure if this is intended.

**To Reproduce**
1. Get the WEAPON_RAYCARBINE
2. Get the ammo-laser
3. Shot the weapon
4. Notice that after a single show the weapon becomes not usable (durability is 0)

**Expected behavior**
The weapon is more durable

**Comment by thelindat** [comment]
Rather, for some reason the weapon gobbles up all your ammo - taking 1000 ammo even though the max is 250. Since durability change is based on the number of shots fired (technically, the diff between loaded ammo and the ammo metadata) shooting 1 "bullet" is counting all those bullets.
