### ISSUE TITLE
Weaponwheel not more working

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_inventory#1182]
Hi, since the latest update, we cannot use the weapon wheel anymore. All the time we have both, Inventory and Weaponwheel but the wheel are empty. 

![image](https://user-images.githubusercontent.com/35350615/222948736-d2bb12f2-779d-4e51-8143-c9434d931de9.png)

![image](https://user-images.githubusercontent.com/35350615/222948751-783e0f70-2b8c-4bb8-93d2-cc0e393fda50.png)

**Comment by thelindat** [comment]
I don't know what you're expecting weapon wheel to do; but enabling it disables inventory items _entirely_ and it doesn't show weapons in your inventory in the wheel.

**Comment by soniXx123** [comment]
Yes i know and it was working all the time. Since the latest OX Update not more :) we use this for our minigame (Paintball)

![image](https://user-images.githubusercontent.com/35350615/222949068-8c45539d-b718-40bd-8f41-15f55eb14fd6.png)

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/222958647-5626aeae-6e60-4ba1-a463-e0e691920d64.png)
![image](https://user-images.githubusercontent.com/65407488/222958660-5bffdadd-5d14-44e0-8ff9-540b793c2b3a.png)


Wheel toggles and I'm able to select non-inventory weapons.
