### ISSUE TITLE
Weight issue? // @ox_inventory/modules/inventory/server.lua:613 - Unknown column 'id' in 'where clause'

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [overextended/ox_inventory#1191]
**Describe the bug**
From Log

```
[ script:ox_inventory] [info] Saving 5 inventories to the database
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:613: ox_inventory was unable to execute a query!
[ script:ox_inventory] Unknown column 'id' in 'where clause'
[ script:ox_inventory] SELECT plate, glovebox FROM `vehicles` WHERE `id` = ?
[ script:ox_inventory] > callbackResponse (@ox_lib/callback/server.lua:60)
[ script:ox_inventory] > handler (@ox_lib/callback/server.lua:76)
[ script:ox_inventory] > <unknown> (@oxmysql/dist/build.js:22495)
[ script:ox_inventory] > processTicksAndRejections (node:internal/process/task_queues:96)
[ script:ox_inventory] 
```

**To Reproduce**
Started noticing these logs from players on the server recently as of the latest versions of oxlib, oxmysql, ox_target and ox_inventory

This is line 613:
```
				inv.weight -= slot.weight
```

**Expected behavior**
I'm not even sure what I'm supposed to do. But I figured I'd post here and see if someone knows how to fix it?

**Comment by thelindat** [comment]
Not sure where your looking, but [this is line 613](https://github.com/overextended/ox_inventory/blob/60c50c6a40595e39361e47d1e142e02c8c11321b/modules/inventory/server.lua#L613).

```lua
result = invType == 'trunk' and db.loadTrunk(id) or db.loadGlovebox(id)
```

https://github.com/overextended/ox_inventory/blob/60c50c6a40595e39361e47d1e142e02c8c11321b/modules/mysql/server.lua#L6
https://github.com/overextended/ox_inventory/blob/60c50c6a40595e39361e47d1e142e02c8c11321b/modules/mysql/server.lua#L134-L136

id certainly exists on ox_core at all times, couldn't tell you for nd_core if that's what you're using.

**Comment by Legacy-TacticalGamingInteractive** [comment]
I will see if @Andyyy7666 can take a look

**Comment by Legacy-TacticalGamingInteractive** [comment]
```
CREATE TABLE `vehicles` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`owner` INT(11) NULL DEFAULT NULL,
	`plate` VARCHAR(255) NULL DEFAULT NULL,
	`glovebox` LONGTEXT NULL DEFAULT '[]',
	`trunk` LONGTEXT NULL DEFAULT '[]',
	`properties` LONGTEXT NULL DEFAULT '[]',
	`stored` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `owner` (`owner`) USING BTREE,
	CONSTRAINT `vehowner` FOREIGN KEY (`owner`) REFERENCES `characters` (`character_id`) ON UPDATE CASCADE ON DELETE CASCADE
);
```

PLACING HERE for anyone else. Thank you guys.
