### ISSUE TITLE
Giving Items doesn't trigger hooks

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_inventory#1193]
**Describe the bug**
Not sure if this is a bug, but when you give another person an item, it doesn't trigger the payload.

**To Reproduce**
```lua
local Inventory = exports.ox_inventory;

Inventory:registerHook('swapItems', function(payload)
    print(json.encode(payload, { indent = true }))
    return false
end, {
    print = true,
    inventoryFilter = {
        '^glove[%w]+',
        '^trunk[%w]+',
    }
})
```

**Expected behavior**
When an item is given shouldn't it trigger  the payload?

**Screenshots**
https://github.com/overextended/ox_inventory/blob/9f8e2bf7d6f4a8219762c1cbf0da3fdd6090b780/modules/inventory/server.lua#L1881-L1890

**Comment by thelindat** [comment]
That filter obviously won’t trigger for give.

**Comment by PoorLatency** [comment]
> That filter obviously won’t trigger for give.

Which one will?

**Comment by thelindat** [comment]
```lua
    inventoryFilter = {
        '^glove[%w]+',
        '^trunk[%w]+',
    }
```

Is a filter for glove(box) and trunk.

**Comment by PoorLatency** [comment]
I tried this and it didn't work unless I am doing something wrong.
```lua
local Inventory = exports.ox_inventory;

Inventory:registerHook('swapItems', function(payload)
    print(json.encode(payload, { indent = true }))
    return false
end, {
    print = true,
    --[[
    inventoryFilter = {
        '^glove[%w]+',
        '^trunk[%w]+',
    }
    --]]
})

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/224205961-c6dd8532-0c32-4a60-9e30-72a0b7b9332c.png)

**Comment by lexinor** [comment]
@PoorLatency Which version are you using ?

**Comment by PoorLatency** [comment]
> @PoorLatency Which version are you using ?
v2.25.0.

**Comment by lexinor** [comment]
> > @PoorLatency Which version are you using ?
> 
> v2.25.0.

That issue (https://github.com/overextended/ox_inventory/issues/1164 ) seems to be what you're experiencing and has been fixed (I'm using this) that's why I was asking for your ox_inv version.

**Comment by thelindat** [comment]
That was itemFilter though; he claims it doesn't work even without filters.

**Comment by lexinor** [comment]
I just tried it and it's working (v2.25.0)

```
exports.ox_inventory:registerHook('swapItems', function(payload)
    print(json.encode(payload, { indent = true }))
    return false
end, {
    print = true,
})
```

in server console
![aaa](https://user-images.githubusercontent.com/28725795/224303070-f588b7a4-b428-4d07-9114-846884ffb771.PNG)

Is that the use case ?

**Comment by PoorLatency** [comment]
> Is that the use case ?

It seems to work like that but however, my use case is trying to 'restrict' giving specific items to people for an example the below, but it seems that it doesn't allow people to `move` items in their inventory. Unless, I am doing this wrong with the hook...
```lua
Inventory:registerHook('swapItems', function(payload)
    if payload.action == 'give' then
        local data = payload.fromSlot

        if data and data.name:find('WEAPON_') then
            return false
        end
    end
end, {
    print = false,
})
```

**Comment by thelindat** [comment]
You posted this and said it didn't work.
```lua
local Inventory = exports.ox_inventory;

Inventory:registerHook('swapItems', function(payload)
    print(json.encode(payload, { indent = true }))
    return false
end, {
    print = true,
    --[[
    inventoryFilter = {
        '^glove[%w]+',
        '^trunk[%w]+',
    }
    --]]
})
```
But now you also say this works, despite being _the exact same_.
```lua
exports.ox_inventory:registerHook('swapItems', function(payload)
    print(json.encode(payload, { indent = true }))
    return false
end, {
    print = true,
})
```
And the last snippet you post doesn't do anything if not 'giving' the item, not affecting the movement of the item in an inventory _at all_.
```lua
Inventory:registerHook('swapItems', function(payload)
    if payload.action == 'give' then
        local data = payload.fromSlot

        if data and data.name:find('WEAPON_') then
            return false
        end
    end
end, {
    print = false,
})
```

This is a waste of time with all this conflicting/nonsense information; especially since there doesn't seem to be a problem whatsoever...
