### ISSUE TITLE
Option for admins to view player inventories

### ISSUE THREAD

**Issue by Remco2022** [overextended/ox_inventory#1196]
**Is your feature request related to a problem? Please describe.**
No, but it's useful to have this feature.

**Describe the solution you'd like**
In ESX inventoryhud there is an option to view player inventories and grab items based on ace permissions. This way you can look into a player inventory as an admin to check if a player has a lot of money or weapons which they shouldn't be able to have at that time. For example: a new player joins the server and he is buying things which he shouldn't have the money for yet or if you don't trust it completely since you know the player and he is known to hack before. Would be nice to check the inventory and confirm suspicions 

**Describe alternatives you've considered**
I have tried to use the export openInventory('player', [id]) but it's based on a policejob and a certain radius. The request i have should be based on ace permissions/user group and no radius.

**Additional context**
N.A.

**Comment by thelindat** [comment]
You can use /viewinv to _view_. Dragging is not available at this time, and you won't get live updates of their inventory; there are other things I need to do to enable multi-accessible inventories (otherwise players would be locked out of their inventory while an admin is using it).

**Comment by thelindat** [comment]
/viewinv will properly sync with the next release (v2.30.0), otherwise https://overextended.github.io/docs/ox_inventory/Functions/Server/forceOpenInventory/ to have access.
