### ISSUE TITLE
Ask about stock item number

### ISSUE THREAD

**Issue by 111YRY** [overextended/ox_inventory#1202]
Ask about stock item number， I can't find a useful simple tutorial ， Hope someone can help me， 
![IK7X5SA7WWIT6X@MQN5 Y7G](https://user-images.githubusercontent.com/108551275/224495547-f9930b2a-9043-4017-8a32-2b30893d5215.png)

**Comment by thelindat** [comment]
what

**Comment by 111YRY** [comment]
item unique number

**Comment by thelindat** [comment]
k
