### ISSUE TITLE
esx_addoninventory error with latest ox_inventory update

### ISSUE THREAD

**Issue by Unavarage** [overextended/ox_inventory#1204]
**Describe the bug**
Latest update gets script error of esx_addoninventory

**To Reproduce**
1. Start your server
2. See error

**Expected behavior**
There was no error before the latest update

**Screenshots**
![1](https://user-images.githubusercontent.com/31205336/225117828-d20d90ed-3a40-4ad7-aa1e-d35c256a58a1.png)

**Comment by jag3dagster** [comment]
What did your load order look like?

**Comment by Unavarage** [comment]
> What did your load order look like?
![1](https://user-images.githubusercontent.com/31205336/225125714-d3548490-0975-4610-82aa-2d59d1efa9e3.png)
Here it is

**Comment by jag3dagster** [comment]
What is in the [ox_inventory] category?

Do you have any errors when starting ox_inventory in your server logs?

**Comment by Unavarage** [comment]
> What is in the [ox_inventory] category?
> 
> Do you have any errors when starting ox_inventory in your server logs?

No I don't have any, errors, in the ox_inventory there are the ox_inventory itself ox_lib; ox_target; ox_doorlock

**Comment by thelindat** [comment]
This is dumb. Either the resource isn’t started or there was an error at startup leading to the export not being created.

If there is an error, it’s non-standard and you need to look at what you’re doing to cause it.

**Comment by Gxalia** [comment]
you need to update your ox-inventory version
