### ISSUE TITLE
Craftin and open items spam

### ISSUE THREAD

**Issue by yumkimiil** [overextended/ox_inventory#1205]
**Describe the bug**
Comment describing that when you open many items, even if you only have one, you can press the key many times and quickly, this will give you many power ups, items, craft items, etc.
**To Reproduce**
1. Open items or craft items with one item 
2.push spam button  and drop more items with one item

**Expected behavior**
It is supposed to be an item, it should only be one, not many.

**Screenshots**
[animations.txt](https://github.com/overextended/ox_inventory/files/10983957/animations.txt)
![image](https://user-images.githubusercontent.com/88397428/225423828-3c514b53-ea5f-4c6e-aec6-ed1c19be3284.png)
![image](https://user-images.githubusercontent.com/88397428/225423941-e1811c36-c60f-4415-8148-27b37d5d8b0c.png)
![image](https://user-images.githubusercontent.com/88397428/225424085-446f4942-c780-401a-8dea-994428d2fc8e.png)
![image](https://user-images.githubusercontent.com/88397428/225424135-789b9bf7-d2c6-45cf-a13e-2f08017c9fb4.png)
![image](https://user-images.githubusercontent.com/88397428/225424208-16691985-4d4f-44bf-ab9b-ee4c827bb6f2.png)

**Comment by thelindat** [comment]
I haven't a clue what you're saying is happening, and your screenshots just make it more confusing.
