### ISSUE TITLE
"R" refreshes skin

### ISSUE THREAD

**Issue by AnxietyPills** [overextended/ox_inventory#1206]
"r" has been resetting skins on the latest build of ox

**Comment by N-fire** [comment]
Most likely a conflicting resource, ox_inventory does nothing to peds.
See https://github.com/overextended/ox_inventory/issues/1020

**Comment by N-fire** [comment]
Most likely a conflicting resource, ox_inventory does nothing to peds.
See https://github.com/overextended/ox_inventory/issues/1020
And before opening an issue search if this issue has not been resolved already
