### ISSUE TITLE
[HELP] ox_inventory settings (server.cfg)

### ISSUE THREAD

**Issue by JstnKlbt** [overextended/ox_inventory#1209]
Hey, I've read through the documentation, but to no avail. I entered the settings into the server.cfg as described there, but nothing changes at all, neither the keys nor the settings for the weight or the like.

Can someone help me on this?

see server.cfg > https://prnt.sc/j_wPLfmakeF1
see inventory.cfg > https://prnt.sc/_NJkcTGOnB6b
see rootfolder > https://prnt.sc/ZdXt72gkFXi0

Sorry for my bad English, I'm from Germany.

**Comment by 1489259653** [comment]
did u fix that? I can set the weight, but i can't set hot keys
