### ISSUE TITLE
Autoreload won't work sometimes

### ISSUE THREAD

**Issue by TrymTube** [overextended/ox_inventory#1215]
**Describe the bug**
As soon as I am using a Weapon while having Autoreload enabled it sometimes will not reload the weapon.

**To Reproduce**
1. Have Autoreload enabled
2. Give yourself a Weapon. prefered a Pistol ( Combat PIstol )
3. Shoot several times until you have to reload. And dont press "R" to reload
4. If it works try it again and again it should eventually not reload until you'll manually reload

**Expected behavior**
as soon as you have 0 ammo it should automaticly reload

**Comment by TrymTube** [comment]
I have made a video to show that it does not reload. the reason could be that it does not update the ammo in the metadata of the weapon correctly as shown in the video

https://youtu.be/xqEbMJp1foo

**Comment by TrymTube** [comment]
@thelindat Have you noticed?

**Comment by Sojobo** [comment]
This happens when a player is shooting quickly - the weaponAmmo becomes out of sync, you'll notice when you reload you don't actually lose all the bullets you've shot too.

**Comment by Sojobo** [comment]
Changing the following in client.lua fixes this, however it doesn't fix the underlying issue of the ammo metadata falling out of sync;
Before:
`local weaponAmmo = currentWeapon.metadata.ammo`

After:
`local weaponAmmo = GetAmmoInPedWeapon(playerPed, currentWeapon.hash)`

**Comment by TrymTube** [comment]
> Changing the following in client.lua fixes this, however it doesn't fix the underlying issue of the ammo metadata falling out of sync; Before: `local weaponAmmo = currentWeapon.metadata.ammo`
> 
> After: `local weaponAmmo = GetAmmoInPedWeapon(playerPed, currentWeapon.hash)`

Thanks, this fixed it. But why is this not in the inventory itself if there is sync issues?

**Comment by thelindat** [comment]
> > Changing the following in client.lua fixes this, however it doesn't fix the underlying issue of the ammo metadata falling out of sync; Before: `local weaponAmmo = currentWeapon.metadata.ammo`
> > After: `local weaponAmmo = GetAmmoInPedWeapon(playerPed, currentWeapon.hash)`
> 
> Thanks, this fixed it. But why is this not in the inventory itself if there is sync issues?

Because _I cannot reproduce these "sync issues"_. Stop being a pest.

![image](https://user-images.githubusercontent.com/65407488/229256360-134d9387-f731-4198-b4e7-3a70eb045ead.png)

You posting a video and tagging me to ask about it doesn't magically make it occur on my end.

**Comment by thelindat** [comment]
15 minutes of shooting a gun has yielded no results. Look into yourself.

**Comment by TrymTube** [comment]
thanks for calling me a "pest" for reporting a bug which appears for me. This is now resolved. you do good and awesome scripts but as a person by yourself you are horrible sorry to say.

**Comment by thelindat** [comment]
> thanks for calling me a "pest" for reporting a bug which appears for me. This is now resolved. you do good and awesome scripts but as a person by yourself you are horrible sorry to say.

Don’t spam and ask dumb nonsense and you won’t be compared to flies and cockroaches, you pest.
