### ISSUE TITLE
Stash Inventory more Grade Settings

### ISSUE THREAD

**Issue by TrymTube** [overextended/ox_inventory#1216]
**Is your feature request related to a problem? Please describe.**
No, but it can be useful to have this feature.

**Describe the solution you'd like**
A solution that there is a setting that says from which rank you can take something from the warehouse and place it.

**Describe alternatives you've considered**
I would like to have a setting that looks like this.

{
		coords = vec3(482.5, -995.5, 30.7),
		target = {
			loc = vec3(451.25, -994.28, 30.69),
			length = 1.2,
			width = 5.6,
			heading = 0,
			minZ = 29.49,
			maxZ = 32.09,
			label = 'Open personal locker'
		},
		name = 'policelocker',
		label = 'Personal locker',
		owner = true,
		slots = 70,
		weight = 70000,
		groups = shared.police,
                placeGrade = 0,
                removeGrade = 6,
},

`{
		coords = vec3(482.5, -995.5, 30.7),
		target = {
			loc = vec3(451.25, -994.28, 30.69),
			length = 1.2,
			width = 5.6,
			heading = 0,
			minZ = 29.49,
			maxZ = 32.09,
			label = 'Open personal locker'
		},
		name = 'policelocker',
		label = 'Personal locker',
		owner = true,
		slots = 70,
		weight = 70000,
		groups = shared.police,
                placeGrade = 0,
                removeGrade = 6,
},`

**Comment by thelindat** [comment]
https://overextended.github.io/docs/ox_inventory/Functions/Server/Hooks/#swapitems
