### ISSUE TITLE
Hide items in Shops

### ISSUE THREAD

**Issue by TrymTube** [overextended/ox_inventory#1217]
**Is your feature request related to a problem? Please describe.**
No, but it is useful to have this feature

**Describe the solution you'd like**
currently you can set the minimum grade to buy items in shops but I would like to see an additional option to hide the items you can buy for people who have no access to this item

**Comment by TrymTube** [comment]
any information to this?

**Comment by LukeWasTakenn** [comment]
Resolved in commit 653b68d.

Rather than hiding the items which is pretty bad ux, they are instead displayed as disabled, which is slightly better than pretty bad ux.

The reason for why they are disabled should probably be added to the tooltip at some point.
