### ISSUE TITLE
component.client.image doesn't show

### ISSUE THREAD

**Issue by Manason** [overextended/ox_inventory#1222]
**Describe the bug**
setting the client.image field of a component doesn't show the image, instead no image is shown within the item box. This is the same for ammo, and I believe weapons as well. If I swap the blank component with another item in the inventory, the component will borrow the other items' image until it is moved again.

**To Reproduce**
1. set client.image field on a component
2. see that the image despite existing in the path doesn't display in-game

**Expected behavior**
client.image should be the image displayed on the component item in the inventory

**Screenshots**
![image](https://user-images.githubusercontent.com/3579092/227476313-75b87e5f-5e8a-4520-bfc3-d9980271cc07.png)

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/commit/d05e9833a8cdc7c8788a5a14e6053cbbf3e2602b
