### ISSUE TITLE
does not interact with the target

### ISSUE THREAD

**Issue by MachadoGT** [overextended/ox_inventory#1225]
Hello dear dev I use this inventory and I use it in version 2.9.9 and as such I iso does not interact with the qtarget to open car bags organization inventory etc that is several functions in it that I use explain to me why the most recent inventory can't interact with qtarget??? and because it's all for the "E" it's already out of fashion
I want to know how I can have my inventory like it is currently!

https://prnt.sc/lK8vBaH5dQKr

**Comment by thelindat** [comment]
I can barely read this nonsense, but qtarget works perfectly fine in all versions. You also _shouldn't be using qtarget anymore_.

**Comment by MachadoGT** [comment]
so tell me how to use it because i have version 2.9.9 and everything is interacting right tell me when i put the most recent version qtargart stops working

**Comment by MachadoGT** [comment]
why not use it? the target? it's interactive much better than "E"
