### ISSUE TITLE
Viewinv, Viewtrunk , Viewglovebox

### ISSUE THREAD

**Issue by SKULL1985** [overextended/ox_inventory#1226]
**Is your feature request related to a problem? Please describe.**
Would be a nice feature for PD or Admins

**Describe the solution you'd like**
We have viewinv for inventory what is great but no option for glovebox or trucks.
But Would be nice to have /viewtrunk AHT865 and /viewglovebox AHT865  the AHT865 of course being the  licence plate of the vehicle

**Comment by thelindat** [comment]
Inventory is non-specific.
`/viewinv gloveX22647RH`

![image](https://user-images.githubusercontent.com/65407488/227746280-eaee4a95-dc07-4a6a-8063-c6efafcdcb8f.png)
