### ISSUE TITLE
Multiple Access Points for a Stash

### ISSUE THREAD

**Issue by Manason** [overextended/ox_inventory#1227]
**Is your feature request related to a problem? Please describe.**
Would like police stashes to be synced across different stations

**Describe the solution you'd like**
The ability to specify more than one coordinate and target for a given stash so it can be accessed from different locations

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by thelindat** [comment]
In this case, just register the stash server-side without any coords.

**Comment by Manason** [comment]
> In this case, just register the stash server-side without any coords.

The target would still need to be an array rather than a single coord though?

**Comment by Manason** [comment]
Oh I think I see what you mean. Taking the stash outside of the config and just registering it directly via function, then creating a zone and having it open the stash via function.
