### ISSUE TITLE
impossible to take temporary "weapons"

### ISSUE THREAD

**Issue by SleepingFox25** [overextended/ox_inventory#1232]
hello, I have a little problem that I can't solve since I use OX inventory, I use scripts such as the carwash with gun, a fire hose script, or the PlasmaGame from Patoche, but when I try to get one of the weapons or items from these scripts, it picks them up then puts them back down immediately, like it can't add the weapon to the inventory temporarily, do you have a solution for this? Thanks in advance

**To Reproduce**
complicated to explain but for example, for the fire hose script (from London Studio) :
when I approach a fire hydrant, it is written that I can take the hose, so I press E, the lance appears for a micro second in my hands then disappears, same for my carwash script

**Expected behavior**
normally, we should have the fire hose in our hands until we put the hose down at the bollard or the truck. Same for the carwash, you're supposed to keep the water gun in your hands until you put it back at your station

**Screenshots**
Haven't, but can take a video if needed

**Additional context**
Thanks in advance for poeple who can help me, or know the same problem.

**Comment by Manason** [comment]
There is a config option you should disable. This sounds like it's caused by the anti cheat feature

**Comment by thelindat** [comment]
```yml
setr inventory:ignoreweapons ["WEAPON_HOSE"]
```

**Comment by SleepingFox25** [comment]
> 

<3 love you guys, thanks for your help

**Comment by SleepingFox25** [comment]
> ```yaml
> setr inventory:ignoreweapons ["WEAPON_HOSE"]
> ```

Where should i copy it?

**Comment by SleepingFox25** [comment]
> ```yaml
> setr inventory:ignoreweapons ["WEAPON_HOSE"]
> ```

Style go
