### ISSUE TITLE
Opening inventory

### ISSUE THREAD

**Issue by Heaven02200** [overextended/ox_inventory#1237]
Hello, I followed the documentation to install the inventory but it does not open, and I have no error in the F8 nor in the server console, I am under esx legacy 1.3.5

**Comment by thelindat** [comment]
> I followed the documentation to install the inventory
> I am under esx legacy 1.3.5

> Use a compatible version of [ESX Legacy](https://github.com/esx-framework/esx-legacy) (1.6.0+).
