### ISSUE TITLE
There is no way to change the local language of OX inventory

### ISSUE THREAD

**Issue by RashRashkw** [overextended/ox_inventory#1241]
Hello Developers
I need help please
There is no way to change the local language of OX inventory

with Regards 
Rashid

**Comment by LukeWasTakenn** [comment]
Hello developer,

There is indeed a way to change the locale language for ox_inventory.

With kind regards,
Luke

**Comment by RashRashkw** [comment]
can you please tell me where i can find the locale language for ox_inventory.
