### ISSUE TITLE
ox shop bug

### ISSUE THREAD

**Issue by VinnyPLV** [overextended/ox_inventory#1243]
**Describe the bug**
If you try to buy an item by ox shop system, and try to stack it, if you have a job where place it in addon_account_data, the player dont waste money, you will get a message where you cannot stack  the item but the money go on the db.

**To Reproduce**
1. Do a ox shop to a job
2. Try to stack a similiar item
3. Get the error on the client where you cannot stack the item
4. See the database and all the time you get the error the addon_account_data will be more and more.

**Expected behavior**
Simply he need to not add the money on the addon_account_data.

**Screenshots**
If request i'll do a video.

**Additional context**
Im using wasabi_oxshop for the tests.

**Comment by thelindat** [comment]
ox_inventory doesn't interact with addon_account_data at all; this sounds more like a bug with wasabi's resource.
