### ISSUE TITLE
GetItem Count Bug

### ISSUE THREAD

**Issue by ynnniV** [overextended/ox_inventory#1244]
**Describe the bug**
When you try to sold the item of the shop in your inventory and maybe in the shop is like more than 10 and you stack it into another item of your inventory the "count" of the ox_inventory:GetItems go down when into the shop is always 10 and not 9/8 etc..

**To Reproduce**
1. Build a shop and into it try to do a print of the GetItem
2. On the console, because is the server side, you will see the problem, the count going down
3. Count going down but in game is always UP at what you cannot buy it.

**Expected behavior**
Just the right count, if there is 10 and i dont buy it because i did a wrong stack he need to remain 10 not 9/8/etc.. as always he do.

**Screenshots**
I'll do a video if need it.

**Additional context**
As always based on Wasabi Shops, but he call the ox_inventory and the print is from the ox_inventory. I dont think is a Wasabi fault here. Because like that people can try to hardcode this part: https://github.com/overextended/ox_inventory/issues/1243. Maybe is a Wasabi's script fault of the last report.. but here i dont think so. Try to replicate it.

**Comment by thelindat** [comment]
> Build a shop and into it try to do a print of the GetItem

GetItem doesn't work on shops.

**Comment by VinnyPLV** [comment]
Ok, what can i use to know how much item i've into the shop?

Because he start good, but always doing down.

**Comment by thelindat** [comment]
I'm struggling to make sense of your bug description. Show code and a video; though if it _only_ happens with wasabi's shops then it's an issue there and not here.

**Comment by thelindat** [comment]
This is, again, an issue with wasabi_oxshops that @wasabirobby needs to resolve.

The createItem hook doesn't guarantee an item is added to a player, as things like slot validation, stacking checks, etc. always occur after triggering it; it's only intended for modifying metadata of an item (and potentially preventing it from being created).

https://github.com/overextended/ox_inventory/blob/0901a5e881f7803beed5befe930c79f4d52a7439/modules/shops/server.lua#L229-L232

A buyItem hook exists now anyway, making it even easier to fix the weird logic here.

https://github.com/overextended/ox_inventory/blob/0901a5e881f7803beed5befe930c79f4d52a7439/modules/shops/server.lua#L245-L257
