### ISSUE TITLE
Licenses item 

### ISSUE THREAD

**Issue by bbeckann** [overextended/ox_inventory#1245]
hello first I want to thank you for the beautiful work for the fivem community.

I would like to see an item for a weapons license.. as soon as you buy a license the item goes into your inventory. as if it were a real document. currently i use this script for this would be a great idea.

![image](https://user-images.githubusercontent.com/95275692/230277648-068bfd2e-7543-46ca-a7f8-b110b843992a.png)

https://github.com/alp1x/um-idcard

**Comment by thelindat** [comment]
I have no reason to add licenses as a base item in this resource; even the identification that exists currently is intended to be deleted in a future update.

**Comment by frafifauzi95** [comment]
you can youse also this resource for license, only modified litle bit from shops/server.lua 
function server.hasLicense(playerInv, license)
				-- print("Memeriksa lisensi...")
				-- print("Parameter playerInv:", playerInv)
				-- print("Parameter license:", license)
				
				if playerInv and license then
					-- Iterasi melalui setiap item dalam playerInv
					for slot, item in pairs(playerInv.items) do
						-- Periksa jika item memiliki metadata dan cardtype yang sesuai dengan license
						if item.metadata and item.metadata.cardtype == license then
							-- print("Lisensi ditemukan:", item)
							return true
						end
					end
				end
				
				-- Kembalikan false jika lisensi tidak ditemukan
				return false
			end
this ist for snippset add it in line 214
