### ISSUE TITLE
Crafting Reputation

### ISSUE THREAD

**Issue by Manason** [overextended/ox_inventory#1257]
**Is your feature request related to a problem? Please describe.**
qb-inventory has a crafting reputation system, which I would like to continue using after switching to ox_inventory

**Describe the solution you'd like**
- player has a reputation level specific to each crafting table
- within the crafting config, crafting a specific item can require a certain reputation, and can give reputation

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Mesrine67** [comment]
Too bad the suggestion wasn't taken into account, it would have been a great addition.
