### ISSUE TITLE
okokCrafting (undefined items) 

### ISSUE THREAD

**Issue by Twinded** [overextended/ox_inventory#1259]
Hi guys, I have the same issue.

Im trying to setup my okokCrafting with ox_inventory. okok is trying to find the items in db and not inside the ox items.

However I'm banned from your discord server and I don't no why ˆˆ

Can you help me ?

Thanks !

![image](https://user-images.githubusercontent.com/17770855/231429684-58f690a8-7848-41b6-882e-38201fe93207.png)
![image](https://user-images.githubusercontent.com/17770855/231429801-76037c44-7d76-4b05-b7c6-4e53abb47a29.png)

**Comment by Twinded** [comment]
I've had this from an same other issue in the `sv_utils.lua` of okokCrafting.

#518 

But the problem isn't resolved.

**Comment by thelindat** [comment]
Don't care.

**Comment by Twinded** [comment]
You don't help me for this issue ?

**Comment by thelindat** [comment]
No, because the issue exists thanks to okok using bad practices and not because of ox_inventory itself. Everyone else that uses the snippet finds it works; if it doesn't (may okok changed something) it's up to him to fix the scripts he _sells_.

**Comment by Twinded** [comment]
Okay, thank you for that clarification.

One last thing, can you help me with my inability to join your discord server? The latter indicates to me to be banned whereas I had never joined it before.

**Comment by thelindat** [comment]
Not without a discord id, but the ban will be due to Warden.
