### ISSUE TITLE
Unable to access drops/give items?

### ISSUE THREAD

**Issue by arlofonseca** [overextended/ox_inventory#1264]
**Describe the bug**
Hello! A lot of people have been bringing to my attention that they are unable to give people items & be able to pick items up that are dropped on the floor. I personally have not found any active reproduction steps for this which I know will make this whole process even harder, or damn near impossible to fix; but I just don't know how else to go about this. I tried to reset the player(s) inventory from the database & still have had no luck, the people who I have attempted to help still seem to be having the same issue.

**Expected behavior**
-> Be able to give player(s) items
-> Be able to pick up items that were dropped on the floor

**Screenshots**
#1 
![image](https://user-images.githubusercontent.com/110794635/232249241-872365cc-d586-42c7-b1aa-8b46a793762a.png)
#2 
![image](https://user-images.githubusercontent.com/110794635/232249265-bdabdbb9-1b37-45b1-9981-0729749f9d98.png)
#3 
![image](https://user-images.githubusercontent.com/110794635/232249287-d15a7a3c-e9c6-4206-b52e-d293310f579b.png)
#4 
![image](https://user-images.githubusercontent.com/110794635/232249356-c31386de-b51b-48e5-bf3f-28c213fe4ccd.png)
#5 
![image](https://user-images.githubusercontent.com/110794635/232249401-be728ce5-352e-4e30-88ca-4d7913a4b206.png)
#6 
![image](https://user-images.githubusercontent.com/110794635/232249469-75be2201-4d30-486a-8b69-579345fd760f.png)
#7 
![image](https://user-images.githubusercontent.com/110794635/232249546-5270ffcf-4f62-4ac2-9c6c-a3d69084c0e9.png)

**Additional context**
There is a ton of other screenshots of people complaining about it but I didn't want to spam it. This seemed to start happening upon updating to the latest release. Didn't see/hear of any reports pertaining to this prior. I am using the latest versions of all ox resources, and if this next part even matters, the server averages 200 player(s).

Server Version: 6386
Build: 2699

**Comment by thelindat** [comment]
> upon updating to the latest release

Nothing has changed recently with that, and this is the first report of it. Sounds like client and server inventory state was desynced but no info/repro and no other complaints.

If you're using any inventory hooks I'd recommend checking there, also.

**Comment by jvstin2k** [comment]
I have the same problem rn, we cant give Items to other players or search them.

**Comment by MrNewb** [comment]
giving items to nearby players as well as searching is problematic for me as well, no errors but seems to always say its unable to access that inventory. I do have list nearby players set on. I dont utilize any hooks and am on qb myself.

**Comment by thelindat** [comment]
Sounds like the people complaining about give not working were giving items to people with open inventories, which wasn’t allowed previously.

Unreleased commits aren’t really intended for production though, so be careful with that. Need to rebuild ui too if you didn’t.
