### ISSUE TITLE
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/items/server.lua:142: bad argument #1 to 'find' (string expected, got nil)

### ISSUE THREAD

**Issue by HiTTA757** [overextended/ox_inventory#1268]
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/items/server.lua:142: bad argument #1 to 'find' (string expected, got nil)

**Comment by thelindat** [comment]
Improperly formatted items in your qbcore (no name property).
