### ISSUE TITLE
Issue with updating weapon durability when using SetDurability 

### ISSUE THREAD

**Issue by Thunderwolfx** [overextended/ox_inventory#1270]
**Describe the bug**
When using SetDurability on a weapon that is at 0 durability, the weapon durability does not change unless you drop the weapon on the ground and pick it back up or reload.

**To Reproduce**
1. Ensure weapon durability is at 0.
2. Attempt to set the weapon durability using;
```
local weapon = exports.ox_inventory:GetCurrentWeapon(source)
if weapon then
	exports.ox_inventory:SetDurability(source, weapon.slot, 100)
end
```

**Expected behavior**
The durability to reflect the new value as soon as the new durability is set i.e., not having to drop or move the weapon outside of the inventory and back in.

**Additional context**
No errors print.
Using ESX Legacy v1.8.5.
Using ox_inventory [v2.27.1](https://github.com/overextended/ox_inventory/releases/tag/v2.27.1).

**Comment by Thunderwolfx** [comment]
Can confirm this sometimes happens when the durability is not always at 0 i.e., attempting to set durability back to 100 when it is at approx 80.

I have had some rare instances where I am unable to replicate this myself but 9 times out of 10 I can replicate.

**Comment by SoCallMeAstro** [comment]
Yeah I was running into this issue as well, tried a bunch of different things to try to get it to update the durability, for me it wasn't updating at all unless I swapped the slots, re-opened the inventory, or moved it to a drop container. 

I was able to find a way to get it to update, right before the durability gets set, on the client side, I have it using the export useSlot, to put the weapon away, and the durability always gets updated always now .

`exports.ox_inventory:useSlot(slot)`
