### ISSUE TITLE
Unable to give item

### ISSUE THREAD

**Issue by jvstin2k** [overextended/ox_inventory#1271]
**Describe the bug**
When trying to give Items to other players, we get an error saying "Unable to give 1 (name of the item) to the target"

**To Reproduce**
1. Go to 'Inventory'
2. Click on 'Any Item'
3. Try to give it to someone
4. See error -> "Unable to give 1 (name of the item) to the target"

**Expected behavior**
Normally you would give the selected item to the selected player. 

**Screenshots**
![image](https://user-images.githubusercontent.com/54100497/232895972-6b66491e-8e38-455e-86b1-584d2bb80559.png)

**Additional context**
Same happens for trying to search someone, wich already worked without problems.

**Comment by thelindat** [comment]
I don't know why you posted on an existing issue and _then_ posted this dupicate issue. Not even a repro.
![image](https://user-images.githubusercontent.com/65407488/232911453-e5faacc8-b1db-45fb-ba45-666c298111f8.png)
