### ISSUE TITLE
Nagative Cash/money

### ISSUE THREAD

**Issue by M1nTd** [overextended/ox_inventory#1276]
When players in my server gets nagative amount of cash it dups when adding it back from there bank account

**Comment by thelindat** [comment]
Ah yes, negative cash makes a lot of sense.

**Comment by M1nTd** [comment]
> Ah yes, negative cash makes a lot of sense.

U know a fix for that?

**Comment by thelindat** [comment]
Check if people have cash before using cash?

**Comment by M1nTd** [comment]
> Check if people have cash before using cash?

For example they have -350 cash and when they wanna add money from there bank account from example they add 350 from there account the cash goes upto 700 and not 0

**Comment by thelindat** [comment]
> > Check if people have cash before using cash?
> 
> For example they have -350 cash and when they wanna add money from there bank account from example they add 350 from there account the cash goes upto 700 and not 0

Have you ever physically held onto negative money? Probably not, no?
When you go to purchase something irl with cash, they'll ask you for money - if you don't have it, you don't get the thing. Not my fault if you're charging people money for things without checking they have money in the first place.
