### ISSUE TITLE
Inventory UI Issue 

### ISSUE THREAD

**Issue by dontaythedon** [overextended/ox_inventory#1279]
**Describe the bug**
I've installed everything down to the point. At least i would believe i did. Installed the updated ox_lib. I installed the ox_inventory. Read the UI issue tried the bundled ox_inventory which was just the current updated inventory. I installed the inventory and target after es_extended. I sourced the inventory.cfg file as well. I really need help i just dont know where im going wrong at this point. 

**To Reproduce**
Simply refreshing and running the server.

**Additional context**
![Capture1](https://user-images.githubusercontent.com/76893439/234406513-4425b64a-abe8-4e82-94e7-28807ac28dd9.PNG)
![Capture2](https://user-images.githubusercontent.com/76893439/234406550-138f96fa-1c0f-4b73-beb7-4d2fcc0f3e21.PNG)
![Capture3](https://user-images.githubusercontent.com/76893439/234406564-57547687-3bbc-45a7-8415-557cd322eee0.PNG)

**Comment by thelindat** [comment]
Why don't you read? Reading solves many problems - like the error messages printed in console; they tell you the problem and even give you a link to download. Instead you ignore them and repeatedly download the repository source code, and then ask why it doesn't work.
