### ISSUE TITLE
Prevent using items or accessing inventory while playing a death animation

### ISSUE THREAD

**Issue by Manason** [overextended/ox_inventory#1283]
**Is your feature request related to a problem? Please describe.**
Downed players can use items and access their inventory

**Describe the solution you'd like**
Similar to https://overextended.github.io/docs/ox_inventory/Functions/Client/openNearbyInventory, prevent players who are fatally injured or playing a death animation from using items or accessing inventory

**Describe alternatives you've considered**
Disabling the inventory keys from the medical script

**Additional context**
N/A

**Comment by thelindat** [comment]
Mark the player as dead, since they're "dead".
