### ISSUE TITLE
Bug with helicopter reload passenger's side

### ISSUE THREAD

**Issue by Tinky124** [overextended/ox_inventory#1287]
**Describe the bug**
The current problem is the firing of weapons from the heli on the passenger's side, that means when I take a carbine rifle or an assault rifle as a weapon, it fires, then after a while the weapons simply disappear and you can't shoot anything or reload weapons, it just happens in other helis that don't work on the heli normally, on maverick or frogger, polmav does not reload on weapons, tested on the last version of inventory, I would like to solve this problem, thank you very much and the inventory is excellent!

**To Reproduce**
1. Spawn weapon carabine rifle or assultrifle and spawn ammo for them : ammo-rifle2
2. Spawn helicopter maverick, frogger, polmav, police heli
3. Go to passenger's side back seat of heli
4. Shoot in the back seat until you run out of bullets

**Expected behavior**
It should automatically reload weapons and not take it out of hand and be reloadable on R.

**Screenshot/Video**
https://youtu.be/9bzbqQowXk8

**Additional context**
I don`t have.

**Comment by florijanftw** [comment]
Yes same issue here please help
