### ISSUE TITLE
Add Discord Webhooks logs

### ISSUE THREAD

**Issue by BulleSierra** [overextended/ox_inventory#1288]
Hi is it possible to add discord logs with webhooks for this:
-For every add/remove from stashes
-For every add/remove from vehicles
-For every give (player to player)
-For every people who took item from other player inventory
-For every craft
-For every item bought

I don't know if the list is complete... (i'm sorry i don't have everything in mind)
Maybe Have the possibility to activate or not each option

This could be really usefull for people who don't want to edit the code but have a big server and need every logs

Thank you so much for reading and for your scripts

**Comment by jag3dagster** [comment]
Discord is not a logging solution. This will not get implemented.

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/issues/773 https://github.com/overextended/ox_inventory/issues/953 https://github.com/overextended/ox_inventory/issues/1030 https://github.com/overextended/ox_inventory/issues/1213

Not sure why you thought your request would be different.
