### ISSUE TITLE
Bug disable control when using item like armour or bandage.

### ISSUE THREAD

**Issue by nnhieutrung** [overextended/ox_inventory#1289]
Hi I am found a issue that if using armour or bandage with be blocked enter Vehicle after that.
I have try debug that the disable add have triggered 3 time but remove only 2 time so is still disabled.

![image](https://user-images.githubusercontent.com/67868869/234940236-448c413d-1cce-4ca8-a212-1c0b08e5952d.png)

**Comment by thelindat** [comment]
Statebag handler shouldn't even trigger unless the value changes, but god knows what's happening with them anymore.
