### ISSUE TITLE
Require item to buy.

### ISSUE THREAD

**Issue by BIGSHAWN2** [overextended/ox_inventory#1290]
Make it so you can allow people to buy things from stores, but they have to have certain items. EX: You want to buy something from the store, like cigarettes or any tabacco/alcohol products, but you need an ID card.

Required item: id_card
Item to buy: redwood_cigs

**Comment by BIGSHAWN2** [comment]
Also, I see that you want to remove the license system in the near-future, but this could also work with gun licenses for the people that do want to keep that feature in. Also allows Police to remove the license from the player aswell.

**Comment by thelindat** [comment]
https://overextended.github.io/docs/ox_inventory/Functions/Server/Hooks/#buyitem

```lua
local hookId = exports.ox_inventory:registerHook('buyItem', function(payload)
    if exports.ox_inventory:GetItem(payload.source, 'id_card', nil, true) < 1 then return false end

    print(json.encode(payload, { indent = true, sort_keys = true }))
end, {
    print = true,
    itemFilter = {
        redwood_cigs = true
      },
})
```
