### ISSUE TITLE
Discord Issue

### ISSUE THREAD

**Issue by Beauty9617** [overextended/ox_inventory#1293]
**Describe the bug**
Hello, I was in the discord with some support threads opened, a few days ago i noticed i couldnt find the discord. I also cant rejoin. Not sure why as i didnt do anything to get banned. 
**Framework**
The framework your server uses for players (e.g. Ox, ESX, QB).
ESX
**Resource version**
The version number listed in fxmanifest.lua, or optionally a commit hash.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thelindat** [comment]
Probably banned by https://discord.gg/jeFeDRasfs, but you neglected to post your discord id so how should I know?
