### ISSUE TITLE
reviving breaks gun ammo

### ISSUE THREAD

**Issue by Manason** [overextended/ox_inventory#1296]
**Describe the bug**
Going down with a gun in the hand and then being revived breaks the way ammo is handled. It seems to recalculate the ammo in the current magazine and the ammo in the gun, as well as not recognizing any additional ammo in my inventory from that point forward.

**Framework**
QB

**Resource version**
2.28.2

**To Reproduce**
1. Have a firearm in hand
2. injure yourself to go down
3. revive yourself

**Expected behavior**

**Screenshots**
[Short Video](https://medal.tv/games/gta-v/clips/17fQ22BmUkd-vh/d1337EkyvuIH?invite=cr-MSxKQ1YsMTQ2MTQ2NTMyLA)

**Additional context**
I originally looked into this because a player reported to me that they could only load 1 round at a time into their rifle that should hold 30 rounds. I couldn't reproduce that issue, but then randomly found this.

**Comment by thelindat** [comment]
I can't repro this. Could be something with qb, another 3rd party resource, or whatever you've changed to allow weapon overloading?

**Comment by Manason** [comment]
weapon overloading? I haven't changed anything related to that. This is most related to QB in some way. I'll try to do some more digging on my end.

**Comment by thelindat** [comment]
> weapon overloading? I haven't changed anything related to that.

![image](https://user-images.githubusercontent.com/65407488/235410221-299bd2cf-8512-434d-a009-85cf1b6cc6b0.png)

Weapons shouldn't exceed clip size.

**Comment by Manason** [comment]
> > weapon overloading? I haven't changed anything related to that.
> 
> ![image](https://user-images.githubusercontent.com/65407488/235410221-299bd2cf-8512-434d-a009-85cf1b6cc6b0.png)
> 
> Weapons shouldn't exceed clip size.

Ah. I'll have to figure out what's causing that.

**Comment by FilipeCuco** [comment]
i have the same problem

**Comment by jag3dagster** [comment]
> i have the same problem

But do you have any additional information that could actually be helpful and lead to a fix? Such as new reproducible steps, conditions, situations, weapons... anything?

**Comment by paruthepro** [comment]
The issue relates to the weapon itself, dropping the weapon and then picking it back up fixes the issue, I have had the same issue with QBox for quite some time but only when using /revive, its possibly related to death handling within QB.

**Comment by FilipeCuco** [comment]
> > i have the same problem
> 
> But do you have any additional information that could actually be helpful and lead to a fix? Such as new reproducible steps, conditions, situations, weapons... anything?

the bug only occurs in gamebuild 2802

**Comment by FilipeCuco** [comment]
I have looked into it and you need to do the following:

qb-ambulancejob:
go to qb-ambulancejob/client/dead.lua

and add this   TriggerEvent("ox_inventory:disarm")   to the line 18

qbx-ambulancejob:
go to qb-ambulancejob/client/dead.lua

and add this   TriggerEvent("ox_inventory:disarm")   to the line 16

wasabi-ambulancejob:
go to wasabi-ambulancejob/client/cl_customize.lua

in the OnPlayerDeath function under TriggerServerEvent("wasabi-ambulancejob:setDeathStatus", true) add TriggerEvent("ox_inventory:disarm")

**Comment by thelindat** [comment]
Is this related to your "last stand" PR?
