### ISSUE TITLE
Duplicating items

### ISSUE THREAD

**Issue by Diggera** [overextended/ox_inventory#1305]
**Describe the bug**
Dropping items, putting them in car, or if another player take it, u just make alt + f4, come back and items are back... Players can duplicate items that way as manytimes they want.

**Framework**
ESX

**Resource version**
version      '2.28.3' is bugged one, 
i changed it to version      '2.26.1' cuz that's one was on server before i made update and its not posible on this one

**To Reproduce**
1. Empty your inventory
2. alt + f4 out of game
3. Get back in game
4. Collect previously dropped items or do it again

I dont have pictures if i need to make them Iam more that happy to maker them but i guess it's pretty clear whats happening

**Comment by thelindat** [comment]
> version '2.28.3' is bugged one

Yes, and it isn't the latest version. https://github.com/overextended/ox_inventory/releases/tag/v2.28.4

This was an issue for frameworks that handle player inventory saving themselves (i.e. ESX) for a single patch.
