### ISSUE TITLE
Inventory NUI error

### ISSUE THREAD

**Issue by DyroS3** [overextended/ox_inventory#1309]
**Describe the bug**
When I buy and get items, I get an error in the picture
(Not sure if this happens on every server).

**Framework**
ESX

**Resource version**
2.28.4

**To Reproduce**
1. Go to anyshops or use giveitem command
2. then F8 show: 
![image](https://user-images.githubusercontent.com/64310374/236976102-fbc1b1d9-f080-47f4-bbac-474a2ce4b854.png)

**Expected behavior**

**Screenshots**
[streamable for this](https://streamable.com/rewzrs).

**Additional context**
None

**Comment by thelindat** [comment]
This isn't something that can be repro'd with the source code or the release build.

**Comment by DyroS3** [comment]
this is maybe only for me? What do you mean

**Comment by DyroS3** [comment]
> This isn't something that can be repro'd with the source code or the release build.

this is maybe only for me? What do you mean

**Comment by thelindat** [comment]
Did you figure something out?

**Comment by DyroS3** [comment]
> Did you figure something out?

yep, make it work
