### ISSUE TITLE
degrade/CONSUME

### ISSUE THREAD

**Issue by jesuisjoszi** [overextended/ox_inventory#1315]
ESX
version      '2.27.1'

hello, it's probably a bug or there is another solution but I don't see it in the documentation.

```
['ht'] = {
label = 'Heart Stopper',
weight = 50,
degrade= 100,
clients = {
anim = 'eating',
prop = 'burger',
usetime = 2500,
export = 'avac_food.avacfoodcompany'
},
consume = 0.5,
stack = true,
close = true,
description = 'Good tasting HeartStopper'
},

```
, everything is fine, but when the degrade is at 0, there is a notification that it cannot be used, but the export goes on, I don't know, is there any solution to block the use of the item despite its degrade to 0?

**Comment by thelindat** [comment]
> It's about mom and dad

huh

> but the export goes on

well show your code for the export.

**Comment by jesuisjoszi** [comment]
```
exports('avacfoodcompany', function(data, slot)
  ox_inventory:useItem(data, function(data)
    if data then 
      
      TriggerEvent('esx_status:getStatus', 'hunger', function(status)
        if status.val < 400000 then -- 500000
          TriggerServerEvent('avac:client:UpdateStatus', 'hunger', 100000)
        else
          print("stop")
      end
    end)
    end
  end)
end)
```

**Comment by jesuisjoszi** [comment]
in short, I mean that the depletion of the item catches at 9-8 degrade and despite this I can use the item further and if the degrade is 0 then I can't, I just need 9-8 at the same time

**Comment by thelindat** [comment]
I have no idea what you're trying to say. 9-8 degrade?

> I can use the item further and if the degrade is 0 then I can't

Yes? Huh?

**Comment by jesuisjoszi** [comment]
![image](https://github.com/overextended/ox_inventory/assets/50300794/8afb2a5d-9b32-4709-bad8-06b782da6071)

**Comment by jesuisjoszi** [comment]
![image](https://github.com/overextended/ox_inventory/assets/50300794/a064acfa-cdef-47e3-973e-0af651ef5b8a)

**Comment by jesuisjoszi** [comment]
In short, if an item has a durability of 7 and, after use, it returns the notification "item depleted," it still allows the export written in items.lua to pass through. However, I need it to not allow the export after receiving this notification indicating that the item is depleted.

**Comment by jesuisjoszi** [comment]
Is there a chance to make something work in this matter or find a solution?
