### ISSUE TITLE
Character identifier XXXX is already active

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_inventory#1318]
**Describe the bug**
sometimes players lost connection to the server and when there try to reconnect it will get this error and we can't do anything. 

**Framework**
Qbox

**Resource version**
2.29.2

**Screenshots**
![image](https://github.com/overextended/ox_inventory/assets/35350615/b02a74e3-23b6-4eaf-a098-38a8e6957ec4)

**Additional context**
When I search for the text it brings me to ox_inv in this case there is something in ox_inv and I hope you can help me with it.

**Comment by soniXx123** [comment]
![image](https://github.com/overextended/ox_inventory/assets/35350615/91f9e142-0377-4b66-a2b7-258dcf63d41b)

**Comment by soniXx123** [comment]
I don't know. We have players there who get a crash (internet connection) and after this, there can't join anymore. There need to wait for the next restart. 

Sorry, this is all I have...

**Comment by DonPoedel** [comment]
`--- To create a stash, please use `exports.ox_inventory:RegisterStash` instead.
function Inventory.Create(id, label, invType, slots, weight, maxWeight, owner, items, groups)
	if invType == 'player' then
		if activeIdentifiers[owner] then
			DropPlayer(tostring(id), ("Character identifier '%s' is already active."):format(owner))
		end
		-- if activeIdentifiers[owner] then
		-- 	DropPlayer(tostring(id), ("Character identifier '%s' is already active."):format(owner))
		-- end

		activeIdentifiers[owner] = 1
	end`

Fixed it for me.

**Comment by thelindat** [comment]
> \ox_inventory\modules\inventory\server.lua Fixed it for me.

Did the definition of "fix" change recently? This _disables_ a vital security check.

Did you know you can easily bypass both ESX's and QB's "active identifier check" and login as the same character twice? I also _already_ committed a change that should mitigate instances where the identifier isn't cleared up (but since I can't repro it, I can't test it and close the issue). The link is _right above your comment_.

https://github.com/overextended/ox_inventory/commit/2d591ca471b62d623b7241b7ced437b97c74a4d2

**Comment by soniXx123** [comment]
yeah i saw the change. i will test it today and let you know.

**Comment by thelindat** [comment]
> yeah i saw the change. i will test it today and let you know.

Any issues?

**Comment by DonPoedel** [comment]
> > \ox_inventory\modules\inventory\server.lua Fixed it for me.
> 
> Did the definition of "fix" change recently? This _disables_ a vital security check.
> 
> Did you know you can easily bypass both ESX's and QB's "active identifier check" and login as the same character twice? I also _already_ committed a change that should mitigate instances where the identifier isn't cleared up (but since I can't repro it, I can't test it and close the issue). The link is _right above your comment_.
> 
> [2d591ca](https://github.com/overextended/ox_inventory/commit/2d591ca471b62d623b7241b7ced437b97c74a4d2)
> 
> ![image](https://user-images.githubusercontent.com/65407488/239432460-edda4a0b-7d8a-47a8-8fc7-a83d7c7e13bb.png)

I should have clarified that I have 2 other checks running in custom scripts.

**Comment by soniXx123** [comment]
Still with the latest update on QB

![image](https://github.com/overextended/ox_inventory/assets/35350615/e1c0d5fb-b88b-485f-a509-b520987076bc)

**Comment by thelindat** [comment]
> Still with the latest update on QB
> 
> ![image](https://user-images.githubusercontent.com/35350615/239990617-e1c0d5fb-b88b-485f-a509-b520987076bc.png)

Are you able to check their old serverId and the result of GetPlayerEndpoint? At this point I don't see how it can be getting stuck from code.

**Comment by thelindat** [comment]
@soniXx123

I can see this is a very serious and high-priority issue for you and your server, based on your ability to provide nothing for a week.

**Comment by soniXx123** [comment]
Hi @thelindat sorry i was not there. I will have a look today with your new Update and i will send you an feedback.

**Comment by thelindat** [comment]
???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
