### ISSUE TITLE
Stashes Issues

### ISSUE THREAD

**Issue by brandondbcc** [overextended/ox_inventory#1319]
HI, currently having an issue with ox_inventory the last few days. When restarting scheduled or just normally my house stashes if they have 2 different lockers in the database they merge into one & only keep 1 of the contents [LOAF_HOUSING]

My job stashes also all do the same but they are for everyone police, gangs etc all have the same after a restart [jobs_creator by jaksam] what I use for the stashes any ideas?

Thanks in advance appreciate your time 

Below is how they're saving in the database when they are the same.

![image](https://github.com/overextended/ox_inventory/assets/79037822/049d91c4-7f61-4f85-b286-b0b0d3f8859c)

**Comment by brandondbcc** [comment]
These was all working perfectly fine before but now they are having issues.

**Comment by brandondbcc** [comment]
Its been happening since 14/03/2023, tried using the scheduled restarts & tried using normal both are doing the same thing i can provide a clip of me putting other stuff in the other storage if you wish & then it saving as the same

**Comment by thelindat** [comment]
A date is meaningless.

**Comment by brandondbcc** [comment]
Since the latest version I updated to I believe its that, as I haven't changed anything else in the server but update the inventory.

**Comment by thelindat** [comment]
and your previous version was .........?
and your framework is ........?

I need information.

**Comment by brandondbcc** [comment]
Version Before = V2.28.4
Version I'm Using Now = V2.29.2
Framework = ESX Legacy 1.8.5

**Comment by thelindat** [comment]
and does reverting inventory version resolve the issue you're experiencing?

**Comment by BMOREGTA** [comment]
Hey @thelindat  i see that you do Fivem i was wondering if you have time if you can contact me about a lil help on installing some of these ox_mods and of course i wouldn't mind tipping you for your time if your interested let me know thanks if you have a discord let me know thanks
