### ISSUE TITLE
Error when shooting a taser

### ISSUE THREAD

**Issue by FieryPig22YT** [overextended/ox_inventory#1320]
**Describe the bug**
An error occurs when shooting a stun gun.

**Framework**
ESX

**To Reproduce**
Shoot a stun gun says this:

**Expected behavior**
No error

**Additional context**
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:2393: attempt to compare number with nil
[ script:ox_inventory] > updateWeapon (@ox_inventory/modules/inventory/server.lua:2393)
[ script:ox_inventory] > handler (@ox_inventory/modules/inventory/server.lua:2419)

**Comment by thelindat** [comment]
_Suuuper_  appreciative of you leaving out important important like resource version. There's also _no error_ when I've tested the stungun several times over the past month.

**Comment by FieryPig22YT** [comment]
> 

My bad. The version is the latest one.

**Comment by thelindat** [comment]
> > 
> 
> My bad. The version is the latest one.

Nope, and like I said _no error_.

https://github.com/overextended/ox_inventory/blob/514e337d81a63d2999b65ccfffa5ecc30c2bfa9e/modules/inventory/server.lua#L2393

**Comment by FieryPig22YT** [comment]
Hmmm. Maybe the problem is just for me. I'll see if there's something wrong on my side.
