### ISSUE TITLE
Weapon wheel activation etc.

### ISSUE THREAD

**Issue by EinfachKlexy** [overextended/ox_inventory#1322]
**Describe the bug**
I do not know exactly how the error occurs. You get an error in F8 and all of a sudden you have a weapon wheel and when you are in inventory and want to use something, you hit players etc.

**Framework**
ESX

**Resource version**
2.27.1

**To Reproduce**
https://cdn.discordapp.com/attachments/1026531827315392532/1109228820629835836/fivem-by-cfx_dMwkzkcR.mp4

**Expected behavior**
That I can use the inventory normally

**Screenshots**
https://cdn.discordapp.com/attachments/1026531827315392532/1109228820629835836/fivem-by-cfx_dMwkzkcR.mp4

**Additional context**
/

**Comment by thelindat** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> https://cdn.discordapp.com/attachments/1026531827315392532/1109228820629835836/fivem-by-cfx_dMwkzkcR.mp4

This isn't _steps_, it's a video; which you linked twice. Update your inventory to a more recent version.

**Comment by EinfachKlexy** [comment]
Thank you for the answer :)
