### ISSUE TITLE
search do play's bag

### ISSUE THREAD

**Issue by bbeckann** [overextended/ox_inventory#1324]
Hi how are you ? I would like to clear a doubt, I have not seen anything like this .. to really open the inventory of the player who wants to steal it or even a job as a policeman. Thanks for the feedback.

**Comment by thelindat** [comment]
English, please.

**Comment by FjamZoo** [comment]
> English, please.

He wants to know how to open another players inventory to steal their items

**Comment by thelindat** [comment]
https://overextended.github.io/docs/ox_inventory/Functions/Client/openNearbyInventory/

`/steal`
