### ISSUE TITLE
Weight limit issues

### ISSUE THREAD

**Issue by lexinor** [overextended/ox_inventory#1333]
**Is your feature request related to a problem? Please describe.**
Hey, I've made my own adaptation of the bag system where when you wear a bag (only one allowed) your weight is increased and when you drop the bag it goes bag to normal but I've having an issue where when I have a full bag dropped, when I want to get it back I've having reaching weight limit and I can't find a way to increase wait just before the inventory block it. 

**Describe the solution you'd like**
I would have loved a way to bypass the weight limit

**Describe alternatives you've considered**
IMaybe by creating a hook system like the swapItems or buyItem that is triggered just when we check for the weight limit

**Comment by thelindat** [comment]
Just set the player weight in your hook?

**Comment by lexinor** [comment]
> Just set the player weight in your hook?

I did in the swapItem one and also the buyItem but after that it seems that these two are not triggered when weight limit is reached

**Comment by lexinor** [comment]
@thelindat Why you closed that ?
