### ISSUE TITLE
Inventory UI not displaying for trunks

### ISSUE THREAD

**Issue by Thunderwolfx** [overextended/ox_inventory#1339]
**Describe the bug**
When using the same keybind to open the primary inventory and secondary inventory (i.e., trunk) you are unable to access a trunk after opening it initially.

**Framework**
ESX

**Resource version**
2.30.1 (happening since approx. V2.30.0)

**To Reproduce**
1. Ensure keybind is the same for bothe main and secondary inventory (in this example the key is 'K' for both trunk and main inventory.
2.  Open a trunk
3.  Close the trunk
4.  Open the trunk again -- at this point you should be presented with a blurry screen and the inventory UI will not display, although sometimes it will occur on the first time you access the trunk.

**Expected behavior**

**Screenshots**
https://cdn.discordapp.com/attachments/890155848268132382/1113241898732236800/image.png

**Comment by thelindat** [comment]
> When using the same keybind to open the primary inventory and secondary inventory

_Don't._ It has never been supported, and if it ever temporarily worked - which it did not at the start and for a long period of time - it was not intended. You're triggering two asynchronous threads which will end in a race condition and unexpected behaviour.

https://github.com/overextended/ox_inventory/issues/706
https://github.com/overextended/ox_inventory/pull/624
