### ISSUE TITLE
Max weight value being ignored

### ISSUE THREAD

**Issue by RoyalLasky** [overextended/ox_inventory#1345]
**Describe the bug**
I just got rid of qb-inventory and installed ox-inventory and I noticed all the AddItem() functions on the QB scripts will still give the item even though you are overweight. This function -> Player.Functions.AddItem()

I then noticed you are able to drop stuff on the ground even though it is overweight from your inventory, which is purely ox_inventory(See picture)

Giving a player a item when their overweight, picking up a item or buying a item from the store works correctly.

**Framework**
I am the the latest qb-core version from 6/1/2023.

**Resource version**
Version '2.30.2'

**To Reproduce**
1. Use /giveitem on a qbcore server and give yourself enough items to be overweight, or use a script which gives you items using the AddItem() function. Both will make you go overweight
2. Drop a stack of items which is overweight on the ground, it will work.

**Expected behavior**
You would be unable to transfer or get items what so ever if it goes over the maximum weight allowed, include from the GiveItem() function.

**Screenshots**
![image](https://github.com/overextended/ox_inventory/assets/103779688/1f8aa354-ba4a-4f43-b49f-0183675ffc24)

**Additional context**

**Comment by thelindat** [comment]
> all the AddItem() functions on the QB scripts will still give the item even though you are overweight. This function -> Player.Functions.AddItem()

I don't use qb because it's gross. If something in the bridge doesn't provide behaviour like qb would, correct it and (ideally) PR it.

> I then noticed you are able to drop stuff on the ground even though it is overweight from your inventory

Seemingly only drops, not sure why it isn't checking weight but entirely unrelated code to AddItem.

**Comment by thelindat** [comment]
Now that I think of it, restricting the drop weight seems problematic if somebody has their inventory overloaded for whatever reason - they'll have to make potentially dozens of drops to deal with it. Probably why I never bothered with the weight check?

Ideally the player shouldn't be given more than they can carry in the first place, while drops match the player carry weight.

See [CanCarryItem](https://overextended.github.io/docs/ox_inventory/Functions/Server/Inventory/CanCarryItem/) and [CanCarryWeight](https://overextended.github.io/docs/ox_inventory/Functions/Server/Inventory/CanCarryWeight)

**Comment by RoyalLasky** [comment]
So I've looked into it further. The /giveitem command issue is actually coming from oxinventory in the actual command lib.addCommand({'additem', 'giveitem'}. It does not check for weight, it just gives it. I can maybe see a purpose to this, if admins need to give items for a specific reason.

The bridge function im having a hard time with.
QB scripts like to remove the item before adding - So if the remove is successful then it adds.

I had it successfully checking if I can carry the item, and if I I didn't have enough weight I would not receive it.. but it would still remove the item as that's what's called first.

```	
QBCore.Functions.AddPlayerMethod(Player.PlayerData.source, "AddItem", function(item, amount, slot, info)
		if exports.ox_inventory:CanCarryItem(Player, item, amount) then
		return Inventory.AddItem(Player.PlayerData.source, item, amount, info, slot)
		end
	end)

	QBCore.Functions.AddPlayerMethod(Player.PlayerData.source, "RemoveItem", function(item, amount, slot)
		return Inventory.RemoveItem(Player.PlayerData.source, item, amount, nil, slot)
	end)
```

I'm trying to figure out a way to edit the bridges instead of every single script so it would check for the item getting received before removing the item then giving it, but having a hard time with the logic I guess.

**Comment by thelindat** [comment]
> I had it successfully checking if I can carry the item, and if I I didn't have enough weight I would not receive it.. but it would still remove the item as that's what's called first.

Is this not an issue with qb though? If they remove items then add items without checking on the success of either it isn't really my problem.

You'd also need to return false if they can't carry.

**Comment by RoyalLasky** [comment]
> Is this not an issue with qb though? If they remove items then add items without checking on the success of either it isn't really my problem.

Yea it's crappy qbcore coding, they use the remove function as the success, so if it removes it successfully it gives the item, but the remove also triggers the oxinventory bridge function, which in turns leads to these events. That's what's happening here, not your problem at all its just QB being QB.

> You'd also need to return false if they can't carry.
 

Yes I've added it tyvm.

I may just change every QBcore additem function with CanCarryItem/CanCarryWeight + exports.ox_inventory:AddItem(). That's my only solution right now.
This can be closed if you feel it necessary, or keep it open so people can see. Maybe someone else can figure out the logic here.
