### ISSUE TITLE
ox inventory stashes

### ISSUE THREAD

**Issue by Arctos2win** [overextended/ox_inventory#1350]
add an option to code the security for opening a stash by yourself, i was writing a resource where 
the security was not involved with groups or players, so it could be very usefull to add the option in the 
register stash to add some security checks yourself

**Comment by thelindat** [comment]
https://overextended.dev/ox_inventory/Functions/Server/Hooks#openinventory

**Comment by Arctos2win** [comment]
thank you i clearly looked over that one
