### ISSUE TITLE
attempt to perform arithmetic on a nil value (field 'ammo')

### ISSUE THREAD

**Issue by sparcoxalpha** [overextended/ox_inventory#1351]
**Screenshots**
![image](https://github.com/overextended/ox_inventory/assets/69634143/c3eb48b2-e10f-4439-9fb5-0f95a3d828d6)

may this fix
if action == 'load' and weapon.metadata.durability > 0 then
    local ammo = Items(weapon.name).ammoname
    local diff = 0

    if weapon.metadata.ammo ~= nil then
        diff = value - weapon.metadata.ammo
    else
        diff = value
    end

    if not Inventory.RemoveItem(inventory, ammo, diff, specialAmmo) then return end

    weapon.metadata.ammo = value
    weapon.metadata.specialAmmo = specialAmmo
    weapon.weight = Inventory.SlotWeight(item, weapon)

**Comment by thelindat** [comment]
So you're trying to load a weapon that doesn't have ammo; explain that to me.
