### ISSUE TITLE
Auto weapon unequip in water

### ISSUE THREAD

**Issue by necaz1337** [overextended/ox_inventory#1354]
**Describe the bug**
I dont find nowhere how can  i deactivate auto unequip weapon in water, example using crowbar, i cant hold crowbar in character hands and i didnt find any settings to deactivate it.
**Framework**
 
ESX
**Resource version**
Latest

 

**Expected behavior**
I want to add an exception or deactivating.
**Screenshots**
 
![image](https://github.com/overextended/ox_inventory/assets/120249798/e7552af7-dee2-4ca8-8e22-5abc514cf1a9)
 

**Additional context**
Thanks and sorry for my bad english, its not my main

**Comment by thelindat** [comment]
Welcome to GTAV - I guess you haven't played before, as you have a misconception that you can use any weapon in any situation. Here's me on GTA Online, showing that you cannot use a crowbar while swimming.

![image](https://github.com/overextended/ox_inventory/assets/65407488/d0da30f7-58da-4079-9fed-ed73a9c02452)

**Comment by necaz1337** [comment]
Bro im playing GTA since 5 years. I mean, the weapon Crossbar automatically unarmed when im in water, and i want to deactivate it

**Comment by thelindat** [comment]
> Crossbar automatically unarmed when im in water

_Yes, you showed that. You're asking me to prevent default GTA behaviour, you donkey._
