### ISSUE TITLE
Add a way to open a shop while driving

### ISSUE THREAD

**Issue by lexinor** [overextended/ox_inventory#1355]
**Is your feature request related to a problem? Please describe.**
I've made a drive thru system using stashes and shops but I'm facing a problem, I can't open my shop while driving

**Describe the solution you'd like**
A way to force open the shop to bypass security checks. I saw that there is **exports.ox_inventory:forceOpenInventory(playerId, invType, data)** but it's not working with shops.

Does adding shops to that function could be possible ? If so, do you think it could be added in the next update ?

I've made a temporary solution on my own but it's not clean. I added a **allowDriving** parameter in the data sent to avoid checking if ped is in a vehicle.

```
exports.ox_inventory:openInventory('shop', { type = "foo" = 1, allowDriving = true })
```

And in **function client.openInventory(inv, data)** I added a if statement on top of the vehicle check :
```
if not data.allowDriving then
    if cache.vehicle then
	return lib.notify({ id = 'cannot_perform', type = 'error', description = locale('cannot_perform') })
    end
end
```

This is not clean so it would be a great improvement to have a clean way using forceOpenInventory. I also saw that there is this cb **lib.callback.await('ox_inventory:openShop', 200, data)** so I think it would not be a pain in the ass to add it

**Comment by lexinor** [comment]
@thelindat Any thoughts ?

**Comment by thelindat** [comment]
There are suggestions from a year ago and you feel the need to tag me for yours.

**Comment by lexinor** [comment]
> There are suggestions from a year ago and you feel the need to tag me for yours.

I didn't see that and I've created that issue one week ago without any answers. So yeah I'm tagging you.

**Comment by thelindat** [comment]
> I've created that issue one week ago without any answers. So yeah I'm tagging you.

1. This is a free open-source resource. I get next to nothing for maintaining it and have no obligation to respond to issues.
2. I've been sick for nearly 2 weeks now and have barely just started doing anything again.
3. You already have your own solution that you can add to your own code, there's no need for me to officially support this at all aside convenience.
4. I'm already annoyed with you because of your impatience on the [other issue](https://github.com/overextended/ox_inventory/issues/1338#issuecomment-1575240435). Considering I was basically bed-ridden at the time, I wasn't in a position to do any more than reject your PR (which was a weird workaround for an incredibly situational problem).
5. Entitlement?

**Comment by lexinor** [comment]
> 5\. Entitlement

1. I know that and that's why I'm creating issues to help improving this resource. I'm not well informed enough of the deep mechanics that you use in the inventory that's why I'm seeking help here to not mess up with it.
2. I'm not suppose to know that mate, I asked just your thoughts on that because no one in the team responded, that's simply that. 
3. I have but it's not clean as I mentioned in the first point, I want to do it clean to not break your resource that is working well.
4. I know that you're annoyed when I post something for some reasons that I can't explain. I'm not suppose to know what how your health is and that's why I'm just simply asking for thought on my suggestions.

Sure thing you've the right to not answer like I've the right to ask questions to. You're not alone in your team I did tagged you because nobody is answering at all and you seems to be the only one that can. I'm not here to break your balls, I'm here to help improve your creation but suggesting improvement that a live server is needing.

Anyway, I hope you're now doing better. I will let my suggestions open if you think there are not worthy then you can just closed them. Just a last thing, I could do my own stuff on that inventory but I dont wanna mess up everything and also I don't have enough time to go in depth in the inventory to know every little aspect of it. 
I tried to do so and that's why in this [issue](https://github.com/overextended/ox_inventory/issues/1355) I tried to give the best informations I could to simplify the job for your team.

Thanks in advance for the reading, keep the good work
