### ISSUE TITLE
Ox inventory

### ISSUE THREAD

**Issue by Alkialex** [overextended/ox_inventory#1356]
How can I activate the weapon wheel in ox_Inventory

**Comment by N-fire** [comment]
https://overextended.dev/ox_inventory/Functions/Client/Utils/weaponWheel

**Comment by Alkialex** [comment]
where do i have to enter it

**Comment by eprimex** [comment]
> where do i have to enter it

If you have no idea how to use the code provided in docs you shouldn't be attempting to do stuff you are requesting. Find a capable dev to do it for you. This isn't right place for asking for coding lessons
