### ISSUE TITLE
Inventory UI Bug

### ISSUE THREAD

**Issue by Smailas01** [overextended/ox_inventory#1358]
**Describe the bug**
When bug happen all picture from inventory disappier nad language changes need restart game to fix it.

**Framework**
ESX Legacy 1.8.5

**Resource version**
version '2.30.4'

**Screenshots**
![image](https://github.com/overextended/ox_inventory/assets/117887430/f788dff1-0538-4482-aa61-413ee2ae5376)
![image](https://github.com/overextended/ox_inventory/assets/117887430/fa7c7280-5894-44f3-8a2d-f70d2e999f29)

**Additional context**
Maybe anyone can help me...

**Comment by thelindat** [comment]
People reported removing or updated xSounds and/or lb-phone resolved a memory leak in cef; otherwise this can't be reproduced.
