### ISSUE TITLE
Shops problem

### ISSUE THREAD

**Issue by Enjoy1982** [overextended/ox_inventory#1363]
**Describe the bug**
someone know why in the shops is not open de inventory when i try to buy something. my shops is whit ped  and one text say: 
you can not open this inventory. some help??

**Framework**
esx

**Resource version**
last version

**Screenshots**
![20230614232921_1](https://github.com/overextended/ox_inventory/assets/136649939/ef9c6115-ba0d-4e29-b4db-42706fb3bd2c)

**Comment by thelindat** [comment]
Well, it would seem "you can not open this inventory". I can't provide any more context.
