### ISSUE TITLE
ESX starting money is not synced

### ISSUE THREAD

**Issue by lexinor** [overextended/ox_inventory#1366]
**Describe the bug**
In my framework (ESX) I've setted 12k in bank and 3k in cash for the new players. With the latest ox_inv version i've added the given convars to specify what account should be added which is "money" in ESX (for cash). Even thought I've added these things, nothing is present in the inventory and nothing is being synced at this time. Is it a normal behavior ?

**Framework**
ESX 1.9.4

**Resource version**
ox_inventory : 2.30.4
ESX : 1.9.4

**To Reproduce**
Said in the intro

**Expected behavior**
When you have "money" (cash) set in ESX it should appear in the inventory as item

Tell me if you need more details

**Comment by ItssJxstnDe** [comment]
What Banking is that?

**Comment by lexinor** [comment]
> > nothing is being synced at this time
> 
>  x7HCtH7oOL.mp4

Okay, what are you listening to trigger that item give ?

**Comment by thelindat** [comment]
Listening? This is just https://github.com/esx-framework/ESX-recipes/tree/legacy-ox, nothing added or changed.

**Comment by lexinor** [comment]
> Listening? This is just https://github.com/esx-framework/ESX-recipes/tree/legacy-ox, nothing added or changed.

I meant what event are you listening to, I'm using the official repo of ESX as I said above.
My issue is that I used this : Config.StartingAccountMoney 	= {bank = 12000, money = 3000 } in ESX and when you first connect to the server, you get the amounts given but nothing is added in the inventory

**Comment by thelindat** [comment]
The starting account money shit is known and not really resolvable without breaking something but you said "nothing is being synced at this time" - I'm not listening to any event.

**Comment by lexinor** [comment]
> The starting account money shit is known and not really resolvable without breaking something but you said "nothing is being synced at this time" - I'm not listening to any event.

Ok. What will be the best solution to force the inventory to retrieve the accounts at first spawn or even just at aspawn ? I tried to set my account money at 20 $ in my database while offline then when I reconnected, I still has the amount I had before disconnecting and not the 20 $. Is there a way to force the sync ?

**Comment by thelindat** [comment]
As with everyone else who asked about adding items on new player creation, esx:playerLoaded event has an isNew argument.
