### ISSUE TITLE
Cannot drop items

### ISSUE THREAD

**Issue by RoyalLasky** [overextended/ox_inventory#1368]
**Describe the bug**
No one in the server can drop items on the ground after updating to version '2.30.4' - Commit hash 1a4d8b7.

Reverted to V2.30.2 commit bee820d and drops work as intended.

I have deleted and did a complete fresh install of ox _inventory version '2.30.4' - Commit hash 1a4d8b7. Issue persisted.
Other stashes like vehicle gloveboxes/trunks, evidence, etc work as intended.

No errors client or server side.

**Framework**
'QB-Core'
version '1.2.6'

**Resource version**
version '2.30.4'
Commit hash 1a4d8b7

**To Reproduce**
1. Join on any character
2. Attempt to drop an item.

**Expected behavior**
The item drops and drop id created.

**Screenshots**
Video: https://youtu.be/iEt2N-pgPWg

**Additional context**
N/A

**Comment by FjamZoo** [comment]
Your video is private

**Comment by RoyalLasky** [comment]
Resolved, new link: https://www.youtube.com/watch?v=iEt2N-pgPWg&ab_channel=powerplay9876

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/assets/65407488/a1e31506-d461-4699-a8d7-53e31e520462

**Comment by RoyalLasky** [comment]
Interesting.. I did a completely fresh install with a fresh character and I cannot drop a single item..

**Comment by thelindat** [comment]
Does one of your resources have an event hook? https://overextended.dev/ox_inventory/Functions/Server/Hooks

**Comment by RoyalLasky** [comment]
Yes one does for a weapon repair system. I completely removed it but the issue persisted.

Funny thing is, I just updated to version '2.30.4' the same way I did the 3 times prior to do some further testing I can now drop items without issue. 
Not sure what the problem was before
