### ISSUE TITLE
Upgrade Stash

### ISSUE THREAD

**Issue by Fedegamer82** [overextended/ox_inventory#1369]
**Describe the solution you'd like**
A way to upgrade some stash somethink like this(sorry for my bad english)

function OpenMenu()
    lib.registerContext({
        id = 'menu_apartments',
        title = 'Gestione Inventario',
        
        options = {
            {
                title = "Apri Inventario",
                icon = "toolbox",
                onSelect = function()
                    HZ_ApartmentsServerT._RegisterStash()
                    exports.ox_inventory:openInventory("stash", {id = "deposito_casa_" .. ESX.GetPlayerData().identifier, owner="property"})
                end
            },
            {
                title = "Potenzia Inventario",
                icon = "arrow-up",
                iconColor = "green",
                onSelect = function()
                    lib.registerContext({
                        id = 'menu_apartments_invupg',
                        title = 'Upgrade Inventario',
                        options = {
                            {
                                title = "Indietro",
                                icon = "arrow-left",
                                onSelect = function()
                                    lib.showContext("menu_apartments")
                                end
                            },
                            {
                                title = "Costo: 100.000$",
                                icon = "dollar",
                            },
                            {
                                title = "Slots Totali: 15",
                                icon = "filter",
                            },
                            {
                                title = "Peso Totale: 500Kg",
                                icon = "weight",
                            },
                            {
                                title = "Conferma",
                                icon = "check",
                                iconColor = "green",
                                onSelect = function()
                                    UpgradeFunction()
                                end
                            },
                        }
                    })
                    lib.showContext("menu_apartments_invupg")
                end
            },
        }
    })
    
    lib.showContext("menu_apartments")
end

**Comment by thelindat** [comment]
No clue what you're trying to ask.

**Comment by Fedegamer82** [comment]
spero che capisci un po l'italiano, il deposito all'inizio ha 15 slot e può tenere 50kg dopo che premo su UPGRADE INVENTARIO lo stesso deposito di prima ora può tenere tipo 50 slot e 100 KG

**Comment by Fedegamer82** [comment]
spero di essermi spiegato bene

**Comment by thelindat** [comment]
https://overextended.dev/ox_inventory/Functions/Server#setmaxweight
https://overextended.dev/ox_inventory/Functions/Server#setslotcount

**Comment by Fedegamer82** [comment]
thanks

**Comment by Fedegamer82** [comment]
non funziona
![image](https://github.com/overextended/ox_inventory/assets/103957127/a6255273-5b22-4a94-b814-3f7334ee8a12)
![image](https://github.com/overextended/ox_inventory/assets/103957127/1f5015d6-6c7e-4840-88d7-932f47b98635)
