### ISSUE TITLE
SetMaxWeight and SetSlotCount

### ISSUE THREAD

**Issue by Fedegamer82** [overextended/ox_inventory#1370]
**Describe the bug**
when i try to trigger the export it gives and error

**Framework**
ESX

**Resource version**
2.18.0

![image](https://github.com/overextended/ox_inventory/assets/103957127/a242d1c9-32f1-4044-b3b7-c885ab58dab9)
![image](https://github.com/overextended/ox_inventory/assets/103957127/ec2a07b2-232b-4d6b-8b3a-e05047f1f9e4)

**Comment by thelindat** [comment]
> Resource version
2.18.0

?????? What are you expecting even.
