### ISSUE TITLE
Client: Weight Exports

### ISSUE THREAD

**Issue by OppoNoppo** [overextended/ox_inventory#1374]
**Describe the bug**
Both GetPlayerWeight() and GetPlayerMaxWeight() return the same value.

**Framework**
ESX

**Resource version**
2.29.2 - Yes I still need to update, but I've checked `modules/inventory/client.lua` and no changes has been made since if I checked correctly

**To Reproduce**
In any client script add
```print(exports.ox_inventory:GetPlayerMaxWeight(), exports.ox_inventory:GetPlayerWeight())```

**Expected behavior**
result of print should be different

**Screenshots**
![image](https://github.com/overextended/ox_inventory/assets/45967788/579d2089-3fc6-4e2d-806f-0984f9d4a8f5)
![image](https://github.com/overextended/ox_inventory/assets/45967788/35c77fa8-ef01-4445-a342-4d3b1ff92c5b)
![image](https://github.com/overextended/ox_inventory/assets/45967788/2cd11805-39fd-4c7c-b19d-74390a6795d0)

**Additional context**
I don't know what is accessible within the script. But my guess is that the export return should be `return shared.playerweight`

**Comment by CodeCool-Developer** [comment]
![image](https://github.com/overextended/ox_inventory/assets/112088784/2038a3c0-010c-4791-986d-b0c0665a6bb5)

so sad 

info in PlayerData variable

![image](https://github.com/overextended/ox_inventory/assets/112088784/aed7cc70-432a-4dac-855f-c23c5544bacc)

**Comment by OppoNoppo** [comment]
I'm aware of the code and what is available in PlayerData, and I guess Linden does to. I think its just oversight.

Dont really see a reason to comment this "info" here.

**Comment by OppoNoppo** [comment]
Fixed - https://github.com/overextended/ox_inventory/commit/5a25d4c8f2087dc7bb7c8ecbd58a08cf24763617
