### ISSUE TITLE
Stash (?)

### ISSUE THREAD

**Issue by ghost** [overextended/ox_inventory#1376]
**Describe the bug**
When inventories save, the amount saved is a table and not the actual amount.

**Framework**
ESX

**Resource version**
2.30.7

**To Reproduce**
1. Use a stash.
2. Wait for inventories to save.
3. It will display 'Saved table: 0000021F1D31B0C0/2 stashes'.

**Expected behavior**
Display the amount of affected rows.

**Screenshots**
```
[ script:ox_inventory] [info] Saving 3 inventories to the database
[ script:ox_inventory] [info] Saved 1/1 gloveboxes
[ script:ox_inventory] [info] Saved table: 0000021F1D31B0C0/2 stashes
```

**Comment by thelindat** [comment]
Stupid auto-close.
