### ISSUE TITLE
Incorrect source being used with lib.logger with inventory logs

### ISSUE THREAD

**Issue by jellyton69** [overextended/ox_inventory#1377]
**Describe the bug**
Whenever the inventory logs an inventory action with lib.logger (from ox_lib), instead of being sent the actual player source, the script sends the player's citizenid (what is 'owner' in ox_inventory with qb-core). Because it doesn't actually send the source, ox lib doesn't correctly generate the data dog tags.

**Framework**
qbx-core

**Resource version**
version '2.30.7'

**To Reproduce**
1. Have a ox_inventory and ox_lib instance on your QB-Core server.
2. Run any inventory action

**Expected behavior**
The player source is sent through the lib.logger function instead of the player's CitizenID. (Alternatively, because the citizenID is a useful identifier for logging, allow the logger to accept it as a valid source, and use it to get the player's actual source to generate the rest of the identifier tags.)

**Screenshots**

Current tags (no generated tags beside the source):
![chrome - June25 - 18 40 - 2472](https://github.com/overextended/ox_inventory/assets/20498875/bb999e6c-95d1-4cd1-80a7-88dd7186177c)

Expected tags:
![chrome - June25 - 18 49 - 2473](https://github.com/overextended/ox_inventory/assets/20498875/7d7b32e5-aa67-49aa-aa83-9711729811bd)

**Comment by thelindat** [comment]
Logging in inventory pre-dates the lib logger so tags never really got looked at.

**Comment by buddizer** [comment]
Adding my support for this enhancement, once time allows. Extremely helpful.
