### ISSUE TITLE
Using ox_inventory on the server will cause problems with ESX Multicharacter, players cannot enter the server

### ISSUE THREAD

**Issue by 2749773995** [overextended/ox_inventory#1381]
**Describe the bug**
Using ox_inventory on the server will cause problems with ESX Multicharacter, players cannot enter the server

**Framework**
ESX 1.9.4

**Resource version**
2.30.7

I am using Esx Legacy 1.9.4. When the server does not use ox_inventory, everything is normal, but when I enable ox_inventory, any player will not be able to enter when connecting to the server and a prompt will appear:
Connection rejected by gaogaolongjiang's server: [ESX Multicharacter] ESX Cannot Connect to your database. Please make sure it is correctly configured in your server.cfg

**Screenshots**
![~`{AROG{2{KX`SFA`%%`CX](https://github.com/overextended/ox_inventory/assets/104758168/ea34769b-bd9d-4225-8aa9-b2e1ce896790)

**Comment by thelindat** [comment]
Nope, esx_multicharacter has some crap logic that throws blame at the database - other people have crap logic that throws the blame at ox_inventory. You'll actually have an error _somewhere_ in the server console that gives a proper reason for connection failing.

Last person who had this had to update oxmysql.
