### ISSUE TITLE
Minimum cops for crafting

### ISSUE THREAD

**Issue by lovelywi** [overextended/ox_inventory#1382]
how add job police for minimum (required) crafting ?

**Comment by thelindat** [comment]
https://overextended.dev/ox_inventory/Functions/Server/Hooks#craftitem

**Comment by lovelywi** [comment]
> 


I do not really understand
please give me an example ?

**Comment by thelindat** [comment]
There are examples on the page I linked; if you can't understand that I don't know what you expect from me.
