### ISSUE TITLE
(feature request) weapons durability with time

### ISSUE THREAD

**Issue by maneskul** [overextended/ox_inventory#1385]
**Weapons Durability and Economy in Server**

Today the weapon system works with a different durability if we compare with general items, or at least I never managed to configure it correctly. 

It would be cool that in addition to weapons losing durability as you shoot, they would lose durability over time.

My idea is to put durability in time, the same as other items, and a factor that spends this durability on shots/reload for each weapon.

**Comment by thelindat** [comment]
Duplicate issue https://github.com/overextended/ox_inventory/issues/1141
