### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jesuisjoszi** [overextended/ox_inventory#1386]
The ability to check the name of an item, for example:
ox_inventory:GetItem("bread").label
The ability to lock an item so that no one else can take it, for example, using handcuffs.

**Comment by thelindat** [comment]
> The ability to check the name of an item

There is a dozen ways to do this, including _the code you posted as an example???_

> The ability to lock an item so that no one else can take it

Hooks.

**Comment by jesuisjoszi** [comment]
This "code" doesn't work, so I wrote a suggestion here. If it's possible to get an example, I would appreciate it.

**Comment by thelindat** [comment]
Use the correct args. Look at the docs. Don't post issues for dumb nonsense that you can _search_ for a solution to.

**Comment by thelindat** [comment]
And now you can enjoy a ban.
