### ISSUE TITLE
Search a player

### ISSUE THREAD

**Issue by Heaven02200** [overextended/ox_inventory#1390]
Hello, I would like to know how to search a player for the police job as well as for all civilians. THANKS

**Comment by N-fire** [comment]
For support, you should ask in the discord, github issue are for suggestion and bug report

**Comment by Heaven02200** [comment]
You should know once I had a problem I posted on discord I was told to come here

**Comment by Heaven02200** [comment]
and we can't even write or make a ticket on the discord

**Comment by N-fire** [comment]
Get yourself unbaned by warden

**Comment by thelindat** [comment]
> and we can't even write or make a ticket on the discord

Why the hell would we have tickets?

There's also this thing known as "documentation" which tells you how to "search".
