### ISSUE TITLE
Weight Count

### ISSUE THREAD

**Issue by Chariix** [overextended/ox_inventory#1391]
**Describe the bug**
I'm having an issue when I update my ox_inventory when it comes to setting the total max kg for players. At first I thought that it was my es_extended that was acting up but when I reverted back to an older version of ox_inventory 2.20.1 the weight kg goes back to my preferred weight type for players. My set max kg is at 100kg. The new version only allows me to hold 30kg max while es_extended still states my max weight is set to 100kg.

**Framework**
ESX Legacy 1.8.5

**Resource version**
v2.31.1

**Comment by N-fire** [comment]
Esx_skin is probably overwriting max weight,  check his configuration

**Comment by Chariix** [comment]
I have checked through my files but I dont use esx_skin, however the older versions I definitely can set my maxweight kg with no issues. But every since This new one installed, I seem to be having this problem. :(

**Comment by thelindat** [comment]
_Something_ is changing weight, up to you to look. Nothing even changed with weight and hasn't for a _long_ time.
What _has_ changed recently is properly refreshing weight values on the client after using [SetMaxWeight](https://overextended.dev/ox_inventory/Functions/Server#setmaxweight) or such.
