### ISSUE TITLE
Players are able to farm weapon attachments

### ISSUE THREAD

**Issue by mr-capy** [overextended/ox_inventory#1393]
Players are able to farm weapon attachments by removing the attachments from an unholstered gun. Once the gun is holstered and drawn again, the attachments will be back on the gun and still in inventory. 
 
Framework: ESX

Resource Version: v2.31.2

To Reproduce: unholster gun with attachments. Use the up arrow on D-Pad to remove the attachments from the gun. Holster the weapon. Unholster the weapon again. (Attachments should be back on gun and you should have new attachments in your inventory).

**Comment by thelindat** [comment]
> Use the up arrow on D-Pad to remove the attachments from the gun.

??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by mr-capy** [comment]
> > Use the up arrow on D-Pad to remove the attachments from the gun.
> 
> ??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

Players are able to farm weapon attachments by removing the attachments from an unholstered gun. Once the gun is holstered and drawn again, the attachments will be back on the gun and still in inventory. 
 
Framework: ESX?

Version: Not sure

To Reproduce: unholster gun with attachments. Use the up arrow on arrow keys (keyboard) to remove the attachments from the gun. Holster the weapon. Unholster the weapon again. (Attachments should be back on gun and you should have new attachments in your inventory). 

Expected Behavior: if the attachments are removed in the field. They should not reappear on the weapon until reattached to the weapon by the player.

**Comment by thelindat** [comment]
> Players are able to farm weapon attachments by removing the attachments from an unholstered gun. Once the gun is holstered and drawn again, the attachments will be back on the gun and still in inventory.

I can read.

> Use the up arrow on arrow keys (keyboard) to remove the attachments from the gun.

Which isn't some default game functionality but some resource - hence

> ??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

Though I fail to see how that results in gaining attachment items.
