### ISSUE TITLE
ox inventory license issue

### ISSUE THREAD

**Issue by Harry755** [overextended/ox_inventory#1395]
cant buy license from shop money is removed from account but licence is not available from ammunation

**Comment by thelindat** [comment]
Why is it so hard for some people to use a template and provide any sort of information? https://github.com/overextended/ox_inventory/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

**Comment by Harry755** [comment]
**Describe the bug**
when wepon license is purchased from shop the money is debited from the inventory but not getting license

**Framework**
esx leagacy latest version

**Resource version**
2.30.7



**Expected behavior**
licence is not saving in the user license table



![Screenshot (136)](https://github.com/overextended/ox_inventory/assets/106462812/9b4ece52-c81f-4886-8404-4cef25980f28)
![Screenshot (137)](https://github.com/overextended/ox_inventory/assets/106462812/3ab80e32-e49e-49aa-b7e9-babf1cf6e809)

**Comment by ItssJxstnDe** [comment]
You need the Item named 'weponlicense'
To buy stuff
