### ISSUE TITLE
ox inventory weapon licence bug 

### ISSUE THREAD

**Issue by Harry755** [overextended/ox_inventory#1396]
Describe the bug
when wepon license is purchased from shop the money is debited from the inventory but not getting license

Framework
esx leagacy latest version

Resource version
2.30.7
![Screenshot (136)](https://github.com/overextended/ox_inventory/assets/106462812/e9e89263-180c-4466-ac1a-1c446f03852b)
![Screenshot (137)](https://github.com/overextended/ox_inventory/assets/106462812/46b1e4a7-1b65-4485-be1f-69292059b541)

Expected behavior
licence is not saving in the user license table even after buying license

**Comment by ItssJxstnDe** [comment]
You need the Item named 'weponlicense'
To buy stuff

**Comment by ItssJxstnDe** [comment]
So Not a Bug Just Too Dumb to use

**Comment by Harry755** [comment]
> So Not a Bug Just Too Dumb to use

what.......do you mean dude once license is purchased we dont get an item or any stuff it gets saved in the user.license table but currently that dont work

**Comment by ItssJxstnDe** [comment]
Cause you have to Give yourself the weaponlicense Item to Buy stuff

Btw Support is in Discord!

**Comment by Harry755** [comment]
> Cause you have to Give yourself the weaponlicense Item to Buy stuff
> 
> Btw Support is in Discord!

do you mean to add an item called weaponlicense in the items list --------- i you mean that i had done that also as per you said nthing helps

**Comment by thelindat** [comment]
![image](https://github.com/overextended/ox_inventory/assets/65407488/21a48fa5-f922-4c3f-b7b5-716944bb69d6)
![image](https://github.com/overextended/ox_inventory/assets/65407488/dd18f41b-3799-45a3-bce4-f3577de40739)

**Comment by Harry755** [comment]
> ![image](https://user-images.githubusercontent.com/65407488/252122093-21a48fa5-f922-4c3f-b7b5-716944bb69d6.png) ![image](https://user-images.githubusercontent.com/65407488/252122098-dd18f41b-3799-45a3-bce4-f3577de40739.png)

https://github.com/overextended/ox_inventory/assets/106462812/a4a9622d-f64d-4426-81e0-799b939e4b50


thank you for the response my ox-inventory version is 2.30.7 and still everytime when purchaisng licence  the money is gone from inentory the licenses and user.licenses are installed correctly
you can see the video

**Comment by thelindat** [comment]
Anything in server log?

**Comment by Harry755** [comment]
> Anything in server log?

nothing no errors

**Comment by thelindat** [comment]
> > Anything in server log?
> 
> nothing no errors

Some _other_ resource that isn't esx_license or is modified or something weird? Buying a license literally just triggers an event and isn't something I control.

https://github.com/overextended/ox_inventory/blob/b9b8259b681c9c4ad269fd6a442785d936dd633a/modules/bridge/esx/server.lua#L72

**Comment by Harry755** [comment]
> > > Anything in server log?
> > 
> > 
> > nothing no errors
> 
> Some _other_ resource that isn't esx_license or is modified or something weird? Buying a license literally just triggers an event and isn't something I control.
> 
> https://github.com/overextended/ox_inventory/blob/b9b8259b681c9c4ad269fd6a442785d936dd633a/modules/bridge/esx/server.lua#L72

no latest esx_license is installed

**Comment by thelindat** [comment]
Well go look at esx_license for why/how it's failing.

**Comment by Harry755** [comment]
> Well go look at esx_license for why/how it's failing.

seems all are ok
current triggers are 
### Available triggers
- `'esx_license:addLicense', function(target, type, cb)`
- `'esx_license:removeLicense', function(target, type, cb)`
- `'esx_license:getLicense', function(source, cb, type)` (callback)
- `'esx_license:getLicenses', function(source, cb, target)` (callback)
- `'esx_license:checkLicense', function(source, cb, target, type)` (callback)
- `'esx_license:getLicensesList', function(source, cb)` (callback)

**Comment by thelindat** [comment]
I do not give a single fuck? This isn't esx_license and I'm not part of esx.
