### ISSUE TITLE
targets supports

### ISSUE THREAD

**Issue by nurrifqialhusaini** [overextended/ox_inventory#1397]
I have a suggestion for the targets array, please create zone data (ox_lib) support for the target data inventory.

**Comment by thelindat** [comment]
what

**Comment by nurrifqialhusaini** [comment]
![image](https://github.com/overextended/ox_inventory/assets/60453612/7e86ad19-4cfc-4e95-9fb4-4f141496a9f2)
This format from ox_lib

**Comment by nurrifqialhusaini** [comment]
can we use zone format from zone creator ox_lib ?

**Comment by thelindat** [comment]
> can we use zone format from zone creator ox_lib

Not until qtarget support is removed.

**Comment by nurrifqialhusaini** [comment]
umm okey
