### ISSUE TITLE
Locales are 'undefinied'

### ISSUE THREAD

**Issue by Lisunio** [overextended/ox_inventory#1398]
Hi. Idk why is it but for example when i use my item, it shows 'undefinied' not 'item used'. I don't know why is that, i have folder with locales in my main ox_inventory directory.
![obraz_2023-07-12_114142645](https://github.com/overextended/ox_inventory/assets/102691682/dabf0a12-984b-4188-a617-0ee5595b097f)
![obraz_2023-07-12_114231047](https://github.com/overextended/ox_inventory/assets/102691682/87d8d61d-cf46-48be-9625-c30844ce9ff8)
(Ignore these folders that i hide names, they are not important)

**Comment by thelindat** [comment]
Your edited UI is not compatible with any version of ox_inventory from the last ~year.

> Ignore these folders that i hide names

Fucking _weiiiiird_.

**Comment by Lisunio** [comment]
> Your edited UI is not compatible with any version of ox_inventory from the last ~year.
> 
> > Ignore these folders that i hide names
> 
> Fucking _weiiiiird_.

okay thank you
