### ISSUE TITLE
vector3 issue

### ISSUE THREAD

**Issue by chrisandkitt** [overextended/ox_inventory#1399]
I got an issue with a script error 
![grafik](https://github.com/overextended/ox_inventory/assets/139385951/ba807953-8ebc-47ed-a650-13b00792c391)

**Comment by chrisandkitt** [comment]
(node:36003) UnhandledPromiseRejectionWarning: Error: ox_inventory was unable to execute a query!
Incorrect arguments to mysqld_stmt_execute
UPDATE ox_inventory SET data = ? WHERE owner = ? AND name = ?
    at @oxmysql/dist/build.js:22461:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async rawExecute (@oxmysql/dist/build.js:22393:10)
(Use `FXServer --trace-warnings ...` to show where the warning was created)
(node:36003) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by thelindat** [comment]
> I got an issue with a script error ![grafik](https://user-images.githubusercontent.com/139385951/253065405-ba807953-8ebc-47ed-a650-13b00792c391.png)

You removed or did not add coords to evidence data.
