### ISSUE TITLE
Weapon/Bullets BUG

### ISSUE THREAD

**Issue by newbialywhodis** [overextended/ox_inventory#1400]
Describe the bug:
There's a bug when you're hiding your weapon and then getting it back in hand. While equipping it back, there's a reload animation along with reaching for weapon one. Then, when u hide your weapon back and pull it out You can only shoot once and have to reload it even if You had a full mag.
The problem is gray ammo number going 0 and white getting gray's previous number after some equips/unequips.

Framework:
ESX

Resource version:
2.31.3

To Reproduce:
Have a weapon equipped.
Use a hotkey to unequip it.
Use a hotkey to equip it back.
reload animation comes in mid equipping, but it doesn't fully load the mag and numbers stay the same when unequipping
Hide your weapon.
Equip it back and try to shoot (gray ammo number is now 0 (was 7), white is the previous gray number (7) and you're gonna shoot only once and have to reload the weapon)

Expected behavior:
There shouldn't be any reload animation while reaching for already loaded weapon (not even fully loaded).
There shouldn't be any problems with remembering weapon's ammo number while equipping/unequipping it forcing us to reload when we already had it fully loaded before.
Also, the ammo number in upper right corner should stay gray, so You are able to shoot a full mag.

Screenshots/videos:

https://streamable.com/77g0aa
----------------

Additional context:

**Comment by LEEOO1** [comment]
I had also noticed this problem and tried some modifications but they didn't work properly until I checked in the previous versions and then I tried to modify the file modules/weapon/client.lua on line 71 and moved the SetPedAmmo after the SetWeaponsNoAutoswap function. I got to try and it seems to work correctly, let me know if it solves this problem. The code should be this:

SetCurrentPedWeapon(playerPed, data.hash, true)
SetPedCurrentWeaponVisible(playerPed, true, false, false, false)
SetWeaponsNoAutoswap(true)
SetPedAmmo(playerPed, data.hash, ammo)
SetTimeout(0, function() RefillAmmoInstantly(playerPed) end)

**Comment by thelindat** [comment]
> While equipping it back, there's a reload animation

No?

**Comment by TomStilson** [comment]
> I had also noticed this problem and tried some modifications but they didn't work properly until I checked in the previous versions and then I tried to modify the file modules/weapon/client.lua on line 71 and moved the SetPedAmmo after the SetWeaponsNoAutoswap function. I got to try and it seems to work correctly, let me know if it solves this problem. The code should be this:
> 
> SetCurrentPedWeapon(playerPed, data.hash, true) SetPedCurrentWeaponVisible(playerPed, true, false, false, false) SetWeaponsNoAutoswap(true) SetPedAmmo(playerPed, data.hash, ammo) SetTimeout(0, function() RefillAmmoInstantly(playerPed) end)

This solution fixed the problem. I have tested it in a 150 players server and everything works like a charm now.
