### ISSUE TITLE
[ESX]After a recent update to ox_inventory, fire hoses and pepper spray no longer work

### ISSUE THREAD

**Issue by azm-T** [overextended/ox_inventory#1402]
**Describe the bug**

**Framework**
The framework your server uses for players (e.g. Ox, ESX, QB).

**Resource version**
The version number listed in fxmanifest.lua, or optionally a commit hash.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thelindat** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **Framework** The framework your server uses for players (e.g. Ox, ESX, QB).
> 
> **Resource version** The version number listed in fxmanifest.lua, or optionally a commit hash.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error
> 
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional context** Add any other context about the problem here.

incredible.

**Comment by azm-T** [comment]
I can't post the video I recorded here, so I posted it on DISCORD's support-forum

**Comment by azm-T** [comment]
I can't post the video I recorded here, so I posted it on DISCORD's support-forum

**Comment by azm-T** [comment]
Resource version The version number listed in fxmanifest.lua is 2.31.3

**Comment by azm-T** [comment]
https://github.com/overextended/ox_inventory/assets/111231726/fa5b157b-b9dc-4737-9dba-b1a82c7e9100

**Comment by azm-T** [comment]
https://github.com/overextended/ox_inventory/assets/111231726/07adf9e3-f13d-40df-ba5a-c06929c67c32

**Comment by azm-T** [comment]
> > **描述错误**清晰、简洁地描述错误是什么。
> > **框架**您的服务器用于播放器的框架（例如 Ox、ESX、QB）。
> > **资源版本**fxmanifest.lua 中列出的版本号，或者可选的提交哈希。
> > **重现**重现该行为的步骤：
> > ```
> > 1. Go to '...'
> > 
> > 2. Click on '....'
> > 
> > 3. Scroll down to '....'
> > 
> > 4. See error
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **预期行为**对您预期发生的情况进行清晰、简洁的描述。
> > **屏幕截图**如果适用，请添加屏幕截图以帮助解释您的问题。
> > **其他上下文**在此处添加有关该问题的任何其他上下文。
> 
> 极好的。

Hope it gets resolved, thanks
