### ISSUE TITLE
Sometimes moving camera and shoot in inventory

### ISSUE THREAD

**Issue by TidolopNick** [overextended/ox_inventory#1405]
**Describe the bug**
Sometimes you can move your camera by moving the mouse in the inventory and you can shoot while in the inventory.
I cannnot describe when this happens but I saw that on some players in the past.

**Framework**
ESX Legacy 1.8.5

**Resource version**
Latest v2.31.3

**To Reproduce**
I dont know how to reproduce it yet.

**Expected behavior**
You shoudl only move your mouse while in the inventory and not move your camera or shoot.

**Screenshots**
Not needed

**Additional context**
Not available

**Comment by thelindat** [comment]
All control actions are disabled (DisableAllControlActions) while the inventory is open.
Some resource is calling EnableControlAction for camera, shooting, etc.

https://github.com/overextended/ox_inventory/blob/3dcf297d148483544dbad7caa943475b3c634a11/client.lua#L1420-L1431
