### ISSUE TITLE
After a recent update to ox_inventory, fire hoses and pepper spray no longer work

### ISSUE THREAD

**Issue by azm-T** [overextended/ox_inventory#1406]
escribe the bug
After a recent update to ox_inventory, fire hoses and pepper spray no longer work

Framework
ESX Legacy 1.8.5

Resource version
Latest v2.31.3

To Reproduce
ox_inventory cannot run when it is started

Screenshots
I send the recorded video

Additional context
Not available

https://github.com/overextended/ox_inventory/assets/111231726/430a567c-db4b-4c4f-8531-aad7b5a86188

https://github.com/overextended/ox_inventory/assets/111231726/51011321-44d6-455b-bb00-8681149481ad

**Comment by thelindat** [comment]
How about actually explaining the problem rather than a constant stream of broken videos and lack of information. Contrary to popular belief I am not an all-knowing wizard.

![image](https://github.com/overextended/ox_inventory/assets/65407488/7266d16e-87ef-42bc-9a23-b85d5e9efee7)

https://github.com/overextended/ox_inventory/issues/1402
https://github.com/overextended/ox_inventory/issues/1404

![image](https://github.com/overextended/ox_inventory/assets/65407488/6d7f54ab-37a7-4039-94b6-6e6b9ab1ac69)
![image](https://github.com/overextended/ox_inventory/assets/65407488/c406067c-be65-4fd6-8ae9-9990c4ba27d5)

**Comment by azm-T** [comment]
I can see the video I posted here, but I don’t know why you can’t see it, it’s really not okay, can I post it on your DISCORD

**Comment by azm-T** [comment]
> 不如实际解释一下问题，而不是不断播放破碎的视频和缺乏信息。与普遍的看法相反，我并不是一个无所不知的巫师。
> 
> ![图像](https://user-images.githubusercontent.com/65407488/254464114-7266d16e-87ef-42bc-9a23-b85d5e9efee7.png)
> 
> [第1402章](https://github.com/overextended/ox_inventory/issues/1402) [第1404章](https://github.com/overextended/ox_inventory/issues/1404)
> 
> ![图像](https://user-images.githubusercontent.com/65407488/254464271-6d7f54ab-37a7-4039-94b6-6e6b9ab1ac69.png) ![图像](https://user-images.githubusercontent.com/65407488/254464216-c406067c-be65-4fd6-8ae9-9990c4ba27d5.png)

I can see the video I posted here, but I don’t know why you can’t see it, it’s really not okay, can I post it on your DISCORD

**Comment by azm-T** [comment]
I can see the video I posted here, but I don’t know why you can’t see it, it’s really not okay, can I post it on your DISCORD @thelindat

**Comment by azm-T** [comment]
I sent the video to your DISCORD, I hope you can watch it @thelindat

**Comment by azm-T** [comment]
https://discord.com/channels/@me/1131085130576953394/1131085219361992834   (The effect of ox_inventory on)
https://discord.com/channels/@me/1131085130576953394/1131085219361992834   (The effect of ox_inventory off)

**Comment by azm-T** [comment]
https://media.discordapp.net/attachments/1131085130576953394/1131085218116292638/2023-07-16_16-07-22.mp4  (When ox_inventory is on)
https://media.discordapp.net/attachments/1131085130576953394/1131085218833498122/2023-07-16_16-14-13.mp4   (When ox_inventory is turned off)

**Comment by thelindat** [comment]
I don't need you responding 3 times, sending me a friend request, and DMing me. Damned pest.

https://overextended.dev/ox_inventory#config

```yaml
# Ignore weapon mismatch checks for the given weapon type (e.g. ['WEAPON_SHOVEL', 'WEAPON_HANDCUFFS'])
setr inventory:ignoreweapons []
```
