### ISSUE TITLE
Error loading script init.lua in resource ox_inventory: @ox_inventory/modules/items/shared.lua:80: attempt to index a number value (local 'clientData')

### ISSUE THREAD

**Issue by Simpiccc** [overextended/ox_inventory#1408]
[    c-scripting-core] Creating script environments for ox_inventory
[ script:ox_inventory] Error loading script init.lua in resource ox_inventory: @ox_inventory/modules/items/shared.lua:80: attempt to index a number value (local 'clientData')
[ script:ox_inventory] stack traceback:
[ script:ox_inventory] 	@ox_inventory/modules/items/shared.lua:80: in local 'newItem'
[ script:ox_inventory] 	@ox_inventory/modules/items/shared.lua:146: in local 'chunk'
[ script:ox_inventory] 	@ox_lib/require/server.lua:51: in function 'require'
[ script:ox_inventory] 	@ox_inventory/modules/items/server.lua:4: in local 'chunk'
[ script:ox_inventory] 	@ox_lib/require/server.lua:51: in function 'require'
[ script:ox_inventory] 	@ox_inventory/modules/inventory/server.lua:411: in local 'chunk'
[ script:ox_inventory] 	@ox_lib/require/server.lua:51: in function 'require'
[ script:ox_inventory] 	@ox_inventory/modules/bridge/server.lua:40: in local 'chunk'
[ script:ox_inventory] 	@ox_lib/require/server.lua:51: in function 'require'
[ script:ox_inventory] 	@ox_inventory/server.lua:7: in local 'chunk'
[ script:ox_inventory] 	@ox_lib/require/server.lua:51: in function 'require'
[ script:ox_inventory] 	(...tail calls...)
[    c-scripting-core] Failed to load script init.lua.
[           resources] Started resource ox_inventory

I don't know what is all this but i think its not supose to be like that ?

**Comment by thelindat** [comment]
I shouldn't have to type-check your data input.
Go to your item data, find where you've decided to define `client` as a number on some item.
