### ISSUE TITLE
Can't open inventory

### ISSUE THREAD

**Issue by NetheriteOfficial** [overextended/ox_inventory#1414]
**Describe the bug**
I Can't access inventory, i must restart script *_ox_inventory_* and every player that joins can't open inventory and after script restart works

**Framework**
ESX

**Resource version**
2.31.3

**To Reproduce**
i don't know how to reproduce it

**Expected behavior**
inventory opening without restarting

**Screenshots**

**Additional context**
I Modified CSS of inventory and stash target positions

**Comment by Scantrax3112** [comment]
I'm having a simular issue. As far as i can tell it has something to do with ESX setjob and not updating the player groups in the inventory. Not sure how to fix this.
