### ISSUE TITLE
Equipped weapon slot change

### ISSUE THREAD

**Issue by Enzix3** [overextended/ox_inventory#1416]
**Describe the bug**
When moving the equipped weapon to other slot and put an other item (for example "water") to the original slot where the equipped weapon was then the inventory will be broken and cannot be used properly anymore.

> SCRIPT ERROR: @ox_inventory/client.lua:1453: attempt to compare nil with number
> callback (@ox_inventory/client.lua:1453)
> fn (@ox_lib/init.lua:123)

**Framework**
ESX Legacy 1.10.1 (Had this issue with 1.9.4 too)

**Resource version**
Inv.: 2.31.3, Lib: 3.6.3, Oxsql: 2.7.2

**To Reproduce**
1. Equip a weapon
2. Open the inventory and move it to other slot while it's still equpped
3. Put an other item to the slot where the equipped weapon was before
4. Close the inventory and open it again
5. See error

**Expected behavior**
-

**Screenshots**
[https://i.imgur.com/ntUAuuH.mp4](url)

**Additional context**
-

**Comment by thelindat** [comment]
This is likely related to and resolved by https://github.com/overextended/ox_inventory/commit/3dcf297d148483544dbad7caa943475b3c634a11.

**Comment by Enzix3** [comment]
Yep, that one resolved it. Thanks!
