### ISSUE TITLE
shop group issue

### ISSUE THREAD

**Issue by SynoFPS** [overextended/ox_inventory#1417]
**Describe the bug**
Updated to newest ox scripts so inv, target, lib, sql, doorlocks. When setting job groups in ox_inventory/data/shops.lua so for example shared.police, the target circle shows up but target options don't come up, but circle turns blue like you are targeting on it, non group targets work fine and as intended. 

**Framework**
Qbox

**Resource version**
version '2.32.0'

**To Reproduce**
Set job to police or any job used for a group in ox_inventory/data/shops.lua.
Go up to any target location and try to target on it.

**Expected behavior**
Ability to open stash for example police armory

**Screenshots**
https://imgur.com/a/ktOyBPn

**Additional context**
Issue didn't happen on a older version of ox_target (version '1.6.1'). No F8 errors or server side errors used git, built everything, targets are formatted correctly with the correct minZ and maxZ (there was no issue for multiple months and they have went unchanged), correct load order (confirmed in support chat already). Everything is up to date and built right job set with the correct ox.cfg and job.lua grades.

**Comment by thelindat** [comment]
![image](https://github.com/overextended/ox_inventory/assets/65407488/53dbc281-442c-4edc-a092-7f0f2eb0864d)

**Comment by Amazingproject-fivem** [comment]
Got same.

**Comment by Mhmortensen** [comment]
what was fix?
