### ISSUE TITLE
Vehicle items not saved when the inventory is opened before database insertion

### ISSUE THREAD

**Issue by edwardexo** [overextended/ox_inventory#1421]
**Describe the bug**
If you access the inventory of a vehicle (glovebox, trunk) before the vehicle is inserted into the database, then the items in that vehicle will not be saved. This causes players to lose all the items that they have placed in the vehicle, as the items will be missing after a server restart.

**Framework**
Custom

**Resource version**
2.31.3

**To Reproduce**
1. Spawn a temporary vehicle
2. Open the glovebox of that vehicle
3. Insert the vehicle into the database (with the exact same license plate)
4. Put something in the glovebox of the vehicle
5. Trigger an inventory save

**Expected behavior**
I expect the inventory to be saved and see 'Saved 1/1 gloveboxes' in the console.

**Actual behavior**
Vehicle items are not saved. Items are missing when the player accesses the inventory after a restart.

**Additional context**
Might seem like an edge case, but a lot of servers use functionality that allow you to convert NPC vehicles into owned vehicles. We personally have a boosting script (the concept of 'boosting' is quite popular in FiveM) with a 'VIN scratch' option. Meaning when doing a job, you can get the vehicle to your garage if you pay a certain amount of money. A lot of players open the glovebox to search for items before they complete the job.

Not having looked at the code, I suppose the vehicle is marked as temporary when the inventory is first opened, and for performance reasons, no further owner checks are done (so the inventory will never be saved).

I understand the performance aspect - it wouldn't be ideal to check the ownership from the database every time a vehicle glovebox/trunk is opened. But perhaps we could somehow manually mark the vehicle inventory to be re-checked again? Any solution here would be welcome to prevent items from disappearing.

**Comment by thelindat** [comment]
> mark the vehicle inventory to be re-checked again

Not a very good solution; for example, we have the export to change the plate reference for an inventory - very easy to use incorrectly or just miss entirely.

Really need to check for valid vehicles before saving, but that's an issue if saving on resourceStop - awaiting an async function will just not save. That rules out querying plates and such.

For now I've just removed the datastore field from vehicles. In the future I'll need something to track ownership and plate changes.
