### ISSUE TITLE
Discord Logging doesnt work

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#1423]
**Describe the bug**
The logging in Discord doesnt work.

**Framework**
ESX

**Resource version**
2.32.0

**To Reproduce**
1. Download inventory
2. set up config
3. set inventory:webhook "https://discord.com/api/xxxxxx"
set inventory:loglevel 2

**Expected behavior**
It should log like told in the doc.

**Comment by N-fire** [comment]
Because it's not for logging, if you want log use ox_lib logger

**Comment by maxcamorra** [comment]
> Because it's not for logging, if you want log use ox_lib logger

How do I use it? in the docs is nothing to find about it.

**Comment by thelindat** [comment]
> The logging in Discord doesnt work.
> It should log like told in the doc.

> Discord webhook url, used for imageurl metadata content moderation (image embeds)
> set inventory:webhook ""

Weird how the term "log" isn't used there.

> Logging via ox_lib (0: Disable, 1: Standard, 2: Include AddItem/RemoveItem, and all shop purchases)
> set inventory:loglevel 1

Oh look logging is mentioned - with ox_lib!

> How do I use it? in the docs is nothing to find about it.

Let's go ahead and use this nifty search bar.

![image](https://github.com/overextended/ox_inventory/assets/65407488/971c4c96-344a-41af-8664-0df8bb364ea6)

**Comment by maxcamorra** [comment]
Yes but in the config of the inventory is the loglevel mentioned if I made it to 2 how do i get the logs then? i have ox_lib installed. i though its implemented in the inventory but how you wrote its not...so why the inventory have this option then?!

**Comment by maxcamorra** [comment]
> > The logging in Discord doesnt work.
> > It should log like told in the doc.
> 
> > Discord webhook url, used for imageurl metadata content moderation (image embeds)
> > set inventory:webhook ""
> 
> Weird how the term "log" isn't used there.
> 
> > Logging via ox_lib (0: Disable, 1: Standard, 2: Include AddItem/RemoveItem, and all shop purchases)
> > set inventory:loglevel 1
> 
> Oh look logging is mentioned - with ox_lib!
> 
> > How do I use it? in the docs is nothing to find about it.
> 
> Let's go ahead and use this nifty search bar.
> 
> ![image](https://user-images.githubusercontent.com/65407488/257249641-971c4c96-344a-41af-8664-0df8bb364ea6.png)

Yes but in the config of the inventory is the loglevel mentioned if I made it to 2 how do i get the logs then? i have ox_lib installed. i though its implemented in the inventory but how you wrote its not...so why the inventory have this option then?!
