### ISSUE TITLE
[SUGGESTION] Rename Button

### ISSUE THREAD

**Issue by TonybynMp4** [overextended/ox_inventory#1427]
**Is your feature request related to a problem? Please describe.**
not really

**Describe the solution you'd like**
A rename button that would simply change the name metadata

**Additional context**
Would be great for clothes as items, would allow the player to name them however they want. but that really applies to anything

**Comment by LukeWasTakenn** [comment]
Already a feature.

https://overextended.dev/ox_inventory/Guides/metadata#special-metadata-properties

**Comment by TonybynMp4** [comment]
![20230321_102246.jpg](https://github.com/overextended/ox_inventory/assets/97451137/50c6e3ef-9897-42fc-95a7-e5233e7cc998)
