### ISSUE TITLE
Is there any way to disable drops for certain items?

### ISSUE THREAD

**Issue by jvstin2k** [overextended/ox_inventory#1436]
**Is your feature request related to a problem? Please describe.**
Its not really a problem, but I am not sure if its possible. Setting "can_remove" to "0" in the database does not disable players dropping the item.

**Describe the solution you'd like**
Want to set items to not droppable

**Describe alternatives you've considered**
Tried to set in in the database

**Comment by N-fire** [comment]
you can use hooks for this : https://discord.com/channels/813030955598086174/830737052352905217/1138210139736907916
https://overextended.dev/ox_inventory/Functions/Server/Hooks
