### ISSUE TITLE
Issues with weight going over limit

### ISSUE THREAD

**Issue by DooubleTap** [overextended/ox_inventory#1440]
**Describe the bug**
In the inventory, when you get more items and it exceede the weight limit, you can still pick the items up, or receive them. (you are never overweight)
![image](https://github.com/overextended/ox_inventory/assets/3772136/49d95ee6-797b-42f4-8eb1-b1f9213d9641)

**Framework**
QB

**Resource version**
version '2.32.3'

**To Reproduce**
1. pickup item
2. be overweight

**Expected behavior**
It should not be overweight

**Screenshots**
its up there

**Additional context**
Pretty simple issue imo.

**Comment by thelindat** [comment]
> Steps to reproduce the behavior:
> 
>     1. pickup item
> 
>     2. be overweight

try again

**Comment by DooubleTap** [comment]
The thing is, i dont have to try again. When you pickup items, you could be 500% overweight, but ox_inventory will not manage that for some reason... is it fixed now on the latest updates or not?

**Comment by thelindat** [comment]
It was never broken, hence my statement of "try again" - because your steps to reproduce the behaviour are invalid.

**Comment by DooubleTap** [comment]
The thing is, there is no way to be overweight, i am not sure how i could reproduce it better then explaining it. 
Whenever i receive, pickup, get given an item. even if i am at maximum weight, it will just ignore the limit and still put the items in my inventory. 
Is it better explained?
