### ISSUE TITLE
when I use exports.ox_inventory:openInventory('player', 3),can not open the inventory

### ISSUE THREAD

**Issue by 1489259653** [overextended/ox_inventory#1441]
when I use id 3, I will get notify "You can not open this inventory"
but when I replace 3 to my id, the notify won't show up, and I still can't open my inventory.

**Comment by thelindat** [comment]
0e40574 and 267bb67

**Comment by 1489259653** [comment]
> [0e40574](https://github.com/overextended/ox_inventory/commit/0e40574884ff0d455f358625ca34e5a183c30be4) and [267bb67](https://github.com/overextended/ox_inventory/commit/267bb67a22383d487ea507dd4c97dd26f92b1a36)

thanks a lot, it can works
