### ISSUE TITLE
QB-target

### ISSUE THREAD

**Issue by NathanT200** [overextended/ox_inventory#1449]
How can I make it work for qb-target with qbcore, please I want my scripts to work with the qb-target I like ox-target but I don't want to change all of my qb-target dependancy to ox-target...

**Comment by thelindat** [comment]
Modifications are _your responsibility_. We do not support qb-target, we never _will_ support qb-target, and we will not assist people with making modifications we aren't interested in ourselves.

_Technically_ qb-target has support for qtarget exports - but qtarget support has just been removed entirely as it's arse.
