### ISSUE TITLE
Issues with vehicle who doesnt have boot/trunk bone index

### ISSUE THREAD

**Issue by luthanirgi** [overextended/ox_inventory#1451]
**Describe the bug**
Trunk cannot be opened if vehicle doesnt have any boot/trunk bone index

**Framework**
ESX Last Version

**Resource version**
ox_inventory Last Version

**To Reproduce**
Example for zentorno
1. Go to data/vehicles.lua
2. Add `[`zentorno`] = 1`, on storage column
3. Scroll down to bone index column, add `[`zentorno`] = 'wheel_rr',`

**Expected behavior**
Trunk/glovebox can be opened if you set on data/vehicles.lua

**Additional context**
i think this is the code who is responsible for that
```
function Inventory.CanAccessTrunk(entity)
    if cache.vehicle or not NetworkGetEntityIsNetworked(entity) then return end

	local vehicleHash = GetEntityModel(entity)
    local vehicleClass = GetVehicleClass(entity)
    local checkVehicle = Vehicles.Storage[vehicleHash]

    if (checkVehicle == 0 or checkVehicle == 1) or (not Vehicles.trunk[vehicleClass] and not Vehicles.trunk.models[vehicleHash]) then return end

    ---@type number | number[]
    local doorId = checkVehicle and 4 or 5

    if not GetIsDoorValid(entity, doorId --[[@as number]]) then
        if vehicleClass ~= 11 and (doorId ~= 5 or GetEntityBoneIndexByName(entity, 'boot') ~= -1 or not GetIsDoorValid(entity, 2)) then
            return
        end

        if vehicleClass ~= 11 then
            doorId = backDoorIds
        end
    end

    local min, max = GetModelDimensions(vehicleHash)
    local offset = (max - min) * (not checkVehicle and vec3(0.5, 0, 0.5) or vec3(0.5, 1, 0.5)) + min
    offset = GetOffsetFromEntityInWorldCoords(entity, offset.x, offset.y, offset.z)

    if #(GetEntityCoords(cache.ped) - offset) < 1.5 then
        local coords = GetEntityCoords(entity)

        TaskTurnPedToFaceCoord(cache.ped, coords.x, coords.y, coords.z, 0)

        return doorId
    end
end
```

**Comment by thelindat** [comment]
boneIndex was a PR made to allow opening trunks for vehicles where the trunk was in a difficult position to get close to, or where it didn't have a trunk but should realistically have storage space (e.g. vans).

Zentorno is clearly marked as "vehicle has no trunk storage", as it does not have any storage space. If boneIndex was overwriting the _disabled_ trunk then it's now working as intended.

If you don't like that, change that on your end.

**Comment by luthanirgi** [comment]
allright, thanks btw!
