### ISSUE TITLE
Crafting item locale

### ISSUE THREAD

**Issue by kuomars110** [overextended/ox_inventory#1454]
**Describe the bug**
I create a crafting table and also added metadata to it
``` metadata = {description = 'Cocaine', weight = 100 , image ='cocaine' }, ```
but when user try to craft it says Crafting %S instead of name of item
[https://media.discordapp.net/attachments/963139894887190580/1142097411137876131/image.png](url)
**Framework**
ESX

**Resource version**
2.33.0

**To Reproduce**

**Expected behavior**
It should send item name

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/blob/b95612068a8be7b6effea7eff0de993f11c36a26/client.lua#L1664
