### ISSUE TITLE
Weapon Durability

### ISSUE THREAD

**Issue by ONyambura** [overextended/ox_inventory#1455]
**Describe the bug**
Weapons won't lose durability after 2.31.0 version.

**Framework**
Any

**Resource version**
2.32.0 + last release

**To Reproduce**
After some updates (i have lost which one it was working last time). Weapons durability has issue. 
While holding a weapon, it always updates players slots > playerInventory with items and weight while items is an non-latest cached from user's inventory 
`local function updateInventory(data, weight) @ox_inventory/client/main@857`
```lua
            if currentWeapon?.slot == item?.slot and item.metadata then
                -- currentWeapon.metadata = item.metadata
                TriggerEvent('ox_inventory:currentWeapon', currentWeapon)
            end
```

`currentWeapon.metadata.durability` print the newest durability the weapon has.
`item.metadata.durability` prints the very first (probably the previeous durability on items which is 100%) and it replaces it.
commeting out this `currentWeapon.metadata = item.metadata` helps to fix my issue for now.
Tried to debugg and went all the way down to function `OxInventory:syncSlotsWithClients(slots, syncOwner) @ox_inventory/modules/inventory/server.lua@74`
being called on a loop while holding a weapon. 
Have no more time today to continue debugging and getting into the right way to fix , but a temp fix is commeting out the above line.
Has anyone else the same issue with me?
tried `version '2.31.0'` and works fine. same issue for version `'2.32.0' and latest`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by thelindat** [comment]
> `OxInventory:syncSlotsWithClients(slots, syncOwner) @ox_inventory/modules/inventory/server.lua@74`
> being called on a loop while holding a weapon.

![image](https://github.com/overextended/ox_inventory/assets/65407488/97a23f33-5ede-4981-9ce5-806b28a7192c)

Not called a single time while holding a weapon nor when shooting; what are you on about?

> currentWeapon.metadata.durability print the newest durability the weapon has.
item.metadata.durability prints the very first (probably the previeous durability on items which is 100%) and it replaces it.
commeting out this currentWeapon.metadata = item.metadata helps to fix my issue for now.

```lua
AddEventHandler('ox_inventory:currentWeapon', function(data)
    if not data then return end

    print(data.name, data.metadata.ammo, data.metadata.durability)
end)
```

![image](https://github.com/overextended/ox_inventory/assets/65407488/ee838749-5b13-4cf1-9aba-17479b486e84)

So working entirely as expected?

**Comment by thelindat** [comment]
And swapping weapon, while we're at it.

![image](https://github.com/overextended/ox_inventory/assets/65407488/5201a8fb-e0e6-4153-9950-2ecf3a071c31)
![image](https://github.com/overextended/ox_inventory/assets/65407488/91b732c4-f30d-4d7b-b364-67cde32d86c3)

**Comment by Lucent94** [comment]
Dunno mate, debugged and found that i've said on the repoort.
I've also made a thread at discord , you can see other ppl too has the same issue.
Ver. 2.33.0
Also on this ver. there's that error.
![image](https://github.com/overextended/ox_inventory/assets/120286032/0b1e6f8d-5145-4804-a6cc-773831b8ace9)

**Comment by ONyambura** [comment]
Dunno mate, i'm not the only one facing this one.
I've made a thread on discord where people claiming they face the same issue with me. 
Ver 2.33.0 and today tried 2.33.1 , same issue.
Clip 1 > https://streamable.com/d35xyw
Clip 2 > https://streamable.com/51g2cl
SS > 
![image](https://github.com/overextended/ox_inventory/assets/51477970/622e5d89-0945-4da9-a10e-500f9d4d3ed3)

**Comment by ONyambura** [comment]
Issue comes on thiss update, after commeting out this change on the lateste version 2.33.1 (or last used for me, 2.33.0) durability works fine.
v2.33.1 , fix(server/inventory): Inventory.SetMetadata should always sync
https://github.com/overextended/ox_inventory/commit/b5fe34ec88902efd54b46a2e97e6d4088bb9e24f

**Comment by thelindat** [comment]
This is a you issue. I don't care if somebody else gets it either, because it doesn't happen on the release build / origin.

Your claims of no durability and syncSlots spam both contradict what actually happens, and it's not like I didn't test your claims.

Metadata has to sync (surprise, server authority), metadata has to be replaced during updateInventory, and you can blame as many commits as you want but when the code is working as intended I cannot do anything for you

**Comment by thelindat** [comment]
By the way SetMetadata is something used by other resources; so you have a script running it and "spamming it while holding a weapon".
