### ISSUE TITLE
Bug with inventory

### ISSUE THREAD

**Issue by RoccoRP** [overextended/ox_inventory#1456]
**Describe the bug**
i want to use  this inventory for PvP server , everytime a player die and revive cant  use his weapons he has to relog or restart inventory so he can use his weapons

**Framework**
ESX

**Resource version**
version '2.33.0'

**Comment by thelindat** [comment]
Reviving in ESX and marking the player as alive (technically, not dead) requires triggering either 'playerSpawned' or 'esx:onPlayerSpawn' events.
