### ISSUE TITLE
OX Core + OX Inventory SQL not saving

### ISSUE THREAD

**Issue by ProXySGit** [overextended/ox_inventory#1459]
actually trying to install ox inventory on ox core, working with no error on console or in the f8 console, everything work correctly until server restart or saveinv command, not saving in sql then when i restart the server, i restart with an empty inventory :/

**Comment by thelindat** [comment]
I do 99% of my testing on ox_core; needless to say I do not have any issues with saving.

**Comment by duckysuck** [comment]
I installed fresh this week with ox_core, saving works fine. This must have been a db issue/setup issue.
