### ISSUE TITLE
Can't drop items on ground

### ISSUE THREAD

**Issue by wreox22** [overextended/ox_inventory#1460]
**Describe the bug**
When I drag items from my inventory to ground on the right side it won't drop it. It used to work but now it just returns item back to my inventory.

**Framework**
ESX

**Resource version**
2.31.3

**To Reproduce**
1. Open inventory by pressing F2
2. Dragging item to right side of inventory to drop it on ground
3. Item just returns back to my inventory and doesn't drop

**Expected behavior**
I expected for item to be on the ground

**Screenshots**
Can't show you via screenshots

**Additional context**
Only when I restart script I can drop items again

**Comment by thelindat** [comment]
![image](https://github.com/overextended/ox_inventory/assets/65407488/7d7db04c-35b0-4f4c-bedb-a6b530e9082c)

> Only when I restart script I can drop items again

Then you likely have a hook preventing drops.

**Comment by wreox22** [comment]
How do I check for hooks?
