### ISSUE TITLE
displayMetadata duplicates

### ISSUE THREAD

**Issue by Edward-Bakker** [overextended/ox_inventory#1463]
**Describe the bug**
If you trigger the `displayMetadata` export with the same key multiple times, with the same value, the metadata shows the amount of time the export has been triggered.

**Framework**
ESX

**Resource version**
`2.33.1`

**To Reproduce**
1. Call `displayMetadata` export.
2. Call it again with same values.
3. Check your inventory, now displays the same metadata twice.

**Expected behavior**
Metadata displays once per key value pair.

**Screenshots**
![image](https://github.com/overextended/ox_inventory/assets/24864616/ac7650af-082d-4b0e-894c-e816aa15fc93)

**Additional context**
This is caused by either restarting the script calling the export, or by just calling the export twice.

**Comment by thelindat** [comment]
How hard is it to just not call exports more than you need to?

**Comment by Edward-Bakker** [comment]
> How hard is it to just not call exports more than you need to?

There's no way to check if the metadata is already displayed, leading to the export being called on script start whether it is needed or not.

If I have to restart that script for some reason (i.e. while developing, I altered that script and want to test the changes), the export gets called again, leading to aforementioned issue.
