### ISSUE TITLE
Weapons License Issue

### ISSUE THREAD

**Issue by RoyalLasky** [overextended/ox_inventory#1467]
**Describe the bug**
If one of your characters has their weapons license, all your characters act as they have a weapons license though in database the metadata is "weapon":false on the character.

This was reported by players, and I tested it myself.
I had no characters which had their weapons license. I provided 1 character with a weapon license and was able to now buy weapons and the metadata in database changed accordingly to "weapon":true. I logged out, logged back in on other characters and was also able to buy weapons even though on those characters the metadata in database is "weapon":false.

**Framework**
QB

**Resource version**
version '2.33.0'

**To Reproduce**
1. Have no weapons license(on any character) and attempt to buy, it will fail.
2. Provide yourself with a weapons license, it will pass and work correctly.
3. Log into another character and attempt to buy a weapons license. 

**Expected behavior**
Characters which do not have a weapons license cannot purchase items which require a weapons license.

**Screenshots**
N/A. Can provide video if necessary.

**Additional context**
N/A

**Comment by thelindat** [comment]
License is checked each time you try to buy something with a license requirement, and is done through QB.
