### ISSUE TITLE
Unable to access shops

### ISSUE THREAD

**Issue by DerekNL** [overextended/ox_inventory#1481]
**Describe the bug**
Since the latest update to the shop coordinates, you are unable to open stores that use peds.

**Framework**
ESX

**Resource version**
2.34.1

**To Reproduce**
1. Create a shop using the similar guide https://overextended.dev/ox_inventory/Guides/shops.
2. Attempt to target the ped and open the shop.
3. The shop wont open.

**Expected behavior**
The shop should open

**Screenshots**
Error log;
\`\`\`
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/shops/server.lua:85: attempt to perform arithmetic on a nil value (field 'minZ')
[ script:ox_inventory] > callbackResponse (@ox_lib/imports/callback/server.lua:60)
[ script:ox_inventory] > handler (@ox_lib/imports/callback/server.lua:76)
[ script:ox_inventory] 
\`\`\`

**Additional context**
- Artifacts: 6683
- Game Build: 2944

**Comment by thelindat** [comment]
![image](https://github.com/overextended/ox_inventory/assets/65407488/ff0c9ea7-97f7-469c-984b-045a89e53515)
