### ISSUE TITLE
errors, scripts don't work

### ISSUE THREAD

**Issue by JeffreyKroonenberg** [overextended/ox_inventory#1483]
**Describe the bug**
We see a number of errors

**Framework**
We use esx

**Resource version**
ox Inventory: 2.34.2
ox Feul 1.4.0

**To Reproduce**

**Expected behavior**
no errors, and that script works

**Screenshots**
[foto 1](https://ibb.co/51NxZcW)
[foto 2](https://ibb.co/g95nhM1)

**Additional context**
we have those 2 errors, see photos
I hope that gets fixed
The inventory script also does not work due to the error
also the tank script does not work due to the error

**Comment by FilipeCuco** [comment]
just start ox_lib above everyone

**Comment by JeffreyKroonenberg** [comment]
unfortunately did not solve the error of addzonebox
