### ISSUE TITLE
Nil value open glovebox vehicles

### ISSUE THREAD

**Issue by nurrifqialhusaini** [overextended/ox_inventory#1487]
Hello, i reported a bug when opening the vehicle's glovebox, an error will appear indicating the nil value.

`attempt to index a nil value (upvalue 'currentInventory')`
ref from `ox_lib/imports/addKeybind/client.lua:58`
[https://github.com/overextended/ox_inventory/blob/beca6d8fb22a516c19914417e354eb22c669b545/client.lua#L706C25-L706C25](url)

Thanks

**Comment by thelindat** [comment]
I cannot find a single instance where currentInventory would be nil when the return from openInventory was true.
