### ISSUE TITLE
Remove inventory from database

### ISSUE THREAD

**Issue by nurrifqialhusaini** [overextended/ox_inventory#1488]
Will there be a function to delete a data inventory from the database (not just make null data) but use the inventory key name?
Like sql query `DELETE FROM ox_inventory WHERE name = ?` and it can be called using an exports server side, such as `RemoveInventoryDatabase`. Better included in function and cache in `db.saveInventories`.
Thanks

**Comment by thelindat** [comment]
Why not just delete it yourself..?

**Comment by nurrifqialhusaini** [comment]
yeah, in this time im delete by query oxmysql, maybe it may take up a lot of bandwidth when deleting without using cache
