### ISSUE TITLE
New items don't work properly but all old ones do

### ISSUE THREAD

**Issue by silez** [overextended/ox_inventory#1489]
**Describe the bug**
Good afternoon dear OX team,

I'm having a problem (recently) with adding items.
This had always worked before without any problems. I don't know what else I'm doing wrong, apparently.
To illustrate this, I have attached two screenshots.
1. The error message in the F8 console
2. The code in data.lua how I add the items to the inventory.
3. The item in the ingame inventory menu

Does anyone have any advice as to why this could happen?
Of course the error message says “item data undefined” but I added the item like everyone else. We currently have over 300 working items. Now I just want to add 5 more and they just don't work. They are displayed in the inventory but you cannot move them, let alone use them or put them on the street.

**Framework**
ESX Legacy 1.10.1

**Resource version**
2.34.3

**To Reproduce**
1. Find the item image, name it like the item in the items.lua and upload it to the web/images folder
2. Restart ox_inventory (or restart the server)
3. Give the item to your character
4. Open the inventory, notice that the item name is on it but not the label and that you cannot move it, give it to someone or put it on the street

**Expected behavior**
I expected the new item to work like any other item I've added in the past.

Thanks for your help in advance!

**Screenshots**
Screenshot 1:
![Screenshot 2023-09-21 153832](https://github.com/overextended/ox_inventory/assets/8078098/8e4748e3-69a3-4acb-b771-683fc03a9b9e)
Screenshot 2:
![Screenshot 2023-09-21 154732](https://github.com/overextended/ox_inventory/assets/8078098/6ed3e625-4e68-49fb-8070-bb2b9b870e9a)
Screenshot 3:
![Screenshot 2023-09-21 154936](https://github.com/overextended/ox_inventory/assets/8078098/2a62364e-b3d4-4955-8dc3-c59699f0c08d)

**Comment by silez** [comment]
Hello again

Now I've tested a little further, when I want to put items on the ground (or the street), this error occurs and the inventory is stuck.

Here is a screenshot of the error message in the F8 console:

![Screenshot 2023-09-21 161118](https://github.com/overextended/ox_inventory/assets/8078098/f14d5ede-5941-4e3a-aa6e-9728d57ce855)

**Comment by thelindat** [comment]
Yes your data files have invalid data. Congratulations.
