### ISSUE TITLE
Inventory stash saving issue

### ISSUE THREAD

**Issue by Alsexk** [overextended/ox_inventory#1495]
**Describe the bug**
Stashes sometimes dont save correctly which can lead to people losing theyre items when putting items to stash or if taking it could dupe the item

**Framework**
QBCore (v1.2.1)

**Resource version**
v2.34.3

**To Reproduce**
https://www.youtube.com/watch?v=aYlOySuvGbo

**Expected behavior**
Inventory saves stash normally 100% of time

**Additional context**
Bug only happens maybe like 30% of time
I use txadmin scheduled restart system
oxmysql version: 2.7.4

**Comment by MCS-1999** [comment]
this is happening to us as well.

**Comment by ProjectRogueRP** [comment]
Having this issue since 2.35 and have this on 2.35.1 as well. It stink to be honest, its killing me cause players stuff keeps loosing everything

**Comment by SoyJuanFran** [comment]
I have the same problem. It doesn't always store the stash. Trunks, gloveboxes and inventories are stored 100% times.
I have tested version 2.34.3 up to 3.35.1
Now I will try version 2.33.2 to see if it works well.

**Comment by SoyJuanFran** [comment]
2.33.2 work fine

**Comment by SoyJuanFran** [comment]
2.33.2 does not work well

**Comment by cjosephdc** [comment]
> 2.33.2 does not work well
> 
> EDIT:
> 
> Last night it gave an error and checked the operation. It seems that CRON is not running correctly and is causing problems. Since 20:00 CRON has not been executed again. So I changed this to see if it saves everything correctly.
> 
> ```
> lib.cron.new('*/5 * * * *', function()
>     saveInventories(true)
> end)
> ```
> 
> ```
> Citizen.CreateThread(function()
> 	while true do
> 		Citizen.Wait(300 * 1000)
> 		saveInventories(true)
> 	end
> end)
> ```
> 
> Ox_inventory 2.33.2 Ox_lib 3.11.0 Ox_mysql 2.7.5

Does that fix the issue? Im still facing same issue with the latest update.
