### ISSUE TITLE
Ox_inventory Slot Search for Durability

### ISSUE THREAD

**Issue by ItzTrivial** [overextended/ox_inventory#1500]
**Describe the bug**
Searching for an item with a certain durability doesnt seem to work properly. 

**Framework**
ESX

**Resource version**
2.34.2

**To Reproduce**
1. Have Weapon with durability 0 in inventory
2. Execute Search on Serverside for slots with metadata set to {durability = 0}
3. Doesnt return the item

4. Same Search but look for serialnumber in metadata instead returns item correctly.

**Expected behavior**
Should return the weapon from the inventory with the set name and fitting durability

**Screenshots**
![image](https://github.com/overextended/ox_inventory/assets/66124070/2ff2df01-acfc-47a3-8372-58c4b5cb7054)
![image](https://github.com/overextended/ox_inventory/assets/66124070/d5c74415-9243-4534-bc2c-5f437bd9e4a4)
Picture one shows prints from the source code of ox_inventory. The first line is the metadata Im looking for in the 2nd line (table.contains), false shows its not in table.

**Additional context**
Tried the same with the serialnumber. Prints were similar, but true instead of false, even though it looks just like the durability print.

**Comment by thelindat** [comment]
Cannot repro.
