### ISSUE TITLE
You can't shoot if you're standing too close to a wall or person

### ISSUE THREAD

**Issue by Schwarzerteddydev** [overextended/ox_inventory#1501]
You can't shoot if you're standing too close to a wall or person

https://prnt.sc/jXnau2he6tQ9

**Comment by thelindat** [comment]
> too close to a wall

Welcome to GTA.

> or person

Which normally triggers a melee (i.e. pistol whip) and you have blocked.

**Comment by Schwarzerteddydev** [comment]
can't be because if i stand in front of one i can shoot at it but if i have a police shield in my hand it won't work
 
and when the inventory is off it works so it can not be because of gta
