### ISSUE TITLE
Adding custom weapons

### ISSUE THREAD

**Issue by Cockers96** [overextended/ox_inventory#1502]
**Describe the bug**
so ive added them, theyre streamed fine, added them to the weapons.lua however in city whenevr i try to pull them out i get 'unable to use "weapon name"'

**Framework**
QBOX

![image](https://github.com/overextended/ox_inventory/assets/142825218/4d4177f3-9350-4a8b-be8e-3cd7f2a0a7e5)

**Comment by LordNiiros** [comment]
I have the same issue, how did you fix this?

**Comment by ItssJxstnDe** [comment]
Same!
