### ISSUE TITLE
Automatic unequip for moved hotbar items

### ISSUE THREAD

**Issue by jxckUK** [overextended/ox_inventory#1514]
**Is your feature request related to a problem? Please describe.**

No, not an issue other than moving an equipped hot bar item from the hot bar slot to a standard slot will then render the player unable to unequip without going back into the inventory and re-assigning to a hot bar slot.

**Describe the solution you'd like**

When an item is moved from a hot bar slot it should holster the item similar to when the item is dropped from the inventory. This will improve user experience as it reduces the required user interaction for unequipping unassigned hot bar items.

**Comment by thelindat** [comment]
![image](https://github.com/overextended/ox_inventory/assets/65407488/a9494c82-f846-4643-9d26-36f9e58f33cc)
