### ISSUE TITLE
Blip name in ox_inventory crafting doesn't work + Fix 

### ISSUE THREAD

**Issue by Mistz-ik** [overextended/ox_inventory#1517]
the issue is in modules/utils/client.lua in the function Utils.CreateBlip()

Your function :

`local blip = AddBlipForCoord(coords.x, coords.y, coords.z)
	SetBlipSprite(blip, settings.id)
	SetBlipDisplay(blip, 4)
	SetBlipScale(blip, settings.scale)
	SetBlipColour(blip, settings.colour)
	SetBlipAsShortRange(blip, true)
	BeginTextCommandSetBlipName(settings.name)
	EndTextCommandSetBlipName(blip)`
	
The Fixed Function :

`local blip = AddBlipForCoord(coords.x, coords.y, coords.z)
	SetBlipSprite(blip, settings.id)
	SetBlipDisplay(blip, 4)
	SetBlipScale(blip, settings.scale)
	SetBlipColour(blip, settings.colour)
	SetBlipAsShortRange(blip, true)
       BeginTextCommandSetBlipName("STRING")
       AddTextComponentString(settings.name)
	EndTextCommandSetBlipName(blip)`
	
I changed the parameter of BeginTextCommandSetBlipName() from settings.name to "STRING" and i added AddTextComponentString(settings.name) between BeginTextCommandSetBlipName()  and EndTextCommandSetBlipName()

**Comment by thelindat** [comment]
![image](https://github.com/overextended/ox_inventory/assets/65407488/629702e2-6499-4d53-b68d-f915fe112934)
![image](https://github.com/overextended/ox_inventory/assets/65407488/c4c29521-026b-48e1-81d6-b481c204f675)


?????
