### ISSUE TITLE
Stash Duplication/Rollback?

### ISSUE THREAD

**Issue by HighLatencyy** [overextended/ox_inventory#1525]
**Describe the bug**
It appears that stashes seem to be duplicating or rolling back on the latest version of the inventory randomly. I'm not sure how to reproduce it fully but there's a video below to showcase you the issue.

**Framework**
es_extended - 1.10.2

**Resource version**
2.35.1

**To Reproduce**
1. Take the item(s) out of the stash.
2. Wait a few minute(s) and go back inside to put them back in the stash.
3. The items should be duped?

**Expected behavior**
The items inside of the stash shouldn't be duplicated.

**Screenshots**
Here's a video on it but I am not sure how to reproduce it because it seems to different every time. To explain it, there was two combats and a Glock 19x. They took the items out, then went back inside and after a while they went to put them back in the stash and the items duped.

https://streamable.com/86mq89

**Additional context**
- Not sure but I seen https://github.com/overextended/ox_inventory/issues/1495 here that someone had the same issue.
- I also seen https://discord.com/channels/813030955598086174/1163263644688199751/1163263644688199751 that someone had the same issue but not sure if it's related.

**Comment by MatinHQ** [comment]
Hello, try 2.7.6 it should be fixed

**Comment by MrTomatenblau** [comment]
Hey, same issue here, duplicated some items random and not reproduceable. 
esx 1.9.4
ox_inv 2.35.1
ox_mysql 2.7.5 // mysql  Ver 15.1 Distrib 10.6.12-MariaDB

**Comment by jag3dagster** [comment]
Okay, but do you have updated reproducible steps @MrTomatenblau ?

**Comment by jag3dagster** [comment]
Actually @MrTomatenblau, update to 2.36.0. Should be fixed in that version
