### ISSUE TITLE
Weapon wheel 

### ISSUE THREAD

**Issue by pep021** [overextended/ox_inventory#1529]
Hello i have a problem. I want to disable the hotbar and enable the default gta5 weapon wheel. How could i do that if someone could help me really or give me basic instructions i will do it myself. I really want the old weapon wheel back

**Comment by jag3dagster** [comment]
This is not a bug. The two systems are incompatible. If you want weapon wheel you'll likely need another inventory system unless you want to spend a lot of time reworking the system yourself.
