### ISSUE TITLE
Can't add custom weapons

### ISSUE THREAD

**Issue by ghost** [overextended/ox_inventory#1531]
**Describe the bug**
I correctly stream custom guns to my server and I added them into the ox_inventory's data/weapons but whenever I try to equip it I get notification saying I can't use the weapon.

**Framework**
ESX

**Comment by ItssJxstnDe** [comment]
same on qb

**Comment by jag3dagster** [comment]
Usually means that the weapon has invalid attachments or some other invalid configuration in their meta files. Ox inventory validates those things more than other systems.

**Comment by LordNiiros** [comment]
> Usually means that the weapon has invalid attachments or some other invalid configuration in their meta files. Ox inventory validates those things more than other systems.

I double checked those files but I'm pretty sure that's all in order, would you have any idea what else it could be?

**Comment by jag3dagster** [comment]
If you are getting the message "Unable to use <weapon name>" then it means that the game was unable to give the weapon to the player ped indicating that the meta files aren't being streamed properly or at all; or the weapon didn't properly load when the inventory attempting to place the weapon in the player ped's hands indicating that something went wrong when the game tried to render the model and the meta files dictate what the default model will render with.

I don't know what 'double checked those files' means to you, but I would check to see if there are any unexpected Items under the `<AttachPoints>` element of your weapon info items.

**Comment by iSentrie** [comment]
You probably have them imported in items.lua instead of weapons.lua or in both, so remove from items.lua
Maybe that's the case for you.
