### ISSUE TITLE
ESX.UseItem won't be called on Item Use

### ISSUE THREAD

**Issue by Phantom1092** [overextended/ox_inventory#1540]
**Describe the bug**
I have registered an item using ESX.RegisterUsableItem (as you described in your documentation), added it into items.lua,
started the necessary scripts in your recommended order and even put some prints into the bridge, ESX.UseItem, etc.
When using Use in ox_inventory, I don't get any output in the console. Calling ESX.UseItem directly, I do.

**Framework**
I'm using ESX Legacy, latest version with the latest commit of ox_inventory

**To Reproduce**
1. ESX.RegisterUsableItem in another script
2. Add the item into items.lua
3. Use the item in the UI
4. Callback-Function in RegisterUsableItem isn't called or if you add a print inside UseItem in es_extended/server/functions.lua it doesn't get printed

**Expected behavior**
My callback function should be called

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/blob/main/server.lua#L271

UseItem is used as a fallback option _when no internal usage_ is in place.
