### ISSUE TITLE
Create container with items inside.

### ISSUE THREAD

**Issue by Tomci0** [overextended/ox_inventory#1542]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Can create container with items inside or add items to container.

**Describe alternatives you've considered**
Add item by export AddItem and inv id = container id doesn't working.

**Comment by thelindat** [comment]
https://overextended.dev/ox_inventory/Functions/Server#getcontainerfromslot

**Comment by Tomci0** [comment]
This returning data with container id, but i can't add items by this id.
