### ISSUE TITLE
View other player's inventory but disable taking items

### ISSUE THREAD

**Issue by Scantrax3112** [overextended/ox_inventory#1545]
Is there a way to view another player's inventory without the ability to take items from them? I would like to have this feature for a situation like the following:

A gang member is trying to rip a civilian but has no idea if the civilian is telling the truth about the items he of she is carrying. I.e. the civilian has some money, food and drinks, a weapon and some jewelry. The gang member then asks what the civilian has with him/her and they don't mention the money, jewelry or weapon. There is no way for the gang member to check this. In this case it would be nice to have an option where the gang member can open the inventory of the civilian, but can not take their items (to prevent abuse). At least then they know if the civilian is telling the truth and they can alert staff if the civilian is not cooperating.

The only thing i could find in the documentation is the option to search for the police job or when a player is nearly dead. It's just not what i'm looking for though

**Comment by Skryptific** [comment]
Use hooks.
