### ISSUE TITLE
ndcore - inventory money not syncing in inventory anymore unless someone relogs

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [overextended/ox_inventory#1546]
Using nd_core framework and ox_inventory v2.36.1. 

When we withdraw/deposit money it updates in our hud (SimpleHUD) on the ND side, which is what we use in conjunction with Ox Inventory.

The only way that we can get the money in the inventory to sync is if the person leaves and rejoins the server. As if it cannot sync in real time.

This prevents people from buying or using the inventory really at all. As it keeps telling them that they dont have enough cash to buy a items.

This was working fine, yet seems to have stopped after the last couple of versions of ox_inventory (I think it was fine before [v2.36.0](https://github.com/overextended/ox_inventory/releases/tag/v2.36.0) but I cannot recall) and we are trying to figure out what the issue is by looking at patch notes there. No updates/changes to ND core have occurred.

We've determined that the "nd:moneyChange" event is not being triggered at all (registerevent debuging outputed nothing). 

Running latest server artifacts as well and game build.

I've seen more reports of this from other server owners, just can't understand why.

Any insight?

cc: @Andyyy7666

**Comment by Andyyy7666** [comment]
I haven't seen this before, I'll look into it tomorrow.

**Comment by thelindat** [comment]
From [Discord](https://discord.com/channels/813030955598086174/1178476648698495046).

> This is in the config.lua for ox_inventory which in the past (8 or 10 versions ago) this was working perfectly
>Set items to sync with framework accounts
>set inventory:accounts ["cash"]

> I also use NDCore. Mine is set to:
>set inventory:accounts ["money"]
>No issues. My HUD syncs with my inventory. This works with both Andy's SimpleHUD and his ModernHUD and tested on both my v1 and v2 dev servers.

**Comment by Legacy-TacticalGamingInteractive** [comment]
I do have it set to 

# Set items to sync with framework accounts
set inventory:accounts ["money"]

thats the strange thing
hmm

**Comment by Legacy-TacticalGamingInteractive** [comment]
> I haven't seen this before, I'll look into it tomorrow. @Andyyy7666 

Any luck?

I'm not sure about the other guys with the issue but could it be linked to NoCharacters or something?

I'm so confused about this. Keep getting daily complaints since nobody can buy anything properly without the real cash amount from their ND.

Could it be some other issue with any of these that you can see?

nd framework
characters table
![image](https://github.com/overextended/ox_inventory/assets/25211271/9d42eeb0-3cc3-4155-970f-f08383913da5)

ox_inventory table
![image](https://github.com/overextended/ox_inventory/assets/25211271/d950c1fe-f800-470c-bc11-4c208d94800d)

**Comment by Legacy-TacticalGamingInteractive** [comment]
I can fully say after multiple rounds on testing on three servers now

The syncing between the SimpleHUD, ND, Inventory for buying items works fine only on the first login after a server restart.
Soon as the person leaves the server and joins again later - the issue is now present. Buying items only taking from inventory money and not ND cash.

I am running ND core 1.0.3 with ox inventory version 2.36.1
game build 2944 and artifacts 7187

**Comment by Andyyy7666** [comment]
@Legacy-TacticalGamingInteractive can you update to v2 on your test server and let me know if you experience the same issue, ND_Characters is not required for v2 if you want to run single characters system ND_Core only should work.

**Comment by Legacy-TacticalGamingInteractive** [comment]
> @Legacy-TacticalGamingInteractive can you update to v2 on your test server and let me know if you experience the same issue, ND_Characters is not required for v2 if you want to run single characters system ND_Core only should work.

Will check it out tonight/tomorrow and let you know any findings
