### ISSUE TITLE
No such export HasItem in ressource ox_inventory

### ISSUE THREAD

**Issue by nathan-collab** [overextended/ox_inventory#1556]
**Describe the bug**
As soon as I spawn I can’t open my inventory, and I have these errors that show up. So I can’t use my inventory. 

**Framework**
Framework is QBCore version : 1.2.2

**Resource version**
Ox_inventory : 2.37.2
Ox_lib : 3.13.0
QBCore : 1.2.2

**To Reproduce**
Connection to the server then appears, appearance of errors, tries to open inventory does not work.

**Expected behavior**
The expected behavior is to be able to open the inventory and that the QBCore.Functions.HasItem(item, count) function is replaced to work with your ox_inventory inventory. And there’s no interference. 

**Screenshots**

![image](https://github.com/overextended/ox_inventory/assets/64704900/0d12edef-54f1-44f3-9b6b-74361167936c)
![image1](https://github.com/overextended/ox_inventory/assets/64704900/8e16c533-733e-4663-a13b-616b2c1390d6)
![image2](https://github.com/overextended/ox_inventory/assets/64704900/caaa8c1e-d193-445f-9832-fbdd1a8c4573)

**Comment by thelindat** [comment]
Not a bug. This isn't a copy paste of qb-inventory, you don't just replace-all.

**Comment by nathan-collab** [comment]
So what should I do, please?
