### ISSUE TITLE
Viewing inventories shows your own

### ISSUE THREAD

**Issue by HighLatencyy** [overextended/ox_inventory#1558]
**Describe the bug**
Viewing inventories on the latest version is bugged, it shows your own inventory.

**Framework**
es_extended - 1.10.2

**Resource version**
2.37.3

**To Reproduce**
1. Type /viewinv [id] (another player)
2. Your inventory shows up, not the others.

**Expected behavior**
You view your own inventory.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by thelindat** [comment]
I'm not going to take a screenshot just to prove you wrong, just know that I updated and tested this shit at the same time, as I needed to make sure item movement was disabled.

Sounds like you didn't update your inventory correctly.
