### ISSUE TITLE
No Stashes opening when target is false

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_inventory#1577]
**Describe the bug**
When target is false in the settings we cant open stashes only shops works.

**Framework**
QB

**Comment by thelindat** [comment]
![image](https://github.com/overextended/ox_inventory/assets/65407488/a0d36868-b61e-4242-8f27-7fdbe53cb868)

**Comment by soniXx123** [comment]
![image](https://github.com/overextended/ox_inventory/assets/35350615/c5b4511a-84cd-4b79-9ea3-1be02ca9e59b)

is not working for us

![image](https://github.com/overextended/ox_inventory/assets/35350615/54a664e8-37c9-49d5-b43f-52aab029199e)

**Comment by ronaldauweb** [comment]
Hi @soniXx123 I have the same problem, did you manage to solve it?
