### ISSUE TITLE
Weapon Attachments inside Vehicles. 

### ISSUE THREAD

**Issue by allyaminou** [overextended/ox_inventory#1583]
**Describe the bug**
You can equip the pistol suppressor and when you shoot it works etc, but when you go into a vehicle the weapon is not suppressed anymore and you can see that the weapon in your hand doens't have the attachement.  
When you get out of the vehicle the suppressor shows again on the weapon. 

**Framework**
ESX

**Resource version**
In all versions, this is for a while but I see no one reported it so far.

**To Reproduce**
1. Equip the pistol with suppressor. 
2. Go inside the vehicle and start shooting. 
3. Get out of the vehicle to see that the suppressor works fine outside vehicle

**Expected behavior**
If you put a silencer on your pistol then it should stay on it until you detach it.

**Comment by Ehbw** [comment]
Not a bug with ox_inventory, it is base game behaviour.
