### ISSUE TITLE
Multiple Exports Called Issue

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [overextended/ox_inventory#1589]
Export issue with a script. For some reason the inventory is only calling the first export in this snippet. The dev of the script has no clue whats wrong. So I'm seeing if someone else has some insight here.

```
RegisterNetEvent('wx_drugs:processedWeedPack')
AddEventHandler('wx_drugs:processedWeedPack', function()
    exports.ox_inventory:AddItem(source, 'weed_package', 1)
    exports.ox_inventory:RemoveItem(source, 'weed_leaf', wx.Drugs['Weed Production'].NeededWeedForPack)
    exports.ox_inventory:RemoveItem(source, 'empty_bag', 1)
end)
```

So it wont matter which export I use it will only trigger the first one each time. For example in this case it will only do the AddItem export here but not the Remove Items. Its extremely frustrating because this Dev wxscripts has no idea whats wrong.

Is something wrong with this code here?

**Comment by RainbowFC1** [comment]
are you sure the source variable doesnt get lost? should probably cache it ```local playerId = source```
