### ISSUE TITLE
UI not updated when items added/removed while open

### ISSUE THREAD

**Issue by Manason** [overextended/ox_inventory#1596]
**Describe the bug**
UI doesn't update when open and items are added/removed/changed it seems. This makes it difficult to make things like a draggable crafting system as the inventory needs to be closed and re-opened to see the effect of changes.

**Framework**
QBX

**Resource version**
v2.38.1

**To Reproduce**
1. Register a swap items hook that returns false and removes an item
2. Open the inventory
3. swap two items
4. Observe that the UI still shows the item present

**Expected behavior**
The item disappears from the UI

**Screenshots**
https://clipchamp.com/watch/J4d7Mn59KCk

**Additional context**

**Comment by thelindat** [comment]
> Register a swap items hook that returns false and removes an item

Hooks generally shouldn't have side effects as you'll run into race conditions like this. Show the code.

**Comment by Manason** [comment]
> > Register a swap items hook that returns false and removes an item
> 
> Hooks generally shouldn't have side effects as you'll run into race conditions like this. Show the code.

```lua
exports.ox_inventory:registerHook('swapItems', function(payload)
    -- checking the player is in their own inventory
	if payload.fromInventory ~= payload.toInventory or payload.fromInventory ~= payload.source or not payload.toSlot then return true end

    local baseItem = recipes[payload.fromSlot.name]
	if not baseItem then return true end

	local craftResult = baseItem[payload.toSlot.name]
	if not craftResult then return true end

    craftResult.requiredFromAmount = craftResult.requiredFromAmount or 1
    if payload.count < craftResult.requiredFromAmount then return true end

	craftResult.requiredToAmount = craftResult.requiredToAmount or 1
	if payload.toSlot.count < craftResult.requiredToAmount then return true end

	exports.ox_inventory:RemoveItem(payload.source, payload.toSlot.name, craftResult.requiredFromAmount)
	exports.ox_inventory:RemoveItem(payload.source, payload.fromSlot.name, craftResult.requiredToAmount)
	exports.ox_inventory:AddItem(payload.source, craftResult.outputItem, craftResult.outputAmount or 1, nil, payload.toSlot.slot)
	return false
end)
```

**Comment by thelindat** [comment]
Wrap the exports in a new thread so they will execute after the hook completes.

**Comment by Manason** [comment]
Yeah that works. Thanks :)
