### ISSUE TITLE
Add a feature to turn off and turn on drop ground

### ISSUE THREAD

**Issue by bicatcho11** [overextended/ox_inventory#1598]
**Is your feature request related to a problem? Please describe.**

The idea is to implement allowing and not allowing items to be dropped on the ground
Through the config file

**Describe the solution you'd like**

I want players on my server to throw their items into trash cans only and not on the ground. I want to prevent them from throwing items on the ground.
As a type of scenario, because I want the other players, when opening the waste baskets, to benefit from the items placed in the baskets, and thus the scenario is completed.

**Describe alternatives you've considered**

config.drop_ground = true or false

**Additional context**

**Comment by thelindat** [comment]
https://overextended.dev/ox_inventory/Functions/Server/Hooks#swapitems
