### ISSUE TITLE
Perishability: The Finite Lifespan of Consumables and Firearms

### ISSUE THREAD

**Issue by kuomars110** [overextended/ox_inventory#1603]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ideally, the implementation of a configurable item lifespan within the configuration settings would greatly enhance functionality, allowing users to set a predetermined period—such as three days—after which the item becomes rendered obsolete, optimizing both control and efficiency.

**Comment by thelindat** [comment]
Degrade (and decay) already exist.

https://overextended.dev/ox_inventory/Guides/creatingItems#defining-item-data

**Comment by kuomars110** [comment]
This is not what i want 
Its gonna reduce the durability over the time (degrade) , I want after for example 1month User cant use cola

**Comment by kuomars110** [comment]
> Degrade (and decay) already exist.
> 
> https://overextended.dev/ox_inventory/Guides/creatingItems#defining-item-data


This is not what i want
Its gonna reduce the durability over the time (degrade) , I want after for example 1month User cant use cola

**Comment by thelindat** [comment]
Well if the cola goes bad over time and reaches 0 durability, you can't use it. Or you can just reimplement your own version of durability by adding a timestamp on the item metadata and then checking if it's past that date..
