### ISSUE TITLE
( QBcore ) Cash removed upon character select.

### ISSUE THREAD

**Issue by misterwu4** [overextended/ox_inventory#1605]
**Describe the bug**
When selecting character and loading into server, what ever cash you had in your inventory when you last left the server is removed.

no errors in the server console or f8 console
**Framework**
QB

**Resource version**
most recent repository 
version '2.38.1'

**To Reproduce**
1. Give money 
2. Leave server 
3. Rejoin server
4. After selecting character, money is removed.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by misterwu4** [comment]
I would ask for support in the discord but for some unknown reason im banned. Never even joined the discord before.

**Comment by dorlevy1** [comment]
if you're looking for the player row in the database 
after he loaded his character . you see difference on the inventory column with the items? 
you can confirm there is money before and none after ?
