### ISSUE TITLE
Evidence Access Question (Jobs)

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [overextended/ox_inventory#1612]
**Is your feature request related to a problem? Please describe.**
Would it be possible to have some way of making Evidence available to everyone via config if we can set something for `setr inventory:police [""]` or what?

**Describe the solution you'd like**
In our case we aren't using jobs, we just use ACE perms and Discord roles for our Police. But we have public officers with no department role too. So we would like to see if we can somehow use Evidence and have it be available to everyone? (We use locked doors of the Evidence rooms anyway to restrict access to certain roles with a passkey so we don't need it restricted to jobs via inventory.)

**Additional context**
Sorry if this is a silly question. I just have not been able to find anything about this anywhere.

**Comment by thelindat** [comment]
You don't _have to_ use internal systems, you can make your own markers and functions to open evidence.
