### ISSUE TITLE
Inventory Use

### ISSUE THREAD

**Issue by terrantdt** [overextended/ox_inventory#1615]
**Describe the bug**
When load mags or click r, I can no longer load any other mags nor eat food items 

**Framework**
ND_Core 

**Resource version**
2.38.1

**To Reproduce**
1. put firearm in hand
2. open inventory
3. drag ammo or right click ammo to use 
4. one mag loads and you cant load any more or eat 

**Expected behavior**
mag bugs when reloads and prevent users from loading more mags and stops them from being able to eat

**Screenshots**
(https://medal.tv/games/gta-v/clips/1SXGBmvVIstyNB/d1337zgW0wcw?invite=cr-MSw4MjEsMTUyNTMwMzEyLA)

**Additional context**
N/A

**Comment by AngryMaximus** [comment]
Can confirm, having a pistol or weapon in your hands disables the use of any item. Can't eat, drink or do anything, i had to drop my weapon just to put on body armour and eat food.

**Comment by 0xDEMXN** [comment]
> Can confirm, having a pistol or weapon in your hands disables the use of any item. Can't eat, drink or do anything, i had to drop my weapon just to put on body armour and eat food.

You can configure `allowArmed` on item to achieve this.

**Comment by 0xDEMXN** [comment]
> **Describe the bug** When load mags or click r, I can no longer load any other mags nor eat food items
> 
> **Framework** ND_Core
> 
> **Resource version** 2.38.1
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. put firearm in hand
> 2. open inventory
> 3. drag ammo or right click ammo to use
> 4. one mag loads and you cant load any more or eat
> 
> **Expected behavior** mag bugs when reloads and prevent users from loading more mags and stops them from being able to eat
> 
> **Screenshots** (https://medal.tv/games/gta-v/clips/1SXGBmvVIstyNB/d1337zgW0wcw?invite=cr-MSw4MjEsMTUyNTMwMzEyLA)
> 
> **Additional context** N/A

Additionally, you can only load one mag at time, that's how inventory works.
