### ISSUE TITLE
Is there a way to change the weight system???

### ISSUE THREAD

**Issue by Krazykoolman** [overextended/ox_inventory#1624]
I don't know if its in already but i would like to remove the weight text in the inventory and next to each item. or at least change the text to display a different unit of measure?

**Comment by tom-osborne** [comment]
You would need to edit the source code to do this.

The code for the inventory weight information can be found here: https://github.com/overextended/ox_inventory/blob/main/web/src/components/inventory/InventoryGrid.tsx#L29-L39
