### ISSUE TITLE
Cant drop items

### ISSUE THREAD

**Issue by LostSoenke0** [overextended/ox_inventory#1630]
**Describe the bug**
A clear and concise description of what the bug is.:

I dont know since when but I cant drop items anymore. when I try to drop items I just get them back in my Inventory

**Framework**
The framework your server uses for players (e.g. Ox, ESX, QB).:

Framework: Ox/ESX

**Resource version**
The version number listed in fxmanifest.lua, or optionally a commit hash.:

Version: 2.30.0

**To Reproduce**
1. I dont know

**Comment by rewindtm** [comment]
@LostSoenke0 how do you have solved?
I've the same problem with latest version of ox

**Comment by Vituoze** [comment]
Pareil et c'est embêtant
