### ISSUE TITLE
How to pay shops in cash then bank

### ISSUE THREAD

**Issue by Rogue38** [overextended/ox_inventory#1632]
Trying to get ox inventory shops to accept cash then if the player does not have enough cash to take it from the players bank.

I suspect its around this part of code-

```
local function canAffordItem(inv, currency, price) 
 	local canAfford = price >= 0 and Inventory.GetItem(inv, currency, false, true) >= price 
  
 	return canAfford or { 
 		type = 'error', 
 		description = locale('cannot_afford', ('%s%s'):format((currency == 'money' and locale('$') or comma_value(price)), (currency == 'money' and comma_value(price) or ' '..Items(currency).label))) 
 	} 
 end 
  
 local function removeCurrency(inv, currency, price) 
 	Inventory.RemoveItem(inv, currency, price)
```

**Comment by dorlevy1** [comment]
if you want to load the bank account and charge from the bank , you should load the player first
QBCore.Functions.GetPlayer(source)
and then you can do some if statement
if Player.Functions.RemoveMoney('bank',price) then 
and do your stuff

something like that

**Comment by Mesrine67** [comment]
I've made some changes to make it possible to pay with society, bank, cash, crypto/dirty money...

https://github.com/Mesrine67/ox_inventory/commit/e75e57d64780998daec6df5ffa94467a5e9ba8b9
