### ISSUE TITLE
Discord webhook is not working

### ISSUE THREAD

**Issue by Praveshkumar11** [overextended/ox_inventory#1662]
Discord webhook url is not working. i have pasted my webhook url in  set inventory:webhook "",but it is not working.

**Comment by jag3dagster** [comment]
![image](https://github.com/overextended/ox_inventory/assets/77469789/d6bd5a2c-014a-401d-8f9d-fa6dcd0b4a34)

Per the documentation, the webhook is not intended to log out every single inventory interaction. It is purely for content moderation of image embeds.

If you want full inventory logging you'll need to utilize ox_lib's logging system: https://overextended.dev/ox_lib/Modules/Logger/Server
