### ISSUE TITLE
Inventory breaks when opened before fully entering vehicle

### ISSUE THREAD

**Issue by edwardexo** [overextended/ox_inventory#1663]
**Describe the bug**
When you open your inventory **just before** fully sitting down in a vehicle, the secondary inventory will remain open (a drop). As soon as you move anything into the secondary inventory, your inventory breaks down. Breaking down meaning that you won't be able to move items anywhere until you reconnect.

**Framework**
N/A

**Resource version**
2.38.1

**To Reproduce**
1. Enter a vehicle
2. Just before fully being seated, open your inventory
3. Move an item to the secondary inventory
4. Close your inventory
5. Open your inventory
6. Try to move anything in your inventory

**Expected behavior**
Be able to move items around.

**Actual behavior**
Items can't be moved around, they instantly return to their position.

**Screenshots**
[Video](https://streamable.com/tmqp4t)

**Additional context**
You have to time the inventory opening right. If you open it too early, it will close when you fully sit down. If you open it too late, you will open the glovebox. If you time it just right, you will encounter this bug. 

Is happening quite often when people quickly want to open the glovebox and put stuff inside.

**Comment by Gamzky** [comment]
This is fixed in #1685
