### ISSUE TITLE
my inventory does not open no more

### ISSUE THREAD

**Issue by kennyboi2xx** [overextended/ox_inventory#1666]
**Describe the bug**

**Framework**
The framework your server uses for players (e.g. Ox, ESX, QB).

**Resource version**
The version number listed in fxmanifest.lua, or optionally a commit hash.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Griefa** [comment]
I love how this provides zero context to your issue

**Comment by GermanWarthog** [comment]
@Griefa  Why should he, I mean it's clear we can read minds
