### ISSUE TITLE
drop inventory problem

### ISSUE THREAD

**Issue by xbrendann** [overextended/ox_inventory#1667]
**Describe the bug**
when I drag anything to the drop inventory it appears back in main inventory and I can't drop anything.

**Framework**
ESX

**Resource version**
2.39.1

**Expected behavior**

**Screenshots**
https://medal.tv/games/gta-v/clips/24nFS0gt5p74fF/d1337xrIQVt2?invite=cr-MSxvUEIsNDc1NDQ0NTIs (heres a clip of the problem)

**Comment by edwardexo** [comment]
Possibly related https://github.com/overextended/ox_inventory/issues/1663
