### ISSUE TITLE
Non removable item

### ISSUE THREAD

**Issue by ziktoh** [overextended/ox_inventory#1669]
Hi, I'm pretty new at programing and i was trying to make a non-removable item, but I couldn't find a way to create an item or weapon that couldn't be stolen from other players.

**Comment by VIRUXE** [comment]
This is not an issue. Read the documentation and if that doesn't suffice ask for support on Discord.

**Comment by CeebDev** [comment]
> Hi, I'm pretty new at programing and i was trying to make a non-removable item, but I couldn't find a way to create an item or weapon that couldn't be stolen from other players.

You have to use hooks, if you need support, don't open GH issue and read the doc / go to Discord
