### ISSUE TITLE
Add A Option To Disable Extras Like Shops & Crafting

### ISSUE THREAD

**Issue by yiruzu** [overextended/ox_inventory#1672]
The title says it all... I simply hate how these features are so heavily pushed without the option to disable them with convars.

**Comment by tom-osborne** [comment]
Shops are defined in `data/shops.lua` - If you don't define any shops (i.e. `return {}` or comment out everything within the curly braces), then the shops "feature" won't be used. Similarly, if crafting is not defined in `data/crafting.lua`, the crafting feature will not be used.

**Comment by yiruzu** [comment]
sure i could do it that way but why not just make it optional with a easy convar

**Comment by googleoblivion** [comment]
Because it is already optional by not defining the data.

> return {}

**Comment by tom-osborne** [comment]
WHY IS THERE CODE!?!?

**Comment by Demigod916** [comment]
where is the exe?

**Comment by yiruzu** [comment]
> WHY IS THERE CODE!?!?

Why are there people like you who don't understand that I requested a feature and NOT a workaround???

**Comment by googleoblivion** [comment]
> The title says it all... I simply hate how these features are so heavily pushed without the option to disable them with convars.

> Feature

Your "feature" request is a workaround.

**Comment by thelindat** [comment]
> Because it is already optional by not defining the data.
> 
> > return {}

**Comment by kingofkingzcd** [comment]
Takes 15 seconds to disable the shops... would be cool to have a convar to do it.... but again... it takes 15 seconds.
