### ISSUE TITLE
inventory causing memory crash on client side

### ISSUE THREAD

**Issue by MrTeaRexx** [overextended/ox_inventory#1674]
**Describe the bug**
When having a weapon or item with no durability, and is swapped out for another in that slot without sheathing it will cause the client to crash when they draw the item in that slot, doing so also corrupts the item that was put into that slot and if put into another slots and drawn results in a crash.

**Framework**
QB

**Resource version**
latest version of ox_inventory

**To Reproduce**
1. have a weapon with no durability drawn
2. open inventory switch the item out for another with the old weapon still drawn
3. then draw out the new weapon in that slot
4. this will result in the client crashing with fivem rejecting it with a memory issue and corrupting that item in the process

**Expected behavior**
[    102750] [b2699_GTAProce]             MainThrd/ Error: FiveM has blocked a potential memory issue. Please file a bug report with the Offending Native Script, if you run into this.
[    102750] [b2699_GTAProce]             MainThrd/ Resource: [unknown]
[    107875] [b2699_DumpServ]                28404/ Process crash captured. Crash dialog content:
[    107875] [b2699_DumpServ]                28404/ FiveM has blocked a potential memory issue. Please file a bug report with the Offending Native Script, if you run into this.
[    107875] [b2699_DumpServ]                28404/ Resource: [unknown]
[    131219] [b2699_DumpServ]                28404/ Error uploading crash: HTTP 0

**Comment by thelindat** [comment]
This was a FiveM problem and afaik a fix was already pushed to production.
