### ISSUE TITLE
Crafting Benches creation via Exports

### ISSUE THREAD

**Issue by zf-development** [overextended/ox_inventory#1676]
**Is your feature request related to a problem? Please describe.**
It's not recommanded to make guides to edit the code to make the additions of crafting bench externally.
Making unknowing people edit specific code is not really great and can cause issues. 

**Describe the solution you'd like**
Possibility to create crafting benches on the fly via export.
Would make it easier to integrate in to other scripts, where you want to use the crafting feature, with out having to create it in the crafting.lua

**Describe alternatives you've considered**
Making a guide to edit the inventory code which is unlike to be done correctly or without breaking something. This would only give more support to everyone.

**Comment by FjamZoo** [comment]
Duplicate of https://github.com/overextended/ox_inventory/issues/1361

**Comment by zf-development** [comment]
My bad
