### ISSUE TITLE
Easy Log system for new members

### ISSUE THREAD

**Issue by Shafat21** [overextended/ox_inventory#1677]
Is there any way for ox lib easy log system to discord?

**Comment by EpKouhia** [comment]
Hey @Shafat21 unfortunately Discord is not mean't to be used for logging purposes. Therefore there is no support for discord logging. You should take a look at Grafana Loki ([Grafana](https://overextended.dev/ox_lib/Modules/Logger/Server#grafana-loki)), Datadog ([Datadog](https://overextended.dev/ox_lib/Modules/Logger/Server#datadog)) or FiveManage ([FiveManage](https://docs.fivemanage.com/getting-started/logs)) logging which are supported.
