### ISSUE TITLE
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/mysql/server.lua:113: ox_inventory was unable to execute a query!

### ISSUE THREAD

**Issue by kirianmladen** [overextended/ox_inventory#1679]
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/mysql/server.lua:113: ox_inventory was unable to execute a query!
[ script:ox_inventory] Query: SELECT inventory FROM `{user_table}` WHERE `{user_column}` = ?
[ script:ox_inventory] Table 's16073_NewLifeRP.{user_table}' doesn't exist
[ script:ox_inventory] > loadPlayer (@ox_inventory/modules/mysql/server.lua:113)
[ script:ox_inventory] > setPlayerInventory (@ox_inventory/server.lua:26)
[ script:ox_inventory] > handler (@ox_inventory/modules/bridge/qb/server.lua:44)
[ script:ox_inventory] > logError (@oxmysql/dist/build.js:26282)
[ script:ox_inventory] > rawExecute (@oxmysql/dist/build.js:26578)
[ script:ox_inventory] > processTicksAndRejections (node:internal/process/task_queues:96)

After making a new database and install all the sql back to my database.. I get this error

**Comment by CeebDev** [comment]
What's your framework ? and what is the value of your `inventory:framework` convar ?
