### ISSUE TITLE
Bug: Stashes Not Registering for Factions

### ISSUE THREAD

**Issue by 0rezh** [overextended/ox_inventory#1681]
When configuring faction-specific stashes, I find that the stashes do not register correctly when I configure the 'factions' field in my 'config.lua' file. However, registration works as expected when I use the 'jobs' field instead. The problem seems to stem from the way 'ox_inventory' handles faction permissions in relation to jobs.

**Framework**
ESX

**Resource version**
version : 2.38.1

**To Reproduce**
1. Configure a stash in config.lua with the factions property:
```lua
stashes = {
    {
        id = 'stash_bloods',
        label = 'Coffre Boss Bloods',
        slots = 50,
        weight = 100000,
        owner = false,
        factions = "bloods",
    },
}
```
2. Use the following code in server.lua to register the stash on server startup or a specific event:
```lua
RegisterNetEvent('ox:loadStashes', function(id)
    for k, v in pairs(stashes) do
        local stash = stashes[k]
        if stash then
            if not shownStashes[stash.id] then
                ox_inventory:RegisterStash(stash.id, stash.label, stash.slots, stash.weight, stash.owner, stash.factions)
                shownStashes[stash.id] = true
            end
        end
    end
end)
```
4. See error :
![image](https://github.com/overextended/ox_inventory/assets/75934598/e39715aa-2594-4ccb-9760-8c8d97145756)

**Expected behavior**
I expected the 'Boss Bloods Chest' stash to be properly registered and accessible by this faction.

**Screenshots**
With factions : 
![image](https://github.com/overextended/ox_inventory/assets/75934598/e39715aa-2594-4ccb-9760-8c8d97145756)

With Jobs :
![image](https://github.com/overextended/ox_inventory/assets/75934598/a69dded1-f1de-4a30-9e83-7a761e6d91fc)

**Comment by Hakkodevelopment** [comment]
whats a faction

**Comment by 0rezh** [comment]
i have fix
