### ISSUE TITLE
Give Player List not working

### ISSUE THREAD

**Issue by Jxncsi** [overextended/ox_inventory#1689]
I switched on the setr inventory:giveplayerlist and it not showing when I try hand over to a close person the item, but I did everything about the documentation. (inventory.cfg, exec inventory.cfg before start/ensure ox_inventory)

**Comment by googleoblivion** [comment]
Do you have more than 1 person near you?

**Comment by Jxncsi** [comment]
Yes, I realized that if there is a person next to me, the menu does not open
