### ISSUE TITLE
Animation Cancellation Bug

### ISSUE THREAD

**Issue by yiruzu** [overextended/ox_inventory#1692]
**Describe the bug**
At first script launch, an odd animation cancellation bug occasionally occurs (as if in a loop), resolving only upon restarting the resource when it already started once.

**Framework**
ESX

**Resource version**
2.40.0

**To Reproduce**
1. Restart server.
2. Go in game and do an animation.

**Video**
https://streamable.com/s0gi67

**Comment by thelindat** [comment]
ox_inventory doesn't call any of the ClearTask natives - could be one of the resources that was depending on it being enabled?
- lab-Combine
- ox_fuel (shouldn't be this?
- wasabi_backpack

or even this ely_radio thing that threw an error for some reason (seems to be running Search in a loop)?

**Comment by yiruzu** [comment]
Oh, yea that makes scenes now I completely ignored the radio script and just focused on the inventory and the scripts that are depended on it.

The radio script actually had a code snippet where it said that it would fix an animation cancelation bug, but yea it did the complete opposite:

```lua
function toggleRadioAnimation(state)
    lib.requestAnimDict('cellphone@')
	if state then
		TriggerEvent("attachItemRadio","radio01")
		TaskPlayAnim(PlayerPedId(), "cellphone@", "cellphone_text_read_base", 2.0, 3.0, -1, 49, 0, 0, 0, 0)
		radioProp = CreateObject(`prop_cs_hand_radio`, 1.0, 1.0, 1.0, 1, 1, 0)
		AttachEntityToEntity(radioProp, PlayerPedId(), GetPedBoneIndex(PlayerPedId(), 57005), 0.14, 0.01, -0.02, 110.0, 120.0, -15.0, 1, 0, 0, 0, 2, 1)
	else
		StopAnimTask(PlayerPedId(), "cellphone@", "cellphone_text_read_base", 1.0)
		ClearPedTasks(PlayerPedId())
		DeleteObject(radioProp)
		radioProp = 0
	end
end

RegisterNetEvent('szxna_radio:leave')
AddEventHandler('szxna_radio:leave', function()
	exports['pma-voice']:setVoiceProperty('radioEnabled', false)
	exports['pma-voice']:setVoiceProperty('micClicks', false)
	exports["pma-voice"]:SetRadioChannel(0)
	exports["pma-voice"]:removePlayerFromRadio()
	toggleRadioAnimation(false)
	RadioChannel = '0 (OFF)'
	RadioOpen = false
end)

-- this is the snippet which causes issues
CreateThread(function()
	while true do
		Wait(3000)
		local count = exports.ox_inventory:Search('count', Config.radio_item_name)
		if count == 0 then
			TriggerEvent('szxna_radio:leave')
		end
	end
end)
```
