### ISSUE TITLE
Weapon is "unable to use"

### ISSUE THREAD

**Issue by John6862** [overextended/ox_inventory#1693]
I have the weapons in the store and am able to get the into my inventory fine but when i go to use them i get a notification saying "unable to use "weapon name".

**Framework**
ND

**Comment by thelindat** [comment]
Copy pasted from discord

the cannot_use notification typically only shows for a weapon if the game actually failed to set the weapon - which isn't something ox_inventory can control
if you go here and add a print above the notification, you'll see if it's that.

https://github.com/overextended/ox_inventory/blob/main/client.lua#L526

beyond that I really don't know why SetCurrentPedWeapon would be failing - I think somebody mentioned poorly formatted weapon metadata or something?
