### ISSUE TITLE
Unable to open shared inventory

### ISSUE THREAD

**Issue by Scantrax3112** [overextended/ox_inventory#1702]
**Describe the bug**
For a while now we are unable to open an inventory/stash/shop in game.  In the config i have the following line:
`setr inventory:police ["police", "kmar", "admin"]`
When leaving the server the player is saved as offpolice or offkmar. They need to use a command ingame to toggle from offpolice/offkmar to police/kmar. When they try to use a shop after this it says "you can't use this inventory". After i restart ox_inventory in game they are able to use it. When a new player joins they can't access the shop until ox_inventory is restarted again. It seems to me that there is an issue with the setjob which is triggered with the command to switch between offpolice/offkmar to police/kmar but i'm not sure on how to fix this. 

**Framework**
ESX Legacy

**Resource version**
Latest (2.40.1)

**To Reproduce**
1. Join the server with any job but the jobs from inventory:police
2. Change the job to any job from inventory:police
3. Try to access the shops

**Expected behavior**
The shops should be working after going from offpolice/offkmar to police/kmar

**Comment by thelindat** [comment]
`esx:setJob` event is used to keep this data updated in the inventory, and others are not experiencing this issue, so there's not enough information here to act on.
