### ISSUE TITLE
Support wildcards in containers white/black lists

### ISSUE THREAD

**Issue by TonybynMp4** [overextended/ox_inventory#1707]
**Is your feature request related to a problem? Please describe.**
Having to manually add every item can be painful when trying to make a container for ammo / weapons (for example, don't see many other cases where this would be useful tbh 🤔 )

**Describe the solution you'd like**
Support wildcards in containers white/black lists

**Describe alternatives you've considered**
Painful list of the items 😭 

**Additional context**
idk

**Comment by thelindat** [comment]
Just use hooks.
