### ISSUE TITLE
Feature: New hook: useItem

### ISSUE THREAD

**Issue by Alexr03** [overextended/ox_inventory#1709]
**Is your feature request related to a problem? Please describe.**
We have an arena system for players to do activities like 1v1s, we like to disable the players use of their inventory to prevent healing, putting armour on etc by using items in their inventory. Right now our only option is to disable use of the inventory all together. We tried to use `invBusy` state on the player, this works but has a side effect of no longer being able to shoot their weapon https://github.com/overextended/ox_inventory/blob/bb8f0292b96b60bc83288420d789c044ad46c342/client.lua#L1422 

We **could** disable this ourself but we're trying to keep `ox_inventory` as vanilla as possible to make updates easier. 

This has led to the idea of making a useItem hook where we can return false if we want to stop the item from being used, then we can disable all items and setup a "whitelist" of allowed items that can be used while in the arena.

**Describe the solution you'd like**
Ability to create a hook for `useItem` that will allow us to cancel the request to use the item.
Example:
```lua
local hookId = exports.ox_inventory:registerHook('useItem', function(payload)
    print(json.encode(payload, { indent = true }))

    local playerState = Player(payload.source).state
    if (not playerState.inArena) then
        return
    end

    if (payload.itemName == 'water') then -- Only allow water to be used in arena, otherwise cancel the use.
        return
    end
    return false
end, {
    print = true,
})
```

**Describe alternatives you've considered**
(The alternatives below will prevent the inventory from opening and allowing weapon shooting, but won't allow us to dynamically cancel the `useItem`)
- Remove/Comment code that disables shooting when `invBusy` is true.
- Check every frame for if state `invOpen` is true, and then call export to `closeInventory` immediately.

**Additional context**
N/A

**Comment by Demigod916** [comment]
https://overextended.dev/ox_inventory/Functions/Client#weaponwheel

this will disable the inventory while allowing you to shoot still

**Comment by Alexr03** [comment]
That is what we currently do to give a temporary weapon. 
Its my understanding that it will disable using weapons from the inventory, but will allow other items like bandages? At least this is how it works for us. (https://aka.x3.dev/s/HRjXNJe/raw it wont let us use a weapon, when weaponWheel is enabled, but can still use other items)

I see what you're saying with the callbacks, but surely a hook is better to define the logic in one place of what can/cannot be used rather than in each callback?

**Comment by Demigod916** [comment]
The weaponwheel being active should completely disable the use of all items

**Comment by Alexr03** [comment]
Yes the docs imply it but code wise it only disable weapons being used as far as I can see.
https://github.com/overextended/ox_inventory/blob/3f298a1dd5455e2f6c2477b9f6860dbf7aa0156d/client.lua#L511

Regardless I still think having a hook for `useItem` is a good addition.

**Comment by Demigod916** [comment]
Interesting. I guess i can see the convenience of the hook in some cases then.

**Comment by Demigod916** [comment]
https://github.com/overextended/ox_inventory/commit/836a0b29ef7cb870ee297802db8d616d69882085

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/commit/70abcfd3ab7d4e6d3dd6e852712cc0467e864ab6
