### ISSUE TITLE
[FIXED] [ESX] After making config.cfg inventory comepletely stops working

### ISSUE THREAD

**Issue by Lorente1** [overextended/ox_inventory#1717]
**Describe the bug**
I wanted to install ox-inventory and ox-target. I installed ox-lib, ox-inventory and ox-target and put config.cfg file in ox-target. Then I started the server and noticed that I forgot to put config.cfg file in ox-inventory folder. When I put config.cfg file in ox-inventory folder, changed code in server.cfg (exec). I started server again and inventory stopped working, but when I remove config.cfg from ox-inventory folder everything works, but I need config.cfg to enable ox-target support.

**Framework**
ESX

**Resource version**
2.40.1

**To Reproduce**
1. Make config.cfg in ox-inventory/
2. Paste everything from https://overextended.dev/ox_inventory#config
3. Make changes in server.cfg
4. Start server
5. Inventory not working

**Expected behavior**
I thought that ox-target will work now in shops etc. After changing target support from false to true.

**Comment by thelindat** [comment]
> Paste everything from https://overextended.dev/ox_inventory#config

🥹 

> Make changes in server.cfg

??????

---

Anyway you are configuring something wrong and/or starting resources in the wrong order.
