### ISSUE TITLE
Item data unidentified!

### ISSUE THREAD

**Issue by dawitcdoc** [overextended/ox_inventory#1724]
**Describe the bug**
this is a fresh install into qb-core when i try to use items in my inventory or at the shops nothing happens i get this error following the item name with this after " (@ox_inventory/web/build/assets/index-3b687188.js:100)"
**Framework**
QB core

**Resource version**
latest Release just installed 6/13/2024

**To Reproduce**
1. Go to '.inventory.'
2. Click on 'the item '
3. Scroll down to 'use'

**Expected behavior**
i expected it to be use some item have animation but nothing happens i dont lose it just the error

**Screenshots**
![image](https://github.com/overextended/ox_inventory/assets/171204117/35ad04e7-0988-43e1-933f-b8b759c43629)

**Additional context**
i have the dependencies downloaded as well.

**Comment by deebandzz** [comment]
i am havign same issue
