### ISSUE TITLE
Wide and Ultrawide support

### ISSUE THREAD

**Issue by Spudszilla** [overextended/ox_inventory#1733]
**Describe the bug**
When using this inventory on wide or ultrawide the body parts don't line up and you cannot access the inventory slots on the right.

![Screenshot_123](https://github.com/overextended/ox_inventory/assets/173580325/6e52b2f3-973f-428f-907c-d3448c15417a)

**Comment by CeebDev** [comment]
This isn't related to ox_inventory

This is a custom layout and should be handled by creator
