### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by roswelldev** [overextended/ox_inventory#1739]
**Describe the bug**
Conversion error when processing the convertInventory qb command

**Framework**
QBCore (Latest)

**Resource version**
2.40.2

**To Reproduce**
Install QBCore from scratch or via the TxAdmin installer,
Install Ox Inventory
Run the convertInventory qb command in console and first load
error is displayed as shown in the picture below

**Expected behavior**
To work with no errors displaying

**Screenshots**
![image](https://github.com/overextended/ox_inventory/assets/109285912/d8b6db0f-d92f-4701-8a88-de3afb37b20c)

**Comment by thelindat** [comment]
> Install QBCore from scratch or via the TxAdmin installer,
> Install Ox Inventory
> Run the convertInventory qb command

Literally why when there is _nothing_ to convert?

> trunkitems no longer exists on there default installation in the SQL

Yes, qb made several breaking changes and qb compatibility shit is almost entirely dependent on qb-users to contribute. I would personally prefer deleting every reference to the stain.
