### ISSUE TITLE
unable to change weapons in equipped vehicles

### ISSUE THREAD

**Issue by TheThomasG** [overextended/ox_inventory#1740]
**Describe the bug**

In the previous version, weapon switching worked - after the update it stopped.
the script correctly knows that the vehicle has a weapon - it does not show the equipment after pressing TAB, but the weapon wheel in the vehicle does not display - after pressing TAB, nothing happens, the keys are set correctly.

**Framework**
The framework your server uses for players (e.g. Ox, ESX, QB).
ESX
**Resource version**
The version number listed in fxmanifest.lua, or optionally a commit hash.
V2.40.2

**To Reproduce**
Enter a vehicle that has several types of weapons - you can't switch them.

**Expected behavior**
After pressing the defined button, a weapon selection wheel should appear - or the weapon should switch.

**Screenshots**

**Additional context**

**Comment by Caseycac** [comment]
just uninstall it there garbage

**Comment by thelindat** [comment]
![image](https://github.com/user-attachments/assets/8e598db3-ddb7-4b78-94d1-6ddd34cff056)
![image](https://github.com/user-attachments/assets/f08e3b43-92e8-4422-b0be-7b65cd612fae)
