### ISSUE TITLE
I can't access the trunks but I can access the glove compartments.

### ISSUE THREAD

**Issue by elnexorp** [overextended/ox_inventory#1741]
**Describe the bug**

I can open any glove box, but I can't open any trunk. Nor of the cars that indicate that the trunk is on the hood.
I approach an open car of mine, go to the trunk, open the inventory and it opens the floor. I go inside the car, open the inventory and open the glove compartment properly.

**Framework**

NewESX

**Resource version**

version '2.40.2'

**To Reproduce**

1. Go to the runk
2. Open inventary
3. See the ground

**Expected behavior**

That when you open the inventory the trunk opens

**Screenshots**

![image](https://github.com/overextended/ox_inventory/assets/170652368/a079973c-e117-4f62-96c2-1c10aec40a91)
![image](https://github.com/overextended/ox_inventory/assets/170652368/96b9ef01-fe5b-442c-ac77-b1c7df1f9fe7)

**Additional context**

Everything else in this inventory works perfectly for me.

**Comment by Demigod916** [comment]
Try using the correct keybind. The “secondary” inventory bind
