### ISSUE TITLE
Splitting Items in Half Randomly

### ISSUE THREAD

**Issue by dnirvine** [overextended/ox_inventory#1745]
**Describe the bug**
When having my item value set to "0" or any other number and drag across using my LMB to drop it on the ground or to another player, drop or move the stack within in my inventory the item splits in half and continuously does so until I've finally moved all items of the stack.

**Framework**
ESX

**Resource version**
ox_inventory (2.38.1)

**To Reproduce**
I am unsure of how to reproduce.  It spontaneously happens at random times.  Usually restarting the game, fixes the issue.

**Expected behavior**
If the amount is "0" drag all items of the stack over at once, or if a number is specified to drag that amount of the stack to the location.

**Screenshots**
  - not really available.

**Additional context**

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/pull/1687

Update your resource.
