### ISSUE TITLE
Discord webhook

### ISSUE THREAD

**Issue by EinfachJustin** [overextended/ox_inventory#1748]
**Describe the bug**
Discord webhook not working for me

**Framework**
ESX

**Resource version**
latest version 

**Expected behavior**
I want to get the discord webhook to work but unfortunately nothing is coming through in discord. I have set everything up in the config.cfg that I created, see below, but nothing is coming through. The cofing cfg works even if I change the drop prop, for example.

**Additional context**

-- Discord webhook url, used for imageurl metadata content moderation (image embeds)
set inventory:webhook "here I have my web hoock which I also tested with a bot"
 
-- Logging via ox_lib (0: Disable, 1: Standard, 2: Include AddItem/RemoveItem, and all shop purchases)
set inventory:loglevel 1

**Comment by tom-osborne** [comment]
Abusing a Discord webhook for "logging" is not supported since Discord is not a logging service.

Recommend you use one of the three logging services that are supported (Fivemanage, DataDog, Grafana Loki) as described in the [documentation](https://overextended.dev/ox_lib/Modules/Logger/Server).
