### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by BoAdla** [overextended/ox_inventory#1753]
Hello

i don't why it doesn't work i install the latest release and follow all step but not work 

![image](https://github.com/user-attachments/assets/c1d86f48-724d-4e30-9b4f-2eb32e90aa3b)
![image](https://github.com/user-attachments/assets/ac1f3b9c-a723-4331-b47b-d258121874d7)
![image](https://github.com/user-attachments/assets/4f8158f8-0019-43d6-905c-54e31d03c658)

**Comment by tom-osborne** [comment]
This is not really a place for support, however you appear to have two common issues. You can read about these here:
[UI has not been built](https://overextended.dev/ox_inventory/issues#ui-has-not-been-built)
[No such export ... ](https://overextended.dev/ox_inventory/issues#no-such-export--in-resource-ox_inventory)

Please use the Overextended Discord for further support questions, making sure to read the support guidelines beforehand.

https://discord.overextended.dev/
