### ISSUE TITLE
Ammo Bug

### ISSUE THREAD

**Issue by hearondale** [overextended/ox_inventory#1755]
**Describe the bug**
After taking gun out while having less ammo than clip can contain, after adding more to inv (while holding gun in hand) it will reload only 1 bullet every time despite having more

**Framework**
The framework your server uses for players
ESX

**Resource version**
version '2.39.1'

**To Reproduce**
1. Leave 1 ammo-9 in inventory
2. Take pistol in hand
3. Shoot (or not), add more ammo
4. Reload and it will load only 1 bullet despite having more

**Comment by PattysDevelopment** [comment]
same issue here

**Comment by thelindat** [comment]
Cannot reproduce. Ammo count is checked on each reload, anyway.
