### ISSUE TITLE
RegisterHook (blacklist items)

### ISSUE THREAD

**Issue by viper052186** [overextended/ox_inventory#1756]
**Describe the bug**
- I blocked the money from being transfer from player to trunk and trunk to player but i found bug...
---- From Player to Trunk - (it is ok and fine)
---- From Trunk to Player - (THIS IS THE BUG- If you do the swap transfer like you have phone or any item in your trunk to swap to money... it will allowed to swap. 

**Framework**
ESX

**Resource version**
version '2.39.1'

**Screenshots**
https://streamable.com/mo0s2g

--see video clip for more info

**Comment by thelindat** [comment]
code...
