### ISSUE TITLE
Shops

### ISSUE THREAD

**Issue by FoxeyBox** [overextended/ox_inventory#1760]
**Describe the bug**

i would like to disable all the ox shops but when I try to it makes me not be able to open up the inventory at all please someone help me 

**Framework**
The framework your server uses for players (e.g. Ox, ESX, QB). Qb core

**Resource version**

It’s a fresh download so most recent one

**To Reproduce**

**Comment by googleoblivion** [comment]
data/shops.lua -> return {}
