### ISSUE TITLE
please i need help for fix this

### ISSUE THREAD

**Issue by steelaymane** [overextended/ox_inventory#1762]
**Describe the bug**

**Framework**
The framework your server uses for players (e.g. Ox, ESX, QB).

**Resource version**
The version number listed in fxmanifest.lua, or optionally a commit hash.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![Capture](https://github.com/user-attachments/assets/ac2d8665-7fe3-4f99-b73b-a1c97f6c10ca)

**Comment by alberttheprince** [comment]
You've likely incorrectly streamed the add-on weapon you're trying to use here. Please review the files and make sure they follow the format used in ox_inventory. 

For example item would be like:

		['WEAPON_GLOCK17'] = {
			label = 'Glock 17',
			weight = 4250,
			durability = 0.2,
			ammoname = 'ammo-9',
			caliber = '9x19mm Parabellum',
		},
		
And you would need to make sure all meta files are properly named (within those files as well.

For example in the anime files: weaponanimations.meta

WEAPON_GLOCK17

![image](https://github.com/user-attachments/assets/beae3acc-7eb4-4e8d-a832-14656e941a9c)

**Comment by steelaymane** [comment]
don't work bro
