### ISSUE TITLE
When trying to use the ox target, the inventory will go away and it says there's no access.

### ISSUE THREAD

**Issue by MffAntt** [overextended/ox_inventory#1766]
With most shops that are setup, using the third eye: The inventory will keep going away

**Comment by FrancoisDeLaune** [comment]
This looks like it solves my problem - 
https://medal.tv/games/gta-v/clips/iNFSk16ZAvlrHGNa8/d1337MtOOJCR?invite=cr-MSx6MUcsMTk3MjUwMzEwLA

Set the distance for a shop at 7, but it auto closes saying "no access".  Getting right up to him seems to fix this.
