### ISSUE TITLE
stash.coords is not optional. Results in ox_lib error.

### ISSUE THREAD

**Issue by CrunchyBadger** [overextended/ox_inventory#1779]
**Describe the bug**
When registering a stash, coords is not optional and must be specified.
Docs show coords as being optional https://overextended.dev/ox_inventory/Guides/stashes#stash-properties
However this is not the case and leaving coords as nil will result in an error.

**Framework**
ESX

**Resource version**
Commit 0317d147

**To Reproduce**
- Create a stash without coords set
- Start ox_inventory
- Be met with an ox_lib error from lib.points.new

**Expected behavior**
Stash is registered without error.

**Screenshots**
N/A

**Additional context**
Will submit a PR with fix.

**Comment by thelindat** [comment]
This guide is related to the `RegisterStash` export and not the datafile.

**Comment by CrunchyBadger** [comment]
> This guide is related to the `RegisterStash` export and not the datafile.

So the two function differently?
