### ISSUE TITLE
bad argument #2 to 'gsub'

### ISSUE THREAD

**Issue by LostNewf26** [overextended/ox_inventory#1783]
**Describe the bug**
SCRIPT ERROR: @ox_inventory/modules/mysql/server.lua:43: bad argument #2 to 'gsub' (string/function/table expected, got nil)

**Framework**
The framework your server uses for players QB.

**Resource version**
2.42.0

**To Reproduce**
1. Add new ox_inventory to resource folder
2. Restart server
3. Error present on dashboard
4. Hit tab inside game
5. Inventory does not appear, F8 shows no other error

**Expected behavior**
New update to continue to operate with causing crash of ox_inventory

**Screenshots**
![image](https://github.com/user-attachments/assets/80ca2930-3632-4783-a45a-8d31069c81e1)

**Additional context**

**Comment by thelindat** [comment]
> Framework
> ... **QB**.

**Comment by jahlil95** [comment]
They break it every time it updates just re install the previous release bro
