### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by jahlil95** [overextended/ox_inventory#1788]
every time yall update this it breaks wtf

**Screenshots**

**Additional context**

**Comment by Demigod916** [comment]
Works fine for me, must be a skill issue

**Comment by jahlil95** [comment]
> Works fine for me, must be a skill issue

lap riding isnt a skill issue for you either, i see

**Comment by Demigod916** [comment]
Try qb-inventory. Probably more your speed

**Comment by thelindat** [comment]
> every time yall update this it breaks wtf

We specifically removed support for qbcore to get rid of cockroaches like you.
