### ISSUE TITLE
How Can I check trunk items for ox_inventory

### ISSUE THREAD

**Issue by imahdiy** [overextended/ox_inventory#1791]
---

**Greetings,**

I've encountered a bit of a dilemma. I'm attempting to inspect the items within a vehicle's trunk using the following trigger:

`local vehicleInventory = exports.ox_inventory:GetInventoryItems(vehiclePlate)`

However, it seems the trigger isn't functioning as expected. Could you kindly offer any guidance or solutions to help resolve this issue?

Thank you in advance for your assistance.

---

**Comment by vrnagy** [comment]
For trunks and gloveboxes You should prefix the plate either with `trunk `or `glovebox`.

For trunks it should look like thus:
`local vehicleInventory = exports.ox_inventory:GetInventoryItems('trunk' .. vehiclePlate)`

**Comment by Cyni4l** [comment]
Hi @vrnagy, I'm dealing with the same issue trying to get the trunk inventory open.  I used your suggestion: 

`local vehicleInventory = exports.ox_inventory:GetInventoryItems('trunk' .. vehiclePlate)`

but am getting - `SCRIPT ERROR: @ox_target/client/defaults.lua:139: No such export GetInventoryItems in resource ox_inventory`

Using latest builds (as of today) for ox_lib, ox_inventory, and ox_mysql.  No errors server side or client side at start. Also ensured the proper start order:

ensure oxmysql
ensure ox_lib
ensure qb-core
start ox_target
ensure ox_inventory

Thank you in advance for your assistance.
