### ISSUE TITLE
Getting issue with ammo reload 

### ISSUE THREAD

**Issue by iampere4u** [overextended/ox_inventory#1792]
**Describe the bug**
Getting issue with ammo reload when reloads the ammo the ammo gets to nil and then again reloads

**Framework**
ESX

**Resource version**
The version number listed in fxmanifest.lua, or optionally a commit hash.

**Comment by qiangshao1** [comment]
yep i am too

**Comment by thelindat** [comment]
Lacking way too much info.

**Comment by qiangshao1** [comment]
> what？
