### ISSUE TITLE
Change cash to bank in shop / gas station

### ISSUE THREAD

**Issue by Kowalec** [overextended/ox_inventory#1796]
**Is your feature request related to a problem? Please describe.**
Currently, payments in stores and gas stations are made using cash, which limits the use of the in-game banking system. Players are not incentivized to manage their bank accounts, leading to a less immersive experience where cash is preferred over bank transactions. This also affects the overall economy balance.

**Describe the solution you'd like**
I would like to modify the system so that all payments at stores and gas stations are made exclusively via the bank account, rather than using cash. This would encourage players to make more use of their bank accounts, enhancing the economic realism of the server and integrating banking into everyday transactions.

**Describe alternatives you've considered**
Keeping the current system where both cash and bank are accepted, but adding a fee for using cash.
Implementing a hybrid solution where certain transactions (above a certain amount) must be processed through the bank account, while smaller payments can still be made with cash.

**Additional context**
The server is using the ox_inventory system, and I want to ensure compatibility with it.

**Comment by thelindat** [comment]
This issue has been posted a dozen times. There is no current plan to work on payment changes and you're encouraged to make the necessary changes yourself in the shops module at this time.
