### ISSUE TITLE
Ammo Not Being Removed

### ISSUE THREAD

**Issue by TheDazedGaming** [overextended/ox_inventory#1803]
**Describe the bug**
Ammo does not remove from the inventory after reloading the first set of rounds in the weapon.

**Framework**
QB

**Resource version**
version '2.42.2'

**To Reproduce**
1. Pull out a pistol
2. Load the Pistol
3. Shoot the pistol
4. Reload
5. Repeat

**Expected behavior**
Ammo should remove otherwise you never have to buy ammo unless its a new gun

**Screenshots**
https://streamable.com/11w2oa

**Additional context**

**Comment by thelindat** [comment]
> **Framework**
> QB
