### ISSUE TITLE
devs are wankers 

### ISSUE THREAD

**Issue by sabotage93thctv** [overextended/ox_inventory#1806]
the devs are wankers had a guy make a profile on highleaks to try and threaten me i asked him if he likes ddos all i said instantly banned but hes allowed to post showing him making fake profiles of members the staff are a bunch of wankers no support and they took all qb support away guess what i have it with all the qbsupport ill sell ox inventory with qb support since they took it away ill make yous give it back or ill profit big time choice is yours funny yous took qb support because of devs being sacammed when yous are the biggest scammers in the community

**Comment by Leah-UK** [comment]
You can barely spell, gl. You were banned for the DDOS threat and the constant shit attitude. The potential leaker status just adds to it, but isn't the reason for the ban.

**Comment by sabotage93thctv** [comment]
lmfao i never threatned him did i asked if he liked them never said id ddos him you guys are crazy he made a fucking fake profile on a leak site to try and discredit people and yous said shit i say ddos and instantly banned so blackmails ok but asking someone if they like something is not lmao glad gabz got scammed be because you guys dont care about the community hench why yous did a schoolground move and shit on everyone using qbcore then even banned the word qbcore in your discord yous are sad little children im gonna sell ox inventory with the qb support and i have devs who can code better than you guys who have been helping me fix your bugs before yous even did id recommend supporting qb again or im gonna make some profits ;)

**Comment by LukeWasTakenn** [comment]
good luck with the profits bro
