### ISSUE TITLE
Transfer items not possible

### ISSUE THREAD

**Issue by DerHobbs** [overextended/ox_inventory#1807]
**Describe the bug**
With the current version, it's not possible to transfer items to other players. I've added several print statements, and it's getting stuck at this part:

modules/inventory/server.lua

if targetState.invBusy then
    print('target is busy')
    return { 'cannot_give', count, data.label }
end

The target is definitely not busy; I’ve tested it thoroughly. It’s not possible to hand over something even though the target is not busy."

Best regards.

**Framework**
The framework your server uses for players (e.g. Ox, ESX, QB).
Qbox/qbx

**Resource version**
The version number listed in fxmanifest.lua, or optionally a commit hash.
version '2.42.2'

**To Reproduce**
Try to transfer something to other players.

**Expected behavior**
That the item is transferred.

**Comment by thelindat** [comment]
At least update to the latest before re-reporting.
