### ISSUE TITLE
May be Stupid Question - Qbcore compatible?

### ISSUE THREAD

**Issue by melvillejt804** [overextended/ox_inventory#1809]
**Is your feature request related to a problem? Please describe.**
I have a new qbcore server - is ox_inventory compatible still?
I know I used it on a previous server but wanted to make sure before I make any big changes

**Comment by LukeWasTakenn** [comment]
It is not since v2.42.0, we encourage you to take a look at [qbox](https://docs.qbox.re/) instead.
