### ISSUE TITLE
Make npc weapons accessible for inventory

### ISSUE THREAD

**Issue by Cin3kk** [overextended/ox_inventory#1818]
**Is your feature request related to a problem? Please describe.**
When npc drop weapons, we can't pick this weapons.

**Describe the solution you'd like**
I want to make this weapons accessible for inventory.

**Describe alternatives you've considered**
Disabling npc weapon drop, but weapons accessible for inventory will be better.

**Additional context**
It will be cool if this weapons can be converted to items and we can picking them from dead npcs.

**Comment by thelindat** [comment]
This is something you can implement yourself (without even touching this resource). I am not going to add it myself and it poses a security issue anyway.
