### ISSUE TITLE
Ox_Inventory Safe Stash with raiding?

### ISSUE THREAD

**Issue by bluelineparabellum** [overextended/ox_inventory#1822]
**Is your feature request related to a problem? Please describe.**
Not necessarily a problem.. but an enhancement.

**Describe the solution you'd like**
Maybe make an option to make a particular stash raidable by law enforcement like business safes?

**Describe alternatives you've considered**
If its not able to be done maybe it could use a ox_doorlock system where you need the code or something if they put one on the safe.

**Additional context**
N/A

**Comment by thelindat** [comment]
There's no reason for this functionality to be added directly to ox_inventory.
