### ISSUE TITLE
No animation and removing item 

### ISSUE THREAD

**Issue by Goz-exe** [overextended/ox_inventory#1827]
**Describe the bug**
Hi, I set this item inside the server, but as you can see from the settings it should be consumed and run an animation and finally run the progress bar but it doesn't do any of this

items.lua

	['joint'] = {
		label = 'Joint',
		weight = 1,
		consume = 1,
		client = {
			anim = 'fuma_joint',
			usetime = 2500,
		}
	},
	

items/client.lua

Item('joint', function(data, slot)
	TriggerServerEvent('SetStress', -10)
end)

**Framework**
ESX

**Resource version**
2.42.1

**To Reproduce**
No error

**Comment by vrnagy** [comment]
You should use the useItem export like this:
```
Item('joint', function(data, slot)
	ox_inventory:useItem(data, function(data)
		if data then
			TriggerServerEvent('SetStress', -10)
		end
	end)
end)
```
