### ISSUE TITLE
ox_inventory bug

### ISSUE THREAD

**Issue by osdaohdph** [overextended/ox_inventory#1836]
======================================================================

 [ script:ox_inventory] SCRIPT ERROR: @ox_lib/imports/require/server.lua:124: file 'modules.bridge.qb.server' not found
 [ script:ox_inventory]      no file '@ox_inventory/modules/bridge/qb/server.lua'
 [ script:ox_inventory]      no file '@ox_inventory/modules/bridge/qb/server/init.lua'
 ======================================================================

**Comment by NICK-a11y699** [comment]
ox_inventory dosent support qb you need to degrade yr inventory version
