### ISSUE TITLE
ox_inventory requires Config.CustomInventory to be set to "ox" in the ESX Config.

### ISSUE THREAD

**Issue by CaTrooDK** [overextended/ox_inventory#1839]
SCRIPT ERROR: @ox_inventory/modules/bridge/esx/server.lua:20: ox_inventory requires Config.CustomInventory to be set to "ox" in the ESX Config.

I have all set up correctly to esx

What should i do? 

![image](https://github.com/user-attachments/assets/affe8451-acd1-45a8-b805-09c85f8003a0)

**Comment by thelindat** [comment]
> What should i do?

I wonder? Maybe read.

**Comment by hotmoneyworld** [comment]
i need the same help can anybody just answer beside being smart about it plz thanks

**Comment by Akku67** [comment]
![Uploading 387008267-affe8451-acd1-45a8-b805-09c85f8003a0.png…]()

**Comment by BogdanKolom2** [comment]
I know how to fix this error you just have to open this location:
resources/[core]/es_extended/shared/config/main.lua

and there you will find Config.CustomInventory = false
but you've to change it to Config.CustomInventory = "ox"

**Comment by BogdanKolom2** [comment]
i hope it will help you!
