### ISSUE TITLE
SCRIPT ERROR: @ox_inventory/modules/bridge/esx/server.lua:20: ox_inventory requires Config.CustomInventory to be set to "ox" in the ESX Config.

### ISSUE THREAD

**Issue by joeyninii26** [overextended/ox_inventory#1843]
SCRIPT ERROR: @ox_inventory/modules/bridge/esx/server.lua:20: ox_inventory requires Config.CustomInventory to be set to "ox" in the ESX Config.
![image](https://github.com/user-attachments/assets/257e0315-31d1-4097-b450-572726d79fb3)

**Comment by thelindat** [comment]
> requires **Config.CustomInventory** to be set to **"ox"** in the **ESX Config**.
