### ISSUE TITLE
It does not allow you to open the trunk of the vehicle when you store the car and take it out of a garage again

### ISSUE THREAD

**Issue by jcabala14** [overextended/ox_inventory#1847]
**Describe the bug**
When you take the vehicle out of the garage and open the trunk as many times as you want, it works. But when you put the car away and take it out again, it no longer allows you to access the trunk.

This happens since this commit, line 158 -> https://github.com/overextended/ox_inventory/commit/39c50fb02779a7e7dba1f693a2085d048c753527

Since the IDs do not match (the initial ID must be cached), it does not allow you to open the trunk. The ID when the vehicle is taken out for the second time is different from the first.

**Framework**
ESX '1.10.5'

**Resource version**
ox_inventory -> '2.43.3'
Garage resource tested:
- cd_garage -> '4.3.4'
- origen_ilegal -> '1.0.5'

**To Reproduce**
1. Take the car out of the garage
2. Get out and open the trunk
3. Exit inventory and save the car
4. Take the car out again
5. When trying to open the trunk you will see the warning "You can not open this inventory"

**Expected behavior**
The expected behavior is that it will allow the vehicle's trunk to be opened again.

**Screenshots**
Not applicable, steps to reproduce

**Additional context**
Not applicable

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/issues/1829#issuecomment-2466228919

**Comment by DyroS3** [comment]
![image](https://github.com/user-attachments/assets/cde6b1c9-a404-4a81-add5-8a38b0027416)
After using the latest version 2.43.4, I still get this server-side bug. I beg you to look into this issue.
