### ISSUE TITLE
Weight discrepancy during crafting 

### ISSUE THREAD

**Issue by Pilouxs** [overextended/ox_inventory#1848]
**Describe the bug**

There is a weight discrepancy when crafting items using ingredients with durability. After crafting, the server-side weight calculation does not match the client-side weight. This difference increases further if an ingredient’s durability reaches zero and the item is removed.

As a result, the player may receive a notification saying they don't have enough space in their inventory, even though they technically do.

**Framework**
qbox

**Resource version**
2.43.3

**To Reproduce**

1. Add item and ingredients to your crafting configuration :

For my test : 
`{
		label = 'Pâtes',
		items = {
			{
				name = 'pate_tomate',
				ingredients = {
					pate_crue = 0.25,
					sauce_tomate = 0.2
				},
				duration = 5000,
				count = 1,
			},
		zones = {
			{
				label = 'Faire un plat de pâtes',
				icon = 'fas fa-fire-burner',
				coords = vec3(381.65, 804.45, 187.73),
				size = vec3(1.0, 1.55, 1.0),
				groups = {['pizzeria'] = 0},
				distance = 2.0,
				rotation = 270.0,
			},
		},
	}`
	

2. Ensure your inventory contains :

10 * pate_crue (100g each, total 1kg).
10 * sauce_tomate (25g each, total 250g).

3. Craft the item pate_tomate (400g).
4. Observe the total weights:
After the first craft, the weight is correct: 1250g (initial) + 400g = 1650g.
After the second craft, the client-side weight shows 2050g (correct), but the server-side weight shows 2175g.

**Expected behavior**
The server-side weight calculation should match the client-side weight. Ingredients with remaining durability should not cause a weight discrepancy, and removing ingredients with zero durability should not further increase the difference.

**Screenshots**

print in ./module/crafting/server

First print  = i print local newWeight = left.weight + (craftedItem.weight + (recipe.metadata?.weight or 0)) * craftCount
Second print = I print newWeight and left.maxWeight just before checking if the player can carry the item or not 
`            if newWeight > left.maxWeight then
                return false, 'cannot_carry'
            end`

- First craft :
(Starter items)           
![image](https://github.com/user-attachments/assets/bf2913db-a7a7-44fe-9484-ca1c98e12e86)

![image](https://github.com/user-attachments/assets/301e45a9-7e10-4319-8db4-a8e46253a774)
![image](https://github.com/user-attachments/assets/01a5b7f6-7b48-4564-bd94-5133fe1f79ab)

- Second craft : 
![image](https://github.com/user-attachments/assets/7c4a7b75-46bc-4eea-80e7-fdbfaae5bb32)
![image](https://github.com/user-attachments/assets/97bc420c-6be3-4049-abe2-4f27c1454303)

**Additional context**
The discrepancy (125g in this case) occurs because the server adds the remaining durability of used ingredients to a new slot, causing an incorrect weight adjustment.
If an ingredient’s durability reaches zero during crafting, it is correctly removed, but the weight discrepancy increases further.

**Comment by subhampro** [comment]
1 >Add a weightAdjustment variable to track weight changes from durability modifications:
```
local weightAdjustment = 0 
```
2 > Calculate weight adjustments based on durability before checking inventory capacity:
```
for name, needs in pairs(recipe.ingredients) do
    if needs < 1 then
        local item = Items(name)
        if item and item.weight then
            weightAdjustment -= item.weight * needs
        end
    end
end

newWeight += weightAdjustment
```

3 > Update how you calculate and apply remaining durability for ingredients:

```
if count < 1 then
    local item = Items(invSlot.name)
    local durability = invSlot.metadata.durability or 100
    
    if durability > 100 then
        local degrade = (invSlot.metadata.degrade or item.degrade) * 60
        durability -= degrade * count
    else
        durability -= count * 100
    end
    
    // ...rest of durability logic
end
```
It may fix your issue 🙂
