### ISSUE TITLE
cannot start ox_inventory

### ISSUE THREAD

**Issue by molcik-dev** [overextended/ox_inventory#229]
Hi, I want start the new 2.0.0 v, and i cannot start ox_inventory

[    c-resources-core] Could not find dependency /server:4394 for resource ox_inventory.

**Comment by thelindat** [comment]
https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/
https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/

It's the latest recommended server artifact. I've made it a dependency to ensure compatibility, since it's being created and tested on that server build.
