### ISSUE TITLE
Weapon Ammo Bug

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#235]
**Describe the bug**
Reloading weapon tooks only 1 ammo from inventory but adds 12 ammo to the weapon.

**To Reproduce**
1. Take a weapon
2. Click R for reload (another bug: you reload and hit with the weapon at the same time)
3. See inventory took only 1 ammo, but on weapon top right shows 0 12

**Expected behavior**
It should take the amount of ammo from the inventory like it got reloaded into the weapon

**Comment by thelindat** [comment]
Yes we know, item use isn't complete.

**Comment by maxcamorra** [comment]
alright :)
