### ISSUE TITLE
[Dev build error] Nil error

### ISSUE THREAD

**Issue by benzon** [overextended/ox_inventory#254]
**Describe the bug**
Nil error in console when opening drops i do belive

**To Reproduce**
Drop something close inventory, open it again there should be a nil error

**Screenshots**
![FiveM_b2372_GTAProcess_us5qmRldnF](https://user-images.githubusercontent.com/3528000/135072651-f776cdd6-3858-4ca2-9d98-45fdaf1ce826.png)

**Additional context**
Freshly build from the dev branch, since latest changes aint compiled for release.

**Comment by thelindat** [comment]
Fixed; didn't update function calls to match a previous change. Currently building new release.
