### ISSUE TITLE
Notification bug with ammo

### ISSUE THREAD

**Issue by benzon** [overextended/ox_inventory#255]
**Describe the bug**
When you fire one shot reload the gun, 2 notifications will popup saying 1x ammo-9 removed

**To Reproduce**
Fire one shot reload the gun thats it

**Expected behavior**
Only one notification and notification using the label insted of the item name.

**Screenshots**
![FiveM_b2372_GTAProcess_zqLZKzjV7b](https://user-images.githubusercontent.com/3528000/135163590-3db619e4-4496-4e2b-b57a-e75def69c99d.jpg)

**Comment by Mrocznyyo** [comment]
due to this inventory bug one extra ammo always disappears when reloading a weapon

**Comment by LukeWasTakenn** [comment]
Think I've experienced this one myself If I'm thinking of the correct one. I'll add it to the trello.

**Comment by benzon** [comment]
that was quick holy :D
