### ISSUE TITLE
some Item removing doesnt work

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#260]
**Describe the bug**
If using scripts with xPlayer.removeInventoryItem the item doesn't get removed from the inventory. (seems only fits to some items) Burger you cant get removed from the inventory with xPlayer.removeInventoryItem :D)

**To Reproduce**
1. Use a script with xPlayer.removeInventoryItem (for example a crafting script)
2. Let the function get triggered
3. On example crafting: crafted item gets added but the needed item doesn't get removed from the inventory

**Expected behavior**
The item should get removed.

**Comment by thelindat** [comment]
That makes 0 sense; why would you be able to delete one item and not another. Your reproduction steps don’t tell me anything either
