### ISSUE TITLE
Slot conflict when buying items

### ISSUE THREAD

**Issue by DokaDoka** [overextended/ox_inventory#262]
When buying an item, if the item is moved to the same slot number that it came from, the transaction will fail, no errors

1. Open a shop
2. Move an item from the shop to the same solt in the player inventory
3. Shop will validate but the transaction will not occur

**Comment by LukeWasTakenn** [comment]
This should be showing the correct notification now 6b48f3d8988ebbbf6b6c95a0313b2fd8670d165d.

**Comment by DokaDoka** [comment]
I'm not sure that you've understood, I just tested with the latest release and the issue persists.

I'm not trying to stack items and the notification is not the issue, I don't get the item at all, no money is taken, the transaction fails.

**Comment by LukeWasTakenn** [comment]
I did misunderstand sorry

**Comment by thelindat** [comment]
Resolved.
