### ISSUE TITLE
Can't Open Inventory frezze like this 

### ISSUE THREAD

**Issue by colector-user** [overextended/ox_inventory#277]
![Untitled](https://user-images.githubusercontent.com/71615541/137605593-cb8f2081-1796-43e6-9388-9d86e3531fca.png)

**Comment by colector-user** [comment]
![cmd](https://user-images.githubusercontent.com/71615541/137605688-32f5e4cd-3c85-40e8-9240-c813cf058b5d.png)
cmd

**Comment by LukeWasTakenn** [comment]
Download latest release and not source code
