### ISSUE TITLE
stack glitch while giving an item

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#283]
**Describe the bug**
Some items can be stack in an other player's inventory while using give feature.

**To Reproduce**
1. Connect to the server with a friend,
2. Give you 2 parachutes, 2 phones, 2 pistols and 2 paperbags (they shouldn't be stackable by default),
3. Give those items to your friend,
4. parachutes and phone will be stacked in your friend's inventory. But not pistols and paperbags. (idk why)

**Expected behavior**
We don't want anyone be able to stack items who are registered with `stack=false`

**Screenshots**
![image](https://user-images.githubusercontent.com/47056777/138364717-3ed2b5c0-658a-499d-834e-c1f13d1fc353.png)

**Additional context**
I created another container and it's not stackable, like the paperbag. So it looks like it's only from "standard" items ?

**Comment by dolutattoo** [comment]
I meant that the items who cause this issue are not a weapon item and not a container item. That's why I called that "standard".

**Comment by thelindat** [comment]
That's because of metadata

**Comment by LukeWasTakenn** [comment]
Linden the problem resolver
