### ISSUE TITLE
Player weight broken when buying from shops

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#285]
**Describe the bug**
We can go up to the player max weight capicity when buying items in shops

**To Reproduce**
1. Go to a shop (yeah that's required),
2. Set the quantity to whathever you want,
3. Buy an item again and again until you go up to the limit,
4. Have fun

**Expected behavior**
If we don't have enough space in our inventory, we should get an error instead of receiving the item.

**Screenshots**
![image](https://user-images.githubusercontent.com/47056777/138367850-3dca4ac2-876d-4e30-aff7-aa962059ef94.png)

**Comment by thelindat** [comment]
Resolved.
