### ISSUE TITLE
Shop issues

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#286]
**Describe the bug**
This is a pretty complicate issue to explain so you should just try to reproduce to understand

**To Reproduce**

READ ALL BEFORE TO TRY
1. Go to a shop,
2. Buy a lot of water and put them always on the same slot, (make sure to count how many time you do it!)
3. At a random quantity of water you'll not be able to carry more (even if you have enough weight),
4. Continue to drag&drop and make sure to continue to count,
5. After couple times, stop the process, go out of the shop and drop all your water,
6. Re-open your inventory on the drop,
7. You'll now see a quantity of water relative the total count, and not the quantity you had in your inventory.

**Expected behavior**
We should be able to receive water if we have enough weight.
If we can't carry more, we should'nt be able to spam the error and then drop everything on the ground later.

**Screenshots**
Cannot be shown trough screenshot.

**Additional context**
This was tested by 2 different players using the water item.
It was very difficult to explain, so if you didnt understand I can make a video.

PS: issue #284 is not fixed

**Comment by thelindat** [comment]
> PS: issue #284 is not fixed

Wasn't happening here and still not happening here, so don't know what to tell you.
