### ISSUE TITLE
Drop weight limit

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#294]
**Describe the bug**
You can put more than 30kg on drop inventories.

**To Reproduce**
1. Make your inventory to 0kg (I only have money),
2. Buy 6 stacks of 20 delicious burgers,
3. Go out and drop the 6 stacks (drop weight = 26.4/30kg),
4. Buy 2 more stacks of 20 burgers,
5. Go to the previous drop marker, and drop the both stacks of burgers you have,
6. First issue is you can visually put them without getting any error notification (drop weight = 35.2/30kg),
7. But second and more serious issue is, if you close and re-open the drop inventory, the first of those 2 stacks is correctly stored in the drop inventory (drop weight = 30.8/30kg), and it shouldn't.

**Expected behavior**
We should have an error once the weight is to high for the target inventory. Instead of having a rollback and this over weight issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/47056777/139052381-b5834de0-646b-4163-bb59-f9a076de2b4d.png)

**Additional context**
If you play with other items/transfer amounts, you can go way higher than the drop weight limit. This was just one example.

**Comment by LukeWasTakenn** [comment]
@thelindat It seems like when creating a new drop and using that drop inventory it ignores the weight of the first item, I'm guessing it's because we aren't passing the `toSlot.weight` to the weight param but instead just a 0?

I also wonder if a part of this is an issue with UI

**Comment by thelindat** [comment]
I've resolved the weight issue, but I'm not sure why the UI reversion isn't happening (we return false to cancel the action).

**Comment by LukeWasTakenn** [comment]
This *should* now be fixed. efbfe6f75ce6c9b6cd44d23a2d057aebc179ceb8
