### ISSUE TITLE
Don´t know

### ISSUE THREAD

**Issue by VojtaNN** [overextended/ox_inventory#305]
Can´t  open inventory 
First startup was good, but adter restart it did this:
console:
![Výstřižek](https://user-images.githubusercontent.com/61760213/139598651-de0a99ff-2e13-41e6-ac6b-2d1b06d90f86.PNG)

**Comment by thelindat** [comment]
Why would you post an error _and not look at nor include the code causing the error_. In this case it's `data/items.lua`.

Works fine for me, but looks like it's failed to properly convert your database items to the table (or you manually added something and it's incorrect).
