### ISSUE TITLE
Not showing inventory but blurs the screen

### ISSUE THREAD

**Issue by withoutchiu** [overextended/ox_inventory#306]
Tried to download the pre release and follow the installation, i tested it and still not working. I tried to install yarn still not working

I have update my city into this inventory hoping it will work just like the Linden Inventory.

Thanks!

**Comment by thelindat** [comment]
If you get screen blur, you didn't download the release. If you had to use yarn, you most definitely didn't download the release.

**Comment by withoutchiu** [comment]
Thank you for the reply. I did download the release but still not working. What work around should i do?
