### ISSUE TITLE
Paper bag weight limit

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#313]
**Describe the bug**
A glitch to put more than 1kg into a paperbag

**To Reproduce**
1. Give you a paperbag `giveitem me paperbag 1`,
2. Go to a shop and buy 1 water, 1 cola and a stack of 3 burgers,
3. Go out, and use your paperbag to open his inventory,
4. Put the water and the cola into the paperbag inventory,
5. Try to put the stack of 3 burgers onto the water, its not possible (ok, fine),
6. Now try to put the water from the paperbag inventory onto the stack of 3 burgers in your inventory,
7. Item are now swapped, the weight of the inventory is higher than 1kg, and you can now add as many items as you want into the paperbag inventory

**Expected behavior**
There should be a check for weight when we try to swap two slots starting from the right inventory

**Screenshots**
![image](https://user-images.githubusercontent.com/47056777/139778735-5a32b641-94ef-46e8-81a4-99b2b2fb6669.png)

**Comment by dolutattoo** [comment]
I just tried with a glovebox and it's the same :)

**Comment by thelindat** [comment]
Everything in swap items runs through the same function, so it will occur with any secondary inventory (including target player inventories). I rewrote the code somewhat recently but clearly I’ve made an error.

While I will resolve the server validation for this, we’ll also want the nui to perform an initial weight check; preventing movement in the first place is more beneficial than rolling back the state.

**Comment by thelindat** [comment]
This should hopefully be resolved with my last commit.

**Comment by dolutattoo** [comment]
> This should hopefully be resolved with my last commit.

Yes it's fixed now :)

**Comment by SirSgtReal** [comment]
> **Describe the bug** A glitch to put more than 1kg into a paperbag
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Give you a paperbag `giveitem me paperbag 1`,
> 2. Go to a shop and buy 1 water, 1 cola and a stack of 3 burgers,
> 3. Go out, and use your paperbag to open his inventory,
> 4. Put the water and the cola into the paperbag inventory,
> 5. Try to put the stack of 3 burgers onto the water, its not possible (ok, fine),
> 6. Now try to put the water from the paperbag inventory onto the stack of 3 burgers in your inventory,
> 7. Item are now swapped, the weight of the inventory is higher than 1kg, and you can now add as many items as you want into the paperbag inventory
> 
> **Expected behavior** There should be a check for weight when we try to swap two slots starting from the right inventory
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/47056777/139778735-5a32b641-94ef-46e8-81a4-99b2b2fb6669.png)



Where can I find the code for this? I would like to create several bags with different sizes.

Do you perhaps know that?
