### ISSUE TITLE
Include containers weight in player inventory weight

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#314]
- **Is your feature request related to a problem? Please describe.**
It's not really a problem, but you can have waaaaay more weight than the default player capacity when putting items into paper bags. And it's not really realistic (in my opinion).

- **Describe the solution you'd like**
When you have a container item in your inventory (like paperbag), his weight value will always display his default value (1g for paperbag), even if you fill his inventory with few items.
It makes way more sense to not remove weight from our inventory when moving an item to a container inventory that we are currently wearing. 
In real life, a bag doesnt gives you any weight capactity, its just easier to carry.  The containers should only give you access to more slots, not more weight. (that's my opinion, again)

- **Describe alternatives you've considered**
A sketchy alternative would be to limit the player to not carry more than 1 paperbag at a time, or 1 heistbag at a time, etc..

- **Additional context**
![image](https://user-images.githubusercontent.com/47056777/139967157-022b0c0f-a297-4398-822d-2e51a6188426.png)

**Comment by LukeWasTakenn** [comment]
Known issue, will be sorted eventually

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/139975288-99f9fdde-1f93-4bc8-97b4-6b46cf6fc405.png)

**Comment by dunak-debug** [comment]
For now we are implementing weight calculation based on locked container position as was before ([#de85438](https://github.com/overextended/ox_inventory/commit/de85438a8c3ba230cdb6152203b70ce8f2812570)). After production release we will look up more into this functionality.

@thelindat After you push weight stuff on server close issue within.

**Comment by thelindat** [comment]
Implemented with new build.
