### ISSUE TITLE
Cannot open a paperbag while standing on a drop

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#315]
**Describe the bug**
If you are on a drop inventory (like standing on a red marker), open your paperbag from the inventory will close the nuio instead of open the container inventory. If you use the shortcuts (1,2,3,4,5), it works.

**To Reproduce**
1. Give yourself a paperbag and any other item,
2. Drop the other item on the ground,
3. Re-open your inventory
4. Try to use your paperbag, the inventory will just close,
6. If you stand somewhere else, it works fine,
6. If you try to use a shortcut to open your inventory, it will work.

**Expected behavior**
We should be able to open a bag while standing on a drop.
Using a shortcut to open the bag should also re-open the inventory with the correct right side(?)

**Additional context**
**While writing this issue I realized that we are not able to open any container if the right inventory is not an "empty drop".**

**Comment by thelindat** [comment]
> While writing this issue I realized that we are not able to open any container if the right inventory is not an "empty drop".
This is intentional behaviour and there have been issues with opening an inventory while already accessing an inventory; it could probably be improved at this point but is low priority.

**Comment by thelindat** [comment]
> **Additional context** **While writing this issue I realized that we are not able to open any container if the right inventory is not an "empty drop".**

```lua
Utils.RegisterServerCallback('ox_inventory:openInventory', function(source, cb, inv, data)
	local left = Inventory(source)
	local right = left.open and Inventory(left.open)
	if right then
		right:set('open', false)
		left:set('open', false)
		right = nil
	end
```
	
This will probably resolve the issue on server-side, if I don't test it before you then let me know.
Client-side will need an update to allow opening any inventory while already in one, though.
