### ISSUE TITLE
buy items with decimal number

### ISSUE THREAD

**Issue by pip2d06b** [overextended/ox_inventory#316]
For example:
Decimals should not be allowed in the input function.

I buy bread from the shop.
When I type "0.1", I can get 0.1 of item. 
And I use bread, it can affect 1.

**Comment by thelindat** [comment]
😕 I'm pretty sure there was something in place for this. @LukeWasTakenn

**Comment by LukeWasTakenn** [comment]
Uhm no I don't think we ever actually checked for decimals lmao

Should be an easy fix

**Comment by LukeWasTakenn** [comment]
Fixed, if you try to put in a decimal value now it will just go back to 0.
