### ISSUE TITLE
Can't Open Inventory

### ISSUE THREAD

**Issue by dontaythedon** [overextended/ox_inventory#317]
When I press F2 to open inventory. I get a blurred screen and no inventory. I dont have any errors so Im not sure what the issue is. I cant close the inventory so its functional. This issue is for stores as well.
![20211103153339_1](https://user-images.githubusercontent.com/76893439/140180306-924a0878-6320-4d1e-9dc6-27d4dbc3106b.jpg)

**Comment by LukeWasTakenn** [comment]
https://overextended.github.io/ox_inventory/issues/#inventory-doesnt-open-and-screen-is-blurry

**Comment by dontaythedon** [comment]
I have one more question. Im using the esx_ambulancejob and Im having an issue with the script finding the items to remove from the inventory. Do you think someone could help me with that?
