### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by dontaythedon** [overextended/ox_inventory#318]
Apologize to repost this figured the last post being closed it wouldnt get anymore attention. But I did have one more question. Im using the esx_ambulancejob and Im having an issue with the script finding the items to remove from the inventory. Do you think someone could help me with that?

My screen pretty much goes black and never loads

**Comment by Senlar** [comment]
Its going black because your ambulancejob is probably still trying to call player loadout and that's not a thing anymore. Remove any calls for player loadout and you'll be good.

**Comment by dontaythedon** [comment]
Do you think you can give me an example of one?

ESX.RegisterServerCallback('esx_ambulancejob:removeItemsAfterRPDeath', function(source, cb)
	local xPlayer = ESX.GetPlayerFromId(source)
	local xPlayerx = ESX.GetPlayerFromId(source)
	xPlayer.ClearInventory()
	MySQL.Sync.execute("UPDATE `users` SET `inventory` = '"..ESX.oxmysql(json.encode({})).."' WHERE `identifier` = '"..xPlayerx.identifier.."'")
	cb()
end)

**Comment by dontaythedon** [comment]
I even tried this and its more of the same 


ESX.RegisterServerCallback('esx_ambulancejob:removeItemsAfterRPDeath', function(source, cb)
	local xPlayer = ESX.GetPlayerFromId(source)
end)

	if Config.RemoveCashAfterRPDeath then
		if xPlayer.getMoney() > 0 then
			xPlayer.removeMoney(xPlayer.getMoney())
		end

		if xPlayer.getAccount('black_money').money > 0 then
			xPlayer.setAccountMoney('black_money', 0)
		end
		xPlayer.setInventoryItem('chanvre', 0)
		xPlayer.setInventoryItem('weed', 0)
		xPlayer.setInventoryItem('weed20g', 0)
		xPlayer.setInventoryItem('weed4g', 0)
		xPlayer.setInventoryItem('weed_pooch', 0)
		xPlayer.setInventoryItem('weedbrick', 0)

		xPlayer.setInventoryItem('coke', 0)
		xPlayer.setInventoryItem('coke10g', 0)
		xPlayer.setInventoryItem('coke1g', 0)
		xPlayer.setInventoryItem('coke_pooch', 0)
		xPlayer.setInventoryItem('cokebrick', 0)

		xPlayer.setInventoryItem('meth', 0)
		xPlayer.setInventoryItem('meth10g', 0)
		xPlayer.setInventoryItem('meth1g', 0)
		xPlayer.setInventoryItem('meth_pooch', 0)
		xPlayer.setInventoryItem('methbrick', 0)

		xPlayer.setInventoryItem('acidesulfurique', 0)
		xPlayer.setInventoryItem('antigel', 0)
		xPlayer.setInventoryItem('bong', 0)
		xPlayer.setInventoryItem('id_card_f', 0)
		xPlayer.setInventoryItem('thermal_charge', 0)
		xPlayer.setInventoryItem('laptop_h', 0)
		xPlayer.setInventoryItem('secure_card', 0)
		xPlayer.setInventoryItem('lockpick', 0)
		xPlayer.setInventoryItem('weapon_pistol', 0)

	if Config.RemoveItemsAfterRPDeath then
		for i=1, #xPlayer.inventory, 1 do
			if xPlayer.inventory[i].count > 0 then
				xPlayer.setInventoryItem(xPlayer.inventory[i].name, 0)
			end
		end
	end

**Comment by thelindat** [comment]
```lua
TriggerEvent('ox_inventory:clearPlayerInventory', source)
```

This will remove everything. I'll be expanding it later to allow setting items that will not be removed as well as removing specific types of items (money, weapons, items).

**Comment by dontaythedon** [comment]
And I should be able to put that in my esx_ambulance/server/main.lua correct?

**Comment by Skryptific** [comment]
> 
> 
> And I should be able to put that in my esx_ambulance/server/main.lua correct?

I think below is what you would like to achieve.
```
ESX.RegisterServerCallback('esx_ambulancejob:removeItemsAfterRPDeath', function(source, cb)
	local xPlayer = ESX.GetPlayerFromId(source)

	if Config.RemoveCashAfterRPDeath then
		if xPlayer.getMoney() > 0 then xPlayer.removeMoney(xPlayer.getMoney()) end
		if xPlayer.getAccount('black_money').money > 0 then xPlayer.setAccountMoney('black_money', 0) end
	end

	if Config.RemoveItemsAfterRPDeath then TriggerEvent('ox_inventory:clearPlayerInventory', xPlayer) end
end)
```

**Comment by dontaythedon** [comment]
Man all of you all are GOATED!!!!. Thank you all so much for your help. I'm trying to be like you all when I grow up lol. And I'll make sure i each myself as much as possible so i dont have to harass you all. Thank you again
