### ISSUE TITLE
Youtool and Ammunation buying data undefined

### ISSUE THREAD

**Issue by Velkostatkar** [overextended/ox_inventory#320]
**Describe the bug**
Youtool and Ammunation buying data undefined

**To Reproduce**
Go to ammu or Youtool 
open shop
take any kind of item/weapon in shop
move to my inventory
nothing happen

**Expected behavior**
Want to work as SHOP with food

**Screenshots**
![image](https://user-images.githubusercontent.com/70021784/140429675-209eb0a8-7be9-4653-90db-93e52667c162.png)

**Comment by thelindat** [comment]
This issue is nothing to do with the shops, but rather the data is not being sent to the UI; supposedly some people have had this occur when updating and leaving old files in the `web` folder.

**Comment by Velkostatkar** [comment]
its shown in fresh instaled server where I trying OX so there was no any updates on files

**Comment by Velkostatkar** [comment]
but what is wierd, its fix when I restart script when I am on server it load and work properly,
![image](https://user-images.githubusercontent.com/70021784/140663553-e29c921c-85b9-4f5f-97f3-8a526f7bdbdd.png)
suggest me please how avoid this? Cant restart script with every player who join :-) Should work restart ox_inventory on end of server.cfg?

**Comment by thelindat** [comment]
With no information and no method to reproduce this, it's not something I can fix. Inventory should be able to start immediately after esx.

**Comment by Velkostatkar** [comment]
As we discuse yesterday on DC is it on PCs who have integrated graphic or on Laptops or ALLINONE pcs so this users must turn ON FIVEM :
![image](https://user-images.githubusercontent.com/70021784/141081876-c86fd6a5-f093-45fb-b9a3-93d2f32ea0af.png)
