### ISSUE TITLE
[bug] missing export for notify system

### ISSUE THREAD

**Issue by MrNewb** [overextended/ox_inventory#328]
**Describe the bug**
Exports and other documentation for using the notification system outside of the inventory does not currently work.

**To Reproduce**
1. Go to '...' https://overextended.github.io/ox_inventory/misc/client/notify/
2. attempt to use examples
3. Attempted export as well with variations of data = as a variable 
4. ESX.RegisterServerCallback('esx_ambulancejob:removeItemsAfterRPDeath', function(source, cb)
    local xPlayer = ESX.GetPlayerFromId(source)
    TriggerEvent('ox_inventory:clearPlayerInventory', source)
    TriggerEvent('ox_inventory:Notify', {type = 'error', text = 'You took the easy way out, in turn lost all yo shit', duration = 2500})
    cb()
end)

**Expected behavior**
Expecting the notification to appear in this amazing notify system :O

**Screenshots**
I meannnnnnnnnnnnn

**Additional context**
no such export error in server side console. , present on the test release and a fresh build from master around 4:40 am est 11/08/21

If I am being potato my bad but even others in the discord said it should be working how I was listing.

**Comment by LukeWasTakenn** [comment]
Maybe you're starting the inventory after the ambulance job so the export isn't registered in time, although I don't know why the event wouldn't be working

**Comment by MrNewb** [comment]
its starting before


ESX.RegisterServerCallback('esx_ambulancejob:removeItemsAfterRPDeath', function(source, cb)
    local xPlayer = ESX.GetPlayerFromId(source)
    TriggerEvent('ox_inventory:clearPlayerInventory', source)
	--xPlayer.showNotification('You took the easy way out, in turn lost all yo shit')
	--Notify({type = 'error', text = 'You took the easy way out, in turn lost all yo shit', duration = 2500})
	data = {type = 'error', text = 'You took the easy way out, in turn lost all yo shit', duration = 2500}
	exports.ox_inventory:Notify(data)
    cb()
end)

gives error



ESX.RegisterServerCallback('esx_ambulancejob:removeItemsAfterRPDeath', function(source, cb)
    local xPlayer = ESX.GetPlayerFromId(source)
    TriggerEvent('ox_inventory:clearPlayerInventory', source)
	--xPlayer.showNotification('You took the easy way out, in turn lost all yo shit')
	--Notify({type = 'error', text = 'You took the easy way out, in turn lost all yo shit', duration = 2500})
	data = {type = 'error', text = 'You took the easy way out, in turn lost all yo shit', duration = 2500}
	TriggerEvent('ox_inventory:notify', data)
    cb()
end)

no error but doesnt work for me either

ESX.RegisterServerCallback('esx_ambulancejob:removeItemsAfterRPDeath', function(source, cb)
    local xPlayer = ESX.GetPlayerFromId(source)
    TriggerEvent('ox_inventory:clearPlayerInventory', source)
	--xPlayer.showNotification('You took the easy way out, in turn lost all yo shit')
	--Notify({type = 'error', text = 'You took the easy way out, in turn lost all yo shit', duration = 2500})
	data = {type = 'error', text = 'You took the easy way out, in turn lost all yo shit', duration = 2500}
	Notify(data)
    cb()
end)

shoots an error about a global


ESX.RegisterServerCallback('esx_ambulancejob:removeItemsAfterRPDeath', function(source, cb)
    local xPlayer = ESX.GetPlayerFromId(source)
    TriggerEvent('ox_inventory:clearPlayerInventory', source)
	--xPlayer.showNotification('You took the easy way out, in turn lost all yo shit')
	--Notify({type = 'error', text = 'You took the easy way out, in turn lost all yo shit', duration = 2500})
	exports.ox_inventory:Notify({type = 'error', text = 'You took the easy way out, in turn lost all yo shit', duration = 2500})
    cb()
end)

same as this giving an error about no such export

![snip2](https://user-images.githubusercontent.com/47620135/140804038-21bd4e0a-8e24-4b70-ba67-365399697cd5.PNG)


![snip](https://user-images.githubusercontent.com/47620135/140803879-c1361584-4fa0-427c-93a0-a474a7a8d0ed.PNG)

**Comment by LukeWasTakenn** [comment]
Please use markdown's code blocks 😢

**Comment by MrNewb** [comment]
oh I didnt know I could on here,

**Comment by thelindat** [comment]
Notify only exists as an export on the client - for server-side usage you need to use the event. There is however an inconsistency with it (Using `Notify` instead of `notify` does not match the casing for other exports and events, so that will be changed).

```lua
TriggerClientEvent('ox_inventory:notify', src, {type='error', text = 'You took the easy way out.'})
```
