### ISSUE TITLE
Inventory open and close events

### ISSUE THREAD

**Issue by DokaDoka** [overextended/ox_inventory#329]
I'd love to be able to keep track of whether the inventory is open or not so I can disable certain commands while it is open

An export simply returning invOpen could be useful too

**Comment by dunak-debug** [comment]
You can use `busy` state-bag

**Comment by GhzGarage** [comment]
Easily done via state bag

**Comment by LukeWasTakenn** [comment]
I added a statebag for the `invOpen` variable.

You can access it in other resources by using `LocalPlayer.state.invOpen` and it will return true or false.
