### ISSUE TITLE
Trunk wont close if you open a paperbag

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#331]
**Describe the bug**
The trunk is stuck open if you open a container while having the trunk inventory open.

**To Reproduce**
1. Spawn a sultanrs (what else should you spawn?),
2. Give yourself a paperbag,
3. Open the trunk of the sultanrs
4. Without closing the trunk, open the paperbag,
5. Close the inventory,
6. Trunk is still open

**Expected behavior**
Trunk should close when at step 4.

**Comment by thelindat** [comment]
To clarify, you mean _the physical trunk is kept open_ and not the inventory?

**Comment by dolutattoo** [comment]
Yes, exactly

**Comment by thelindat** [comment]
It's fixed but not exactly ideal.
