### ISSUE TITLE
[feat] skillbar

### ISSUE THREAD

**Issue by MrNewb** [overextended/ox_inventory#332]
**Is your feature request related to a problem? Please describe.**
No problem but further utilization of a already beautiful interface

**Describe the solution you'd like**
expand oxs notify/progressbar system to support a skillbar with variations of circle/bar timing to complete an event. ie similar to qb-skillbar.

**Describe alternatives you've considered**
to long have people been using 4 different progressbar/skillbar/notification systems in resources, this could eliminate awful or paid ui systems from being run in addition.

**Additional context**
lockpicking that was featured in linden_inventory woulda been a bit more entertaining with a skillbar system :P. plus with the way the events trigger could eliminate the extra overhead other resources use to go -event- a diffrent progressbar - a skillbar and such. additionally heres a idea on somewhere it would be useful.

`RegisterNetEvent('aussielindenpoopoo:startlockpicking')
AddEventHandler('aussielindenpoopoo:startlockpicking', function()
    local ped = PlayerPedId()
    local pedc = GetEntityCoords(ped)
    local closeveh = GetClosestVehicle(pedc.x, pedc.y, pedc.z, 5.0, 0 ,71)
    local lockstatus = GetVehicleDoorLockStatus(closeveh)
    local distance = #(GetEntityCoords(closeveh) - pedc)
    if distance < 3 then
		SetCurrentPedWeapon(PlayerPedId(), GetHashKey("WEAPON_UNARMED"),true)
		TaskTurnPedToFaceEntity(PlayerPedId(), closeveh, 15000)
        if lockstatus == 2 then
			math.randomseed(math.random(1,9999))
			local random = math.random(1,10)
			if random >= 5 then
				progressbar()
				Citizen.Wait(15000)
				TriggerEvent('mythic_notify:client:SendAlert', {type = 'inform', text = 'Successfuly picked the lock', length = 2500})
				SetVehicleAlarm(closeveh, true)
				SetVehicleAlarmTimeLeft(closeveh, 120000)
				SetVehicleDoorsLocked(closeveh, 1)
				SetVehicleDoorsLockedForAllPlayers(closeveh, false)
			elseif random <= 4 then
				progressbar()
				Citizen.Wait(15000)
				SmashVehicleWindow(closeveh, 0)
				TriggerEvent('mythic_notify:client:SendAlert', {type = 'error', text = 'Your lockpick broke', length = 2500})
				TriggerServerEvent('linden_inventory:removeItem', 'lockpick', 1)
				SetVehicleAlarm(closeveh, true)
				SetVehicleAlarmTimeLeft(closeveh, 900000)
			end
        else
            ESX.ShowNotification('Vehicle is not locked')
        end
    else
        ESX.ShowNotification('No vehicle nearby')
    end
end)`

**Comment by MrNewb** [comment]
oh god whyd that end up so messed up looking

**Comment by thelindat** [comment]
\```lua
code
\```
