### ISSUE TITLE
Problem when inserting item from database

### ISSUE THREAD

**Issue by withoutchiu** [overextended/ox_inventory#333]
https://github.com/overextended/ox_inventory/blob/0370534a1aa835e4adcef246732fa190c5fa7bae/modules/items/server.lua#L46

Above trying to replace "}" in to space but it was unsuccesful.

Solution:

file[1] = string.sub(file[1], 1, (string.len(file[1]) - 1))

Substring the whole file from the start till the end of string - 1 which is the "}" at the end.

Making sure there is no whitespaces or new line at the end.

**Comment by thelindat** [comment]
If both are going to fail due to line breaks or whitespace, I'll need to adjust the pattern to check for and replace any whitespace.

**Comment by withoutchiu** [comment]
> If both are going to fail due to line breaks or whitespace, I'll need to adjust the pattern to check for and replace any whitespace.

Sounds good! That would be better. You can optimized my solution. Thanks!

**Comment by withoutchiu** [comment]
> If both are going to fail due to line breaks or whitespace, I'll need to adjust the pattern to check for and replace any whitespace.

Sounds good! That would be better. You can optimized my solution. Thanks!

**Comment by thelindat** [comment]
I changed it to use `string.strtrim` from the loaded data before searching for the pattern; should resolve it.

**Comment by withoutchiu** [comment]
Perfect! Great work lindat! Closingthe ticket. Thank you.
