### ISSUE TITLE
Register Shops Export

### ISSUE THREAD

**Issue by benzon** [overextended/ox_inventory#337]
**Is your feature request related to a problem? Please describe.**
I'm playing around with qTarget, and i thought about vending machines, and it would be nice to actually use the shop feature for buying from vending machines.

**Describe the solution you'd like**
A way to register, or access predefined shops for vending machines, using qTarget entity tracking, insted of predefined coords.

**Comment by rklgaming** [comment]
you can do it via triggering the data shops add your shop there and trigger the open inventory

**Comment by benzon** [comment]
There is a security check in place @rklgaming so no not with out changes to the code :)

It checks the distance to the shop when using the trigger :)

**Comment by rklgaming** [comment]
just put your player ped to coords and it will work

**Comment by benzon** [comment]
Just put your player ped to coords and it will work, but it's not a solution in this case??

The vending machines are all over the map, not gonna sit down and wright down every single coord for it, if you check the code, there is a distance check, when you open up a shop, if you are not with in distance it wont open up for you by design...

https://github.com/overextended/ox_inventory/blob/9c80540802288698f556424c084176f257bda15f/modules/shops/server.lua#L43

Thats why a solution needs to made if Linden is willing to do so since it will compromise security somewhat.

**Comment by rklgaming** [comment]
RKLGaming#4403 i will explain it to you im saying this cause i already do that many times in single line of code

**Comment by benzon** [comment]
Then show an example of how to do it @rklgaming

**Comment by thelindat** [comment]
Something something heart of server. Anyway

https://github.com/overextended/ox_inventory/commit/e9f2e6e8d8ba274fee78d460cecc74114847abc2
