### ISSUE TITLE
Issue with dragging items and closing inventory while dragging

### ISSUE THREAD

**Issue by benzon** [overextended/ox_inventory#339]
**Describe the bug**
First off this bug is not mine, was posted on discord, just checked and validated the bug.

When dragging an item and closing the inventory, the item stays on screen, when re-opening the inventory you are still dragging the same item.

**To Reproduce**
Open inventory
Drag item
ESC to get out of inventory
Item stuck on screen
Open Inventory
Item is still the one you are dragging around

**Expected behavior**
Icon not staying on screen and dragging is reset, so you are not dragging anything when opening the inventory again.

**Screenshots**
![image](https://user-images.githubusercontent.com/3528000/142216209-8da2f8e8-fedf-47ab-b45a-7bf044106b38.png)

**Comment by LukeWasTakenn** [comment]
Fixed
