### ISSUE TITLE
make logs for putting items in and out of glovebox or trunk

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#341]
**Is your feature request related to a problem? Please describe.**
Nearly everything gets logged but no interaction with the glovebox or trunk

**Describe the solution you'd like**
have logs for these things inside the log file

**Comment by thelindat** [comment]
What are you even talking about? 
```
"date": "15/Nov/2021", "time": "17:32:55", "source": "Peter Linden [1] - char1:611c0a85f0fc5292eb0fdd1d38bedd7c140c398e", "target": "20HWR040 [trunk20HWR040] - false", "content": "Transferred 1 paperbag"

"date": "15/Nov/2021", "time": "17:33:04", "source": "20HWR040 [trunk20HWR040] - false", "target": "Peter Linden [1] - char1:611c0a85f0fc5292eb0fdd1d38bedd7c140c398e", "content": "Transferred 1 paperbag"

"date": "15/Nov/2021", "time": "17:33:05", "source": "Peter Linden [1] - char1:611c0a85f0fc5292eb0fdd1d38bedd7c140c398e", "target": "20HWR040 [trunk20HWR040] - false", "content": "Transferred 1 paperbag"
```
There is no unique "vehicle transfer event", it all utilises the exact same code regardless of type. Stash, container, another player, whatever - they all go through the exact same steps and logging function.
