### ISSUE TITLE
Can exceed any inventory weight by stacking items

### ISSUE THREAD

**Issue by vWernay** [overextended/ox_inventory#342]
**Describe the bug**
Can exceed the inventory maxWeight by stack a item.

1. Go to an second inventory
2. Store any quantity of heavy items in he
3. Now store more item in the same slot
4. Is that, now the weight of inventory is bugged and u can exceed he

**To Reproduce**
Steps to reproduce the behavior: https://streamable.com/cbp2o4 or https://streamable.com/9fyqit

**Comment by LukeWasTakenn** [comment]
I can't reproduce this, the items revert back to the truck as they should do.

**Comment by vWernay** [comment]
> I can't reproduce this, the items revert back to the trunk as they should do.

Hi, sorry for the delay...
Try make the same in this another video: https://streamable.com/3fk5de

**Comment by thelindat** [comment]
hi could you post a third video from a slightly different angle showing the exact same lack of information

**Comment by vWernay** [comment]
> hi could you post a third video from a slightly different angle showing the exact same lack of information

Hi, yep

**Comment by vWernay** [comment]
> hi could you post a third video from a slightly different angle showing the exact same lack of information

Hey, there is: https://streamable.com/v3v2du

**Comment by thelindat** [comment]
> > hi could you post a third video from a slightly different angle showing the exact same lack of information
> 
> Hi, yep

I was being facetious. Your video shows nothing, and neither Luke nor myself are able to reproduce the problem you are reporting.

Luke thought perhaps additem was breaking weight, but no. I'll leave this open until you decide to grace us with some actual usable information; if there's nothing in a week then I'll be closing it.

**Comment by vWernay** [comment]
> > > hi could you post a third video from a slightly different angle showing the exact same lack of information
> > 
> > 
> > Hi, yep
> 
> I was being facetious. Your video shows nothing, and neither Luke nor myself are able to reproduce the problem you are reporting.
> 
> Luke thought perhaps additem was breaking weight, but no. I'll leave this open until you decide to grace us with some actual usable information; if there's nothing in a week then I'll be closing it.

Please, try this: Let's say your player max weight is 15kg and the item you want to store has 1kg, put 5x (5kg) of this item in a second inventory(veh trunk for example), now get more 11x (11kg) of this item, your player inventory will weigh 11kg and the second inventory 5kg, if you try to get the item from the second inventory you won't be able to, however if you put +5(5kg) of the item together with the other x5 that are in the second inventory you will be able to get them, exceeding you max weight, you will be left with 16kg and the max is 15kg!

Look at this other short video: https://streamable.com/9fyqit

**Comment by vWernay** [comment]
I reverted the changes from https://github.com/overextended/ox_inventory/commit/60ad3728daef675082c50dee6b99f68e267a34a5#diff-1b8f97d898e63162c92a0f09152d067cbe6a053a3fe5d96b96d751cbacce5786 and it "solves" a part of the problem

**Comment by vWernay** [comment]
Hi, i have news, when swap item to a stack in other Inventory, the playre inv(for example) loose to much weight, i think the problem is on https://github.com/overextended/ox_inventory/blob/5b1d0e2acfe9f9c7755913a0e03dcb40f88af087/server.lua#L250 , i replaced this line for `fromInventory.weight = (fromInventory.weight - data.count * Items(toData.name).weight)`  only for a test and now its works great.

Note: I don't think it's the right solution, but it's something...

**Comment by thelindat** [comment]
Try now.

**Comment by vWernay** [comment]
> Try now.

Hey, worked! Thx
