### ISSUE TITLE
F8 Error with qtarget

### ISSUE THREAD

**Issue by QuinouDEV** [overextended/ox_inventory#343]
F8 Error with QTARGET

When I connect to my server, it is impossible for me to open the inventory without restarting the script, this error appears in my F8. This problem appears when I enable qtarget in config of ox_inventory

This is my start order:
ensure oxmysql
ensure es_extended
ensure PolyZone
ensure qtarget
ensure pe-lualib
ensure ox_inventory

This is the error
![image](https://user-images.githubusercontent.com/47609618/142699538-d7fd7dd5-298c-4bc1-986b-e4f1280a81a8.png)

**Comment by Skryptific** [comment]
Make sure the export `AddTargetModel` exists in qtarget.

**Comment by QuinouDEV** [comment]
AddTargetModel exist

**Comment by thelindat** [comment]
No repro, no help. The export exists and, if it is claiming otherwise, the resource has not started.
