### ISSUE TITLE
Item Stacking when given an item

### ISSUE THREAD

**Issue by Leah-UK** [overextended/ox_inventory#350]
You're already aware. But wanted to document it so people don't re-report the same issue. 

Giving an item that is already owned by a player through xPlayer.addInventoryItem or any other means (Inventory.AddItem(source, item, count)) doesn't stack when it should be able to (_ie on items that are stackable_).

**Comment by thelindat** [comment]
Resolved with https://github.com/overextended/ox_inventory/commit/16216b98a8b1bcc1d4011469abaf8e154d0391ca
