### ISSUE TITLE
drops not working properly

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#360]
**Describe the bug**
If I create a drop and disconnect the server, another player is taking the items out of the drop the marker gets deleted for this player. Now if I rejoin I can stil see the marker but it tells me "You can not open this inventory".

**To Reproduce**
1. Create a drop and put an item inside
2. disconnect from the server
3. let another player take the item out
4. connect the server again and see the error (marker is showing but not accessible)

**Expected behavior**
the marker should get deleted on any client side even if I disconnected

**Screenshots**
![image](https://user-images.githubusercontent.com/78707245/144717154-276c2770-4dc8-41ac-b797-d0257c261a4f.png)

**Comment by thelindat** [comment]
Resolved.
