### ISSUE TITLE
steal command doesnt work

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#361]
**Describe the bug**
If the player died I can't use /steal

**To Reproduce**
1. kill a player
2. do /steal near him
3. See error

**Expected behavior**
The player's inventory should be opened

**Screenshots**
![image](https://user-images.githubusercontent.com/78707245/144717348-47d405ed-2fd2-4599-ace5-42377e4eabf5.png)

**Comment by thelindat** [comment]
Should be resolved.
