### ISSUE TITLE
PD armory not showing up

### ISSUE THREAD

**Issue by Fleevo73** [overextended/ox_inventory#374]
**So I updated to the latest of everything & I'm currently using release of the inventory. I was configuring my shops and set up everything just fine. I loaded in to find out that even with the PD job the armory isn't accessible. When I say this I mean its not showing up at all. There isn't any errors in my F8 and or console + the inventory is ready to use upon every load in. I cant seem to find the problem. Here is where the armory is normally located.**
![image](https://user-images.githubusercontent.com/92953389/145713346-e29dc5b3-5105-4bc7-9867-2dbee9de20d4.png)

**Here is my armory block. This is in fact the only shop I did NOT touch which is why I'm really confused.**
![image](https://user-images.githubusercontent.com/92953389/145713464-40e89722-ce06-4a31-8c48-af568432b535.png)

**Comment by thelindat** [comment]
No issue with markers or qtarget upon testing.
