### ISSUE TITLE
Weapons in vehicles and reloading issues

### ISSUE THREAD

**Issue by frazz1234** [overextended/ox_inventory#375]
So if you DriveBy and need to reload, r put yourself in cinematic mode. So something in this script for desactivate this could be amazing! thanks

**Comment by dunak-debug** [comment]
Could you please test this native to disable cinematic mode?

https://docs.fivem.net/natives/?_0xDCF0754AC3D6FD4E

**Comment by frazz1234** [comment]
SO the native work, but for anyreason... the gun is holstered and have to take it back

**Comment by thelindat** [comment]
I'll look at drivebys another time, but it's always been awkward to get working properly.
