### ISSUE TITLE
Drop and Give

### ISSUE THREAD

**Issue by frazz1234** [overextended/ox_inventory#381]
**Describe the bug**
Open inventory, drag a thing for drop on the ground. The arrow is visible but you can't take back the thing you put on the ground. If you try to give an item to someone... its imposisble, you can't see the id of the other person and its impossible to giveitem

**To Reproduce**
https://streamable.com/bs1kqg

**Expected behavior**
Give item to someone, or put some stuff on the ground and take it back

**Screenshots**
https://streamable.com/bs1kqg

**Comment by thelindat** [comment]
> you can't take back the thing you put on the ground

Drops are the first thing I test before any update; they work fine and I have not experienced any scenario in which they do not open.

> you can't see the id of the other person and its impossible to giveitem

That's not how it works, and like drops they have been tested to work - I even increased the radius for the raycast to find a target.

**Comment by frazz1234** [comment]
so, have you seen my video ? we can't take bake the drops
