### ISSUE TITLE
stashes not working anymore

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#385]
**Describe the bug**
When I try to add items into the stashes the label doesn't get changed above the second inventory slot also it doesn't create an entry inside the database.

**To Reproduce**
1. open stash
2. put item
3. check label and database, furthermore reconnect to the server

**Additional context**
there is no error shown up but it shouldn't be like this.

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/146265827-dabaf0e4-cad9-46f7-98fa-702e6ce2a04f.png)
![image](https://user-images.githubusercontent.com/65407488/146265849-20384a9c-6099-4326-bc7f-93c46b63e17b.png)

> See error
> Additional context
there is no error shown up but it shouldn't be like this.

**Comment by maxcamorra** [comment]
hmm ok it takes just a damn high amount of time til it saves, can't it get saved instantly after closing the stash it would prevent the losing of items when the client for example crashes.

**Comment by thelindat** [comment]
> hmm ok it takes just a damn high amount of time til it saves

It gets saved as part of a 10 minute interval on the server.

> can't it get saved instantly after closing the stash

It can, but then we're sending queries to the database constantly for no reason

> prevent the losing of items when the client for example crashes.

What? Items are stored _on the server_. The client has nothing to do with storage of items; the only way you lose data is if your server crashes (which would result in lost player data too).

**Comment by skyner22** [comment]
what property script is that?
