### ISSUE TITLE
clearinventory

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#386]
**Describe the bug**
shows error when it should clear the inventory. why?

Error:
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:698: bad argument #1 to 'wipe' (table expected, got nil)
[ script:ox_inventory] > ref (@ox_inventory/modules/inventory/server.lua:698)
[ script:ox_inventory] > ref (@esx_ambulancejob/server/main.lua:115)
[ script:ox_inventory] > TriggerServerCallback (@es_extended/server/functions.lua:148)
[ script:ox_inventory] > handler (@es_extended/server/common.lua:56)

I have exchanged TriggerEvent('ox_inventory:clearPlayerInventory', xPlayer) to exports.ox_inventory:ClearInventory(xPlayer) but it still shows the error above? Forgot something?

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/146288837-ad5dc79b-9028-46a4-a3d8-a596f57c2a1e.png)
```lua
exports.ox_inventory:ClearInventory(source)
```
