### ISSUE TITLE
Viewing Inventories

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#390]
**Describe the bug**
You can no longer see the contents of someone's inventory via `/inv`, not sure if this is on my end but it's blank.

**To Reproduce**
1. Login in-game.
2. Type `/inv [id]`.
3. Inventory is blank.

**Expected behavior**
Ability to view the other persons inventory.

**Additional context**
- **Game Version:** 5122
- **Client:** Production

**Comment by thelindat** [comment]
`viewinv`
