### ISSUE TITLE
Viewing Inventories

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#393]
**Describe the bug**
Viewing another person inventory and closing it doesn't allow you to utilize your inventory functions (use, move, drop, right click context menu).

**To Reproduce**
1. Type `/viewinv [id]`
2. Close the inventory (stop viewing the persons inventory).
3. Try to move/drop/right click an item in your inventory.

**Expected behavior**
Ability to move, drop, right click after closing the /viewinv (unless its suppose to be like this).

**Additional context**
- **Game Version:** 5122
- **Client:** Production
- **Inventory Build:** 43e3b38

**Comment by LukeWasTakenn** [comment]
Should be fixed now.
