### ISSUE TITLE
Item Props

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#397]
**Describe the bug**
Uncertain if this is a bug with the `inventory` or `pe-lualib`, but the props from the items get stuck in your hand after using it. I don't know whether this is an issue with **Onesync Infinity** but it was tested with 90+ people and the item doesn't clear after using it. I understand that this inventory is work in progress.

**To Reproduce**
1. Purchase an item that uses a prop from a store (i.e.: burger or water)
2. Use the item and then the prop for said item will be stuck in your hand.

**Expected behavior**
The specified prop for the item should be removed from the persons hand.

**Additional context**
- **Game Version:** 5127
- **Client:** Production
- **Inventory Build:** f7ce3d9

Thank you guys for everything you do and for the swift responses to most of the bug reports.

**Comment by thelindat** [comment]
Prop clears perfectly fine for me so unless there's an actual repro

**Comment by DogsGoBark** [comment]
> Prop clears perfectly fine for me so unless there's an actual repro

Could it be because of Onesync Infinity or an entity lockdown?

**Comment by thelindat** [comment]
props wouldn't spawn at all during entity lockdown, and I solely use infinity.

**Comment by DogsGoBark** [comment]
> props wouldn't spawn at all during entity lockdown, and I solely use infinity.

I try to record it for you today.

**Comment by DogsGoBark** [comment]
Here's an example; https://streamable.com/kkbik5

**Comment by thelindat** [comment]
Still a _sounds like a you_ problem.

**Comment by dunak-debug** [comment]
yes
