### ISSUE TITLE
Containers are empty after giving them

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#402]
**Describe the bug**
If you fill a container item with few items, and give it to another player, he'll receive an empty item. Giving it back to you wont make the item appearing again, looks like they are lost.

**To Reproduce**
1. Give yourself a paperbag `/giveitem me paperbag 1`,
2. Put some items in it like 2 delicious burgers,
3. Give the paperbag to your friend,
4. He will get an empty paperbag

**Expected behavior**
The paperbag should keep the items you just put in it.

**Additional context**
I tried to create other container but same result as well
Beside that, it works very good. We didnt find any weight glitch, etc. Amazing job <3

**Comment by thelindat** [comment]
Is it regenerating the container Id?

**Comment by dolutattoo** [comment]
> Is it regenerating the container Id?

Yes, it's regenerating the container Id. Only way to keep the same bag is to drop it then others players can grab it and see their content.

**Comment by thelindat** [comment]
Should be resolved.
