### ISSUE TITLE
Weapon Withdrawing

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#403]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but more of a enhancement?

**Describe the solution you'd like**
When a person with a `cop` job takes out or puts away a `stungun` or `pistol` can the animation be the same. Right now, the pistol withdraws from holster, but the stungun takes out / puts away like a gangster.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LukeWasTakenn** [comment]
Resolved in 3a1ca4a32522d6dd8bb8cfbb6089c9003c51e289.
