### ISSUE TITLE
override description in metadata (&more)

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#404]
**Is your feature request related to a problem? Please describe.**
Not really, but it can make the upgrade process from linden_inventory way easier.

**Describe the solution you'd like**
It would be very cool if we can override the item description by adding a 'description' value in metadata. Like linden_inventory do. (well, did ^^)

**Additional context**
Some stuff that I also personnaly loved to add in linden_inventory was the ability to override item label, and item image in metadata.
```lua
metadata = {
    image = 'my_image2', -- to be able to update the item image buy another one
    label = 'another name', -- to be able to update the item label
    description = 'super pepega stuff', -- to be able to update the item description
}
```

As example, this is how it currently works on my server using linden_inventory:
I'm using this stuff for bags, like people are able to buy different bags in shops, and the image is related to the color of the bag they are buying (and wearing for sure). So instead of having on item per bag, I prefer to have 1 bag item, with few metadatas who overrides the color, the image, and the label

For car keys, the label is updated depending of the vehicle plate
etc..

**Comment by dunak-debug** [comment]
Basic implemention (untested) in https://github.com/overextended/ox_inventory/commit/e191a1a1fa43d07b6717199f54fd120146eafaec

**Comment by dolutattoo** [comment]
It works fine inside inventories, but not in item notifications (add/remove), and hotbar neither

> Basic implemention (untested) in [e191a1a](https://github.com/overextended/ox_inventory/commit/e191a1a1fa43d07b6717199f54fd120146eafaec)

**Comment by dunak-debug** [comment]
Hotbar fixed in https://github.com/overextended/ox_inventory/commit/7f4334babf1a9433a4aa113de6ec3df18c1f0908

Notifications pending

**Comment by dunak-debug** [comment]
Fully implemented in https://github.com/overextended/ox_inventory/commit/e5607333f0a50d7a1fd90b6d8491cd71ba719466 and https://github.com/overextended/ox_inventory/commit/afa63c27c643de9ce2c5560f0b9ccfd449b736f3
