### ISSUE TITLE
Custom metadata are ignored when giving new item

### ISSUE THREAD

**Issue by AbsCreach** [overextended/ox_inventory#405]
**Describe the bug**
Custom metadata are ignored when giving new item.
The item is given fine but metadata are ignored.

**To Reproduce**
1. Give yourself any item with custom metadata (for example, type)
2. Hover over item to see that there is no type shown
3. Save your inventory and see in database that there is no metadata saved

**Expected behavior**
Give item with specified metadata

**Additional context**
No error and using latest build (25.12)
```lua
--this is the way i give the item
Inventory.AddItem(source, 'burger', 1, {
  type = 'cheese'
})
```

**Comment by thelindat** [comment]
Fixed.
