### ISSUE TITLE
Grade Requirements

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#406]
**Describe the bug**
Unable to take items that have grade requirements from specific shops.  Yes, I have a weapon license and my grade is three, Everything else works fine except this.

```lua
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/server.lua:207: attempt to index a boolean value (local 'fromInventory')
[ script:ox_inventory] > callback (@ox_inventory/server.lua:207)
[ script:ox_inventory] > handler (@server.lua:11)
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/shops/server.lua:118: attempt to index a nil value (field 'data')
[ script:ox_inventory] > callback (@ox_inventory/modules/shops/server.lua:118)
[ script:ox_inventory] > handler (@server.lua:11)
[ script:ox_inventory] > safeCallback (@oxmysql/oxmysql.js:19903)
[ script:ox_inventory] > <unknown> (@oxmysql/oxmysql.js:19928)
[ script:ox_inventory] > runMicrotasks (<anonymous>:0)
[ script:ox_inventory] > processTicksAndRejections (node:internal/process/task_queues:96)
```

`{ name = 'WEAPON_CARBINERIFLE', price = 1500, metadata = { registered = true, serial = 'POL' }, license = 'weapon', grade = 3 },`

**To Reproduce**
1. Open a `Police Armory`
2. Attempt to withdraw a Carbine Rifle?

**Expected behavior**
Ability to take the weapon with the proper grade.

**Additional context**
- **Game Version:** 5132
- **Client:** Production
- **Inventory Build:** 311f91e
- **Framework:** Latest es_extended from Overextended.

**Comment by thelindat** [comment]
Problem resolved.
