### ISSUE TITLE
Error when opening other player inv

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#408]
**Describe the bug**
Everything works fine, there is just this error who appear in server console when you open another player inventory

**To Reproduce**
1. Open your friend's inventory using something like:
`TriggerEvent('ox_inventory:openInventory', 'player', GetPlayerServerId(targetPlayer))`
2. check server console

**Screenshots**
![image](https://user-images.githubusercontent.com/47056777/147428536-8088de11-b136-4bfe-8554-82440e3e57f5.png)

**Comment by dunak-debug** [comment]
Should be fixed in https://github.com/overextended/ox_inventory/commit/51feb10902dae1c261d869b2753349099f6421e4

Pending feedback so re-open if occurs again.
