### ISSUE TITLE
Exports Notify

### ISSUE THREAD

**Issue by withoutchiu** [overextended/ox_inventory#409]
Cannot use export Notify from other resources, Do we forget to add them to fxmanifest?

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/blob/main/modules/utils/client.lua#L57-L58

**Comment by withoutchiu** [comment]
Tried to use this exports.ox_inventory:notify( {type = 'error', text = 'Lost access to the target inventory'}) but its not working, Do you know why @thelindat ? Thanks!
