### ISSUE TITLE
Having issues with ox_inventory

### ISSUE THREAD

**Issue by BRZM1** [overextended/ox_inventory#410]
client.lua:5: bad argument #1 to find (string expected, got nil)
<img width="816" alt="error" src="https://user-images.githubusercontent.com/96719775/147453156-c5991fcf-dfc8-499f-8e69-5e2268b4eb19.png">

**Comment by BRZM1** [comment]
i guess im not getting any help with an issue?

**Comment by thelindat** [comment]
Like the other 3 reports on this, it's caused by other resources setting the 'busy' statebag from some policejob release.

**Comment by BRZM1** [comment]
oh ok thanks
