### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#412]
**Describe the bug**
it shows that there is no metadata but is it necessary?

![image](https://user-images.githubusercontent.com/78707245/147515526-80ffc1aa-d7d4-4efc-b5b8-d3022a60171f.png)

the affected code is this: (line of removeInventoryItem)
![image](https://user-images.githubusercontent.com/78707245/147515538-2abacc43-b56e-42ea-8c24-913fdda5e176.png)

**Comment by thelindat** [comment]
This error was already fixed but isn't included in the current release build.
