### ISSUE TITLE
All items say NO LABEL

### ISSUE THREAD

**Issue by T3mpu5** [overextended/ox_inventory#414]
**Describe the bug**
When you equip, drop, give, use, unequip any item it will pop up with No Label instead of the item

**To Reproduce**
1. equip a weapon

**Expected behavior**
Should pop up equipped 1x Pistol

**Screenshots**
![image](https://user-images.githubusercontent.com/39499405/147604045-07c9b30c-6233-4e58-b47e-bda599ff80d1.png)

**Additional context**

**Comment by thelindat** [comment]
Your item data hasn't been loaded into the NUI properly, and it's not something I can reproduce.

**Comment by vWernay** [comment]
Try this commit if using the release version: https://github.com/overextended/ox_inventory/commit/af0479642ca78e92c17748a76bf967a0b38ed61e

**Comment by T3mpu5** [comment]
Just tried to install latest commit and inventory doesn't open at all!

**Comment by T3mpu5** [comment]
Never mind, Fresh install fixed it :)
Thanks for the response though :)
