### ISSUE TITLE
Serials

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#416]
**Describe the bug**
Weapons that are in the Police Armory only display `POL` and not the full serial now. The other weapons work fine.

**To Reproduce**
1. Goto the Police Armoury
2. Buy a weapon that has a serial.
3. You will only see the serial `POL`.

**Expected behavior**
Display the serial number with `POL`.

**Additional context**
- **Game Version:** 5137
- **Client:** Production
- **Inventory Build:** f0dc469

Thank you guys for everything you do and for the swift responses to most of the bug reports.

**Comment by thelindat** [comment]
Resolved.
