### ISSUE TITLE
Item Registering

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#417]
**Is your feature request related to a problem? Please describe.**
Not related to a problem or enhancement but question I guess?

**Describe the solution you'd like**
Noticed that in the [examples](https://github.com/overextended/ox_inventory_examples) that there's a way to register clientside item events, but is there a way to do them for server too? For an example; every time we update the inventory the `modules/items/client.lua` or `modules/items/server.lua` gets wiped. Maybe some place in data where we can register them i.e.: `data/items/client.lua` or `data/items/server.lua`.

**Describe alternatives you've considered**
Yes, I know git control exists, but I think a lot of people will like this.

**Additional context**
N/A

**Comment by thelindat** [comment]
How would data/items be safer than modules/items? Rather than just wiping your items, see what changed and apply changes as needed.

The items module will rarely be updated after release, anyway.

**Comment by DogsGoBark** [comment]
Talking about registering items via like `client.lua`, `server.lua` for an exemple would be stored in a  different thing where as default items would be registered in `modules/items/client.lua`, but I get what you're saying.

```lua
Item('fanta', function(data, slot)
	ox_inventory:useItem(data, function(data)
		if data then
			ox_inventory:notify({text = 'You drank some delicious '..data.name})
		end
	end)
end)
```
