### ISSUE TITLE
Switching from weapon to melee throws error

### ISSUE THREAD

**Issue by AbsCreach** [overextended/ox_inventory#418]
**Describe the bug**
Switching from weapon capable of holding ammo to melee weapon throws error.

**To Reproduce**
1. Give yourself weapon which **can** hold ammo
2. Give yourself weapon which **can't** hold ammo (melee)
3. Equip "ammo weapon"
4. Equip "no ammo weapon"
5. See error in server console

**Expected behavior**
Don't compare nil

**Additional context**
```
SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:862: attempt to compare number with nil
> handler (@ox_inventory/modules/inventory/server.lua:862)
```

**Comment by thelindat** [comment]
Fixed.
