### ISSUE TITLE
usedItem callback event is not called

### ISSUE THREAD

**Issue by AbsCreach** [overextended/ox_inventory#419]
**Describe the bug**
Callback function with event "usedItem" is not called after using item.

**To Reproduce**
1. Give yourself an item with server callback using "usedItem" (testburger is fine)
2. Use the item
3. See it triggers only "usingItem" and not "usedItem"

**Expected behavior**
Trigger callback even after finishing using the item.

**Comment by thelindat** [comment]
Resolved.
