### ISSUE TITLE
Support Peds for Shops!

### ISSUE THREAD

**Issue by TlYPN** [overextended/ox_inventory#422]
**Is your feature request related to a problem? Please describe.**
My feature request isn't directly a problem! and people could just use there 5 head! but i have noticed it hard for new players to figure out how to "open" the shop. without being told to use Qtarget on the register.

**Describe the solution you'd like**
Possibly support the use of a ped in the shop, as oppposed to "qtarget to a cash register"

**Describe alternatives you've considered**
GIANT HOLOGRAPHIC text to tell players to third eye cash register (im only kidding, i dont really have another solution)

**Additional context**
Sorry if this isnt the place for suggestions! wasnt sure where else to put it

**Comment by thelindat** [comment]
It's not something any of us plans to actively work on (original bt-target support was a PR), but it's not undesired.
Can refer to https://github.com/overextended/ox_inventory/pull/321

I could setup some ped management as an export inside pe-lualib so it can handle peds for every resource (I need to move marker code there, too). As for actual implementation into the inventory and setting up all the positions, I'd probably just do one as a sample and leave the rest for community commits.

**Comment by Senlar** [comment]
I found another resource called droopies-peds and I modified it to work with qtarget. I use it to manage all interactable peds on my server from one resource like your suggesting Linden. Here's my version: https://github.com/Senlar/droopies-peds

Also, could I please get unbanned from the discord? Haven't been able to find a way to contact anyone for a while.
