### ISSUE TITLE
Impossible to remove weapon components if durability == 0

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#429]
**Describe the bug**
Not sure if it's intended or not, but when a weapon durability is down, you can't wear it anymore so you cannot get back the components :/

**To Reproduce**
1. Give yourself a weapon `/giveitem me weapon_microsmg 1` (fastest for test imo),
2. Give yoursel some ammos `/giveitem me ammo-45 1000`,
3. Give yoursel a weapon accessory `/giveitem me at_clip_extended_smg 1`,
3. Apply the accessory on the weapon,
4. Shoot, shoot and shoot until durability hit 0,
5. Good luck to remove the component :/

**Expected behavior**
We definitely should be able to grab weapons with 0 durability (can use it as fake weapon in certain situations)

**Comment by thelindat** [comment]
> We definitely should be able to grab weapons with 0 durability (can use it as fake weapon in certain situations)

One day, but it's hard enough trying to prevent abuse of the weapon system.

Resolved, you can remove components from weapons without equipping them.
