### ISSUE TITLE
Weapon holstered if we keep shooting with auto weapons

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#430]
**Describe the bug**
If you constantly shoot with a automatic weapon (like microsmg), and make your ammo clip empty, the weapon will be weirdly holstered. (by weirdly, I mean with a kind of broken animation)

**To Reproduce**
1. Give yourself a weapon `/giveitem me weapon_microsmg 1` (fastest for test imo),
2. Give yoursel some ammos `/giveitem me ammo-45 1000`,
3. Hold right click forever, you need to aim during the whole test without any interuption,
4. Hold left click forever, you need to shoot during the whole test without any interuption,
5. When your ammo count will hit 0, you'll probably experience the bug where weapon is weirdly holstered. If not, just keep holding both clicks while reloading to eat another ammo clip, do that few times and you'll get the bug for sure.

**Expected behavior**
Weapon should stay in our hands until we use the item from inventory or hotbar shortcut (or police arestation maybe)

**Comment by thelindat** [comment]
Should be fixed? Let me know how it goes.

**Comment by dolutattoo** [comment]
> Should be fixed? Let me know how it goes.

It's fixed boss!
