### ISSUE TITLE
container issue if he has metadata

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#431]
**Describe the bug**
If you put metadatas on a container item in shops, you'll get an issue while opening it.
This issue happened recently, not sure which commit is causing this...

**To Reproduce**
1. Add those line to the standard shops:
```lua
{ name = 'paperbag', price = 10 },
{ name = 'paperbag', price = 10, metadata = { label = 'bag test', image = 'water' }},
```
2. Restart the inventory, go to the shop, buy the `bag test` item you just created, the one with the water image,
3. Close the shop, open your inventory again,
4. See error: you lose nui focus, buttons are not working, etc..

**Video**
https://streamable.com/pkunme

**Comment by thelindat** [comment]
Err I just fixed a bug like this on drops, which likely affected containers; nothing to do with metadata.

**Comment by dolutattoo** [comment]
> Err I just fixed a bug like this on drops, which likely affected containers; nothing to do with metadata.
Okay it's fixed :)
