### ISSUE TITLE
animation broken when fast use

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#432]
**Describe the bug**
If you "fast use" a food item using `ALT+LMB`, the animation is broken

**To Reproduce**
1. open the inventory,
2. Do very fast a `ALT+LMB` on an item who animation & prop in `data/items.lua`

**Video**
Here is a video where I first use the item slowly, then the second time I'm doing it fast:
https://streamable.com/yip10u

**Comment by thelindat** [comment]
Resolved.
