### ISSUE TITLE
Item limit bug when giving items.

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#435]
**Describe the bug**
If you try to give an item with limit = 1, to someone who already have this item, it's giving it anyway. (sometimes it works, sometimes not)

**To Reproduce**
1. Add an item with `limit = 1`
2. Give yourself this item, and also to a friend
3. Then you will be able to give him your item.

**Expected behavior**
You only should be able to override item limit using the `/giveitem` command

**Additional context**
Looks like `Inventory.GetItemSlots(...)` sometimes return 0 for `totalCount` where it shouldn't

**Comment by dolutattoo** [comment]
Looks like the bug is more present with container having limit > 0 ? not sure tho

**Comment by dolutattoo** [comment]
Ok so, line 513 in `modules/inventory.server.lua` is causing the issue
```lua
if not metadata or table.matches(v.metadata, metadata) then
```

Because I have a container item, called 'bag', who have the limit set to 1, and can have different metadata (for ped component model and colors).
So if you give one of this bag to another player, who also have a bag but with different metadata, the bug is happening.

**Comment by thelindat** [comment]
table.matches is just that - the tables must have the same values in the same order. CanCarryItem is comparing the return for GetItemSlots compared to item.limit, but the giveItem event is checking for exact metadata.

The limit system doesn't pair well with the weight and metadata system since there's so many different variations to check.

**Comment by dolutattoo** [comment]
> table.matches is just that - the tables must have the same values in the same order. CanCarryItem is comparing the return for GetItemSlots compared to item.limit, but the giveItem event is checking for exact metadata.
> 
> The limit system doesn't pair well with the weight and metadata system since there's so many different variations to check.

Isnt it possible to first check if the item have a limit, then if yes, check if player can carry this amount of item, then if yes, compare the metadatas ?
Cause the limit is here to prevent people to have X item with the same name, don't really care about metadatas, right?

**Comment by thelindat** [comment]
```lua
function Inventory.GetItemSlots(inv, item, metadata)
	inv = Inventory(inv)
	local totalCount, slots, emptySlots = 0, {}, inv.slots
	for k, v in pairs(inv.items) do
		emptySlots -= 1
		if v.name == item.name then
			if metadata and v.metadata == nil then
				v.metadata = {}
			end
			if not metadata or item.limit or table.matches(v.metadata, metadata) then
				totalCount = totalCount + v.count
				slots[k] = v.count
			end
		end
	end
	return slots, totalCount, emptySlots
end
exports('GetItemSlots', Inventory.GetItemSlots)
```

Try that, I'm not pushing since I don't know if it will work.

**Comment by dolutattoo** [comment]
> ```lua
> function Inventory.GetItemSlots(inv, item, metadata)
> 	inv = Inventory(inv)
> 	local totalCount, slots, emptySlots = 0, {}, inv.slots
> 	for k, v in pairs(inv.items) do
> 		emptySlots -= 1
> 		if v.name == item.name then
> 			if metadata and v.metadata == nil then
> 				v.metadata = {}
> 			end
> 			if not metadata or item.limit or table.matches(v.metadata, metadata) then
> 				totalCount = totalCount + v.count
> 				slots[k] = v.count
> 			end
> 		end
> 	end
> 	return slots, totalCount, emptySlots
> end
> exports('GetItemSlots', Inventory.GetItemSlots)
> ```
> 
> Try that, I'm not pushing since I don't know if it will work.

That fixed it like a charm.
I think you can also replace
`totalCount = totalCount + v.count`
with 
`totalCount += v.count`
Just because it looks more sexy, right?
