### ISSUE TITLE
Weapon component overrides

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#436]
**Describe the bug**
You can put multiple weapon components of the same type on the same weapon.
It's not a major bug, but it can be a glitch for players since they can hide components into their weapons.

**To Reproduce**
1. Give yoursel a weapon who support components `/giveitem me weapon_smg 1`,
2. Give yoursel a component supported by this weapon `/giveitem me at_clip_extended_smg 1`,
3. Equip this component,
4. Give yoursel a component of the same type `/giveitem me at_clip_drum_smg 1`,
5. Equip this component too,
6. You have both component installed in your weapon, but only the last one is physically here.

**Expected behavior**
I see 2 solutions:
1. Prevent player to put a component of the same type and notify with an error
2. Remove the old component from the weapon, and put it back into the inventory (player should be able to carry it since a slot is now free, but they can also have different weight ...)

**Screenshots**
On this screenshot, I use the FR locale, and I edited weapons labels:
*viseur = visor*
*bouche = muzzle*
![image](https://user-images.githubusercontent.com/47056777/148281596-742970a4-c55b-4b2e-a675-f4c142f9c75c.png)

**Additional context**
If it's needed to sort components by type or anything, I can probably help with that, I'm just not sure how you wanna do it.

**Comment by thelindat** [comment]
I thought @LukeWasTakenn did something with this 😿
Afaik there's no natives, so we need to define conflicting components by slot (clips, muzzles, etc)

**Comment by LukeWasTakenn** [comment]
I'm pretty sure we did have something in place to prevent adding components of the same group type?

**Comment by LukeWasTakenn** [comment]
This should be fixed now, my solution for this probably isn't the best and I manually added the component types so hopefully I didn't overlook anything.

**Comment by dolutattoo** [comment]
> This should be fixed now, my solution for this probably isn't the best and I manually added the component types so hopefully I didn't overlook anything.

There is a bug since your fix:
You can use a component even if you're not wearing a weapon. Then the progress bar is showing, but the component not applied on anything, he's lost

**Comment by LukeWasTakenn** [comment]
Apparently this was an issue before my commit as well, what the hell happened to the check for `currentWeapon` lol

**Comment by LukeWasTakenn** [comment]
Should be good now, guess I'll leave it to @thelindat to refactor it later if he wants.
