### ISSUE TITLE
Confiscation receipt 

### ISSUE THREAD

**Issue by T3mpu5** [overextended/ox_inventory#437]
A receipt of goods confiscated by police when using the f6 search and confiscate option.

From Discord:
would need the export to have bool of whether to give a receipt or not (for stealing or confiscating) 
if true than add all items taken to an array
giveitem of 'receipt' with metadata of that array?

**Comment by LukeWasTakenn** [comment]
I feel like it would be a bit weird to receive a piece of paper that lists all your stolen items on it once someone is done searching/stealing from you.

Perhaps sending a notification on item remove is a better idea?

**Comment by T3mpu5** [comment]
I don't think it's needed for stealing and theft but more for the police job when they search and confiscate items... You then can be produced a receipt of items from the officer

**Comment by dolutattoo** [comment]
Imo, police should write the receipt themself when confiscating items.
Maybe a boolean for the notification could be usefull, if people wanna make a rob feature where the 'victim' shouldn't be able to see what is happening ?
Like if a player have rob experience, he can do it silently ? idk

**Comment by duckysuck** [comment]
From a gameplay perspective these would be ideal;
* When people are arrested a report should be made by the police including
what was confiscated (this should be deliberately prone to user error or
corruption)
* Victims should keep a proof of ownership.(this is handled in RP)
* When the police confiscate items from a thief they should go into a
locker.
* Locker items are then compared to items reported as stolen and the person
is contacted to visit the police station to confirm.
* Also applies to items stolen from cars and houses.

Scope creep (aligned to what I'd like to bring to the BN1 RP city)
* If proof of ownership cannot be made then the items are auctioned. *Only
items worth over £100 are worthy.*
* Car paperwork to prove ownership of car.
* Repeat driving violations result in a users driving licence being removed
from them (handled in RP)
* Cars are confiscated from players that have repeat traffic violations and
car is auctioned off.

**Comment by dolutattoo** [comment]
@duckysuck This is something that people need to do themself, nothing related this inventory resource in my opinion.
If officers wants to write shit on any document, they should be able to.
They should sign the receipt so someone can check it later, and they shouldn't do that alone.

**Comment by T3mpu5** [comment]
The trouble we found when police were trusted to do this themselves was they would be taking money and other items from people and then denying it... And without some form of audit trail we couldn't prove otherwise... We then added notifications to tell them every item that was confiscated and started to pull people up on it..

This is why I would like it to be automated and not be able to be manipulated by a user.
Of course though it is your script and you can say no xD

**Comment by duckysuck** [comment]
that sounds like corrupt police. aka roleplay :)

**Comment by thelindat** [comment]
Notification changes will come along with some changes to how data is updated (I want to count items without iterating _every_ time). Something like a confiscation receipt is fucking bizarre 🤨
