### ISSUE TITLE
Weapons Deplete Way Too Fast, No Matter What

### ISSUE THREAD

**Issue by ProjectRogueRP** [overextended/ox_inventory#438]
**Describe the bug**
I have set pistols to be at durability = 0.05, however, the weapon degrades EVERY SINGLE BULLET. For instance, I shoot 1 bullet, and the gun will be at 99. I shoot another bullet. Will be at 98. I cannot seem to fix this issue no matter what value I place. It does not do anything different!
**To Reproduce**
SImple place the durability on anything in weapons.lua. 1 bullet = 1 durability.

**Expected behavior**
To be a percentage of durability to be taken off, not 1 per bullet

**Screenshots**

**Additional context**

**Comment by ProjectRogueRP** [comment]
To add more context as well. I have noticed if I spam the trigger, and shoot, its fine. Or an automatic weapon, its fine. However, If I use a pistol, a shoot 1, wait 2 second, shoot again, wait 2 seconds, and shoot and repeat this. Its 1 durability per bullet if shot this way. If you spam shoot, it will be fine. Single shooting, is not.

**Comment by ProjectRogueRP** [comment]
Adding more, I turned the values to 0.00, and the durablity completely stopped. So thats working. It just seems the single shots from the pistols or another weapon that can single tap, will always degrade 1 every bullet

**Comment by thelindat** [comment]
Known issue.

**Comment by thelindat** [comment]
Should be resolved.
