### ISSUE TITLE
nil value local vehicle

### ISSUE THREAD

**Issue by xrtw** [overextended/ox_inventory#441]
**Describe the bug**
just saw an error in console

**To Reproduce**

**Expected behavior**

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
https://i.gyazo.com/f0b927c4b57ec9994671e63632c91b3e.png

**Additional context**

**Comment by LukeWasTakenn** [comment]
That's cool that you saw the error in the console and all but how are we expected to fix it if we don't even know how to preproduce the issue to get the error?

**Comment by xrtw** [comment]
ok
