### ISSUE TITLE
PlayerList and Weapon hide

### ISSUE THREAD

**Issue by badfantomass** [overextended/ox_inventory#444]
I'm posting some of my suggestions here after testing the server.
1) No player list is shown when giving an item. This is a big problem you give someone by mistake and he will not logically return it to you: D
2) When you run out of ammo the weapon automatically hide. 

**This will probably be everything for now. I don't know if you have any plans for this or not.**

**Comment by badfantomass** [comment]
2. Fixed in the new version

**Comment by LukeWasTakenn** [comment]
We discussed player lists when giving an item before and decided it's not something we want to include, at least yet.

It's difficult to not make it look weird having a dialog suddenly pop up and inventory close when you drag or click give.

**Comment by pstomi** [comment]
> We discussed player lists when giving an item before and decided it's not something we want to include, at least yet.
> 
> It's difficult to not make it look weird having a dialog suddenly pop up and inventory close when you drag or click give.

Player lists is definitely something what you need to consider, lot of people has problem with that... Many players on my server wants to remove the inventory because they have problem with giving item.

**Comment by thelindat** [comment]
> 
> Player lists is definitely something what you need to consider, lot of people has problem with that... Many players on my server wants to remove the inventory because they have problem with giving item.

I don’t particularly care what your players want, I refuse to add an ugly give box. When you want to give somebody something, you stand next to them, look at them, and hand it over. It’s not rocket science.

**Comment by pstomi** [comment]
> > Player lists is definitely something what you need to consider, lot of people has problem with that... Many players on my server wants to remove the inventory because they have problem with giving item.
> 
> I don’t particularly care what your players want, I refuse to add an ugly give box. When you want to give somebody something, you stand next to them, look at them, and hand it over. It’s not rocket science.

I can not imagine, how this can be ugly to you:

![image](https://user-images.githubusercontent.com/5259996/150701821-34bb92d6-afed-4667-b708-4d09179f45fe.png)

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/150701937-f022b8a4-e244-4304-9f6f-bb56d500c640.png)

![image](https://user-images.githubusercontent.com/65407488/150701943-37298df3-8e5d-463f-a7de-dc407d1914d6.png)


Guess I'm removing give, as promised.
