### ISSUE TITLE
No notification when inventory full

### ISSUE THREAD

**Issue by dernathan** [overextended/ox_inventory#445]
Players dont receive a notification that they are overburdened when picking up items from the ground.
They cant pickup the item, its just about a notification that they cant.

**Comment by thelindat** [comment]
I always forget the average FiveM player is braindead and can't tell that trying to pick up 20kg of shit when they have an available capacity of 4kg means it will fail.

It'll be added soon.

**Comment by GeerdoDaGr8** [comment]
Another one that i think people will be confused on is trying to use an item while having a weapon out

**Comment by frazz1234** [comment]
What he could be nice is , is like Skyrim.

whne your inventory is full you walk very very slow 🤷‍♂️ He could Ben another way to work when a player have a heavy thing to transport from the a point to b point !

**Comment by RedAlex** [comment]
In file ox_inventory/modules/bridge/client.lua
I have add this to slowdown the player and show a notification.
Feel free to use and adapt it to your server
```
local sleep = 500
Citizen.CreateThread(function() 
	while PlayerData and shared do
		Wait(sleep)
		if PlayerData.weight and shared.playerweight then
			if PlayerData.weight > shared.playerweight then
				if sleep == 500 then
					exports["skeexsNotify"]:TriggerNotification({
						['type'] = types or "error",
						['message'] = 'Votre poid vous ralentie!!!'
					})
				end
				sleep = 5
				ratio = shared.playerweight/(PlayerData.weight+100000)
				SetPedMoveRateOverride(PlayerPedId(), ratio)
				DisableControlAction(0, 22, true) -- Jump
			else
				sleep = 500
			end
		end
	end
end)
```
