### ISSUE TITLE
bug(dumpsters): server loop hungs

### ISSUE THREAD

**Issue by GRZ-D3V** [overextended/ox_inventory#446]
**Describe the bug**
When two players try to open the benne (with the randoms loots), the server seems to crash. See image [here.](https://imgur.com/a/gHDiW1S)

**To Reproduce**
1. Go to pinkage motel with two players (_or any other place with dumpsters_)
2. Click on open second inventory for the dumpsters
4. Error happen: server crash

**Expected behavior**
To be able to open the inventory following the opening of the trash cans without the server crashing.

**Screenshots**
See image [here.](https://imgur.com/a/gHDiW1S)

**Comment by GRZ-D3V** [comment]
Note that no modification on the core + inventory has been made.

**Comment by Sojobo** [comment]
I'm having the same issue when trying to open up dumpsters.
`[              server] Error: Loop svMain seems hung! (last checkin 45 seconds ago)
[              server] Warning: svMain watchdog stack: ox_inventory: event __cb_ox_inventory:openInventory <- root
[              server] Uploaded a live hang dump to the CitizenFX crash reporting service. The report ID is 636d54a3-84c4-43c6-8988-86d3b5a2602b.
[              server] Error: Loop svMain STILL seems hung! (last checkin 90 seconds ago)
[              server] Warning: svMain watchdog stack: ox_inventory: event __cb_ox_inventory:openInventory <- root
[              server] Uploaded a live hang dump to the CitizenFX crash reporting service. The report ID is 864381e7-963d-42b0-bb82-a7a076f15f1e.`

**Comment by thelindat** [comment]
Refer to https://github.com/overextended/ox_inventory/commit/3681a98efa686af58a1822a27bb537c07bdc5a16 and see if it made a difference (entity was duplicating and may have been causing issues on larger servers).

Otherwise, I'm unable to reproduce a server hitch with just 2 clients and the issue is something else.

**Comment by Sojobo** [comment]
I've tried applying those changes but I'm still getting the issue with just 1 client on local. I can't seem to open up any dumpsters at all actually, not sure why it seems to completely lock up the entire server.

**Comment by thelindat** [comment]
OneSync Legacy or Infinity?

**Comment by Sojobo** [comment]
Infinity
FX 5181
b2372

I've actually fixed it by removing the ox_inventory_loot convars and using the default lua ones instead - hope that helps you. The main difference I notice is that in the convars it's using square brackets for an array whereas in the lua it's curly brackets like an object.. Not sure if that's just how convars work or whether that's an actual issue.

**Comment by thelindat** [comment]
Convars use JSON. Is there something screwy in your convar, perhaps, causing the crash? Post what you were using.

**Comment by Sojobo** [comment]
I was using the default ones provided;

`set ox_inventory_loot {
    "vehicle": [
        ["water", 1, 1],
        ["money", 1, 50],
        ["money", 200, 400, 5],
        ["bandage", 1, 1]
    ],

    "dumpster": [
        ["money", 1, 10],
        ["burger", 1, 1]
    ]
}`

**Comment by thelindat** [comment]
Resolved.
