### ISSUE TITLE
Item consumption

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#447]
**Describe the bug**
Items get consumed when usage is cancelled?

**To Reproduce**
1. Use `water` or `burger` for an example.
2. Half-way through usage press `X`, and cancel it.
3. Item gets depleted. 

**Expected behavior**
Don't consume the item, and keep it.

**Additional context**
- **Game Version:** 5181
- **Client:** Production
- **Inventory Build:** v2.1.7

**Comment by thelindat** [comment]
Resolved.
