### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by sickderp** [overextended/ox_inventory#448]
**Describe the bug**
These repro steps crash the inventory

**To Reproduce**
1. Clear your inventory
2. Give yourself a `weapon_assaultrifle`
3. Give yourself some `ammo-rifle2`
4. Press 1 and fire some shots
5. Clear your inventory (`clearinv`)
6. Give yourself some `ammo-rifle2` (yes just ammo without rifle)
7. Press 1 and you shoud get 
```lua
SCRIPT ERROR: @ox_inventory/server.lua:468: attempt to compare number with nil
```

**Comment by thelindat** [comment]
Resolved.
