### ISSUE TITLE
Close = true not working with event on item

### ISSUE THREAD

**Issue by GeerdoDaGr8** [overextended/ox_inventory#450]
When adding the client event to an item *close = true* doesnt do anything anymore and you have to put a close inventory event in the clioent event you are triggereing to close the inventory on use.
```lua
['identification'] = {
		label = 'ID Card',
		weight = 150,
		stack = false,
		close = true,
		description = 'ID Card. Not a License.',
		client = {
            consume = 0,
            event = "qidentification:identification",
        }
	},
```

**Comment by baguscodestudio** [comment]
Just made a [pull request](https://github.com/overextended/ox_inventory/pull/451)

**Comment by thelindat** [comment]
Just to clarify, the event being triggered _must_ use the item callback wrapper in some way (exports.ox_inventory:useItem) to correctly utilise things like item consumption, item validation, etc. Also, events are deprecated anyway.

Whoever updated qidentification for ox_inventory hasn't updated the items appropriately.
