### ISSUE TITLE
giveitem permissions

### ISSUE THREAD

**Issue by WooAf** [overextended/ox_inventory#459]
**Is your feature request related to a problem? Please describe.**
Not at all

**Describe the solution you'd like**
Would like to be able to choice which group can give specific items

**Describe alternatives you've considered**

```
['black_money'] = {
        label = 'Argent sale',
        permissiontogive = 'admin'
}
```
**Additional context**
Kiss to Liden

**Comment by thelindat** [comment]
This seems excessive to me; if you trust somebody to use commands and give items, why not just allow any items? Otherwise they shouldn't have an admin role or such in the first place.

**Comment by WooAf** [comment]
> This seems excessive to me; if you trust somebody to use commands and give items, why not just allow any items? Otherwise they shouldn't have an admin role or such in the first place.

I'm allowing my moderator to give items but only admin can give weapons, money and black_money
