### ISSUE TITLE
Costumizable Markers and HelpNotifications

### ISSUE THREAD

**Issue by ItzTrivial** [overextended/ox_inventory#461]
I modified lindens inv so I can add HelpNotifications when stepping on a marker or even change the color and id of the marker, so I wanted to ask if there could be a possibility to change the id and the color and the HelpNotification of the stashes/shops... if wanted in the config. 

It would really help me, since Im not using qtarget and some Players need advanced information.

Thanks up front.
Trivial

**Comment by thelindat** [comment]
I'm not going to implement this after all, however the new points API should make this fairly trivial if you want to do it yourself.
