### ISSUE TITLE
stash issue

### ISSUE THREAD

**Issue by AamiRobin** [overextended/ox_inventory#462]
**Describe the bug**
trying to make a stash in my house script and it does not allow me to make it.

this one is for testing 
https://i.imgur.com/j3Qz54K.png

and this one for house 
![image](https://user-images.githubusercontent.com/22963668/149596270-3a43354b-022c-4224-845f-7ffa2eb45eae.png)
https://i.imgur.com/CmZMeru.png

**Comment by thelindat** [comment]
I can't tell what you're doing with any of this, or what error you're getting, from a screenshot. Upsetting as hell query though.

**Comment by AamiRobin** [comment]
that is the think it not showing me any error. i am exporting this to make a stash but not a stash created in the database and no error.

**Comment by AamiRobin** [comment]
TriggerEvent('ox_inventory:openInventory', 'stash', 'allhouse'..InsideHouse.Id)

work for open stash thank you for your time.
