### ISSUE TITLE
Cannot open trunk of Pounder truck

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#463]
**Describe the bug**
We cannot access to the trunk of the vehicle `pounder` from truck class.

**To Reproduce**
1. spawn a pounder
2. try to access the trunk (position is usually like the screenshot)
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/47056777/149607770-c3f2bdc6-c4c6-4dde-916c-40518662305f.png)

**Additional context**
The trunk was working with linden_inventory

**Comment by dolutattoo** [comment]
Looks like the script is checking for 'boot' bone name, but if it's not found then you check for 'platelight'.
But it looks like the platelight bone doesnt exists on this vehicle neither

**Comment by dolutattoo** [comment]
in linden_inventory, the second option was `wheel_rr` and not `platelight`

**Comment by dolutattoo** [comment]
Could be nice to have an option in `Vehicles.Storage` to put the boneIndex that we want to check.
I personnally have a dev tool to display the bone names and it could be very easy for people to overrides this value for specific vehicles.
Can use xyz coords too, idk

**Comment by dolutattoo** [comment]
A better idea would be to do some maths with the bounding box of the vehicle, the heading and the world coordinates. But idk how hard/performance hungry that would be

**Comment by LukeWasTakenn** [comment]
Fixed in a7b862a47589590ffe816e6e3755c4df224b8d4e
