### ISSUE TITLE
Client option "add" returns wrong count in first slot

### ISSUE THREAD

**Issue by antond15** [overextended/ox_inventory#468]
**Describe the bug**
Moving an item to the first slot passes wrong item count to the **`add`** function.

**To Reproduce**
1. Add debug prints from **Additional context** part ⤵
2. Move the item from any slot to the first slot
3. See it passed different count

**Expected behavior**
Alaway pass the actual item count.

**Screenshots**
https://streamable.com/7iufad

**Additional context**
To see the prints, add this to your item data in **`data/items.lua`**.
```lua
client = {
	add = function(count, added)
		print('Added item', count, added)
	end,
	remove = function()
		print('Removed item')
	end
}
```

**Comment by thelindat** [comment]
Going to need to figure out a better way to handle this stuff; if I don't get it done within a few days I'll probably disable it until v2.2.1

Are you or @dolutattoo using the add/remove callbacks for anything in particular? The updateInventory event should be fine, still.

**Comment by thelindat** [comment]
@antond15 @dolutattoo This _should_ work now; add and remove functions will receive the total count (rather than total and amount added/removed).

Let me know if I missed something again 😢

**Comment by antond15** [comment]
It works well!
