### ISSUE TITLE
inventory always full

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#471]
**Describe the bug**
The inventory is always shown as full even though it doesn't have 20kg. I check it by xPlayer.canCarryItem.

**To Reproduce**
1. use a script for checking the inventory with canCarryItem
2. check it ingame
3. See error (it shows always inventory full)

**Expected behavior**
Even if its deprecated it should work like it got told in your docs.

**Additional context**
How I should change this to the new export?
local xPlayer = ESX.GetPlayerFromId(source)
    for item, random in pairs(Config.loot or {}) do
    	local amount = math.random(random.min, random.max)
    	local chance = math.random(1, 99)
    	if chance < random.chance then
			if ox_inventory:CanCarryItem(xPlayer, item, amount) then
			-- if xPlayer.canCarryItem(item, amount) then
    		-- xPlayer.addInventoryItem(item, amount)
				ox_inventory:AddItem(xPlayer, item, amount)
			else
				TriggerClientEvent("esx:showNotification", xPlayer.source, (Config.FullInventoryText)) 
			end
    	end	
    end
    
I did this code change but it doesnt work for me. I simply get this error code inside the console:
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:514: bad argument #1 to 'for iterator' (table expected, got nil)
[ script:ox_inventory] > GetItemSlots (@ox_inventory/modules/inventory/server.lua:514)
[ script:ox_inventory] > ref (@ox_inventory/modules/inventory/server.lua:601)
[ script:ox_inventory] > handler (@Bigyzis_LootBagsV2/server/main.lua:37)
[script:Bigyzis_LootB] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:841: An error occurred while calling export CanCarryItem of resource ox_inventory
[script:Bigyzis_LootB] nil
[script:Bigyzis_LootB] (nil stack trace)

**Comment by antond15** [comment]
Use [code blocks](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) next time, please.

The first argument must be inventory id. You are passing whole xPlayer object.
So simply change `xPlayer` to `xPlayer.source`.
```lua
ox_inventory:CanCarryItem(xPlayer.source, item, amount)
ox_inventory:AddItem(xPlayer.source, item, amount)
```

**Comment by maxcamorra** [comment]
Oh ok, thank you :)

But what about the always full problem? Will the export fix this problem?

**Comment by antond15** [comment]
> Oh ok, thank you :)
> 
> But what about the always full problem? Will the export fix this problem?

Try it. Or maybe your item weights too much.

**Comment by maxcamorra** [comment]
I have all items on 1 :D so 1g

**Comment by maxcamorra** [comment]
> > But what about the always full problem? Will the export fix this problem?
> 
> Try it. Or maybe your item weights too much.

I tested it now with the new export and it still doesn't work, it still tells me Inventory full although i only have 8.51/30kg

**Comment by maxcamorra** [comment]
Some items work but some not and the weight is everywhere perfect. The max weight of item is the heavy sniper with 14000g but still it should work because I only have 8kg with me

**Comment by thelindat** [comment]
I need to know what _some_ items are, if there's a specific thing breaking here.

**Comment by maxcamorra** [comment]
> I need to know what _some_ items are, if there's a specific thing breaking here.

Im still in testing and find out why it happens but it seems it works now afaik
