### ISSUE TITLE
Being able to still use broken weapons

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#472]
**Is your feature request related to a problem? Please describe.**
Imagine being in a fight and your weapon breaks, you get instantly unarmed.

**Describe the solution you'd like**
It would be nice to be still having the weapon in the hands but only use it as a melee weapon for hitting.

**Comment by thelindat** [comment]
Gets complicated dealing with ammo because default gta weapons. It’s. it that I don’t want this to be possible; rather it’s complicated and I have to experiment for hours and probably rewrite entire durability system so this doesn’t break everything.

**Comment by N-fire** [comment]
what about disabling left click when a player is using a weapon with no durability ?

**Comment by thelindat** [comment]
Can equip it now, though hitting is disabled. Will probably look into it more later but cbf now.
