### ISSUE TITLE
Very immature creator

### ISSUE THREAD

**Issue by mrleduck** [overextended/ox_inventory#473]
you can close this all you want but people in your server are asking for help and you simply insult them while they are talking with respect and you then ban them what a sad way to thank people for showing interest in your projects

**Comment by thelindat** [comment]
I can't tell which incredible person you are. The one that complained because your four year old copy of ESX isn't compatible, or the one incapable of reading the installation guide that tells you about the dependencies?

**Comment by mrleduck** [comment]
I wasnt showing respect? i simply stated that the issue was on my end and that i even wanted to upgrade my current older version of esx to be able to use your resource and that it was a bummer that i indeeed missed the info that it didnt support v1. not on any front did i attempt or did any insult to you all i did was show interest in your project as i was suprised by your reaction and the ban
