### ISSUE TITLE
Police Armory is not showing up.

### ISSUE THREAD

**Issue by xrb936** [overextended/ox_inventory#474]
I just updated the script to the latest release, the armory is not showing up at the default position. No notification, nothing shows up when pressing F2.

**Comment by LukeWasTakenn** [comment]
It works fine

![image](https://user-images.githubusercontent.com/39926192/150191595-55bad5c8-85ff-432e-9ccc-733493fa70ea.png)

**Comment by Fleevo73** [comment]
Update to the latest everything, there shouldn't be any issues. Also check your config for ox_inventory and make sure support for qtarget is disabled if you want a blip. IF not its accessible through your 3rd eye.

**Comment by xrb936** [comment]
> 

It is not working, even though I used the ox_base script to create a new server without changing anything. I am not using qtarget.

**Comment by xrb936** [comment]
I assume it is caused by something with the job name or type because all other shops work fine, but I am not sure. I am using the latest esx_legacy from here: https://github.com/overextended/esx-legacy

**Comment by xrb936** [comment]
> 

OK I got it. I changed line 109 in /data/shops.lua from `jobs = shared.police,` to `jobs = { ['police'] = 0 },`, it works now.
