### ISSUE TITLE
Define metadata to display in toolip

### ISSUE THREAD

**Issue by JiminyKroket** [overextended/ox_inventory#475]
Added item to player inventory with metadata and no information displayed in the inventory when hovering over the item.

**Comment by LukeWasTakenn** [comment]
Only certain metadata will be display in the tooltip, type, description, durability, ammo count, serial and weapon components

**Comment by LukeWasTakenn** [comment]
This was added in commit 29a69fcd88bea2e64f4df895ac37accf687972fb.
