### ISSUE TITLE
Cannot give if any entity is closer than the player

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#476]
**Describe the bug**
If you try to give anything to another player (on foot, not in a vehicle), but any another entity is in the middle, you won't be able to give anything.

**To Reproduce**
1. You need another player to test it,
2. Spawn a motorcycle `/car manchez`,
3. Place you & your friend on both sides of the motorcycle (c.f. screenshot),
4. You won't be able to give anything.

**Expected behavior**
You should be able to give to the closest ped if he's not too far away, even if an entity is blocking. (I don't know how to prevent giving through wall though)

**Screenshots**
![image](https://user-images.githubusercontent.com/47056777/150048313-22a0aee1-be42-483c-ad72-d6a180c793ca.png)

**Additional context**
By looking at `RegisterNUICallback('giveItem', ...)`, I seen that you're using `Utils.Raycast()` to detect the target.
Problem is, this function is returning any type of entity, and in the giveitem callback, nothing happen if the detected entity is not a ped.

If this is intended, there should be at least a notify error saying "Something is blocking an you cannot give" or something similar.

**Comment by thelindat** [comment]
People bitched that closest entity is random so I set a raycast; those same people bitch that it doesn’t work at all.

**Comment by dolutattoo** [comment]
> People bitched that closest entity is random so I set a raycast; those same people bitch that it doesn’t work at all.

Giveitem is quite weird in any case in my opinion, because a player should be able to accept/refuse the item.
Anyway, this is something my players a reporting everydays, because in a gameplay perspective, it looks like the inventory sometimes don't give, and they don't really understand why, unless they figure it out 200 tries later...

**Comment by antond15** [comment]
I really like this feature which was posted on OX Discord by Jonneis#5607.
https://i.gyazo.com/ead3aa28b3e42149ee55f1555564c5e8.mp4

**Comment by pstomi** [comment]
Same I have lot of problem with raycast. Especially when multiple people is around me.

I agree with @antond15 

This solution would be great too (this is edited ox_inventory): https://media.discordapp.net/attachments/860852359176650752/934839694154407966/unknown.png

So it shows mugshots with ID at the bottom and you can drag and drop the item to the player you choose. That would be the most cleanest solution.

**Comment by dolutattoo** [comment]
> > That would be the most cleanest solution.
> 
> No it wouldn't...?
> 
> The cleanest solution is the current solution, where you just have to look at the player you want to give the item to and not have to bother with clicking someone's face every time you want to give them something.

Yes, but currently it doesn't work properly, players sometimes doesn't understand how to give items, just because an entity is between them. (example: impossible to give a beer to a customer as bartender, because there is a shit ton of props on top of the bar.)

Cleanest solution would be the same as right now, but with a raycast who only return players, not the first entity.

**Comment by LukeWasTakenn** [comment]
Should be resolved now.
