### ISSUE TITLE
(small bug) Error when give item and no free slots

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#477]
**Describe the bug**
If you use AddItem (maybe other ways to reproduce) while not having any free slot in your inventory,
`function Inventory.SetSlot(inv, item, count, metadata, slot)` will cause an error because `slot` is `nil`

**To Reproduce**
1. Fill your inventory,
2. Give yourself another item who won't stack on any other one,
3. See error

**Expected behavior**
We should have a notification who say "you don't have enough space in your inventory"

**Additional context**
This shouldn't happen in a gameplay context cause people should use `Inventory.CanCarryItem` pretty much everywhere they use `Inventory.AddItem`. But when you give an item as admin, you don't want to verify if you can carry or not, you're maybe in a rush where you need to help many people, etc.. Anyway, there should be a clean notification :)

**Comment by RedAlex** [comment]
Fix with https://github.com/overextended/ox_inventory/pull/616
