### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by BalloutJay** [overextended/ox_inventory#479]
This is the errors im getting on the console pls help.
![Screenshot 2022-01-19 145139](https://user-images.githubusercontent.com/98054918/150203837-b0400cbb-2ad5-42b7-8ef2-5b0e2f8c6ff4.png)

**Comment by BalloutJay** [comment]
[script:ox_inventory-] Error loading script modules/init.lua in resource ox_inventory-2.1.9: @ox_inventory-2.1.9/modules/init.lua:36: 
[script:ox_inventory-] [error] Unable to locate ox_inventory/web/build, refer to the documentation or download a release build.
[script:ox_inventory-] stack traceback:
[script:ox_inventory-]  [C]: in function 'error'
[script:ox_inventory-]  @ox_inventory-2.1.9/modules/init.lua:4: in field 'error'
[script:ox_inventory-]  @ox_inventory-2.1.9/modules/init.lua:36: in main chunk
[    c-scripting-core] Failed to load script modules/init.lua.
[script:ox_inventory-] Error loading script modules/player/server.lua in resource ox_inventory-2.1.9: @ox_inventory-2.1.9/modules/player/server.lua:6: 
[script:ox_inventory-] [error] Ox Inventory requires a modified version of ESX, refer to the documentation.
[script:ox_inventory-] stack traceback:
[script:ox_inventory-]  [C]: in function 'error'
[script:ox_inventory-]  @ox_inventory-2.1.9/modules/init.lua:4: in field 'error'
[script:ox_inventory-]  @ox_inventory-2.1.9/modules/player/server.lua:6: in main chunk

**Comment by LukeWasTakenn** [comment]
Read the error messages.
