### ISSUE TITLE
Press F2 Inventory Not Popping UP

### ISSUE THREAD

**Issue by BalloutJay** [overextended/ox_inventory#480]
When i press F2 inventory not even popping up

**Comment by LukeWasTakenn** [comment]
Download release not source code, or build the UI yourself, there's a guide for it in the docs.

**Comment by BalloutJay** [comment]
> Download release not source code, or build the UI yourself, there's a guide for it in the docs.

can you send me the link for resource pls

**Comment by BalloutJay** [comment]
release*

**Comment by Fleevo73** [comment]
https://github.com/overextended/ox_inventory/releases/tag/v2.1.9 @BalloutJay
