### ISSUE TITLE
make larger player inventory with bags/paperbag

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#482]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a larger inventory if you use a bag item.

**Describe the solution you'd like**
So basically you use the bag item and it appears on the playerped at the same moment you get a larger inventory because you are wearing a bag.

**Comment by thelindat** [comment]
Not a trivial matter at all. The only thing I'm okay with doing would be increasing max weight when holding a container.

**Comment by maxcamorra** [comment]
> Not a trivial matter at all. The only thing I'm okay with doing would be increasing max weight when holding a container.

So how this would work?

**Comment by cod3engine** [comment]
there is a script (gmx_backpack), which gives you the possibility to change the maximum weight according to the type of bag you wear (3 different items with the addition of 3 different weights. Sorry for the translation.

**Comment by RedAlex** [comment]
Can be done with https://github.com/overextended/ox_inventory/pull/613

**Comment by maxcamorra** [comment]
> Can be done with #613

Tested it out but not working, when I try to put an item inside it just jumps back to my inventory.
