### ISSUE TITLE
Job Setting (Disconnect)

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#483]
**Describe the bug**
When you set the job on disconnect of a player it returns an error with the inventory.

**To Reproduce**
1. Use `esx:playerDropped` event and set their job to i.e: `offpolice`.
```lua
AddEventHandler('esx:playerDropped', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    if not xPlayer then return end

    local job = xPlayer.job.name
    local grade = xPlayer.job.grade

    if job == 'police' or job == 'ambulance' then
        xPlayer.setJob('off' ..job, grade)
    end
end)
```
2. Quit the game when you have your job as `police`.
3. Bingo, error;
```lua
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:771: attempt to index a nil value (field '?')
[ script:ox_inventory] > handler (@ox_inventory/modules/inventory/server.lua:771)
[ script:ox_inventory] > ref (@es_extended/server/classes/player.lua:266)
[ script:ox_inventory] > Logout (@es_extended/server/main.lua:246)
[ script:ox_inventory] > handler (@es_extended/server/main.lua:258)
[ script:ox_inventory] > DropPlayer (DropPlayer.lua:2)
```

**Additional context**
- **Game Version:** 5240
- **Client:** Production
- **Inventory Build:** v2.1.9

**Comment by thelindat** [comment]
Drop player is drop player.. why are you setting xPlayer job lmao

**Comment by DogsGoBark** [comment]
So, I should set it on spawn the resetting duty state?

**Comment by thelindat** [comment]
Why don't you just set a state for when the player is on/off duty, rather then that weird offpolice stuff?
