### ISSUE TITLE
Qtarget configurability 

### ISSUE THREAD

**Issue by Vumono** [overextended/ox_inventory#501]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

It would be lovely to have an option to use qtarget per individual stash, shop, storage. Instead of all on or all off

**Comment by dolutattoo** [comment]
This is already the case :) You actually have a lot of way to manage stash access.
Easiest one is probably to add you stashes into `data/stashes.lua`. You'll see a target key where you can put the target values (or not).
