### ISSUE TITLE
Blip names

### ISSUE THREAD

**Issue by Fanttomas** [overextended/ox_inventory#502]
It would be useful to be able to put a different name on the blip at the shop than on qtarget :D

Example:
		name = 'Obchody',
		blip = {
			id = 59, colour = 69, scale = 0.8, name = 'Some shit'
		},

**Comment by dolutattoo** [comment]
This is already the name of the blip:
![image](https://user-images.githubusercontent.com/47056777/151565914-03017c2d-026c-47c2-8655-1dd4120a495b.png)

**Comment by Fanttomas** [comment]
I know that ... But if you put the name there with the font, it will also appear with qtarget: D

**Comment by antond15** [comment]
You can add `label` option to replace the default text from locales.
```lua
General = {
	name = 'Shop',
	label = 'Open this sick shop!',
	blip = {
		id = 59, colour = 69, scale = 0.8
	}, inventory = {
		{ name = 'burger', price = 10 },
		{ name = 'water', price = 10 },
		...
```
