### ISSUE TITLE
Better loging

### ISSUE THREAD

**Issue by czsquizer** [overextended/ox_inventory#505]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A better way of sending values that are beeing logged. Because now I get a sentence string "Player has transfered 1x bread to ...", and it is impossible to split those logs into multiple Discord channels. If I received multiple values, such as: Player, actoin, target, item, amount. ..., it would be easier to create a Discord log.

**Additional context**
I have no dificulties creating the log, but we want to split those messages depending on the action to multiple Discord channels to make it easier to read etc. ... Because with the datadog, it is kinda complicated to give access to all the members of our staff team.

**Comment by thelindat** [comment]
How many times do I need to tell people that Discord is _not_ a logging application?

>  it is kinda complicated to give access to all the members of our staff team

All you need to do is add a user via email.
