### ISSUE TITLE
Trunks not working on certain vehicles

### ISSUE THREAD

**Issue by JustDeltaAU** [overextended/ox_inventory#507]
**Describe the bug**
Rumpo, Youga and Speedo vans (unsure if more) are unable to have trunk space. 

**To Reproduce**
1. Find/Spawn one of the vehicles listed above, walk to the rear of the vehicle and use your secondary inventory key
2. Cry because your players are whinging that it's not working

**Expected behavior**
When you press K at the rear of the vehicle a trunk should be opened as a secondary inventory.

**Additional context**
Glovebox works fine, even adding the models in the vehicles.lua file doesn't help.

**Comment by thelindat** [comment]
No issue here.

![image](https://user-images.githubusercontent.com/65407488/152099351-9aefa498-c26d-41e0-8475-fd006c46cbe5.png)
![image](https://user-images.githubusercontent.com/65407488/152099385-cba115f5-5271-433a-a12a-6114a4f74446.png)
![image](https://user-images.githubusercontent.com/65407488/152099421-8993dd84-469c-41d0-a074-0f40ff34d453.png)

**Comment by thelindat** [comment]
Is this still an issue for you, and does it happen with a default install? Just to note, I haven't changed anything.. never reproduced.
