### ISSUE TITLE
Weapons problem

### ISSUE THREAD

**Issue by StableBarcodeDev** [overextended/ox_inventory#509]
**Describe the bug**
weapons equipped & holstered  without really equipped
 
**To Reproduce**
1. /additem 1 weapon_pistol 1 
2.  Pressed the Number  of slot ( For example the pistol is at slot number 1 )
3. The weapon appear in the hand and after one second it goes back 
4. No Errors at  F8 No errors at  TxAdmin console 

**Expected behavior**
The weapons should stay at hand 

**Screenshots**
![Screenshot_49](https://user-images.githubusercontent.com/92280829/151991651-1b575791-b3cd-4129-b632-8b8db4548440.png)

**Additional context**
I install custom weapons. i remove it and the problem still appears

**Comment by thelindat** [comment]
You have something else causing this.
