### ISSUE TITLE
Possibly a bug, but possibly an enhancement.

### ISSUE THREAD

**Issue by TlYPN** [overextended/ox_inventory#510]
**Describe the bug**
There is no way to degrade weapons that dont actually use "ammo"

**To Reproduce**
There is no way to reproduce, aside that my paintball guns (in my city) dont actually degrade as they "dont" actually use ammo

**Expected behavior**
Have a way to degrade them naturally

**Screenshots**
i can provide screenshots, but all i could provide would be a video of me using it without it degrading

**Additional context**

**Comment by thelindat** [comment]
How do your paintball guns work, exactly? Durability changes by shooting, which one normally does with a gun.

**Comment by TlYPN** [comment]
So the basically act as a "weapon_stungun", i noticed stun guns also dont degrade, so im assuming this is intentional! now im curious if i can keep the stunguns from not degrading while still degrading the Paintball gun
