### ISSUE TITLE
Give Item to show players around

### ISSUE THREAD

**Issue by DistrictZion** [overextended/ox_inventory#512]
As much as I like the raycast method of giving item, the players in our server are very used to selecting the player to give. Can you give us a method how to implement giving item to a specific player by selection from a menu?

**Comment by LukeWasTakenn** [comment]
Discussed in about 20 other similar Issues.

**Comment by DistrictZion** [comment]
I've been looking for a similar thread since 3 days but I haven't found an actual response of how to implement it. That is why I asked. Thanks for the reply though. I'll try and find it.
