### ISSUE TITLE
Problem adding ox_inventory

### ISSUE THREAD

**Issue by matikh1** [overextended/ox_inventory#513]
**Is your feature request related to a problem? Please describe.**
Hello, I wanted to ask about a problem I have. I need to add ox_inventory to my loaf_housing storage, how can I do it?
I've been trying but I can't get it to work.

functions.lua

OpenStorage = function(houseid, k, v)
    ESX.UI.Menu.CloseAll()

    ESX.UI.Menu.Open("default", GetCurrentResourceName(), "select_storage_wardrobe", {
        title = Strings["storage_wardrobe"],
        align = ((Config.Options and Config.Options.MenuAlign) or ("bottom-right")),
        elements = {
            {label = Strings["storage_option"], value = "storage"},
            {label = Strings["wardrobe_option"], value = "wardrobe"},
        }
    }, function(data, menu)
        if data.current.value == "storage" then
            StorageMenu(houseid, k, v)
        elseif data.current.value == "wardrobe" then
            Wardrobe()
        end
    end, function(data, menu)
        menu.close()
    end)
end

If you can help me that would be great, thank you very much. and excellent project that you are doing!

**Comment by thelindat** [comment]
Loaf housing already supports ox inventory, and has for quite a while..

**Comment by thelindat** [comment]
Okay yeah, you're using leaks. Piss off lmao.
