### ISSUE TITLE
Return Inventory overwrites inventory possibly removing items

### ISSUE THREAD

**Issue by Senlar** [overextended/ox_inventory#517]
**Describe the bug**
When using confiscate inventory to take items before sending a player to jail, if items are obtained in jail when using return inventory it overwrites the players inventory taking those items and only giving back the previous inventory.

**To Reproduce**
1. Loadout inventory with test items
2. Run Confiscate Inventory on player
3. Give player additional items
4. Run return inventory on player
Given items from step 3 will be overwritten by step 4.

**Expected behavior**
Items obtained during step 3 should be retained.

**Comment by thelindat** [comment]
Not a bug, and could be problematic restoring items because you could exceed item weight or limit.
