### ISSUE TITLE
okokCrafting (undefined items)

### ISSUE THREAD

**Issue by Cloud10Dev** [overextended/ox_inventory#518]
Hey guys,

Im trying to setup my okokCrafting with ox_inventory. okok is trying to find the items in db and not inside the ox items.
Is there a way to make it work? It crafts and gives the correct item but the name isnt displayed.

![image](https://user-images.githubusercontent.com/98747665/152454093-c69a637c-aeba-41e1-bc80-034e1afc677f.png)

**Comment by thelindat** [comment]
Copy-paste right from discord pinned messages.
```lua
local itemNames
ESX.RegisterServerCallback('okokCrafting:itemNames', function(source, cb)
    if not itemNames then
        itemNames = {}
        for item, data in pairs(exports.ox_inventory:Items()) do 
            itemNames[item] = data.label
        end
    end
    cb(itemNames)
end)
```

**Comment by Twinded** [comment]
Hi guys, I have the same issue.

@thelindat I had your snippet in the `sv_utils.lua` file of OkokCrafting, but never changes.

Can you help me ?

Thanks !
