### ISSUE TITLE
Tooltip info bug

### ISSUE THREAD

**Issue by Jonneis** [overextended/ox_inventory#521]
**Describe the bug**
There is a bug between shops when you hover the items, when you reopen your inventory if u hover your items u will get the last tooltip info from the last item you hover the previous shop, this hapens only if you exit the shops with keybinds not with the button close inventory.

**To Reproduce**
1. Go to any shop
2. Hover any item until you see the tooltip info, then close it  (described access keys F2,ESC)
3. Reopen your inventory and hover any item.
4. You will  see the tooltip from the last item u hovered the previous shop and not your actually item u hover right now.

[Video](https://streamable.com/itar28)

**Comment by antond15** [comment]
Can reproduce ✔
This happens when hovering on item in **any** second inventory (_shops, drops, stashes, etc._).

**Comment by LukeWasTakenn** [comment]
Fixed in 3218ee16f94ff863690ad94ca2230afeb67e7f7a
