### ISSUE TITLE
 Problem with opening the home inventory

### ISSUE THREAD

**Issue by matikh1** [overextended/ox_inventory#523]
**Is your feature request related to a problem? Please describe.**
Hello, I hope you are well.

I don't know if it's the right way to consult on this topic, but I'm having problems with the home inventory, I can't open it since it's configured by default with esx_inventoryhud. How can I make it open with ox_inventory? I've tried changing the code but I can't get it to work.
I hope you can help me.
Thank you.

----------------
RegisterNetEvent("esx_inventoryhud:openPropertyInventory")
AddEventHandler("esx_inventoryhud:openPropertyInventory", function(data, playerSafe, playerMotel, allHousing)
    if playerSafe then isPlayerSafe = playerSafe; else isPlayerSafe = false; end
    if playerMotel then isMotel = playerMotel; else isMotel = false; end
    if allHousing then isHousing = allHousing; else isHousing = false; end
    setPropertyInventoryData(data)
    openPropertyInventory()
end)

function refreshPropertyInventory()
    if isPlayerSafe then
        ESX.TriggerServerCallback('playersafes:GetSafeInventory', function(inventory) 
            setPropertyInventoryData(inventory); 
        end,isPlayerSafe.safeid)
    elseif isMotel then
        ESX.TriggerServerCallback('motels:getInventory', function(inventory) 
            setPropertyInventoryData(inventory); 
        end,isMotel.zone,isMotel.door)
    elseif isHousing then
        ESX.TriggerServerCallback('Allhousing:GetInventory', function(inventory) 
            setPropertyInventoryData(inventory); 
        end,isHousing)
    else
        ESX.TriggerServerCallback("esx_property:getPropertyInventory",function(inventory)
            setPropertyInventoryData(inventory)
        end,ESX.GetPlayerData().identifier)
    end
end

**Comment by LukeWasTakenn** [comment]
At least use code blocks please.
