### ISSUE TITLE
Ammo returns at relog

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#526]
**Describe the bug**
Ammo returns after relogging (one bullet)

**To Reproduce**
1. Give yourself any weapon, and four ammo.
2. Shoot four bullets.
3. Relog.
4. Return and you will have 1 bullet left in the gun.

**Expected behavior**
The gun should have no bullets.

**Additional context**
- **Game Version:** 5181
- **Client:** Production
- **Inventory Build:** v2.3.2

**Comment by 0xDEMXN** [comment]
> Cannot reproduce.

I did just by firing all the bullets I had in the pistol and I actually have got one bullet left after relogging.

**Comment by thelindat** [comment]
I emptied the clip a dozen times and consistently had no bullets remaining when relogging.

**Comment by 0xDEMXN** [comment]
> I emptied the clip a dozen times and consistently had no bullets remaining when relogging.

It seems like it's not very consistent, doesn't happen all the time but I'm able to reproduce by doing the steps a few times .

**Comment by DogsGoBark** [comment]
Not sure then, I have it happening on 2.3.5 too.
