### ISSUE TITLE
[Request] Search filter

### ISSUE THREAD

**Issue by WooAf** [overextended/ox_inventory#528]
**Is your feature request related to a problem? Please describe.**
Not at all, just a request

**Describe the solution you'd like**
Would be great to add a search feature so we can filter items !

**Comment by DogsGoBark** [comment]
Server: https://overextended.github.io/ox_inventory/modules/inventory/server/search/
Client: https://overextended.github.io/ox_inventory/modules/inventory/client/search/

Probably would be great if you looked at the docs too.

**Comment by WooAf** [comment]
> 

I'm talking about a filter right in the UI for user to search though their items in houses or any containers etc..

**Comment by LukeWasTakenn** [comment]
Like a search bar? because no

**Comment by dunak-debug** [comment]
> > 
> 
> I'm talking about a filter right in the UI for user to search though their items in houses or any containers etc..

Not possible with current implementation as we are moving items based on slot number from UI.
