### ISSUE TITLE
SCRIPT ERROR: @ox_inventory/modules/bridge/client.lua:10: attempt to index a nil value (field 'groups')

### ISSUE THREAD

**Issue by Marc85BPG** [overextended/ox_inventory#529]
Updated to newset Release Version

SCRIPT ERROR: 
@ox_inventory/modules/bridge/client.lua:10: attempt to index a nil value (field 'groups')
@ox_inventory/modules/bridge/client.lua^7:10)
@ox_inventory/client.lua^7:837)
@pe-lualib/init.lua^7:108)

**Comment by DogsGoBark** [comment]
You most likely have to update your `data` and change `jobs` to `groups`. Compare your `data` files to the ones on the repo.

**Comment by Marc85BPG** [comment]
nope, there was  already good to go.

Solved this due to Build new
