### ISSUE TITLE
Period instead of comma, breaks existing inventories

### ISSUE THREAD

**Issue by Senlar** [overextended/ox_inventory#532]
https://github.com/overextended/ox_inventory/blob/eab41b5f76936cfbc3542b1869deaeda9795f638/modules/inventory/server.lua#L311

**Comment by Senlar** [comment]
Should be
`v.metadata = Items.CheckMetadata(v.metadata, item, v.name)`

**Comment by LukeWasTakenn** [comment]
Why not make a PR?

**Comment by Senlar** [comment]
Done, if possible it would be nice if the discord ban on my account could be removed. I have attempted to reach out with no success.

**Comment by LukeWasTakenn** [comment]
You were banned by Warden for being in a cheating discord, get it appealed and then we'll see about an unban.

**Comment by Senlar** [comment]
Not sure about that or where to even appeal. I'm in a ton of discords for all kinds of scripts and mappings for my server so it would be nice to find out about it.

**Comment by LukeWasTakenn** [comment]
You can find more information and what you need to do here: https://discord.gg/jeFeDRasfs

Locking the issue now.
