### ISSUE TITLE
DisableControlAction

### ISSUE THREAD

**Issue by frazz1234** [overextended/ox_inventory#541]
**Describe the bug**
So, whit the last update, you can now hit in the space, shoot if you have a gun and you are in the inventory! you can moove the mouse and you see the cam follow the everything. 

the version i have before update is 2.1.8 and work well! did multiple try and everything. try to look in the code if something have change.. but from my knowledge nothing.

any help? thanks

**Comment by 0xDEMXN** [comment]
This is not happening for me.
Make sure you didn't mess something up, try with a fresh install and provide reproduction steps in case.
