### ISSUE TITLE
Bugged Jerrycan

### ISSUE THREAD

**Issue by MJRamon** [overextended/ox_inventory#544]
**Describe the bug**
When using WEAPON_PETROLCAN, player instantly stops pooring liquid from it and hides it into inventory. This stops from creating petrol "fuses" and refuel process using LegacyFuel.

**Comment by thelindat** [comment]
Any weapons that aren't given as items aren't going to work properly, and anything that relies on default ammo logic is going to bug out as well.

**Comment by MJRamon** [comment]
> Any weapons that aren't given as items aren't going to work properly, and anything that relies on default ammo logic is going to bug out as well.

It is given as item.

**Comment by thelindat** [comment]
Petrol can durability and ammo is synced, and it works completely fine when given as an item.
![image](https://user-images.githubusercontent.com/65407488/153741179-20fa789e-8fcd-40d6-abc6-ad267b846482.png)

**Comment by MJRamon** [comment]
Okey. Is it `/giveitem 1 WEAPON_PETROLCAN 1` ?

**Comment by MJRamon** [comment]
Okey. So, when I poor liquid on floor, it spends 4 "ammo", then hides item into inventory.
If I try tofuel a car using LegacyFuel, LegacyFuel says that can is empty.

**Comment by thelindat** [comment]
That is because legacyfuel isn’t set up for the inventory. There was a version to work with linden inventory, but we decided to drop it and work on our own fuel system.

**Comment by MJRamon** [comment]
Is ox_fuel usable or not ready at all?

**Comment by thelindat** [comment]
I haven’t looked through everything; it’s usable but I can’t say if it’s production ready or not.
