### ISSUE TITLE
Weapon not holstering correctly on certain slot change

### ISSUE THREAD

**Issue by 0xDEMXN** [overextended/ox_inventory#546]
**Describe the bug**
While holstering works well when moving the weapon you are currently holding to a different slot, it won't work if the weapon is swapped by dragging another item into it

**To Reproduce**
1. Give yourself a `weapon_pistol`
2. Give yourself a `weapon_pistol_mk2` (can be any item actually)
3. Extract `weapon_pistol`
4. Open the inventory and drag the `weapon_pistol_mk2` over the `weapon_pistol` that's currently extracted

**Comment by LukeWasTakenn** [comment]
Fixed in commit c72ba3fa06684c35dbe3294e1bb9f0aa654b07f9
