### ISSUE TITLE
Server console error for moving weapon too fast

### ISSUE THREAD

**Issue by 0xDEMXN** [overextended/ox_inventory#547]
**Describe the bug**
A server console error pops up if you move the weapon you're hold too fast

**To Reproduce**
1. Extract a weapon
2. Open inventory, drag the weapon you're holding to the right side inventory and then rapidly back to your inventory
3. This error should show up: `SCRIPT ERROR: @ox_inventory/server.lua:195: attempt to index a nil value (local 'fromInventory')`

**Comment by thelindat** [comment]
Is this with any inventory, or with drops only?

**Comment by 0xDEMXN** [comment]
> Is this with any inventory, or with drops only?

Looks like it's drops only actually

**Comment by thelindat** [comment]
Race condition I guess, though the inventory should lock while waiting for a response. Can’t reproduce locally but managed to get it a couple times in my vps.

**Comment by thelindat** [comment]
Should be resolved.
