### ISSUE TITLE
Item Multiplication/Loss with Stashes & Save Interval

### ISSUE THREAD

**Issue by Ru661** [overextended/ox_inventory#550]
**Describe the bug**
I am able to duplicate items when I grab Items from a stash less than 10 minutes before a planned server restart.
The Item will then after the restart be in my inventory but also again in the Stash, since the stash is only saved to the DB every 10 minutes.

**To Reproduce**
1. Go to any stash when a server restart is happening in less than 10 minutes.
2. Grab something which has been in the stash for more than 10 minutes and been saved already.
3. After the restart of the server go back to the stash and grab the same items again.

**Expected behavior**
Explicitly save the stashes on edit (I guess you want to improve performance with the current behaviour)
Or Trigger the save ahead of a restart event.

**Additional context**
As a side effect of this also stashed items might be lost if putting them into the stash when a server restart is about to happen in less than 10 minutes.

**Comment by thelindat** [comment]
> Or Trigger the save ahead of a restart event.

How are you restarting? There's already an event handling txAdmin scheduled restarts, and it triggers the same as in ESX.

**Comment by Ru661** [comment]
I am using txAdmin.
But I also just noticed an Error Message when restarting: 
[    c-scripting-core] WARNING: NON-EXISTENT NATIVE 00000000a4ea0691

So seems to be a problem on my end then.
