### ISSUE TITLE
On registration, in inventory name is displayed as steam name and not RP character name

### ISSUE THREAD

**Issue by hyprell** [overextended/ox_inventory#560]
**Describe the bug**
On registration, when created RP character with esx_identity, in inventory the name is displayed as steam name and not RP character name. Also items as identification generates description with date of birth: nil.

**To Reproduce**
1. Remove your character
2. Connect and register
3. Open inventory, give yourself identification item
4. Check identification item's description

**Expected behavior**
On register both name and date of birth should update.

**Comment by LukeWasTakenn** [comment]
Does the character name display properly after restarting the game/server?

**Comment by hyprell** [comment]
> Does the character name display properly after restarting the game/server?

Yup

**Comment by LukeWasTakenn** [comment]
I wonder if this is an esx/esx_identity issue 🤔

**Comment by thelindat** [comment]
More an issue when people don't use some sort of multicharacter system which is pretty standard nowadays.

**Comment by skyner22** [comment]
> **Describe the bug** On registration, when created RP character with esx_identity, in inventory the name is displayed as steam name and not RP character name. Also items as identification generates description with date of birth: nil.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Remove your character
> 2. Connect and register
> 3. Open inventory, give yourself identification item
> 4. Check identification item's description
> 
> **Expected behavior** On register both name and date of birth should update.

did u fixed i have the same issue
