### ISSUE TITLE
i cant open inventory

### ISSUE THREAD

**Issue by skakaj5** [overextended/ox_inventory#561]
when i press f2 i got only error
![image](https://user-images.githubusercontent.com/100050550/154821548-39247cb1-e195-4a7d-b377-766206d875e7.png)
![image](https://user-images.githubusercontent.com/100050550/154821555-384aed04-baa2-43b1-b0ab-7b9c1e361276.png)

**Comment by LukeWasTakenn** [comment]
Print the conditions in the `CanOpenInventory` function in the client file and see what's not matching, this error is very vague.

**Comment by skakaj5** [comment]
and how to fix this ? 

![image](https://user-images.githubusercontent.com/100050550/154822240-cf769dd8-ebb0-4da2-a0cd-96bf24c7f057.png)

**Comment by TheSpaceGamerV2** [comment]
@skakaj5 do u have the last version of <a href="https://github.com/project-error/pe-lualib"/>pe-lualib ?
