### ISSUE TITLE
(logs) bug when giving amount of a stack

### ISSUE THREAD

**Issue by WooAf** [overextended/ox_inventory#566]
**Describe the bug**
When you give a certain amount of items from a stack its not showing the exact amount of given in the logs

**To Reproduce**
Have a stack of items in your inventory and give ex: half of it to a player

**Expected behavior**
Logs should show the exact amount given to that player but its giving the amount in the stack instead

**Comment by LukeWasTakenn** [comment]
This is from a stack of 28, it seems to be working fine.

![image](https://user-images.githubusercontent.com/39926192/155544919-6c29c65d-2a46-4d1c-9edf-b1f72de08edc.png)

**Comment by thelindat** [comment]
I fixed this yesterday.
