### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ArGo75** [overextended/ox_inventory#568]
[    c-scripting-core] Creating script environments for ox_inventory
[ script:ox_inventory] Error loading script modules/bridge/server.lua in resource ox_inventory: @ox_inventory/modules/bridge/server.lua:39: Ox Inventory requires a modified version of ESX, refer to the documentation.
[ script:ox_inventory] stack traceback:
[ script:ox_inventory] 	[C]: in function 'error'
[ script:ox_inventory] 	@ox_inventory/modules/bridge/server.lua:39: in main chunk
[    c-scripting-core] Failed to load script modules/bridge/server.lua.
[ citizen-server-impl] Started resource ox_inventory

**Comment by N-fire** [comment]
This is not a bug if you want support go on the discord of overextended

**Comment by LukeWasTakenn** [comment]
Use the official ESX Legacy, currently there is no release with the support for the inventory so you would have to use the latest commit there.
