### ISSUE TITLE
cant open Inventory after reconnect

### ISSUE THREAD

**Issue by qggamer1** [overextended/ox_inventory#569]
**Describe the bug**
If i connect fresh on the server i can open Inventory , If i reconnect on the Server without game reestart or i reestart the server and  connect directly without game reestart.  Then i can not more open the Inventory. It says you can not open the inventory right now. If i Restart my game completly and reconnect its worked again. 

**To Reproduce**
1. Connect to Server
2. Shut Down the Server
3. Reconnect on the server without Game Reestart
4. Now i Cant open the inventory it says now  " you cant open inventory right now"

**Screenshots**
https://cdn.discordapp.com/attachments/268857914859585546/946714010101907477/unknown.png

**Additional context**
i use the Multicharacter System from Code Design

**Comment by thelindat** [comment]
This seems to be an issue with statebags when I’ve experienced it.

**Comment by benzon** [comment]
It's more or less always advised to shut down fivem client when disconnecting from a server, since a lot of wird things tends to happen.

**Comment by thelindat** [comment]
This bug should be resolved on canary (state bags are wiped when disconnecting).
