### ISSUE TITLE
Vehicule DATA

### ISSUE THREAD

**Issue by frazz1234** [overextended/ox_inventory#574]
**Is your feature request related to a problem? Please describe.**
Some car like rubble or the stokade are very hard to get an acces to the trunk.

So he would be amazing if in vehicule lua in data where you can force the trunk in the front, you add number 4
and the number force the trunk in the back .. or the sed of the vehicule ! 

We got lot trouble whit this ! thanks

**Comment by LukeWasTakenn** [comment]
You can already declare custom bones for accessing the trunk.

https://github.com/overextended/ox_inventory/blob/6b7db0f1deda9b3b92d01cb356526f40edcc8cea/data/vehicles.lua#L89-L91

**Comment by frazz1234** [comment]
> You can already declare custom bones for accessing the trunk.
> 
> https://github.com/overextended/ox_inventory/blob/6b7db0f1deda9b3b92d01cb356526f40edcc8cea/data/vehicles.lua#L89-L91

Just fucking dumb... i read to fast... ! thanks
