### ISSUE TITLE
No Async function in ox_lib callback

### ISSUE THREAD

**Issue by karthik-pitchai03** [overextended/ox_inventory#583]
**Describe the bug**

**To Reproduce**
1. Go to Armory near legion square
2. Press E on the marker to buy license
3. f8 console error regarding Async

**Expected behavior**
Need to buy weapon license

**Screenshots**
![20220302203006_1](https://user-images.githubusercontent.com/89032825/156387216-c20ce954-3137-4f50-9672-dab7d20feee6.jpg)

**Additional context**
lib.callback.Async(shared.resource, 'buyLicense', 1000, function(success, message)
	if success == false then
	    Utils.Notify({type = 'error', text = shared.locale(message), duration = 2500})
	else
	    Utils.Notify({text = shared.locale(message), duration = 2500})
	end
end, closestMarker[2] )

**Comment by thelindat** [comment]
Fixed.
