### ISSUE TITLE
interface lib.disableControls

### ISSUE THREAD

**Issue by Ru661** [overextended/ox_inventory#586]
**Describe the bug**
lib. is missing in interface/client.lua Line94

IS: 
`if count > 0 then disableControls:Add(progress.disable) end`
SHOULD:
`if count > 0 then lib.disableControls:Add(progress.disable) end`

**Comment by LukeWasTakenn** [comment]
Fixed in PR https://github.com/overextended/ox_inventory/commit/c29f5ae452d52bbf4f717fab529b6082874fdf2f.
