### ISSUE TITLE
Warehouse status is not updated

### ISSUE THREAD

**Issue by criminalist** [overextended/ox_inventory#587]
Version 2.5.1
**Describe the bug**
After the update, a god appeared, warehouses are registered in the house exports.ox_inventory:RegisterStash(res[i].id, res[i].id, 60, 5000000, res[i].owner)
Before the update, everything worked well, without errors, now the items that I transfer to the warehouse disappear as soon as you close it, that is, for example, the money that I transfer from the warehouse to my inventory after closing remains in the warehouse, the status of the warehouse is not actually updated.

**Screenshots**
no screenshots

**Comment by criminalist** [comment]
new items do not appear in the database either, only if the inventory is restarted

**Comment by thelindat** [comment]
> After the update, a god appeared

🙏 

> the items that I transfer to the warehouse disappear as soon as you close it, that is, for example, the money that I transfer from the warehouse to my inventory after closing remains in the warehouse, the status of the warehouse is not actually updated

I understand many of these words, but when strung together in this particular order I have no idea what you are saying.

> new items do not appear in the database either, only if the inventory is restarted

The inventory saves every 10 minutes, on resource restart, and before a txAdmin scheduled restart.

**Comment by thelindat** [comment]
After double checking inventory access, it was not working as intended. Going to assume it's resolved.

**Comment by criminalist** [comment]
Last update fixed, thanks.
