### ISSUE TITLE
Bag/Inventory

### ISSUE THREAD

**Issue by fascinatingact** [overextended/ox_inventory#593]
This is a question. I don't know if it already existed but i already read the whole documentation and haven't seen anything about it. Is it possible to make the bags that you buy in clothing store to expand your player storage? For example a duffle bag. And also is there an item exist that will fix the durability of the weapons ? Thank you 
![image](https://user-images.githubusercontent.com/80687279/156900364-f5f0fa3b-4293-46cb-9e2d-2b32cf4c6a5c.png)

**Comment by dolutattoo** [comment]
You should use the discord for this kind of questions

**Comment by thelindat** [comment]
> is there an item exist that will fix the durability of the weapons

no

> make the bags that you buy in clothing store to expand your player storage

Reference esx_skin which has something like this.
