### ISSUE TITLE
Glitch weight with containers

### ISSUE THREAD

**Issue by dolutattoo** [overextended/ox_inventory#595]
**Describe the bug**
Putting items into a containers let you go up to the player inventory weight limit.
Please test this because I have some minor changes in my inventory, but I'm pretty sure this will happen for everyone.

**To Reproduce**
1. Give yourself a container item `/giveitem me paperbag 1`,
2. Fill your inventory with another item, `/giveitem me water ?`, but do not go up to the player weight capacity,
3. Give yourself one more of this item, but drop it (the command allows you to go up to the weight capacity),
4. Try to grab the dropped item, you should be blocked cause you cannot carry more weight (fine!),
5. Now re-open your inventory, and put 1 item in your bag,
6. Close your bag, open the drop and try to grab the item,
7. You should now see your weight bigger than the limit, and you're able to carry as much item as you want!

**Screenshots**
![image](https://user-images.githubusercontent.com/47056777/156914956-0818cf90-eee3-4b7e-befa-81a11883606b.png)

**Additional context**
I realized that on many scripts where I use `Inventory.CanCarryItem()`, and then `Inventory.AddItem()`.
By putting some prints in the inventory ressource, I think that it is caused by the `ox_inventory:swapItems` server callback, who is not up to date with the current client weight because at this state.
In some very rare cases, the limit is working, because the server just updated the player weight.

**Suggestion**
I would like to use this issue to suggest something related to weight:
What about include something similar as `Inventory.CanCarryItem()` into `Inventory.AddItem()` ?
Cause I personnally have a lot of resources who use that, and I'm always using both functions.
Maybe a last argument like `ignoreWeight` into the `Inventory.AddItem()` function could be usefull, for `/additem` command for example?

**Comment by thelindat** [comment]
Pending feedback on fix.

**Comment by thelindat** [comment]
Reported as fixed.
