### ISSUE TITLE
Duplicating Dumpsters.

### ISSUE THREAD

**Issue by TlYPN** [overextended/ox_inventory#597]
**Describe the bug**
basically, if 2 or more players attempt to open a dumpster simultaneously they basically duplicate in front of your eyes.

**To Reproduce**
1. have 2 players go to a dumpster and try and open the inventory at the same time

**Expected behavior**
see the same inventory and not duplicate them XD

**Screenshots**
if needed i can actually provide a video of the occurance

**Additional context**
i am on the latest version

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/157144918-a6f37ae1-153d-4052-8853-d82faf8b50cf.png)
![image](https://user-images.githubusercontent.com/65407488/157144949-5a88aa65-5091-448a-9510-5ff91db27616.png)

**Comment by thelindat** [comment]
Did manage to have it duplicate once out of ~30 dumpsters. Haven't had it since removing mission entity.

**Comment by TlYPN** [comment]
10-4!

**Comment by thelindat** [comment]
Any issues since?

**Comment by NotZombiee** [comment]
Hmm we disabled the dumpsters going back to our old ways.. since someone could bump them with a car and they respawn or duplicate on impact.

**Comment by TlYPN** [comment]
THE "BUMP AND DUPLICATE" is an issue and i have noticed it. however multiple players can no longer duplicate the dumpsters in front of your eyes.

**Comment by Gbronski** [comment]
Having 2 players near a dumpster and bumping it with a vehicle, I can consistently make this happen. I will try disabling mission entity
