### ISSUE TITLE
This is a Korean translation proposal (kr.lua locales)

### ISSUE THREAD

**Issue by AriaFlolence** [overextended/ox_inventory#604]
return {
	-- Buttons, context menu
	['ui_use'] = "사용",
	['ui_give'] = "건네기",
	['ui_close'] = "닫기",
	['ui_drop'] = "떨구기",
	['ui_removeattachments'] = "부착물 제거",
	-- Tooltip
	['ui_durability'] = "내구도",
	['ui_ammo'] = "탄약",
	['ui_serial'] = "시리얼 넘버",
	['ui_components'] = "컴포넌트",
	['ui_tint'] = "색조",
	-- Useful controls
	['ui_usefulcontrols'] = "도움말",
	['ui_rmb'] = "아이템 컨메뉴 열기",
	['ui_ctrl_lmb'] = "다른 인벤토리로 빠르게 옮기기",
	['ui_shift_drag'] = "아이템 절반으로 나누기",
	['ui_ctrl_shift_lmb'] = "절반 아이템 빠르게 옮기기",
	['ui_alt_lmb'] = "퀵사용",
	--
	['$'] = "$",
	['male'] = "남성",
	['female'] = "여성",
	['used'] = "사용된",
	['removed'] = "사라짐 %sx",
	['added'] = "추가됨 %sx",
	['holstered'] = "Holstered",
	['equipped'] = "장착됨",
	['using'] = "사용 %s",
	['inventory_setup'] = "인벤토리 사용이 준비되었습니다!",
	['inventory_player_access'] = "당신은 지금 인벤토리를 열 수 없어요.",
	['inventory_right_access'] = "당신은 이 인벤토리를 열 수 없어요.",
	['inventory_lost_access'] = "더 이상 이 인벤토리에 액세스할 수 없습니다.",
	['wrong_ammo'] = "%s 탄약을 %s 탄약으로 로드할 수 없습니다.",
	['weapon_license'] = "무기 라이센스",
	['has_weapon_license'] = "당신은 이미 무기 라이센스를 가지고 있습니다",
	['bought_weapon_license'] = "무기 라이센스를 구매했습니다",
	['poor_weapon_license'] = "당신은 무기 라이센스를 감당할 수 없습니다",
	['purchase_license'] = "[~g~E~s~] 라이선스 구매",
	['weapon_unregistered'] = "%s은(는) 누구에게도 등록되지 않았습니다.",
	['weapon_registered'] = "%s(%s)이(가) %s에 등록되었습니다.",
	['weapon_broken'] = "이 무기는 고장났다",
	['vehicle_locked'] = "차량이 잠겨 있습니다",
	['nobody_nearby'] = "근처에 아무도 없다",
	['give_amount'] = "제공할 금액을 입력해야 합니다.",
	['buy_amount'] = "구매하려면 금액을 입력해야 합니다.",
	['component_has'] = "이 무기에는 이미 %s이(가) 있습니다.",
	['component_invalid'] = "이 무기는 %s과(와) 호환되지 않습니다.",
	['cannot_perform'] = "이 작업을 수행할 수 없습니다.",
	['cannot_carry'] = "당신은 그렇게 많이 가지고 갈 수 없습니다",
	['cannot_carry_other'] = "대상 인벤토리는 그렇게 많이 보유할 수 없습니다.",
	['cannot_carry_limit'] = "%s %s을(를) 초과할 수 없습니다.",
	['cannot_carry_limit_other'] = "대상은 %s %s을(를) 초과할 수 없습니다.",
	['items_confiscated'] = "귀하의 물품이 압수되었습니다.",
	['items_returned'] = "귀하의 항목이 반환되었습니다",
	['item_unauthorised'] = "이 항목을 구매할 권한이 없습니다.",
	['item_unlicensed'] = "이 항목을 구매할 수 있는 권한이 없습니다.",
	['item_not_enough'] = "%s이(가) 충분하지 않습니다.",
	['cannot_afford'] = "당신은 그것을 감당할 수 없습니다(%s 누락)",
	['stash_lowgrade'] = "이 항목을 가져갈 권한이 없습니다.",
	['cannot_use'] = "%s을(를) 사용할 수 없습니다.",
	['shop_nostock'] = "품목이 품절되었습니다",
	['identification'] = "성별:%s 생년월일: %s",
	['search_dumpster'] = "쓰레기 수거통 검색",
	['open_shop'] = "열기 %s",
	['purchased_for'] = "%s %s을(를) %s%s에 대해 구매했습니다.",
	['unable_stack_items'] = "이 항목을 쌓을 수 없습니다",
	['police_evidence'] = "경찰 증거물",
	['open_police_evidence'] = "경찰 증거물 열기",
	['open_stash'] = "보관함 열기",
	['locker_number'] = "로커 번호",
	['locker_no_value'] = "사물함을 열려면 값이 있어야 합니다.",
	['locker_must_number'] = "사물함은 숫자여야 합니다.",
	['weapon_hand_required'] = "당신은 손에 무기가 있어야합니다",
	['weapon_hand_wrong'] = "손에 잘못된 무기",
	['open_player_inventory'] = "플레이어 인벤토리를 엽니다~",
	['open_secondary_inventory'] = "2차 인벤토리 열기~",
	['disable_hotbar'] = "인벤토리 핫바 표시~",
	['reload_weapon'] = "무기 재장전~",
	['use_hotbar'] = "핫바 항목 %s 사용~",
	['no_durability'] = "%s 내구도가 고갈되었습니다",
	['cannot_give'] = "대상에 %s %s을(를) 제공할 수 없습니다.",
	['evidence_cannot_take'] = "증거로 삼을 만큼 등급이 높지 않음",
	['dumpster'] = "쓰레기 수거통"
}

**Comment by AriaFlolence** [comment]
I'm new to github, so I don't know how to use it
I'm sorry :(

**Comment by LukeWasTakenn** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
