### ISSUE TITLE
Work in stash server side

### ISSUE THREAD

**Issue by RedAlex** [overextended/ox_inventory#606]
**Is your feature request related to a problem? Please describe.**
Work in stash server side.
Here a demo of use server side for a Factory with esx_addoninventory

![Code_917nGjDlxo](https://user-images.githubusercontent.com/855331/158232747-32158435-7cd7-4ecf-b312-9d61d2cb8eb5.png)

**Describe the solution you'd like**
Have the function(with exports) to
GetStash(id)
   return the stash inventory

StashGetItemCount(id, item)
   return item count & slot

StashRemoveItem(id, slot, count) Or (id, item , count)

StashAddItem(id, item, count, slot) or (id, item, count)

**Describe alternatives you've considered**
Can be client side but i will prefer server side.

**Comment by RedAlex** [comment]
![Code_DmpraJ8xLo](https://user-images.githubusercontent.com/855331/158239165-6a5f19b6-439c-424e-aa47-7148d945f217.png)

I have test but return nil
![cmd_ikUyYcl7Xl](https://user-images.githubusercontent.com/855331/158239038-6321f401-4708-42ac-8359-02bbacc4c9cf.png)

I will register the stash like this :
![Code_CQRzv11Rar](https://user-images.githubusercontent.com/855331/158239135-4703564e-cae1-4234-a328-c241f1ff97c6.png)

Here the data base
![heidisql_jEfkKoPvUS](https://user-images.githubusercontent.com/855331/158239238-297984dd-08fc-4a86-87c2-a3b5f1aa3ff5.png)

**Comment by thelindat** [comment]
@RedAlex Try pulling the latest commit.

```lua
local inventory = exports.ox_inventory:Inventory('society_vignefactory')
for k,v in pairs(inventory) do
	print(k,v)
end
```

![image](https://user-images.githubusercontent.com/65407488/158251951-fd21f379-9d88-46fb-9f7a-a9b8ff1d3445.png)

**Comment by RedAlex** [comment]
Tested and work well.
A huge thank you for the quick adaptation of your beautiful inventory
![Code_kn4lvuGt1a](https://user-images.githubusercontent.com/855331/158258208-fb8b00cf-385b-41e4-b586-84da9591f30f.png)
![cmd_Zs9ggNUAyt](https://user-images.githubusercontent.com/855331/158258221-9ae227ef-1736-4cfc-aeda-dfcfa46f3368.png)
