### ISSUE TITLE
Need not be a feature in an update. Just need help.

### ISSUE THREAD

**Issue by DistrictZion** [overextended/ox_inventory#607]
Hi, my community isnt exactly raycast friendly when it comes to giving item. If I were to add multiple players around me, where would I go about adding this?

**Comment by LukeWasTakenn** [comment]
You'd need to make some sort of UI in React and then handle a promise when giving an item on the Lua side.

**Comment by DistrictZion** [comment]
Please.... I really beg you, or pay you or something!
please please please don't ignore this and close this. There are lots of people like me looking for this, and not finding a solution.

UI on react, NO clue at all. So, let's talk nh-context or zf. 
Now, I know how to fetch closest players like a table. How would I add this to context menu? and how would I go about making the selection the target.


Please help....
