### ISSUE TITLE
Stash can only be open with a job but without Have the job

### ISSUE THREAD

**Issue by RedAlex** [overextended/ox_inventory#611]
**Describe the bug**
Property stash can't be open without set a job.
But i don't have the job set and can open it.

**To Reproduce**
I have set property stash without owner like this
![heidisql_2JhvLucZRL](https://user-images.githubusercontent.com/855331/158618376-5908ab4c-10f9-4e14-93f2-684403c6a1dc.png)

I will register all property like this.
![Code_fnLT48I8s2](https://user-images.githubusercontent.com/855331/158618486-7c1ec3e8-5b0e-46e1-9a32-7621d19372e2.png)

I use this code to open the stash
![Code_kRsFLx4sQW](https://user-images.githubusercontent.com/855331/158619375-8f4079b6-1b24-4df8-bc24-31b5c3435309.png)

And here the result the stash is open register with the job "police" but i'm "ambulance"
![FiveM_b2189_GTAProcess_ljp97uvQjt](https://user-images.githubusercontent.com/855331/158619433-2d56fb54-9738-4cd1-aa35-71f8176f888e.png)

**Expected behavior**
A stash with a job register need to look the player job to be open.
And my trouble are if i don't set a job i can't open the stash...

**Comment by RedAlex** [comment]
https://github.com/overextended/ox_inventory/commit/011e9ce159fc00cf88e21e102e1dfdd79a772631
This commit fix a part of trouble, now i can register property stash like this and work
![Code_hfCIMrVIx1](https://user-images.githubusercontent.com/855331/158621674-848c1f5d-3a40-4178-8a13-4e3f676bde8d.png)

**Comment by thelindat** [comment]
I've changed stash group permissions which should resolve this.
