### ISSUE TITLE
Shop with item sold by player

### ISSUE THREAD

**Issue by RedAlex** [overextended/ox_inventory#612]
**Is your feature request related to a problem? Please describe.**
Shop have unlimited stock.

**Describe the solution you'd like**
Add system to place shop linked to a stash to sell item by player with the inventory.

Add option in a stash of type Shop to setup metadata price for item.

A player opening a shop Custom see only item put in stock and with price by the reseller.

**Describe alternatives you've considered**
Item can only be sell from player to player

**Additional context**
![FiveM_b2189_GTAProcess_bULFZeuECd](https://user-images.githubusercontent.com/855331/158649058-24b743fd-f1f7-4162-bb4e-84ab8d5f8eea.png)

**Comment by thelindat** [comment]
> Shop have unlimited stock.
You can define the available count for that session, but a system to keep persistent stock and require deliveries requires a lot more work to implement; an investment I'm not willing to make right now, considering the reward of developing FiveM resources is getting flamed on a daily basis.

> Add system to place shop linked to a stash to sell item by player with the inventory.
Not something I'm interested in adding. See above.
