### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dankooooo** [overextended/ox_inventory#614]
cfx> start ox_inventory
[    c-scripting-core] Creating script environments for ox_inventory
[ script:ox_inventory] Error loading script modules/bridge/server.lua in resource ox_inventory: @ox_inventory/modules/bridge/server.lua:34: Ox Inventory requires a modified version of ESX, refer to the documentation.
[ script:ox_inventory] stack traceback:
[ script:ox_inventory]  [C]: in function 'error'
[ script:ox_inventory]  @ox_inventory/modules/bridge/server.lua:34: in main chunk
[    c-scripting-core] Failed to load script modules/bridge/server.lua.
[ citizen-server-impl] Started resource ox_inventory
[ script:ox_inventory] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export query in resource oxmysql
[ script:ox_inventory] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:867: No such export query in resource oxmysql
[ script:ox_inventory] (nil stack trace)cfx>

**Comment by dankooooo** [comment]
please help i really want to use ox inventory its soo good and yes good job for the inventory

**Comment by dankooooo** [comment]
i read the documentation and nothing can you tell me what to do

**Comment by RedAlex** [comment]
![chrome_EjJdTEZGmS](https://user-images.githubusercontent.com/855331/158877892-cfe28b86-4998-407b-8d70-6923da3e0c23.png)

**Comment by dankooooo** [comment]
what i have to do

**Comment by dankooooo** [comment]
> ![chrome_EjJdTEZGmS](https://user-images.githubusercontent.com/855331/158877892-cfe28b86-4998-407b-8d70-6923da3e0c23.png)

please help

**Comment by dankooooo** [comment]
> Read the documentation.

please help
