### ISSUE TITLE
Unable to use weaponised vehicles

### ISSUE THREAD

**Issue by kelevra69** [overextended/ox_inventory#619]
I have found an issue that is affecting my server. And definitely narrowed to this script. It is preventing my fire trucks from spraying and from using the ladder. There is some function that is changing this and if I can please be directed to the lines and where this is so I can either take it out or edit it some how as it's a huge issue for that department. Thanks for doing great work!

**Comment by MrNewb** [comment]
the watercannon on firetrucks is a vehicle weapon this is why, way more would have to be re-written for something this niche. As far as the ladder I dont think that was ever a thing in gta unless you are streaming some custom model of course. could be wrong but just my 2 cent

**Comment by kelevra69** [comment]
No offence are you the author or have anything to do with the script writing if this? Usually there is a function for this and I don't know why weapons on vehicles would be touched in an inventory script. I have been going through some of it but there has to be a function and reason why. So if the authors can let me know or I guess I'll scrap the script and mark my review. As most servers that are fully functioning use fire vehicles with the sprayer. So thanks for the input but it's really not as difficult as you are making it sound. It's just knowing which function is doing it

**Comment by DokaDoka** [comment]
the regular firetruck works just fine, make sure you are using the latest version
no idea what you are talking about with the ladder

**Comment by kelevra69** [comment]
Maybe the generic fire truck works fine. But not any add on ones nor any military vehicles. As for the ladder...add on fire truck (ladder trucks) have a functioning ladder that moves and extends.  This script is preventing that. So that is why I'm looking for the function that is restricting vehicles

**Comment by thelindat** [comment]
> nor any military vehicles

I shoot tanks on the daily. There's code to enable the weapon wheel when in a weaponised vehicle and I've yet to have any issues.

**Comment by kelevra69** [comment]
Weapon wheel? Are we talking about the same script?

**Comment by thelindat** [comment]
> Weapon wheel? Are we talking about the same script?

Just fuck off if you want to act a fool.

**Comment by kelevra69** [comment]
How are you activating a weapon wheel with this script. I'm lost how you are doing that. As none of my tanks fire which is the reason I was looking for the part that functions that. Can I please just have an author or someone who knows lua and functions to tell me where there is regarding vehicles. Thanks

**Comment by thelindat** [comment]
> Weapon wheel?

![image](https://user-images.githubusercontent.com/65407488/159150131-3fd74ab1-05c7-4dcb-83f8-741d80a063f6.png)
![image](https://user-images.githubusercontent.com/65407488/159150149-725dd60e-348e-43a1-8f45-662ae1014f88.png)
![image](https://user-images.githubusercontent.com/65407488/159150156-5976bfb1-2a67-439c-b3cc-7ddb0fbfd01d.png)
![image](https://user-images.githubusercontent.com/65407488/159150173-ded4e66a-2925-427a-aa8d-64c47fdbe145.png)

> How are you activating a weapon wheel with this script.

```lua
-- Enables the weapon wheel, but disables the use of inventory items
-- Mostly used for weaponised vehicles, though could be called for "minigames"
function Utils.WeaponWheel(state)
	client.weaponWheel = state
	SetWeaponsNoAutoswap(not state)
	SetWeaponsNoAutoreload(not state)
	SetPedCanSwitchWeapon(cache.ped, state)
	SetPedEnableWeaponBlocking(cache.ped, not state)
end
exports('weaponWheel', Utils.WeaponWheel)
```
```lua
lib.onCache('vehicle', function(vehicle)
	if vehicle then
		if DoesVehicleHaveWeapons(vehicle) then
			return Utils.WeaponWheel(true)
			-- todo: check if current seat has weapon
		end
	end

	Utils.WeaponWheel(false)
end)
```

> Can I please just have an author

![image](https://user-images.githubusercontent.com/65407488/159150275-dc90d972-18e7-43f5-9e06-c6190cd45b05.png)

> someone who knows lua

Fresh out.


> tell me where there is regarding vehicles
![image](https://user-images.githubusercontent.com/65407488/159150220-df2e54d7-386e-4c3e-b68b-a1f983bc4daf.png)

**Comment by thelindat** [comment]
> I don't know why weapons on vehicles would be touched in an inventory script.

Weapons are touched in the script because the resource handles all weapons. The natives that disable weapon swapping affect ped weapons and vehicle weapons just the same.

**Comment by kelevra69** [comment]
Ok so if this script handles the weapons as well..aka watercanon can you tell me where do I can disable that function. Thanks. And thanks for telling me to fuck off. Don't think that was necessary. That seems rather childish. You obviously have your setup different as there is no weapon wheel as it was taken out from this as well. So if you edit it to do it then how would I be able to do that. As I have nothing but added it. And I do not have that. So please refrain from being confrontational. I get it you know some stuff but you are telling me it does it in the script and that's the question. Where does it say that about weapons like the water cannon.

**Comment by thelindat** [comment]
> Ok so if this script handles the weapons as well..aka watercanon can you tell me where do I can disable that function

I showed exactly what code blocks weapons.


> And thanks for telling me to fuck off.

Thanks for ignoring me.


> You obviously have your setup different

What? I have the resource as it exists here on this repository.


> So if you edit it to do it then how would I be able to do that. As I have nothing but added it. And I do not have that.

What?


> Where does it say that about weapons like the water cannon.

Why did I bother posting the responsible code? Why can't you use the search function? Why are you ignoring everything I say?

**Comment by DistrictZion** [comment]
I like this thread. It feels like reddit.

**Comment by kelevra69** [comment]
Ok....so I realize the reason why we are not understanding each other....we are looking at different scripts per say....I have the an older version of ox_inventory and that is why I could not understand what you were saying.  I get it thats on my bad but please understand from my view.  I want to say I tried updating to the recent version and everything we had disappeared (even when copying and pasted the items/shops) and the script then did not work which the inventory did not come back up.  So looks like stuck with old version and no way to stop that from happening (vehicles shut off from using weapons).  And yes I did listen but it wasnt what I was seeing so it didnt make sense.  So I guess thanks for trying to understand me and helping.  Take care
