### ISSUE TITLE
Changing the symbol of currency in the locale, doesn't change in the UI.

### ISSUE THREAD

**Issue by zerksuk** [overextended/ox_inventory#622]
**Describe the bug**
Changing the symbol of currency in the locale, doesn't change in the UI.

**Expected behavior**
The symbol to be changed in the UI

**Comment by thelindat** [comment]
The UI uses toLocaleString 'en-US' which sets the currency display.

**Comment by N-fire** [comment]
I remember needed to alter this $ for changing currency display in shop
https://github.com/overextended/ox_inventory/blob/e0ed73783876f9f985b0aaa9cf5879f698189da6/web/src/components/inventory/InventorySlot.tsx#L180
it seems hard coded.

**Comment by LukeWasTakenn** [comment]
It just needs the Locale passed through, I just haven't gotten around to it.

**Comment by thelindat** [comment]
I stand corrected then. Fixed.
![image](https://user-images.githubusercontent.com/65407488/160467689-050f2171-02ea-442a-8900-3637b35e04a8.png)
