### ISSUE TITLE
How to change defaut key ???

### ISSUE THREAD

**Issue by Edmondio** [overextended/ox_inventory#628]
I try to change default key (F2 / K / TAB)
It doesn't work, I have to change it 
setr inventory:keys ["F2", "K", "TAB"]
by 
setr inventory:keys ["F9", "K", "TAB"]
????

**Comment by LukeWasTakenn** [comment]
Settings > Keybinds > FiveM

**Comment by Edmondio** [comment]
Thanks Okay, and how do I set the default keys for all player ?

**Comment by LukeWasTakenn** [comment]
New players will have keybinds you set with the convar.

**Comment by Edmondio** [comment]
Ok thx :)
