### ISSUE TITLE
viewInventory

### ISSUE THREAD

**Issue by N-fire** [overextended/ox_inventory#634]
I would like an export to open an inventory, but not being able to take anything from it.
Like the way `/viewinv` does, but for all inventory.
This would be very helpful for checking an inventory.
And I would use that for custom shops like a pawnshop.

**Comment by thelindat** [comment]
Just trigger the command 🤷 

> /viewinv glove11BEPW42

**Comment by N-fire** [comment]
It will only work if the player is an admin, right ?

**Comment by antond15** [comment]
> It will only work if the player is an admin, right ?

Yes.
