### ISSUE TITLE
Car inventory items when when vehicle is destroyed

### ISSUE THREAD

**Issue by og23rd** [overextended/ox_inventory#636]
**Is your feature request related to a problem? Please describe.**
When a car gets destroyed and then you take it back from a garage the items in the inventory are still avalaible and thats not realistic

**Describe the solution you'd like**
Make it so that the items save only when the vehicle is stored in the garage

**Comment by N-fire** [comment]
being able to take a destroyed vehicle is not realistic as well
anyway you could modify your garage script to remove item if the vehicle as not being stored
not sure if the inventory can do anything with that every garage script is different

**Comment by og23rd** [comment]
I mean you have to pay to be able to take the vehicle from the garage again in my case.
But now i understand, when a vehicle gets destroyed it also gets auto saved to the garage so its the same.
Anyway if that can be possible should be very nice

**Comment by thelindat** [comment]
> Make it so that the items save only when the vehicle is stored in the garage

There's no concept of a "garage" in the game code or inventory code, nor is there a set standardised event when storing a vehicle.
