### ISSUE TITLE
Request for firetruck

### ISSUE THREAD

**Issue by frazz1234** [overextended/ox_inventory#637]
Just saw your commit in the github about firetruck. instead of adding the truck name in the code, could you do a config.firetruk so we can add directly in the config the firetruk name we have need this feature? thanks

**Comment by thelindat** [comment]
> Just saw your commit in the github about firetruck. instead of adding the truck name in the code, could you do a config.firetruk so we can add directly in the config the firetruk name we have need this feature? thanks

And what if your random firetruck mod _doesn't_ use the same weapon as firetruk? I won't be adding a bunch of config crap or making dozens of elseif statements to compare model, seat, and weapon.
