### ISSUE TITLE
Convert process from sql to items.lua comma issue

### ISSUE THREAD

**Issue by duckysuck** [overextended/ox_inventory#638]
When importing in from the sql db the comma isnt being added to the previous item and removed from the last item being imported.

**To Reproduce**
1. Look at your last item on items.lua
2. import a new item from an sql file
3. restart ox_inventory
4. look at the updated items.lua

**Expected behavior**
The comma should be removed on the last item and added on the previously last item.

![image](https://user-images.githubusercontent.com/4807016/160504879-f7434bb5-5135-4ae8-9d53-1dabbd14e4aa.png)

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/160505481-a38a269b-ea05-4ee1-8e52-8ec9826d97bb.png)

Default files use a trailing commas, 

![image](https://user-images.githubusercontent.com/65407488/160505520-1a8141df-dcac-4867-99f0-509a13594d8b.png)

Item dumping uses a trailing commas.


This isn't an "issue", it's just you not using a trailing comma when manually adding items.

**Comment by duckysuck** [comment]
oh blimey, I never added a trailing comma before to the last item. I always thought it wasn't wanted.
