### ISSUE TITLE
change of the weight layer when changing clothes in the store

### ISSUE THREAD

**Issue by luchowolf** [overextended/ox_inventory#639]
when using the clothing store to select any garment, the inventory weight is bugged and comes out purple, indicating that the maximum weight is 0.035kg instead of the assigned 35kg.

usually happens at the change of clothes in general (buying and putting away the outfit)

![image](https://user-images.githubusercontent.com/95424040/160624145-4b2dd16b-c7dd-429c-9984-f896447379cb.png)

**Comment by N-fire** [comment]
you need to multiply this value by 1000
switching from grams to kilograms 
https://github.com/esx-framework/esx-legacy/blob/main/%5Besx%5D/esx_skin/config.lua#L6-L9

**Comment by RedAlex** [comment]
This trouble are in ex_extended config.
Max weight without backpack are set to 80 by default

**Comment by luchowolf** [comment]
> This trouble are in ex_extended config. Max weight without backpack are set to 80 by default
in the extended I have it set to 35 as in the ox_inventory config.

**Comment by RedAlex** [comment]
> > This trouble are in ex_extended config. Max weight without backpack are set to 80 by default
> > in the extended I have it set to 35 as in the ox_inventory config.

If you have set 35 after change cloth players have an inventory Limits if 35g not 35kg
35kg  are 35000
