### ISSUE TITLE
Add ability to sell items in a shop

### ISSUE THREAD

**Issue by JohnnyS** [overextended/ox_inventory#642]
Wondering if it is possible to get the functionality of selling items to certain shops. So we can use the inventory to sell items, maybe shop on the right side and u just drag items and hit Sell and it will get what items are in there or any way possible to sell certain items.

This way we can have a full feature shop system with the inventory and not have to use other scripts to perform this function. Also better looking if the script uses for example a menu and just text vs the same UI the shop has.

**Comment by LukeWasTakenn** [comment]
This is something that was brought up before, though I don't think we have any intention of adding any functionality like this.

**Comment by JohnnyS** [comment]
> This is something that was brought up before, though I don't think we have any intention of adding any functionality like this.

That's understandable I mean there are other scripts that do achieve this but it would def be nice to have it supported in there by default!

**Comment by thelindat** [comment]
Not happening.
