### ISSUE TITLE
Nil Value Bug with Ammunition & Weapon Components

### ISSUE THREAD

**Issue by CsyonDerEchte** [overextended/ox_inventory#645]
**Ammunition Nil Error:**
If you take out a firearm and holster it back and remove the weapon out of the fast slot, you will trigger a nil value when using the ammunition for it. You can't open the inventory anymore.

**The error:**
SCRIPT ERROR: @ox_inventory/server.lua:205: attempt to index a nil value

**Weapon Components Nil Error:**
If you try to mount weapon components like a rifle drum clip, weaponskin, or flashlight on the weapon, it will trigger a nil value. The components will not save.

**The error:**
SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:1303: attempt to index a nil value (local 'component')
[ script:ox_inventory] > handler (@ox_inventory/modules/inventory/server.lua:1303) 

I hope i can help with this bugreport.

**Comment by LukeWasTakenn** [comment]
Are you on latest release version?

**Comment by LukeWasTakenn** [comment]
Should be fixed in commit f0368761e88d79b19dc52815efe61b1d42424df0

**Comment by CsyonDerEchte** [comment]
Hey im on the newest version yes. So the first bug is fixed now just the weapon components will not work and still give this error:

[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:1303: attempt to index a nil value (local 'component')
[ script:ox_inventory] > handler (@ox_inventory/modules/inventory/server.lua:1303)
