### ISSUE TITLE
Trunk and glovebox issue

### ISSUE THREAD

**Issue by GeerdoDaGr8** [overextended/ox_inventory#647]
**Describe the bug**
If you look in a glove box you can't look in a trunk after and vice versa.

**To Reproduce**
Open a Trunk/glove box then try to open a glove box/trunk or hand people items.

**Expected behavior**
Being able to access both without issue

**Screenshots**
Can get video if needed

**Additional context**
This is only happening on the latest release.  If i revert back to 2.6.1 i dont have this issue

**Comment by GeerdoDaGr8** [comment]
![image](https://user-images.githubusercontent.com/56656726/161416161-cc7e4e76-6698-41ad-880f-9d614b469d33.png)
this is the only thing that prints at all while it is happening.

**Comment by GeerdoDaGr8** [comment]
https://streamable.com/k89xts
https://streamable.com/pxs7x6
https://www.youtube.com/watch?v=tsl80FeYM5A
Here are some videos showing the odd behavior of trunks and gloveboxes.   Its like there is a timer on them of some sort.

**Comment by LukeWasTakenn** [comment]
wat

I am not getting this issue at all.

![image](https://user-images.githubusercontent.com/39926192/161450805-a13561bb-fd5e-418b-9c14-1574e94d8ded.png)

![image](https://user-images.githubusercontent.com/39926192/161450809-25b336a9-abfe-44c3-a77e-e1b86cf6ce40.png)

**Comment by thelindat** [comment]
> ![image](https://user-images.githubusercontent.com/56656726/161416161-cc7e4e76-6698-41ad-880f-9d614b469d33.png)
> this is the only thing that prints at all while it is happening but i dont think it is related

How would that be triggering “while it is happening”, whatever it refers to, when it’s specifically related to giveItem while in a vehicle?

Which itself is a different issue altogether and may require updating ox_lib if you’re not on the latest.

**Comment by GeerdoDaGr8** [comment]
When i update inventory and ox_lib to the latest release i have this issue buit when i revert back i no longer have these issues.  I dont know what else i can provide to try and get this resolved.

**Comment by LukeWasTakenn** [comment]
This still seems to be the only report of this issue I've seen, really not sure what's going on here.

**Comment by thelindat** [comment]
I've asked for some debug information a dozen times and gotten nothing. Closing.
