### ISSUE TITLE
items not working after a while

### ISSUE THREAD

**Issue by maxcamorra** [overextended/ox_inventory#649]
**Describe the bug**
When I create an item it works fine after the server started but just after a while the item just doesnt work anymore. It works again only after I revive myself or restart the server. What's wrong there? What I have to change ?

This is how I made an item:

```
ESX.RegisterUsableItem('boxrifle2', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
	ox_inventory:AddItem(xPlayer.source, 'ammo-rifle2', 30)
	ox_inventory:RemoveItem(xPlayer.source, "boxrifle2", 1)
end)
```

And in the items.lua of the inventory it's like this:
```
['boxrifle2'] = {
		label = '7.62-Box',
		weight = 240,
		stack = false,
		close = true
	},
```

So basically I have zombies who drop this item. After the server restart I can use the "boxrifle2" directly after I got it dropped but just after a while of killing zombies I can't use the item anymore. Then I have to rejoin, revive me or restart the server to be able to use it again. 

Why is that so? I assume there is nothing wrong but it doesn't work.

Thank you

**Comment by maxcamorra** [comment]
I just found out that I can't use items that I created like above when I have a weapon in my hands. When I put away the weapon I can use all items normal.

**Comment by N-fire** [comment]
That's normal if you want you can add `allowArmed = true` like this:
https://github.com/overextended/ox_inventory/blob/main/data/items.lua#L176
