### ISSUE TITLE
No notification when someone gets robbed with  /steal

### ISSUE THREAD

**Issue by zZOGZz** [overextended/ox_inventory#651]
**Is your feature request related to a problem? Please describe.**
When you use the exxport ``exports.ox_inventory:openNearbyInventory()`` and you take items from the target, the target doesnt get notified how much items they removed/added, like when you buy an item or use an item etc...

**Describe the solution you'd like**
That should be nice because people always know what they get robbed at the moment and should be more easy to people that have a lot of items.

**Comment by LukeWasTakenn** [comment]
Wouldn't this just cause a lot of spam with item notifications?

**Comment by og23rd** [comment]
I dont think, because you dont get robbed every minute. But a normal notification should be good also, its just that the person knows that he is being robbed. What do you think?

**Comment by duckysuck** [comment]
maybe a generic notification 'You've been robbed' and only shows once, rather than per item.

**Comment by Gameadictive** [comment]
Yes but what about do it?

**Comment by ShadowzNight** [comment]
> **Is your feature request related to a problem? Please describe.** When you use the exxport `exports.ox_inventory:openNearbyInventory()` and you take items from the target, the target doesnt get notified how much items they removed/added, like when you buy an item or use an item etc...
> 
> **Describe the solution you'd like** That should be nice because people always know what they get robbed at the moment and should be more easy to people that have a lot of items.

I did it, when Player(A) steal something from Player(B), Player(B) receive the notification of the item stealed/removed from his inventory.
I created a NetEvent with the notification function in _modules/utils/client.lua_, called "ox_inventory:itemnotify".
`RegisterNetEvent('ox_inventory:itemnotify', Utils.ItemNotify)`
![modules/utils/client](https://user-images.githubusercontent.com/34161328/185796812-16388178-e981-49d1-9078-fe7b0df1ceb4.png)

After that, in _modules/inventory/server.lua_ , copy and paste this _if_ like in the images, **3 times**
`if not sameInventory and fromInventory.type == 'otherplayer' then
    TriggerClientEvent("ox_inventory:itemnotify", fromInventory.id, {fromData.label, fromData.name, shared.locale('removed', fromData.count)})
end`
![modules/inventory/server 1](https://user-images.githubusercontent.com/34161328/185796846-99de2e99-e8e5-4ef7-9d9c-32b9262d32d2.png)
![modules/inventory/server 2](https://user-images.githubusercontent.com/34161328/185796853-07675760-a695-484c-aefb-be1bf0932844.png)
![modules/inventory/server 3](https://user-images.githubusercontent.com/34161328/185796888-af10dcfd-67b5-4c69-8065-a00a3bfee19b.png)
