### ISSUE TITLE
Adding Items to trunks/gloveboxes not working properly

### ISSUE THREAD

**Issue by FelixDE** [overextended/ox_inventory#652]
If you add an item to a trunk from a not owned vehicle or a freshly owned vehicle, the item is not in the trunk inventory, if you haven't opened the trunk once before. 

```
exports.ox_inventory:AddItem('trunk'..plate, item, 1, nil, nil, function(success, reason)
        if not success then
            print(reason)
        end
 end)

```
Will print "invalid inventory".

Only if you open the trunk inventory before you call the AddItem Function it will added to the trunk.

**Comment by benzon** [comment]
To be honest i think you need to register the inventory, since it's not created beforehand, so you actually need to create it.

**Comment by FelixDE** [comment]
> To be honest i think you need to register the inventory, since it's not created beforehand, so you actually need to create it.

Yes, but i dont see any export for this case. You can register a stash but not a trunk or glovebox. That would be useful if you want to spawn new vehicles with items in the trunk, like rental cars with the key in the glovebox or job wars with cargo.

**Comment by benzon** [comment]
Naa true there aint a export of it since it's an internal function.

**Comment by benzon** [comment]
You would prop have to create the export your self even tho it clearly says internal function, but ye bit tough  if there is no way around it

**Comment by thelindat** [comment]
> Only if you open the trunk inventory before you call the AddItem Function it will added to the trunk.

The inventory is loaded with information from the vehicle class, which is determined when opening the vehicle.  
Even if I did a similar rework as I did with stashes so they can be instantiated by the server, I still need to know the vehicle class - which isn't stored anywhere.
