### ISSUE TITLE
AddItem, not properly functioning

### ISSUE THREAD

**Issue by TlYPN** [overextended/ox_inventory#654]
**Describe the bug**
does anyone else get "ghost" items. Like it should give you something however it doesn't actually do it.

For example:

Players will be fishing and succeed upon the mini game and SHOULD catch a fish but sometimes it just doesn't give it to you, now i have debugged and broken apart my fishing system and it doesn't seem to have anything wrong with it. 

This also seems to be presistent with another one of my "giveitem" systems as well

**To Reproduce**
Using either the built in "add item" system for ox or even the "giveitem" function for esx.

**Expected behavior**
To give said item to the player

**Additional context**
If there is any confusion i am more than will to create a small video and provide it so you understand.

**Comment by benzon** [comment]
Same test made on current release version.

Every item is adde correct.
