### ISSUE TITLE
Can't open inventory at this moment

### ISSUE THREAD

**Issue by WhereiamL** [overextended/ox_inventory#656]
I noticed that a lot players on my server started to complain that they can't search other players.
I tried the search function with my admin panel ,it's working.
Tried the search function with export for police / gang , it's not working.
I get the message "You can't access this inventory at this time"
I tried to update/downgrade , still same.
Updatex oxmysq, ox_lib , still the same.
Sometimes it's working let's say for player A but for player B it's not.

**Comment by Upsszao** [comment]
Same problem here!
