### ISSUE TITLE
I think I have a mess going on.....

### ISSUE THREAD

**Issue by BRAD845** [overextended/ox_inventory#657]
This maybe can help.....I have upgraded to this version and this is what happened.....sorry im very new at this as I tried to mimic some of the stuff from the previous setup of ox that was installed.....any help would be super appreciated

![mess](https://user-images.githubusercontent.com/103504132/162948993-fdfd85f6-cda5-4617-8b7e-1e99cd28e99c.JPG)

**Comment by BRAD845** [comment]
why did this get closed?

**Comment by LukeWasTakenn** [comment]
User error.
