### ISSUE TITLE
Can't open inventory

### ISSUE THREAD

**Issue by BigYoo93** [overextended/ox_inventory#659]
Someone sometimes cant open inventory i don't know whats happend but when i restart the script then he can open again

![obraz](https://user-images.githubusercontent.com/83595218/163193698-8ab162ef-ef2b-48f3-8c42-508f1b95ed6d.png)

**Comment by ArGo75** [comment]
me too

**Comment by LukeWasTakenn** [comment]
"Someone sometimes" isn't a valid reproduction step, if somehow you could give negative amount of info in an Issue, this one might be it.

**Comment by BigYoo93** [comment]
I write it like that because its weird i connect with my friend to serwer and try to open inventory and we cant but sometimes works perfectly idk whats happend but when we in server and ensure ox_inventory then again we can use inventory. We nothing do
