### ISSUE TITLE
Weapon bug, ammo dupe

### ISSUE THREAD

**Issue by kFxDaKing** [overextended/ox_inventory#661]
There is bug with weapons, and ammo duplication/infinite ammo.

1. Video / Weapon bug - https://streamable.com/0fa0ld
- Take weapon in hands
- Open inv, and move another weapon to the slot, where is your current weapon
- Weapons that you hold should holster, but it doesnt.

2. Video / Infinite ammo - https://medal.tv/clips/hDWkjYolp2s-E/vpbfA2OTp?invite=cr-MSxCSnEsNTkwMjEwNDIs
- You can also dupe ammo with it.

**Comment by kFxDaKing** [comment]
Which commit fixed it please?

**Comment by LukeWasTakenn** [comment]
https://github.com/overextended/ox_inventory/commit/b52bb54f53a1122a91b44f46598e7dd11db6f3f4
