### ISSUE TITLE
Items are not stacking while fast moving them

### ISSUE THREAD

**Issue by kFxDaKing** [overextended/ox_inventory#662]
**Describe the bug**
When you move for example money to storage, where is another pack of money, it wont stack if using fast move, you have to move money by mouse to another money to stack it.

**To Reproduce**
https://streamable.com/cr6adu

**Expected behavior**
Should automaticaly stacks stackable items, if u using fast move.

**Comment by LukeWasTakenn** [comment]
This is likely happening because the `findAvailableSlot` function in the UI finds the empty slot first before getting to the item that it can stack with

https://github.com/overextended/ox_inventory/blob/184599db5ca3c01a7d5d9786657aaa8b6119cfb1/web/src/helpers/index.ts#L12-L20
