### ISSUE TITLE
Weapon bug, ammo dupe

### ISSUE THREAD

**Issue by kFxDaKing** [overextended/ox_inventory#670]
There is bug with weapons, and ammo duplication/infinite ammo.

Part of this was fixed in #661 , it doesnt work when you move weapon from another storage (right inventory) but if you move the weapon from left inv, it works.

https://medal.tv/games/gta-v/clips/imgRCHCfO9zCV/d1337NcwODzp?invite=cr-MSxyZXQsMzQ3MzUxNDEs

**Comment by thelindat** [comment]
Weapon is always set back to the correct ammo, no matter how many times I copy what you're doing in the (laggy as fuck) video.

**Comment by kFxDaKing** [comment]
Tried latest relase and its still happening, here is better video, with latest relase.

**Video:** https://youtu.be/Q16f9-pRYwE

**Repro steps:**

1. Get for example WEAPON_ASSAULTRIFLE
2. Get 30x ammo-rifle2
3. Get for example 100x money item.
4. Take weapon in hands and load it with ammo.
5. Shoot untill you have no ammo left (dont holster)
6. Move money item, to the slot where is your weapon located and after that move weapon back.
7. Holster and unholster.
8. Now you have ammo again.

**Comment by thelindat** [comment]
> * Get for example WEAPON_ASSAULTRIFLE
> 
> * Get 30x ammo-rifle2
> 
> * Get for example 100x money item.
> 
> * Take weapon in hands and load it with ammo.
> 
> * Shoot untill you have no ammo left (dont holster)
> 
> * Move money item, to the slot where is your weapon located and after that move weapon back.
> 
> * Holster and unholster.
> 
> * Now you have ammo again.

That's what I did, and is what I just did again. Ammo is 0, weapon durability is 99.

**Comment by Antro3** [comment]
I'm having the same problem, exactly what's happening to Kfx.

**Comment by kFxDaKing** [comment]
> > * Get for example WEAPON_ASSAULTRIFLE
> > * Get 30x ammo-rifle2
> > * Get for example 100x money item.
> > * Take weapon in hands and load it with ammo.
> > * Shoot untill you have no ammo left (dont holster)
> > * Move money item, to the slot where is your weapon located and after that move weapon back.
> > * Holster and unholster.
> > * Now you have ammo again.
> 
> That's what I did, and is what I just did again. Ammo is 0, weapon durability is 99.

Are you giving yourself "fresh" weapon?

**Comment by thelindat** [comment]
> Are you giving yourself "fresh" weapon?

Of course.

Now if this is something specifically happening with weapons from a saved stash that would be _entirely new information_. Find me a way to actually reproduce this with all specific variables, or hell test it on a fresh install to see if you can reproduce it there - but right now it isn't something that seems to be an issue from my testing.

**Comment by luchowolf** [comment]
the same thing happens to me with all weapons

**Comment by Tinky124** [comment]
Same problem

**Comment by thelindat** [comment]
Don't need a bunch of parrots with #metoo nonsense.

You can see the information and evidence given, and it has not been reproduced in multiple tests. If you don't have anything to contribute, then don't comment.
