### ISSUE TITLE
Notification Styling Not Working

### ISSUE THREAD

**Issue by EpKouhia** [overextended/ox_inventory#671]
https://github.com/overextended/ox_inventory/blob/ed9b7f790c772279aaf5ec90c59961c3fcbe93f9/modules/utils/client.lua#L64
Ox_lib style cannot be string, problem solved maybe by removing the line and pass data into the lib.

**Comment by LukeWasTakenn** [comment]
Resolved in commit cec07544c82ccd3374b658ffe16cdea0ba9bad5f.
