### ISSUE TITLE
Hint for opening inventory

### ISSUE THREAD

**Issue by GFA-SkyRanger** [overextended/ox_inventory#672]
I have put in
`\client.lua`
on line 433 the following Code, to inform the user, he can open his F2 / Inventory, with a sound:

```
                            if closestMarker[4] == 'Liquor' or closestMarker[4] == 'General' then
                                exports.bulletin:Send('Drücke ~y~[F2] ~w~um was zu kaufen.')
                            end

                            if closestMarker[3] == 'drop' then
                                exports.bulletin:Send('Drücke ~y~[F2] ~w~um das aufzuheben.')
                            end
                            
                            if closestMarker[3] == 'shop' and closestMarker[4] == 'PoliceArmoury' then
                                exports.bulletin:Send('Drücke ~y~[F2] ~w~um die Waffenkammer zu öffnen.')
                            end

                            if closestMarker[3] == 'stash' and closestMarker[4] == 'policelocker' then
                                exports.bulletin:Send('Drücke ~y~[F2] ~w~um Deinen Spint zu öffnen.')
                            end
```

So i cannot find the code for the markers in the new, updated version.
where can i put this code aain? i want to have the user informed optical and acoustical, so he is able to open something... a drop, a shop, or whatever, i can define.

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/blob/main/modules/shops/client.lua#L95-L103
https://github.com/overextended/ox_inventory/blob/main/modules/inventory/client.lua#L163-L171
https://github.com/overextended/ox_inventory/blob/main/client.lua#L739-L745

**Comment by GFA-SkyRanger** [comment]
Oh great, thank you very much for the quick answer, so I can install the new version right away. 
I hope the trash cans and the coke machines work now.

So before that was better, at least everything was in one place. 
I had a debug message in it, where I had indicated that if I was standing at what, what you could do on what it was, now I have to install it in three different places. 

Have you ever thought about installing your code correctly? 
If I have the opportunity to open a shop, the game is usually informed that he can open it, that's just missing.

but no matter, you're doing a great job! Thank you very much for that!

**Comment by GFA-SkyRanger** [comment]
Is there a variable, where i can check, if the inventory is open?
it calls my message in loop, so i want to prevent that. 
for this i have to get anything like` isInventoryOpen true / false`
