### ISSUE TITLE
[Help] Trunks

### ISSUE THREAD

**Issue by GFA-SkyRanger** [overextended/ox_inventory#673]
Is it possible to assign different trunks to different cars?
And how do the numbers relate to the categories?
data/vehicles.lua
e.g. [9] = {11, 88000} -- Offroad
Where is the number 9 defined with the category "offroad"?
Where are the vehicles associated with the appropriate category?

I use esx_advancedvehicleshop which in turn uses different database tables for the categories and vehicles.

I can't figure out where and how this is connected to the vehicles.lua in the data folder to make changes.

I'm trying to "rub" a trunk to a specific vehicle. I need it for esx_jobs. Vehicles that do not belong to me are made available there. But I need access to the trunk.

Glove compartment works, but is somehow not saved or deleted.
8 stones became a coke can.
that's useless for a job.

**Comment by thelindat** [comment]
> Where is the number 9 defined with the category "offroad"?

https://docs.fivem.net/natives/?_0x29439776AAA00A62

> Glove compartment works, but is somehow not saved or deleted.

Unowned vehicles do not have persistent storage through restarts.
