### ISSUE TITLE
People losing items

### ISSUE THREAD

**Issue by WhereiamL** [overextended/ox_inventory#679]
**Describe the bug**

People keep losing stuff on my server when they do relog/crash. There is no errors at all. It's random happening. I tried to debug but everything seems to work without any issues. I'm not the only one who is experiencing this problem.

**Comment by thelindat** [comment]
Player inventory saving is handled by esx

**Comment by WhereiamL** [comment]
So what should I do then ?

**Comment by thelindat** [comment]
Not here.
