### ISSUE TITLE
Update vehicle inventory identifier when plate changes

### ISSUE THREAD

**Issue by Donad555** [overextended/ox_inventory#682]
**Is your feature request related to a problem? Please describe.**
Yes, if we change the vehicle's registration number (plate), the inventory will be deleted.

**Describe the solution you'd like**
A function that sets the inventory to a new license plate and then changes the license plate internally for storage in the DB.
The Plate should then be cleared so that items are not duplicated

**Describe alternatives you've considered**
an export to Save the license plate in the DB and then delete it from the internal script memory.

**Additional context**

**Comment by thelindat** [comment]
Inventory is stored **in the owned_vehicles** table, on the vehicle in question. How would the inventory be “deleted”?

**Comment by Donad555** [comment]
If we change the number plate of the vehicle, the new number plate will be stored in DB. However, the old license plate is stored in the inventory system and the inventory is not saved later, since the inventory system only saves at intervals and on the old license plate.

The items then only exist if they were saved at the last interval.

**Comment by thelindat** [comment]
Been meaning to add an export for unloading an inventory by id for a while; will look at this soon probably.

**Comment by thelindat** [comment]
I'm dumb.
`Inventory.Remove` already exists. Bit inconvenient for vehicles though.
