### ISSUE TITLE
prices differ from shops.lua to ingame

### ISSUE THREAD

**Issue by duckysuck** [overextended/ox_inventory#687]
**Describe the bug**
Setting prices on the shops.lua doesnt seem to match up to what is seen in-game.

**To Reproduce**
1. set price for item in youtool for instance for zipties
2. restart ox_inventory
3. goto youtool and view shop items
4. Notice prices are different for some but not all

**Expected behavior**
All prices should match shops.lua

**Screenshots**
![image](https://user-images.githubusercontent.com/4807016/165645575-633a0ceb-8dbc-47f7-a214-b868c205ec68.png)

**Comment by thelindat** [comment]
```
# Item prices fluctuate in shops
set inventory:randomprices false
```
