### ISSUE TITLE
AimedFire Convar

### ISSUE THREAD

**Issue by ohqpr** [overextended/ox_inventory#689]
**Describe the bug**
When using `setr inventory:aimedfiring true` melee weapons become broke.

**To Reproduce**
1. Enable `setr inventory:aimedfiring true` in your convar.
2. Spawn in brass knuckle, bat, etc. or any melee weapon.
3. Attempt to swing on someone with the melee weapon.

**Expected behavior**
The ability to use melee weapons.

**Additional context**
- **Game Version:** 5489
- **Client:** Production
- **Inventory Build:** v2.8.3
- **Framework:** Overxtended ESX

**Comment by thelindat** [comment]
Resolved.
