### ISSUE TITLE
Errror when Equip Gas Can

### ISSUE THREAD

**Issue by DerBro11** [overextended/ox_inventory#691]
Hello everyone,

I tried to fix my Legacy Fuel with ox_inventory but when i empty it and reeqiup (Yes it doesnt delete), it has 100 Ammo, when i empty a little bit and put it away and reequip the JerryCan has 100 Ammo, My Server Console throws an error:

`[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:1313: attempt to compare number with nil`

i tried to print the weapon hash before the if clause, and it throws a nil value.

Isn't it possible to request a weapon hash anymore?

**Comment by viper052186** [comment]
Hi,

if you use jerry can it will not fill the car gas...also some times u cannot target the vechicle..

i use the updated qtarget and ox_inventory
