### ISSUE TITLE
Trunk Config won't work

### ISSUE THREAD

**Issue by GFA-SkyRanger** [overextended/ox_inventory#692]
i want to specify trunks of vehicles but it wont work.

`        models = {
            ['mule1'] = {250, 2000000},
            ['mule2'] = {250, 2000000},
            ['mule3'] = {250, 2000000},
            ['hvywrecher'] = {111, 888000},
            ['t440boxbara'] = {900, 7200000}
        },`

doesnt change anything if i change there any numbers.

are the 8000 per slot a suggestion or is this hardcoded somewhere?
there are too much slots i think.

**Comment by GFA-SkyRanger** [comment]
Still no Answer yet, but need to know, how.
thx

**Comment by LukeWasTakenn** [comment]
In the code you provided you're defining the models as strings instead of hashes.

Replace your `'` with `
