### ISSUE TITLE
Intems Container -  They do not save items when the server restarts

### ISSUE THREAD

**Issue by Goz-exe** [overextended/ox_inventory#693]
**Describe the bug**

If I leave and come back from the server the items count to remain inside the paperbag if I restart the server instead they disappear

**Comment by N-fire** [comment]
Make sure to either use txAdmin scheduled restart or use `/saveinv`  before restarting

**Comment by Goz-exe** [comment]
> Make sure to either use txAdmin scheduled restart or use `/saveinv` before restarting


ah so not using TxAdmin when I reboot do I lose things?

**Comment by N-fire** [comment]
yes, you must use txAdmin scheduled restart in prod
https://github.com/overextended/ox_inventory/blob/main/modules/inventory/server.lua#L1266-L1272
