### ISSUE TITLE
Stacked Items Metadata doesn't update separately

### ISSUE THREAD

**Issue by Senlar** [overextended/ox_inventory#694]
**Describe the bug**
If you try to update metadata for items that you transfer from a stack, it updates the metadata for all items regardless of the inventory and slot you attempt to update the metadata of. It acts as if the entire stack is linked somehow even if its in different inventories.

**To Reproduce**
1. Go to inventory\server.lua
2. Line: 1040 find
```
fromInventory.items[data.fromSlot] = fromData  
toInventory.items[data.toSlot] = toData
```

3. Add this ABOVE that code.
```
if toData then
	if toData.name == 'water' then 
		if toInventory.type == 'player' then
			toData.metadata.durability = 10
		else
			toData.metadata.durability = 50
		end
	end
end
```
5. Restart script
6. Give yourself a stack of water
7. Move part of that stack into a different inventory, you will notice that BOTH the water in your inventory AND the water you move both will end up with 50 durability.

**Expected behavior**
I would expect only the water moved into the other inventory (toData/toInventory) to have the metadata updated.

**Additional context**
(https://streamable.com/t2ho9s)

**Comment by thelindat** [comment]
Why are you editing metadata during the swapSlots event

**Comment by Senlar** [comment]
Because I want to update certain items that are going into certain stashes or trunks. I have refrigerators in my housing and when the items go in I want to modify them.

**Comment by Senlar** [comment]
I have tried using Inventory.SetSlot and Inventory.SetMetadata and the same thing happens. It just seems like no matter what I try, stacked items stay linked somehow.

**Comment by thelindat** [comment]
Last commit should fix, don't have time to test.

**Comment by Senlar** [comment]
> Last commit should fix, don't have time to test.

Yea, that looks to have fixed it! Thanks!
