### ISSUE TITLE
Issues with RemoveItem

### ISSUE THREAD

**Issue by Kallock** [overextended/ox_inventory#696]
**Describe the bug**
When using exports.ox_inventory:RemoveItem with no metadata, it works (But removes any existing metadata of an item with metadata if any remain).

 But passing it **WITH** metadata, and no slot, it does not seem to work at all

I took a peeking inside and noticed it was triggering the function, GetItemSlots in the removeitem function and while peeking at that it seems to get stuck on the table.matches, I believe (from ox_lib?)

**To Reproduce**
Pass RemoveItem with Metadata, string or table

**Expected behavior**
Removal of items with said metadata being passed

This is the metadata that was sent to the function before the table.matches 
(v.metadata) and
(metadata)
![image](https://user-images.githubusercontent.com/56092478/166237960-3a2875e0-1557-4ed4-af51-cb525f36db29.png)

**Additional context**
Maybe it's a me issue, if so, I'll commit sudoko.

**Comment by thelindat** [comment]
table.matches requires the two tables to be equal (contain the same values).
I'll have to look into metadata being removed.

**Comment by Kallock** [comment]
I'll give it a try tonight/tomorrow morning and let ya know

**Comment by thelindat** [comment]
Tested it now and committed.
My recommendation for removing items with a bunch of metadata is to remove by slot id.

The search method will return items that contain metadata (rather than matching tables).
