### ISSUE TITLE
Trunk/Glovebox items missing after update

### ISSUE THREAD

**Issue by DistrictZion** [overextended/ox_inventory#701]
**Describe the bug**
Trunk/Glovebox items and details are shown under owned_vehicles table but it does not show up in game. 
Also, owned vehicles also shows random loot. All saved items now became random loot. and We can save new items, and it gets saved somehow. But not to the table in owned_vehicles.

Was there a change regarding this? If not, its a bug or I have no idea what I'm talking about.

**To Reproduce**
Updated to latest version [this was the only change we made]

**Expected behavior**
Owned Vehicles should have everything saved since before.. Using ox_inventory since v2.2.1 and this never occured

Screenshots
1. Trunk in Database : 
![unknown](https://user-images.githubusercontent.com/78443434/166460053-722d46dc-a9b5-4d8c-a1a3-15349c7ade0c.png)

2. Trunk in game : 
![unknown (1)](https://user-images.githubusercontent.com/78443434/166461053-3bdce2bb-9b12-474d-84b8-1ac5863c25d5.png)

**Comment by thelindat** [comment]
> it gets saved somehow. But not to the table in owned_vehicles.

Which puts this where exactly?
![image](https://user-images.githubusercontent.com/65407488/166461571-9994f8b1-9208-4dfc-8a0f-f2e68839845a.png)

If it opens with random loot, then it _can't_ save to the database since it's marked as temporary storage. If it's not finding the vehicle in the database I can only assume the platetrim convar is set incorrectly, but you claim it's saving.. somewhere?

**Comment by thelindat** [comment]
> Yes.. It is saving somewhere.. which is the weird part, :|

Okay please for the love of God be less vague. Where is _somewhere_.

> The old database table

What "old database table" are you referring to? Still no information.

> not the ones shown in DB

Database saves every ~10 minutes.

**Comment by DistrictZion** [comment]
This is given in config 
setr inventory:trimplate false

> Okay please for the love of God be less vague. Where is somewhere.
I don't know. That's why I keep mentioning "somewhere". Is there an alternative sql given in ox inventory other than owned_vehicles--trunk/glovebox. I said that to know if you know about this. 

> What "old database table" are you referring to? Still no information.
Not old. The database stays the same [10 mins or 1 hour later] after I moved some items into the trunk/glovebox. The change does not reflect in the database. But, the change I did in game is shown in game. 
You see why this is all very confusing right? English isn't my first language, I'm trying my best to convey what I am going through. Sorry about it .

**Comment by thelindat** [comment]
> no spaces in LAM999 both in the db or the inventory
> setr inventory:trimplate false

Which means you _want_ trimplate.

> alternative sql given in ox inventory

What?

> The old database table
> Not old. 

What?

>  database stays the same [10 mins or 1 hour later]
> The change does not reflect in the database

Because you're not trimming whitespace, even though you said elsewhere that plates have no spaces.

> the change I did in game is shown in game

Because the database state has nothing to do with the in-memory inventory state, which in this instance isn't even recognised as an "owned_vehicle" because you aren't trimming plates.

**Comment by DistrictZion** [comment]
Alright. I will change  setr inventory:trimplate to true. But, It was always kept false since 2.2.1. 
I was at 2.5.2 before I updated to 2.8.3

**Comment by DistrictZion** [comment]
And 2.8.3 is when this started occurring.

**Comment by thelindat** [comment]
It didn't start occurring _at_ 2.8.3, it started after you updated _to_ 2.8.3.

There is a _lot_ of releases between 2.5.2 and 2.8.3 and nobody has reported losing access to previous vehicle storage.

**Comment by DistrictZion** [comment]
> It didn't start occurring at 2.8.3, it started after you updated to 2.8.3.

It being the problem that I'm facing. Was not complaining on the Inventory! 
You may close this. Thank you for the help. :)
