### ISSUE TITLE
Inventory error after conversion

### ISSUE THREAD

**Issue by Ricko0o** [overextended/ox_inventory#702]
**Describe the bug**
I’m updating from DP_inventory to OX, have the ESX (1.6), latest ox_inventory, ox_lib, oxmysql. ran the conversion, which updated the users inventory column in the db, but when I join the server, I get an error "@ox_inventory/client.lua:839: attempt to index a nil value (local '(temp)' )… any ideas?
**To Reproduce**
1. imported users table, ran setup/convert.lua/removed convert.lua from maifest/ rebooted server.
2. Click on F2 to open inventory, got above error in F8 console

**Expected behavior**
expectedthe inventory to open

**Screenshots**

**Additional context**
![oxerror](https://user-images.githubusercontent.com/84867571/166564590-f06fd020-6e12-436a-a873-ce83aca9a80b.jpg)

**Comment by thelindat** [comment]
Might be invalid item in inventory, though that shouldn't throw any errors afaik

**Comment by Ricko0o** [comment]
ok, new problem.. or question.. Is the convert.lua supposed to clear items from player inventory and move them to the ox_inventory table? I ran the convert again, and left the money and black money in the users table, but deleted the other items

**Comment by Ricko0o** [comment]
scratch my last.. I reloaded the users table, ran the convert again and I'm back to the first problem. I tried bumping the slots to 150 thinking that might be an issue because some items aren't stackable and with my character, it ended up filling 63 slots, but no luck...

**Comment by Ricko0o** [comment]
what is that "temp" the error is referring to?

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/166870746-a4278dd6-1851-4cf9-8ff3-05026507e29a.png)

One of those table indexes is nil, except I don't see _any_ feasible way for that to be the case.
Add the following for me above `Items[data.name].count += data.count`.
```lua
print(data.name)
print(data.count)
print(Items[data.name])
```

**Comment by Ricko0o** [comment]
[ox.txt](https://github.com/overextended/ox_inventory/files/8631578/ox.txt)

also got this after I ran the convert.lua this time..
![ScreenShot_20220505091105](https://user-images.githubusercontent.com/84867571/166933459-e8746a03-aa2e-4a60-ba61-9c29c77f9251.jpeg)

**Comment by thelindat** [comment]
Last commit should fix it.
