### ISSUE TITLE
shops.lua bug report.

### ISSUE THREAD

**Issue by BalloutJay** [overextended/ox_inventory#703]
in my shops.lua im putting the coordinates. And it's not placing the shops In there. 

Image Of Me Putting The Coordinates In : 
!https://user-images.githubusercontent.com/98054918/166823515-07977c3c-4b72-445e-ae70-d6faca660362.png

Image Of Me At The Coords ( In the FiveM Server ) : 
https://user-images.githubusercontent.com/98054918/166823736-1d5bf3e7-7a46-4b66-bf01-bed7f6c79cd4.png

And i need to get unbanned from the cord Discord Name : Jaay#6873.

**Comment by thelindat** [comment]
A picture of only worth a thousand words when it's not cropped to be smallest possible amount of information possible.

> And i need to get unbanned

![image](https://user-images.githubusercontent.com/65407488/166825995-b7abcc2a-7459-4849-8f8b-9e43300a3480.png)

No.
