### ISSUE TITLE
Discord related! Sorry I had to raise this here...

### ISSUE THREAD

**Issue by Emichikox** [overextended/ox_inventory#704]
Hi, 
This is my Discord ID. I was a part of OX inventory discord for 3-4 months. I was kicked suddenly and I cannot join again. Seems like 
I was banned. I don't know what mistake I did. 

Discord ID: SkyeDox#0820

Please let me know because it is an amazing community and I was enjoying being part of it. :)

**Comment by Emichikox** [comment]
I raised this here because I did not know where else I can do this.

**Comment by LukeWasTakenn** [comment]
you were banned by Warden for being in leaking or cheating Discord communities, when you make an appeal in Warden's Discord server you'll be automatically unbanned.

https://discord.com/invite/warden
