### ISSUE TITLE
Giving millions of money within players

### ISSUE THREAD

**Issue by Nag1ch4n** [overextended/ox_inventory#705]
**Describe the bug**
So the bug is simple, player hands up and other person turn off his wifi, or disconnects ethernet cable, the second person steal his money and the player is still few seconds on server, then it kicks him, after he joins back he still have his money and second player have it too, players can reproduce this way millions of money.

**To Reproduce**
1. Hands up
2. Disconnect wifi / ethernet cable
3. Second player rob you for any item / money
4. After it disconnects you connect back
5. See, you have items / money and second player too

**Expected behavior**
To be honest i didn't wanted to try it, the bug we found by accident when player gives like 50 millions, and with logs we can see what he done and we tried it and it works.

**Screenshots**
I don't really have any photos, you really need to try it yourself.

**Comment by thelindat** [comment]
Repro failed and user could not repro on their dev server.
Closing this issue, but if they find something they can DM me.

Personally don't see _how_ it would be possible.
