### ISSUE TITLE
Keybind Feature Request

### ISSUE THREAD

**Issue by JohnnyS** [overextended/ox_inventory#706]
Not related to a problem more of a suggestion/question if it is possible to remove the secondary inventory and just have the F2 key open the secondary inv when near it. For example, if you are in a vehicle and you press F2 you cant access the glovebox hence the 2nd keybind is there. However, it would be more seamless for it to be available when just hitting F2

Ability for the main keybind to detect if there is the glovebox available to be opened or if the trunk should be opened

**Comment by thelindat** [comment]
There's been multiple PR's for this, except it's broken in basically every single possible way.
Requires _a lot_ of changes to not fuck everything, needs to attempt to open multiple inventories (if unable to access secondary, open primary), etc.

Benefit is almost non-existent.

**Comment by JohnnyS** [comment]
> There's been multiple PR's for this, except it's broken in basically every single possible way. Requires _a lot_ of changes to not fuck everything, needs to attempt to open multiple inventories (if unable to access secondary, open primary), etc.
> 
> Benefit is almost non-existent.

All good wanted to see if it was ever talked about or not, it is very small just a small little QoL improvement for some people but like you said basically non existent. Thanks @thelindat !
