### ISSUE TITLE
The Models in Shops are not working

### ISSUE THREAD

**Issue by GFA-SkyRanger** [overextended/ox_inventory#713]
Thos Models wont work at all.
if i stand beside any of those Models, i cannot get any of the items in there, even if i put own items, which are working, in them.
I have tryed with other models like prop_news_disp_02a for making a newspaperdispenser, but even this one wont work.

The following code from data/shops.lua is original except the name variable.

	VendingMachineDrinks = {
		name = 'Warenautomat',
		inventory = {
			{ name = 'water', price = 10 },
			{ name = 'cola', price = 10 },
		},
		model = {
			`prop_vend_soda_02`, `prop_vend_fridge01`, `prop_vend_water_01`, `prop_vend_soda_01`, `prop_vend_coffe_01`, `prop_vend_fags_01`, `prop_vend_snak_01`
		}
	},

**Comment by thelindat** [comment]
Can you stop using github for support? Or are you banned from discord for using leaks?

Shops linked to a model are for qtarget.

**Comment by GFA-SkyRanger** [comment]
I will never use discord. This is just as bad a data octopus as google.
And every idiot uses discord, and thus sells his soul.
There are better alternatives.
