### ISSUE TITLE
Save Dumpsters Inventories

### ISSUE THREAD

**Issue by StopherTv** [overextended/ox_inventory#714]
Hey,
First thing, thank you for this inventory système.

Second thing, i suggest you to make update about saving dumpsters inventories maybee on a json files,  a new table on database or datastore_data table. 

Why saving? 
Cause lots of people who making illegual thing on rp, use it  for delivering weapons, drugs or other items. But when restarting server or just inventorie all in dumpsters are reset. So when a server crashing it could be too shy to giveback items when a big part of players use this systèm.

Thank you again and have a nice day !!!

**Comment by thelindat** [comment]
Requires a rewrite of the dumpster system, which will need to be done _eventually_ for better sync, entity lockdown, etc.

**Comment by thelindat** [comment]
As much as dumpsters need to be improved, there's nearly 8k dumpster locations.
There's no real way to set a unique identifier for dumpsters to persist between sessions and be properly supported server-side.

Coordinates and frozen dumpsters are the only thing that come to mind; unless somebody has another idea.

**Comment by eprimex** [comment]
> As much as dumpsters need to be improved, there's nearly 8k dumpster locations.
> There's no real way to set a unique identifier for dumpsters to persist between sessions and be properly supported server-side.
> 
> Coordinates and frozen dumpsters are the only thing that come to mind; unless somebody has another idea.


How i fixed this issue on my server a couple years ago was always when someone triggers looting dumpster it sends coords and obj id of dumpster to server then it checks has a obj been used within range of 2. I didn't store data on db because i reseted the dumpster cache every 6 hour but if someone wants a system where you can put stuff in dumpster then sure use db for them. Sure dist check of 2 isn't perfect but it works good enough for our purpose

**Comment by thelindat** [comment]
Keep in mind dumpsters aren't (or shouldn't be) networked so all you can do is coord checks, and dumpsters can be much closer than 2 units by default or moved well outside that range.

**Comment by eprimex** [comment]
> Keep in mind dumpsters aren't (or shouldn't be) networked so all you can do is coord checks, and dumpsters can be much closer than 2 units by default or moved well outside that range.

Networking them would be stupid and cause more harm than help. Coords check isn't perfect but there really isn't a perfect way of doing it. Reason i used range of 2 was people wouldnt grind 3 closest dumpsters that way only 1 out of few closest dumpsters actually had something
