### ISSUE TITLE
Disable TAB Option?

### ISSUE THREAD

**Issue by Gameadictive** [overextended/ox_inventory#718]
**Is your feature request related to a problem? Please describe.**
Yes, my players want to use the normal radial weapon menu instead of the tab one with numbers usable one.

**Describe the solution you'd like**
A way to disable the tab function and let the radial normal menu be able with a option to true or false in config.

**Comment by N-fire** [comment]
did you even read the documentation ?
https://overextended.github.io/docs/ox_inventory/Functions/Client/Utils/weaponWheel

**Comment by thelindat** [comment]
> did you even read the documentation ? https://overextended.github.io/docs/ox_inventory/Functions/Client/Utils/weaponWheel

Irrelevant, he wants to _always_ use the radial menu. Which won't happen.
