### ISSUE TITLE
Multiple reasons why I am raising this here, sorry if this is the wrong place. 

### ISSUE THREAD

**Issue by DistrictZion** [overextended/ox_inventory#725]
Good Evening, I hope you're having a wonderful day.

I am facing a problem with ox_lib [due to my lack of knowledge not issue per se]
I used this code somewhere [not important] in my server. 

> local input = lib.inputDialog('Police locker', {
>     { type = 'select', label = 'Value select', options = {
>         { value = 'option1', label = 'Option 1' },
>         { value = 'option2', label = 'Option 2' },
>         { value = 'option3', label = 'Option 3'},
>     }}
> })
> local selection = json.encode(input, {indent=true})

I cannot fetch the value of selection. Again, I don't know how to fetch it as 1 string. So, if I need the value of selection as 'option1', how would I do that?

Also, I would have asked this in the overextended discord group, but I was banned. I had appealed from Warden too, and it was not even intended. I cleared everything with them. 

Discord ID : SkyeDox#0820

**Comment by thelindat** [comment]
> I had appealed from Warden too, and it was not even intended. I cleared everything with them.

You should be automatically unbanned, but apparently you were not. 🤷
This isn't related to the inventory at all, so not sure why you've posted it here.

`print(json.encode(input, {indent=true}))` will show the contents of the table; surely you can figure out how to index the table.

**Comment by DistrictZion** [comment]
I'm a spud. :|
If I knew it, I would not have asked. 
input[1]? :)
