### ISSUE TITLE
Routing bucket bleed

### ISSUE THREAD

**Issue by aqua3man** [overextended/ox_inventory#733]
**Describe the bug**
Some parts of inventory is bleeding cross routing buckets.

**To Reproduce**
1. Login with user A to bucket 0
2. Login with user B to bucket 1
3. Teleport to same position in world with both users
4. Drop an item on the ground
5. Drop is shown cross bucket

**Comment by thelindat** [comment]
“Bleed”. Nice way to make it sound so fucking dramatic.

There’s no events for routing buckets, and the client has no concept of them. There’s some statebag you can set in the client that Loaf and I decided to use for exactly this.

**Comment by thelindat** [comment]
LocalPlayer.state.instance = value

Can be anything arbitrary like a property name, or routing bucket ids.
