### ISSUE TITLE
(bug) player will punch other when click/drag in inventory

### ISSUE THREAD

**Issue by Steviol** [overextended/ox_inventory#738]
**Describe the bug**
Some player have this weird bugs, and this print out error in the console. This bug player will punch other when click/drag in inventory

**Screenshots**
![Screenshot_1941](https://user-images.githubusercontent.com/29462114/173232571-ab7b56d5-91d9-4363-8ec7-0260d673cdcf.png)

**Comment by thelindat** [comment]
That specific line would require you to be holding `WEAPON_PETROLCAN`, `WEAPON_HAZARDCAN` or `WEAPON_FIREEXTINGUISHER`; and shouldn't even trigger while the inventory is open (shooting is disabled).

I also don't see how currentAmmo would be nil, but `currentWeapon.metadata.ammo - 0.05` didn't throw an error (you can't subtract from nil).

![image](https://user-images.githubusercontent.com/65407488/174440103-aff35933-f18e-476b-bf97-e341dda81617.png)
