### ISSUE TITLE
(bug) amount not the same as output

### ISSUE THREAD

**Issue by Steviol** [overextended/ox_inventory#740]
**Describe the bug**
sometimes amount not the same as output

https://user-images.githubusercontent.com/29462114/173569435-4c797e4f-af53-4709-8493-6a2066799b74.mp4

**Comment by N-fire** [comment]
You should use a better anti-virus you have a lot of ads on your script. I recommend you MacCoffea

**Comment by thelindat** [comment]
Your shift key is pressed or stuck.
