### ISSUE TITLE
When creating stores doesn't show

### ISSUE THREAD

**Issue by BalloutJay** [overextended/ox_inventory#742]
So I have made store, and the shops.lua. And it's now showing.|
![image](https://user-images.githubusercontent.com/98054918/174495287-9d6d1902-676e-426c-860e-1663149ac62e.png)
Preview Of the store
![image](https://user-images.githubusercontent.com/98054918/174495371-8f951bfa-7df2-4ef5-af5b-35d36ce801ad.png)

**Comment by LukeWasTakenn** [comment]
> And it's now showing.|

Glad it's working fine for you.

**Comment by BalloutJay** [comment]
Wait @LukeWasTakenn I mean not*
