### ISSUE TITLE
When creating stores doesn't show

### ISSUE THREAD

**Issue by BalloutJay** [overextended/ox_inventory#743]
So I have create a store, and it's not working or not showing the store blip at all.
![image](https://user-images.githubusercontent.com/98054918/174496028-809a42ba-4824-4826-a5ff-72a079d02e42.png)
![image](https://user-images.githubusercontent.com/98054918/174496037-afa38f3c-4d70-47fa-bf61-85947f800c7f.png)

**Comment by thelindat** [comment]
User error, and you don't even grace us with any information.
This report is worthless.
