### ISSUE TITLE
Create a way to use shared inventories without using jobs

### ISSUE THREAD

**Issue by Mgil10** [overextended/ox_inventory#745]
**Is your feature request related to a problem? Please describe.**
I haven't found a way to give a player access to a shared inventory without using jobs. Which is sometimes necessary.

**Describe the solution you'd like**
A function to grant and revoke a user's access to a shared inventory

**Describe alternatives you've considered**
A function to add and remove a group to a user to access the inventory (something similar to the job system)

**Additional context**
This could be useful for gang warehouses (without using the jobs system), for shared houses between several users...

**Comment by thelindat** [comment]
> I haven't found a way to give a player access to a shared inventory without using jobs

Job/group adds a restriction when trying to open an inventory, it doesn't make it shared.
An inventory with no owner is shared.

**Comment by thelindat** [comment]
Search 'job', copy-paste code.

ESX jobs are remapped into groups, where the index is groupName and the value is the grade.
You send through your gang, job2, etc. with the correct format or add additional parsing to put it into the correct format.
Then you add an event handler for when that group changes value.
