### ISSUE TITLE
Clear all inventories 

### ISSUE THREAD

**Issue by GurraG004** [overextended/ox_inventory#748]
If you want to clear an item from every inventory on the server (ox_inventory, users,  owned_vehicles, ...), something that needs to be removed. Or if you just wanna have a weaponwhipe on the server, there is not a way for that. I would like to have it built in as an command and a config where you put item names in a table like.

```
remove_items = {
'weapon_heavypistol',
'lockpick'
}
```

**Comment by thelindat** [comment]
This requires SQL queries and doesn't really need to exist in the resource. Somebody is free to put in the effort and share it, but not planned.
