### ISSUE TITLE
it makes a error with es_extended that doesnt let us on the server

### ISSUE THREAD

**Issue by johnsmith600** [overextended/ox_inventory#750]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
it brings up a error that states
![Screenshot 2022-06-24 183642](https://user-images.githubusercontent.com/105131296/175497522-68324863-3ff5-4b85-9e8e-4b17a9748379.png)
![Screenshot 2022-06-24 183630](https://user-images.githubusercontent.com/105131296/175497539-ce7b9c65-3c76-4c82-bd29-305433260487.png)
 [  script:es_extended] SCRIPT ERROR: error object is not a string
[  script:es_extended] (nil stack trace)Xplayer is nil or player is not register in server table
[  script:es_extended] SCRIPT ERROR: @es_extended/server/classes/overrides/oxinventory.lua:15: attempt to index a number value (local 'v')
[  script:es_extended] > rawExecute (@oxmysql/dist/build.js:21892)
[  script:es_extended] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by thelindat** [comment]
Note how the error originated in ESX and not ox_inventory. I also PR'd a fix _to ESX_ after they broke the function.

**Comment by johnsmith600** [comment]
this isnt complete as i cant get into the server and its the inventory that is making it so i cant get into the server
