### ISSUE TITLE
"GetCurrentWeapon" does not check if you put away the weapon

### ISSUE THREAD

**Issue by Mgil10** [overextended/ox_inventory#751]
**Describe the bug**
"GetCurrentWeapon" returns the last weapon you held in your hand after saving it

**To Reproduce**
1. Pull out a gun
2. Put away the weapon
3. Call the export GetCurrentWeapon() (you will receive the information of the weapon that you no longer have in your hand)

**Expected behavior**
That not having a weapon in the hands returns that the weapon is the hands or something similar

**Screenshots**
<img src="https://user-images.githubusercontent.com/25798464/175610588-831d4ffe-d3fb-4495-a9dc-0e48e2a01d43.png" width="400" height="400">
![image](https://user-images.githubusercontent.com/25798464/175611670-edddafb0-4be9-4da1-b053-5dd93ae698bc.png)

**Additional context**
Everything updated to the latest version

**Comment by Mgil10** [comment]
The "GetCurrentWeapon()" function continues to give me the same thing when it is disarmed

**Comment by thelindat** [comment]
It was resolved and has been tested..
