### ISSUE TITLE
I use 2.91 without any problems, but I got an error when I upgraded 2.92 today

### ISSUE THREAD

**Issue by Tompizza** [overextended/ox_inventory#759]
[ script:ox_inventory] Error loading script modules/init.lua in resource ox_inventory: @ox_inventory/modules/init.lua:87: bad argument #1 to 'load' (function expected, got nil)
[ script:ox_inventory] stack traceback:
[ script:ox_inventory]  [C]: in function 'load'
[ script:ox_inventory]  @ox_inventory/modules/init.lua:87: in function 'data'
[ script:ox_inventory]  @ox_inventory/modules/init.lua:125: in main chunk

**Comment by thelindat** [comment]
User error. Failed to load a resource file.

Line 87 and 125 don't match up at all, so god knows what the issue is.
