### ISSUE TITLE
Bug with inventory spam sql same job safe and wont let them open it

### ISSUE THREAD

**Issue by Burx12** [overextended/ox_inventory#762]
**Describe the bug**
A clear and concise description of what the bug is
Random time it just doesn't let people open jobs safe when they try it spams error that i don't really understand and it makes more then 1 sql for 1 safe and i need to clear all the sql safe inventory then it works again then couple hours it does that again

newest version tried reinstalling 3 times

![unknown2](https://user-images.githubusercontent.com/107647166/178113696-4e044ebf-2ecd-4998-b57c-050948a2f1cd.png)
![unknown](https://user-images.githubusercontent.com/107647166/178113697-11328019-4a8e-4ab5-9368-26ee892f53f4.png)

**Comment by thelindat** [comment]
> makes more then 1 sql for 1 safe

Are you somehow not using the table index?
`UNIQUE KEY `owner` (`owner`,`name`)`

It shouldn't be possible for multiple rows to exist with the same name and owner.

**Comment by Burx12** [comment]
how do i check that im new

**Comment by thelindat** [comment]
```sql
SHOW INDEX FROM ox_inventory;
```
![image](https://user-images.githubusercontent.com/65407488/178114331-d91da297-98f3-416d-ab71-d5cc68f47c39.png)

I don't understand _how_ you don't have indexes, but it certainly seems that you don't. Following will add it.

```sql
ADD UNIQUE INDEX `owner` (`owner`, `name`);
```

**Comment by Burx12** [comment]
ok i will see if this fix my problem and i have a second problem

**Comment by Burx12** [comment]
ok thanks for the help i will see if this fixed my problem

**Comment by thelindat** [comment]
>  i have a second problem

If you're referring to the error from the screenshot, it's because what _should_ be a string is returning a table of strings instead (due to the duplicates in the database).

**Comment by Burx12** [comment]
the second problem was that players could buy gun license but seems now that it fixed

**Comment by Burx12** [comment]
thanks for the help and fast respond <3
