### ISSUE TITLE
Cannot Open Inventory

### ISSUE THREAD

**Issue by FMC-One** [overextended/ox_inventory#765]
As the title says I cannot open the inventory at all. I am pressing F2 but nothing happens. I have all the dependencies and running ox_inventory 2.9.3 release. I also have job creator installed and when I try to open the already made stashes I get an error on the top right corner "You cannot open your inventory right now".

**Comment by teeJ-0** [comment]
I had this same problem, please let me know if someone finds fix! I fixed by creating a new character.

**Comment by thelindat** [comment]
> I had this same problem, please let me know if someone finds fix! I fixed by creating a new character.

That just screams "i ignored an error on the server, as i tried to use invalid inventory data".
