### ISSUE TITLE
Weapon.  lua Request

### ISSUE THREAD

**Issue by frazz1234** [overextended/ox_inventory#766]
adding the possibilty to do as same whit the item for the 

add and remove  like npwd or what ever !

**Comment by frazz1234** [comment]
['WEAPON_ASSAULTRIFLE'] = {
			label = 'Ak-47',
			weight = 3470,
			durability = 0.03,
			ammoname = 'ammo-rifle2',
			add = function(total)
				if total > 0 then
	
				end
			end,

			remove = function(total)
				if total < 1 then
	
				end
			end
		},

**Comment by N-fire** [comment]
I wonder if it's not already working, try it.
Anyway you can also listen to the event `ox_inventory:updateInventory`

**Comment by frazz1234** [comment]
> I wonder if it's not already working, try it. Anyway you can also listen to the event `ox_inventory:updateInventory`

already try whit the add and remove not working


humm how i could doignt that ?

**Comment by frazz1234** [comment]
we could an easy sling weapon avec that

**Comment by thelindat** [comment]
They work fine. Add and remove methods should be added in a nested "client" table; see phone
![image](https://user-images.githubusercontent.com/65407488/179446660-70c11bcc-b849-4bec-a0fc-cc93aa951bf5.png)

**Comment by frazz1234** [comment]
Humm... try it in the weapon.lua and not working

**Comment by frazz1234** [comment]
Im using this method on a lot item, I know how to improve it but the weapon lua it's not working

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/179449286-cfc1aed5-86c1-4844-a32a-dd694f80aff2.png)
```lua
		['WEAPON_ADVANCEDRIFLE'] = {
			label = 'Advanced Rifle',
			weight = 3180,
			durability = 0.03,
			ammoname = 'ammo-rifle',
			client = {
				add = function(total)
					print('add advanced rifle', total)
				end,
				remove = function(total)
					print('remove advanced rifle', total)
				end
			}
		},
```
