### ISSUE TITLE
WeaponWheel bug

### ISSUE THREAD

**Issue by hAKIZOR** [overextended/ox_inventory#770]
Sometimes when players die and respawn the weaponWheel start working and if u press TAB it appear. 
How to permanent disable it?

**Comment by thelindat** [comment]
This has _never_ been reproduced by members of Ox or respectable members of our community, and nobody has provided any information beyond "weaponwheel shows".

**Comment by hAKIZOR** [comment]
Ok, I will try to start the inventory on a clean server
