### ISSUE TITLE
Rename Items

### ISSUE THREAD

**Issue by Leandro7141** [overextended/ox_inventory#772]
**Enhancement**
Good morning !
Thank you very much for the work you have done !
 I wanted to propose to make a feature that allows to rename the elements
This is a feature that I find very important in an inventory.

Big thanks to you

**Comment by thelindat** [comment]
item.metadata.label

**Comment by Leandro7141** [comment]
I think you misunderstood what I was talking about, a feature where you can move items onto the "Rename" button in order to put custom labels

![image](https://user-images.githubusercontent.com/55460457/179878007-38453f5f-be00-4554-b8a5-da0b09de4924.png)

**Comment by thelindat** [comment]
Make button. Drag item to button. Trigger nui callback. Set metadata.label for the item based on input.
I'm not adding this to the inventory and fail to see how it's "very important".
