### ISSUE TITLE
Attacking while using inventory

### ISSUE THREAD

**Issue by Dejvi1** [overextended/ox_inventory#775]
**Describe the bug**
While is player in inventory and trying to use anything he keeps attacking everyone.

**To Reproduce**

**Expected behavior**
Dont attack while using inventory

**Comment by thelindat** [comment]
You have some conflict; attacking _is_ disabled when the inventory is open.

**Comment by Dejvi1** [comment]
I saw disabling it but it still happens tho.. I dont really see any other script what could do that..

**Comment by thelindat** [comment]
So you see it’s disabled in the resource, and there are some ~1200 servers using ox inventory and not complaining about attacking while the inventory is open; but it’s definitely an issue with the resource?

**Comment by Dejvi1** [comment]
Ok so issue was with some players only.. tried to delete my game cache and now no attacks. .. sorry for bothering :)
