### ISSUE TITLE
Please fix Menanak47 script compatibility. 

### ISSUE THREAD

**Issue by larsiepoohh** [overextended/ox_inventory#783]
**Describe the bug**
Menanak47 is well known for his FiveM scripts that many server owners use. Currently, ox inventory is the only inventory not compatible with his usable scripts. I do not wish to change my ox inventory as I really enjoy it and its features, clean look, and etc and you guys will always have my support but for the sake of us server owners please make this fix!

**Comment by thelindat** [comment]
Ah yes menan. The guy who earns some $10,000 a month by selling stolen and low quality scripts via Patreon subscription.

The ones with remote loading and obfuscation.

_THAT_ super popular FiveM developer. And I should put in the work to make my script compatible with _”his”_ stolen and/or low-quality _closed-source_ resources. Makes sense to me.

Maybe you should go try his inventory instead.
https://github.com/MenanAk47/ak47_inventory
