### ISSUE TITLE
Items in personal stash deleted after server restart

### ISSUE THREAD

**Issue by Droid91** [overextended/ox_inventory#785]
I’m making a script that allows players to create their own stash using an item. When the item is used, I write the new inventory on the addon_inventory table (only for marker coords) and then i use the RegisterStash function of ox_inventory. Then through the marker the players is able to access the inventory and deposits or withdraws what they wants, however, when the server is restarted, the stored items are deleted.

**Comment by thelindat** [comment]
https://overextended.github.io/docs/ox_inventory/#stashes--trunks-are-not-saved-at-server-restart
