### ISSUE TITLE
How do I get rid of the holstering of a weapon completely.

### ISSUE THREAD

**Issue by MurdaManQuan** [overextended/ox_inventory#786]
**Describe the bug**
When you give yourself a weapon like a ak or a machine pistol it holsters the weapon on your back or on your side. You pull the weapon out it is continued to be holstered. Is there a way I can turn this off completely. or just not make the holstering visible.

**Expected behavior**
Whenever you have a weapon it doesnt show in plain sight

**Screenshots**
![holster](https://user-images.githubusercontent.com/84297292/182738346-a4a9a59f-ec50-422c-be3a-96bb1221439d.jpg)

**Additional context**

**Comment by thelindat** [comment]
The inventory doesn't spawn or attach weapons to players.
