### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Nulzyy** [overextended/ox_inventory#792]
Items are not usable if you start the script after inventory in server.cfg

**Comment by thelindat** [comment]
> Items are not usable if you start the script after inventory in server.cfg

Your script is just garbage and feels the need to do some weird nonsense when registering items via ESX.
Ox Inventory waits 1500ms before it retrieves the ESX "shared" object which _should_ contain all callbacks for ESX.RegisterUsableItem; but somehow people find a way to wait to create their items.
