### ISSUE TITLE
Drug system dont work with This inventory

### ISSUE THREAD

**Issue by selnferreira** [overextended/ox_inventory#794]
Good afternoon. I use a drug system but it doesn't work because I can't check the items in the inventory. the script uses ESX Player Data. is there any solution to work

**Comment by thelindat** [comment]
```lua
for k, v in pairs(ESX.GetPlayerData().inventory) do
    print(k, v)
end
```

**Comment by selnferreira** [comment]
Where do I put this function? the script is encrypted I can't change anything

**Comment by thelindat** [comment]
> Where do I put this function? the script is encrypted I can't change anything

Then tell the author of the resource to
a) make the change themselves. they're either using ipairs or for i right now.
or
b) don't encrypt parts that people may need access to for framework compatibility (fat chance, they want the extra money selling versions of ESX and QB)

**Comment by selnferreira** [comment]
[main.zip](https://github.com/overextended/ox_inventory/files/9331493/main.zip)
After all, it was my mistake, the client is not encrypted. The seller says he doesn't know how to solve it and said to speak with your support. I'll leave the file attached, if you can take a look, I'd appreciate it. I'm new to this. Thanks

**Comment by selnferreira** [comment]
After all, it was my mistake, the client is not encrypted. The seller says he doesn't know how to solve it and said to speak with your support. I'll leave the file attached, if you can take a look, I'd appreciate it. I'm new to this. Thank
[main.zip](https://github.com/overextended/ox_inventory/files/9331499/main.zip)
s

**Comment by thelindat** [comment]
Quit posting a _paid_ script file.

**Comment by selnferreira** [comment]
I'm sorry, but you can't help me since the seller says he doesn't know how to do it?

**Comment by thelindat** [comment]
As above
```lua
for k, v in pairs(ESX.GetPlayerData().inventory) do
    -- code here
end
```
This isn't ox_inventory specific, it's the standard for ESX.

**Comment by selnferreira** [comment]
for k, v in pairs(ESX.GetPlayerData().inventory) do
    if v.name and sellableLookup[v.name] and v.count and v.count >= Config.MinSellAmount then
      playerSellables[v.name] = v.count
      hasSellable = hasSellable + 1
    end
end

I put it as I said and it continues to say I don't have any drugs in my inventory

**Comment by thelindat** [comment]
```lua
print(json.encode(ESX.GetPlayerData().inventory, {indent=true})

for k, v in pairs(ESX.GetPlayerData().inventory) do
    print(v.name, v.count, v.slot)
end
```
