### ISSUE TITLE
Give items to others is a bit buggy/weird and doesn't seem to be the optimal solution

### ISSUE THREAD

**Issue by LostJ3ster** [overextended/ox_inventory#805]
**Is your feature request related to a problem? Please describe.**
It's a bit frustrating giving items to players that aren't the closest ones, and that are'nt supposed to get the items

**Describe the solution you'd like**
The option to give items to id's (maybe with a popup) if there are more than 1 Player nearby

**Additional context**
When giving items to other players, sometimes it happens, that not the closest player is chosen. Also in RP it's not always possible to stand right in front of the player you want to give the items to (In a bar for example). Therefore it would be appreciated if there would be the option to give items to id's, so it's more precisely.

**Comment by thelindat** [comment]
> Give items to others is a bit buggy/weird

No, you're just incompetent; not hard to stare at a player and give the item.

> Therefore it would be appreciated if there would be the option to give items to id's, so it's more precisely.

Glad I added this stupid feature so people would ignore it.

`setr inventory:giveplayerlist true`
