### ISSUE TITLE
A bug on registering esx items

### ISSUE THREAD

**Issue by BlackCock00** [overextended/ox_inventory#806]
when i using ESX.RegisterUsableItems it not registered but when i restart the resource ingame it start to be usable idk what is happening the issue starts after i update the inventory on the latest my last version is 2.8.4
![image](https://user-images.githubusercontent.com/59727785/185814126-8323d486-8418-4f55-982c-7877443dd589.png)
https://streamable.com/f3cqy7

**Comment by eprimex** [comment]
Todays facepalm #1 who ever made that script made it spam getting xPlayer just to get source of player when it already is provided during registration of repair kit

**Comment by thelindat** [comment]
thanks blackcock00

still can't repro even if i delay registerusableitem by 3 seconds but ok
