### ISSUE TITLE
QBCore.Functions.RemoveMoney, not syncing money right

### ISSUE THREAD

**Issue by FuZZED105** [overextended/ox_inventory#810]
**Describe the bug**
When using the function QBCore.Functions.RemoveMoney, the inventory then sets the money item to the amount that you have been charged for. For example if I had a $100 and I was charged for $100, it would set my inventory money to $100.

**Expected behavior**
Its might to set your inventory money to the new amount you have on you.

**Screenshots**
https://prnt.sc/Zap2W_KspN2D
https://prnt.sc/mxPLt6BUp3YH

**Comment by thelindat** [comment]
Resolved afaik
