### ISSUE TITLE
(QB) Group access is not properly updated for jobs

### ISSUE THREAD

**Issue by ansljeremy** [overextended/ox_inventory#811]
**Describe the bug**
When using QB version you cannot access the job locked store if you did not load into the server with that job.

**To Reproduce**
1. Login with a Job1
2. Get Job2
3. Attempt to access Job2's store
4. Fail to access the said store

**Expected behavior**
You should be able to use the store if you don't load in with the job but get it later on.

**Additional context**
I also use qtarget instead of arrows to access shops

**Comment by thelindat** [comment]
To clarify, the option _does_ show in qtarget?

**Comment by ansljeremy** [comment]
> To clarify, the option _does_ show in qtarget?

Apologies for not being clear, the qtarget option does not appear.

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/commit/40262471bb794c23fbeacfa13a14106a360bf899

This should resolve it, but I don't have a test server setup for qb + ox_inventory yet.

**Comment by thelindat** [comment]
@ansljeremy Let me know if things are working with the latest release.

**Comment by ansljeremy** [comment]
@thelindat things are working as intended, thank you for the quick resolution.
