### ISSUE TITLE
Creating stores with qtarget.

### ISSUE THREAD

**Issue by BalloutJay** [overextended/ox_inventory#814]
So I want to make an store using qtarget, and I wanted to know what are these? Kind of new to developing.

Preview of Image :
![Screenshot_1](https://user-images.githubusercontent.com/98054918/186970849-2cea41d4-8316-4058-8829-47e8ab995880.png)
Don't get these headings, minZ, maxZ. I don't know if it's about coords or something else.

**Comment by thelindat** [comment]
https://github.com/mkafrin/PolyZone/wiki/BoxZone
