### ISSUE TITLE
Add weight bar display to hotbar [TAB]

### ISSUE THREAD

**Issue by HSalazar23** [overextended/ox_inventory#819]
Adding a weight bar to the quick hotbar [TAB] similar to the weight bar displayed on the full opened inventory.
This makes it easier to check how much a player can still take instead of needing to open the full inventory.
This weight bar could be added above or below the hotbar.

![image](https://user-images.githubusercontent.com/8644902/187076652-3cb3f8a8-4624-4806-a05b-b9682c6edca2.png)

![image](https://user-images.githubusercontent.com/8644902/187076712-54620405-670f-4d5c-a98a-8a6c5a0969d5.png)

**Comment by LukeWasTakenn** [comment]
Pending further feedback whether this is something people would actually like to see.

**Comment by thelindat** [comment]
Would just look ugly.
