### ISSUE TITLE
Attachment Changing Metadata

### ISSUE THREAD

**Issue by Steviol** [overextended/ox_inventory#820]
Metadata from attachment will change if someone attach to weapon, and remove the attachment from weapon

**Comment by Steviol** [comment]
i mean serial number from metadata

**Comment by thelindat** [comment]
Serial is changing or being removed? I'll look into it later but seems odd.

**Comment by Steviol** [comment]
serial numebr is being removed

**Comment by thelindat** [comment]
Metadata is perfectly fine when adding and removing attachments. Not sure how you're experiencing different behaviour.
