### ISSUE TITLE
Remove/Change Item Name who have 0 durability

### ISSUE THREAD

**Issue by Steviol** [overextended/ox_inventory#821]
Remove/Change Item Name maybe its better than left 0 durability, because someone still can abuse RemoveInventoryItem if you hold item with 0 durability
example: 
i have 1 burger with 100 durability and 9 burger with 0 durability
RemoveInventoryItem will remove item 1 from 10 burger (random) in inventory

**Comment by thelindat** [comment]
Check item durability
