### ISSUE TITLE
core_jobutilites

### ISSUE THREAD

**Issue by afterko** [overextended/ox_inventory#822]
Hi, I have a problem. When I want to insert money it does not go as if it takes from the default inventory from esx, when I select it and dam back so it goes so it is for other inventories. Does anyone know please?

**Comment by thelindat** [comment]
I understood about 5% of what you just said.

**Comment by kikyre** [comment]
what version are you using? i am using ox since the beta version i dont have a problem in core_jobutilities, even if its using a xPlayer.getMoney()
