### ISSUE TITLE
Weapon on back

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_inventory#823]
Is there a chance to get a native weapon on back support for ox? :) 

![image](https://user-images.githubusercontent.com/35350615/187550539-db8c816e-bd6b-489e-8cf3-c5479b6d7d87.png)

**Comment by Skryptific** [comment]
I believe @PlouffeLuL made a similar resource for this already: https://github.com/PlouffeLuL/plouffe_weapons

**Comment by PlouffeLuL** [comment]
@Skryptific As much as i appreciate you referring people to my scripts and im very happy to see you doing so i dont think it should be done on the ox git as my script a 'soft-lock' behind a paywall if people dont have the knowledge to edit them and i know the ox team dont want anything to do with people selling scripts.

**Comment by Skryptific** [comment]
> @Skryptific As much as i appreciate you referring people to my scripts and im very happy to see you doing so i dont think it should be done on the ox git as my script are 'soft-lock' behind a paywall if people dont have the knowledge to edit them and i know the ox team dont want anything to do with people selling scripts.

Ah did not know that, watched your stream for a minute yesterday when you were working on the mentioned script, my bad.
