### ISSUE TITLE
[Enhancement] Override registered stashes' name

### ISSUE THREAD

**Issue by mahanmoulaei** [overextended/ox_inventory#824]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Be able to override/rename an already registered stash name when you call ```exports.ox_inventory:RegisterStash```

**Describe alternatives you've considered**
N/A

**Additional context**
For the first time when the ox_inventory starts, you can name your stashes whatever you want using ```ox_inventory:RegisterStash```. But when you want to change the name of your desired registered stash to a new one without restarting the resource, only the first name that you registered for that stash would be shown on the left side of the inventory's front-end.
_A simple usage of this feature request can be seen [here](https://github.com/qbcore-framework/qb-apartments/pull/90/files#diff-d4503a9550899ea7880582e02d5404019dbce696d1b27a7c63f18b99eddeb088R85)_

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/blob/main/modules/inventory/server.lua#L1660-L1669

"name" being the stash id and what it's stored in the db with, label being what you want to change (already supported???????).

**Comment by mahanmoulaei** [comment]
Hmm, that's really weird because the same code that I use to register the stash for the first time doesn't actually rename the stash when it's called for the second time.
I'm going to do more tests now...

**Comment by mahanmoulaei** [comment]
I actually tried this again and noticed [where the problem is coming from](https://github.com/overextended/ox_inventory/blob/main/modules/inventory/server.lua#L24-#L28) possibly. The stash attributes such as the stash label don't get modified if you register the same stash with a different name, because the stash is already registered and available in ```Inventories``` table. The only way you can modify some stash attributes like its label is to restart the resource.

My repro: [link](https://github.com/mahanmoulaei/Stash-Test)

**Comment by thelindat** [comment]
Right ofc. I'll update it later.

**Comment by mahanmoulaei** [comment]
Thank you, Linden. I'll go ahead and close this issue
