### ISSUE TITLE
Inventory runs sloooooow when using qb-core

### ISSUE THREAD

**Issue by GhzGarage** [overextended/ox_inventory#825]
We're doing some testing of the inventory with the recent experimental support for QB and noticed a delay when dragging an item from a shop into your inventory. Is this normal behavior?

Video here: https://medal.tv/games/gta-v/clips/yZQquad1Qtjst/d13377AWE1lY?invite=cr-MSxTS2MsMTkwOTE1ODgs

**Comment by thelindat** [comment]
Usually close to instant for me, though I haven't tested the QB support (like at all); shouldn't really cause any issues though.
Dragging items (from any inventory) sends basic info like inventory id and slot, then validates the input.

https://github.com/overextended/ox_inventory/blob/main/modules/shops/server.lua#L126

**Comment by GhzGarage** [comment]
Alright that's what I figured, just wanted to make sure. Thank you

**Comment by thelindat** [comment]
First issue I notice is that qb commands will still register and overwrite ox_inventory, so I had to restart to get the correct commands running.

Using giveitem/additem command has this same delay (~1s) before actually triggering, and item dragging validation is also incredibly slow; though you'll visibly see it move, the inventory is locked for ~1s while pending server response.

**Comment by thelindat** [comment]
@GhzGarage @BerkieBb

**Comment by thelindat** [comment]
Problem is in qb-core.

```lua
function self.Functions.UpdatePlayerData(dontUpdateChat)
    if self.Offline then return end -- Unsupported for Offline Players
    TriggerEvent('QBCore:Player:SetPlayerData', self.PlayerData)
    TriggerClientEvent('QBCore:Player:SetPlayerData', self.PlayerData.source, self.PlayerData)
    if not dontUpdateChat then
        QBCore.Commands.Refresh(self.PlayerData.source)
    end
end
```

Everytime player data is updated, commands get refreshed.
When the chat resource is adding chat suggestions, it blocks NUI events - the result is everything becomes slow af.
![image](https://user-images.githubusercontent.com/65407488/187754755-cb084f77-01f3-46c7-84ef-f73c62d66db2.png)
