### ISSUE TITLE
[QB] Identification shows Player name and not Character name

### ISSUE THREAD

**Issue by ansljeremy** [overextended/ox_inventory#828]
**Describe the bug**
Identification shows your steam/cfx/whatever name instead of your character name

**To Reproduce**
1. Get an ID
2. Check name
3. See steam/cfx/whatever name

**Expected behavior**
Should show character name

**Screenshots**
![image](https://user-images.githubusercontent.com/68263976/188257985-a8c3c07c-0c53-4656-8cb8-a53ad4751ff1.png)

**Comment by mahanmoulaei** [comment]
You have to modify your id card within your id card resource and structure it however you want (example:)
![image](https://user-images.githubusercontent.com/75180223/188265426-cbd99c85-e8a2-451e-a9f0-0ff159a19c27.png)

Your problem is not an ox_inventory bug!

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/188527057-3c91d3e5-7ff9-4bf8-b5ac-71f1612ee310.png)

Identification I just gave myself has the expected data; though it needs some adjustments if you want it to work like QBs.

**Comment by mahanmoulaei** [comment]
> can you show me how you did it please?

Yes, I'll give you an example of how you can customize your ID Card:

Go to **qb-cityhall/server/main.lua** and find ```local function giveStarterItems()``` and replace it with [this one](https://github.com/QB-JolbakLife-RolePlay/qb-cityhall/blob/main/server/main.lua#L15-L53).
in the **same file** find ```RegisterNetEvent('qb-cityhall:server:requestId', function(item, hall)``` and replace it with [this one](https://github.com/QB-JolbakLife-RolePlay/qb-cityhall/blob/main/server/main.lua#L63-L119).

-------------
Moreover, if you have other resources that add an id card (like qb-multicharacter if I'm not mistaken), you need to go to their server-side file and modify the description and the type of the item being added to players(like the one I did for qb-cityhall).
