### ISSUE TITLE
Weapon Wheel

### ISSUE THREAD

**Issue by maverickphp** [overextended/ox_inventory#831]
How can i enable weapon wheel in this inventory ?

**Comment by soniXx123** [comment]
https://overextended.github.io/docs/ox_inventory/Functions/Client/Utils/weaponWheel

**Comment by maverickphp** [comment]
how can i apply this please help, where to put this function

**Comment by Legacy-TacticalGamingInteractive** [comment]
> how can i apply this please help, where to put this function

did you figure it out
