### ISSUE TITLE
evidence

### ISSUE THREAD

**Issue by DrWobby** [overextended/ox_inventory#833]
**Describe the bug**
Police evidence locker, for some players they can't take items out after they have put them back and for some players, it can.
also, i set inventory:evidencegrade 7 but this does not fix the problem.

go to evidence 
press e then type 1 
take out any item already in there.
it should give a notification which does for only for some players
other players do it with no notification and they can take it.

**Comment by thelindat** [comment]
... that's by design.

> i set inventory:evidencegrade 7 but this does not fix the problem

Yes, you set the required grade to withdraw items to grade 7, when ESX grades start from 0.

**Comment by DrWobby** [comment]
yes that's true I wanted only grade 7 to be able to withdraw items but even grade 0 can withdraw items but not all grade 0  withdraw, some grade 0 can , that's weird part and it doesn't give any error to see whats the problem.

**Comment by thelindat** [comment]
"some but not all" is not something I can work with, reproduce, nor fix.

**Comment by thelindat** [comment]
Can't reproduce at all, and the code for checking isn't exactly complex.
![image](https://user-images.githubusercontent.com/65407488/188515333-bebe1cf3-c0f3-4c20-a58d-8e3e313e4436.png)

As always I advise using latest versions to ensure it's not something that was resolved.
