### ISSUE TITLE
ox_inventory:openInventory 'player' -> is it safe?

### ISSUE THREAD

**Issue by xrtw** [overextended/ox_inventory#835]
hello, have a question.
https://github.com/overextended/ox_inventory/blob/main/server.lua#L51
why there is no logs what player took from opened players' inventory? or it's not safe to use?

**Comment by thelindat** [comment]
What does that line have to do with giving items to others (which are logged fyi)?

**Comment by thelindat** [comment]
Still has _nothing_ to do with taking items from another player.
