### ISSUE TITLE
v2.12 metadata handling in shop

### ISSUE THREAD

**Issue by mikigoalie** [overextended/ox_inventory#844]
**Describe the bug**
Seems like metadatas broken when set up in shop. Example, I set tint for weapon in shop, bought the weapon yet got no tint. v11.3 or so worked well, updated to 12.0, bronk.

**To Reproduce**
Already in description

**Expected behavior**
Give me skinz on weapons

**Screenshots**
No

**Additional context**
I believe registration works, but tints don't.

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/189135521-ba269d61-99de-42f1-ad90-04e61d118477.png)

**Comment by mikigoalie** [comment]
**{ name = 'weapon_stungun', price = 1250, metadata = { registered = true, tint = 3}},**
tried this on v12.0 and didn't give me any tints, however I will test it properly again in a bit. Thanks for confirming though.
