### ISSUE TITLE
Problem with visual durability

### ISSUE THREAD

**Issue by varkosqc** [overextended/ox_inventory#851]
**Describe the bug**
Is the durability meant to be like that?

**Screenshots**
![unknown](https://user-images.githubusercontent.com/100730901/189708997-6dd072be-14b6-4fb1-aee1-0ecd9aa47d4b.png)

**Comment by LukeWasTakenn** [comment]
Should be resolved in commit cc445212682eacf7e27dc99744f3997b7bd614cf
