### ISSUE TITLE
@esx_addoninventory/server/main.lua:9: No such export RegisterStash in resource ox_inventory

### ISSUE THREAD

**Issue by JuanCarlos023** [overextended/ox_inventory#853]
Good morning, I need help, this error appears on my console, I haven't touched any of the esx_addoninventory code.

(I attach a photo)

![Captura de pantalla 2022-09-14 100236](https://user-images.githubusercontent.com/76178594/190096836-3640a661-c51e-4175-9850-b016a1b41a7b.png)

Thanks in advance

**Comment by JuanCarlos023** [comment]
Had a bug in ox_lib, just reinstalled the version

**Comment by BiG-ADLER** [comment]
Hello Dear Staff, Yes i have same problem, same with this person error, 
**(im attach error pic)**
![Screenshot 2022-09-14 212809](https://user-images.githubusercontent.com/95148142/190233763-9a151c2a-fd7c-483c-9fd0-755b3924bb73.png)

**Comment by thelindat** [comment]
I don't care if you people are so incompetent you can't start your resources correctly.
