### ISSUE TITLE
Problem in shops

### ISSUE THREAD

**Issue by DyDyPoWeR** [overextended/ox_inventory#854]
**Describe the bug**
Hello,

I currently have a problem with the ox_inventory in relation to the creation of a store.

In the resource ox_inventory/data/items.lua, when I leave all the lines of code by default all the stores work correctly but as soon as I want to add a coordinates to create my own stores, this coordinates that I added does not work.

Of course when I restart the resource I have no error.

**Screenshots**
Screen 1 : https://i.imgur.com/izXsKXu.png
Screen 2 : https://i.imgur.com/KCQA5Lt.png

**Comment by thelindat** [comment]
If it works until you add code, it isn't our issue.
