### ISSUE TITLE
ClearInventory error with keeping items

### ISSUE THREAD

**Issue by ItzTrivial** [overextended/ox_inventory#855]
**Describe the bug**
When trying to clear the inventory and keep certain items it throws an error if the player only carries the items which should be removed.

**To Reproduce**
1. Add item "phone" to the inventory, nothing else
2. Try to clear the inventory and keep the item "phone"
3. error, because theres nothing to clear.

**Expected behavior**
Shouldnt throw an error and just not clear the inventory.

**Screenshots**
![image](https://user-images.githubusercontent.com/66124070/190434188-ee761095-2d09-4aba-9971-55462e72ba98.png)

**Comment by ItzTrivial** [comment]
I was wrong. Its not only if the player only has items which should be removed. Its not working in general for me.

**Comment by thelindat** [comment]
Resolved.
