### ISSUE TITLE
Support for ox_target

### ISSUE THREAD

**Issue by SneakyAF** [overextended/ox_inventory#857]
**Is your feature request related to a problem? Please describe.**
Not that it is a problem, I'm just intrigued by the better performance stated in the resource

**Describe the solution you'd like**
Add a ox_target support

**Describe alternatives you've considered**
N/A

**Additional context**
I assume it is planned since it is your resource guys. The question would be an estimate to when and will qtarget still be supported ?

**Comment by thelindat** [comment]
- delete qtarget
- add ox_target
- enable "qtarget" support
- ???
- profit
