### ISSUE TITLE
AddItem/RemoveItem exports do not produce logs

### ISSUE THREAD

**Issue by ansljeremy** [overextended/ox_inventory#860]
**Describe the bug**
When using either the AddItem or RemoveItem exports it does not produce a log saying the item was added/removed from the player.

**To Reproduce**
1. Use either export
2. See no log

**Expected behavior**
A log should still be sent through to datadog when the item is added/removed.

**Comment by thelindat** [comment]
They're not supposed to, and if I were to add it I would refactor the logging entirely.

**Comment by thelindat** [comment]
Supported with convar `set inventory:loglevel 2`
