### ISSUE TITLE
error buying from a shop 

### ISSUE THREAD

**Issue by Crxfty** [overextended/ox_inventory#867]
Everytime i buy from a shop it doesnt go into the inventory and i get an error at line 123

![5a74a38fe6b8dce48dce75c24e17fa60](https://user-images.githubusercontent.com/60398698/191852203-6b9cea47-7e64-46b8-8002-73151a8d7f86.png)
 
SCRIPT ERROR: @ox_inventory/modules/shops/server.lua:123: attempt to index a nil value (local 'num')

im using a number in the shop too thinking maybe it was due to dragging the item on 0 but didnt change nothing

**Comment by thelindat** [comment]
Your item has no price.
