### ISSUE TITLE
Metadata (durability - shops)

### ISSUE THREAD

**Issue by varkosqc** [overextended/ox_inventory#869]
**Describe the bug**
Let me explain, if we add durability on items in shops (data/shops.lua) like the image below. Here we have the toolbox that has metadata 100 durability, if I buy the item in the shop the item has the metadata Durability: 100. However, if I reboot the inventory, the item does not have any durability anymore, it is gone. If I disconnect my character without reboot the inventory this one notes well the durability in the database as the image below. I reconnect and the item has lost the durability, the bar does not exist any more.

**Screenshots**
data/shops.lua
![image_2022-09-24_114645243](https://user-images.githubusercontent.com/100730901/192106954-b39c26c1-12fc-428b-a8b6-801d3e0e9b88.png)

After the purchase
![image_2022-09-24_114806251](https://user-images.githubusercontent.com/100730901/192107003-fa5d696c-940d-455c-aa66-6e6a329b5ce6.png)

Disconnect without reboot inventory (saving on database)
![image_2022-09-24_114947872](https://user-images.githubusercontent.com/100730901/192107093-15c8fb84-8968-4af0-b4fa-06fbe5f7e51c.png)

After reboot / reconnect
![image_2022-09-24_114824560](https://user-images.githubusercontent.com/100730901/192107019-40f0b33a-0ebd-45cd-8f9b-5209df31e8fb.png)

**Comment by thelindat** [comment]
Fixed. https://github.com/overextended/ox_inventory/commit/5987bfa15777440b905cce060d85c06aa49d6b09
