### ISSUE TITLE
Impossible to build

### ISSUE THREAD

**Issue by Cyril-Beeckman** [overextended/ox_inventory#870]
**Describe the bug**
The project can't compile

**To Reproduce**
1. Clone the project
2. Go to web directory
3. Launch pnpm i
4. Launch pnpm build
5. See error

**Expected behavior**
The project is compiled

**Screenshots**
![image](https://user-images.githubusercontent.com/11323987/192113339-99a50124-4822-4abe-b332-6d9dcfe04236.png)

**Additional context**
Node v18.9.0
Pnpm v7.1.9

**Comment by LukeWasTakenn** [comment]
Upgrade your pnpm and downgrade your node as anything above LTS is not guaranteed to work.

**Comment by Cyril-Beeckman** [comment]
> 

Downgrade to Node 16.17.1
Upgrade to pnpm 7.12.2

Now i can't `pnpm i`

![image](https://user-images.githubusercontent.com/11323987/192114333-f1bf07eb-821d-4001-9c50-1b423c94a7df.png)

**Comment by LukeWasTakenn** [comment]
Just tested it again, works fine so not sure why the patched dep is not applying for you 🤷
