### ISSUE TITLE
Failed execution of native (RegisterKeyMapping)

### ISSUE THREAD

**Issue by AzraDevOps** [overextended/ox_inventory#872]
**History**
Everything works well.
I delete the data in the database for refresh the server
I restart and now i can't open the inventory with the message "you can't open...actually"
In F8 i saw : SCRIPT ERROR: Execution of native 00000000d7664fd1 in script host failed: Argument at index 3 was null

**Screenshots**
see above

![BugOxInv01](https://user-images.githubusercontent.com/72076704/192141547-15156e9e-6275-4b25-acf7-30e9360bf41b.png)
![BugOxInv02](https://user-images.githubusercontent.com/72076704/192141548-7c02704d-47f1-4306-aebc-ffb7798c6c89.png)

**Comment by thelindat** [comment]
Native is RegisterKeyMapping; whatever default key you've set is invalid.
