### ISSUE TITLE
[WARNING] 0R-admin used esx:getSharedObject

### ISSUE THREAD

**Issue by MisterSpex83** [overextended/ox_inventory#873]
[WARNING] 0R-admin used esx:getSharedObject, this method is deprecated and should not be used! Refer to https://docs.esx-framework.org/tutorials/sharedevent for more info!

How can I change / rewrite this ? Thanks for the help. I am using an ESX legacy build

**Comment by thelindat** [comment]
What the fuck does this have to do with *ox_inventory*?
