### ISSUE TITLE
[BUG] Dropping weapon and firing it in a quick succession will result in duplicated weapons

### ISSUE THREAD

**Issue by mikigoalie** [overextended/ox_inventory#874]
**Describe the bug**
*Title*

**To Reproduce**
1. Drop your weapon from inv (preferrably SMG)
2. There's slight delay before ped plays holster anim, so shoot asap
3. Stonks; now you have weapon in hand and on the ground

**Expected behavior**
Probably to holster weapon instantly while closing inv

**Comment by luchowolf** [comment]
The same thing happens to me, but the weapon in hand only fires the loaded bullets, then it can't be loaded and you can't use another item from the inventory until you pick up the weapon again, does the same thing happen to you?

**Comment by DokaDoka** [comment]
can confirm

**Comment by thelindat** [comment]
I can't shoot _at all_.
![image](https://user-images.githubusercontent.com/65407488/192395191-85876dcb-c779-4334-a05e-464cdc97afc0.png)
Ammo is set to 0 immediately, and you can't shoot if you have no ammo..

**Comment by thelindat** [comment]
I can't shoot and ped is _always_ disarmed, so whatever you're experiencing isn't reproducible for me; no matter how quickly I attempt it.

**Comment by DokaDoka** [comment]
You've gotta be really quick, it looks like it might be something to do with the inventory opening animation
https://user-images.githubusercontent.com/31368547/193259225-9bc1f0b0-1123-424f-a307-dd5bb62a093e.mp4

**Comment by LukeWasTakenn** [comment]
I also can't reproduce this issue.

**Comment by mikigoalie** [comment]
> I also can't reproduce this issue.

But.. it works, anyway, I made a check in my anticheat whether the player had weapon recently so it doesn't matter, but it's still a major issue to me
