### ISSUE TITLE
krz_personalmenu Weapons and Inventory.

### ISSUE THREAD

**Issue by LPDaVinci** [overextended/ox_inventory#879]
Dear reader,

when I'm using ox_inventory with krz_personalmenu the inventory and weapon options are not working and my client ist lagging when pressing inventory.
Is there a function i need to integrate in krz_personalmenu that it will working together with ox_inventory (i like both scripts but ox_inventory more) i disabled the option in krz_personalmenu to open the inventory and weapons so this lag/frame drop bug disappears but i want to use this feature as well.

hopefully you understand what im trying to say.

thanks alot.

**Comment by N-fire** [comment]
Ox_inventory won't work with this kind of inventory display.
Ps: github is for bug report and suggestion, please use the discord for support.

**Comment by LukeWasTakenn** [comment]
So you want to use a menu to open the inventory instead of just pressing a single button and opening the inventory itself?

Idk about the thing you are talking about showing weapons, but loadout weapons aren't used with ox_inventory, instead they are used as items.
