### ISSUE TITLE
qtarget and ox_target configuartion in the config.cfg

### ISSUE THREAD

**Issue by Eiskxlt** [overextended/ox_inventory#880]
So my Idea is it that because qtarget is not maintained anymore by you guys and the Inventory just have a configuration for qtarget in the config.cfg and that would be good to have an option to set it to the new targeting script of you guys (ox_target).

Much Love to the Team.

**Sry for my Bad English**

**Comment by thelindat** [comment]
Just leave qtarget settings as they are and enable qtarget convar; ox_target will handle the events.
This is the fourth "issue" on this..
