### ISSUE TITLE
SHOP - Hide out of stock items

### ISSUE THREAD

**Issue by ESK0** [overextended/ox_inventory#881]
Hi, 
Would it be possible to hide items from the shop in case the item is sold out? (if "count" is used in the item declaration)

10pcs on stock
![image](https://user-images.githubusercontent.com/8851795/193456494-d9280e0f-4e28-4fd2-981e-0d8764c8b5fe.png)

Sold out but still being shown
![image](https://user-images.githubusercontent.com/8851795/193456502-121ba51e-8679-45b1-a2e1-5ab6c34cea69.png)

**Comment by LukeWasTakenn** [comment]
Instead of hiding (can possibly interfere with the way inventory slots work) maybe just make it grayed out 🤔

**Comment by ESK0** [comment]
> 

Graying would be good enough

**Comment by LukeWasTakenn** [comment]
Implemented in 44fde9083a799fdca5b4527c0bd76ff6d9c0408e

If the count for the shop item is defined and is 0 the item will be grayed out, darkened and it won't be draggable.
