### ISSUE TITLE
Cannot reload at helicopter

### ISSUE THREAD

**Issue by Steviol** [overextended/ox_inventory#882]
Cannot reload at helicopter

**Comment by kukiiii** [comment]
any news about this bug? On come helicopters it's working like cargobob but on maverick or polmav won't

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/194785084-d04071ed-b95e-468e-adbd-fec6bf97f1da.png)

![image](https://user-images.githubusercontent.com/65407488/194785076-53f8ad78-5a44-4e04-87c2-0266bcd4ca64.png)

**Comment by kukiiii** [comment]
After you empty gun you can reload?

**Comment by thelindat** [comment]
Yes.
