### ISSUE TITLE
[QB] ox_inventory duplication glitch

### ISSUE THREAD

**Issue by FuZZED105** [overextended/ox_inventory#886]
**Describe the bug**
A user from my server found a duplication glitch with inventory stashes. When a player puts an item in a stash then causes his game to crash, I think he said his internet went out so that caused him to time out. But when their game crashes the item will be in his inventory and inside the locker.

**To Reproduce**
1. Put an item into a container or stash
2. Make your game crash or Alt + F4
3. When you load back into the game you should see the item in your inventory and in the stash

**Expected behavior**
The item should not be inside you inventory and only in the stash

**Comment by N-fire** [comment]
What core do you use did you modified it ?
Make sure that player inventory is saved on player drop.

**Comment by BerkieBb** [comment]
And make sure the core is up to date
