### ISSUE TITLE
I can't see/store/retieve items from glovebox or trunk

### ISSUE THREAD

**Issue by Ruben-GA** [overextended/ox_inventory#889]
When I click F2 I don't see the glovebox inventory while inside the vehicle nor the trunk inventory when in front of the trunk. When I try to put something on the glovebox, it fails. When I attempt the same in the trunk, the item is dropped.

In theory there shouldnt't be any problem, but maybe I missed something in the setup, so I came here for help.

If you need more info from me I can provide it, just ask, I don't know what more to provide besides a description of the issue right now to be honest.

**Comment by thelindat** [comment]
Because `F2` doesn't open trunk or glovebox, you press `K`.
