### ISSUE TITLE
Question: Non-Stealable items

### ISSUE THREAD

**Issue by LostJ3ster** [overextended/ox_inventory#891]
Is it possible to declare items as "non-stealable"?

I'm locking doors für a gang, and because i dont want to use passcodes, and want them to be able to use normal jobs, i have to use items for checking if they should be allowed to open doors.
But if they got the items in their inventory, the items could be stolen. But I dont want others to have access to the locked buildings.. Any way I can do that?
Sorry if I'm missing any feature, but I haven't found a solution yet.

Thank you in advance.

**Comment by thelindat** [comment]
https://overextended.github.io/docs/ox_inventory/Functions/Server/Hooks/
