### ISSUE TITLE
QTarget Issue opening shops, dumpster, etc

### ISSUE THREAD

**Issue by PERPGamer** [overextended/ox_inventory#893]
**Describe the bug**
Nothing will happen when you try to open a shop, dumpster, police evidence, trunk, or stash with qtarget.

**To Reproduce**
1. Add the newest version of ox_inventory
2. Have qtarget on your server
3. Try to open a shop, dumpster, police evidence, trunk, or stash
4. Nothing will open

**Expected behavior**
For the  shop, dumpster, police evidence, trunk, or stash to open

**Additional context**
I did some digging and found it to be caused by 
`elseif IsNuiFocused() then return` 
in
**function client.openInventory(inv, data)**
since qtarget has NuiFocus when you press the option.

**Comment by thelindat** [comment]
GitHub auto-closed 😟 but let me know if that commit works.
