### ISSUE TITLE
no more steal since update

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_inventory#894]
Hi, since the update from yesterday we cant use steal anymore. Is this an ox bug or is the bug from our side? we dont have any error logs.

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/195161921-4cd8e228-86be-41fe-ae34-122c8ce1a842.png)

**Comment by soniXx123** [comment]
Ok Thanks <3
