### ISSUE TITLE
[BUG] Final round in a weapon will not have recoil

### ISSUE THREAD

**Issue by jag3dagster** [overextended/ox_inventory#896]
**Describe the bug**
When firing a weapon, after firing the final round player ped does not experience recoil. Likely due to the `ClearPedTasks` [here](https://github.com/overextended/ox_inventory/blob/66b6c6b74500d58525c855d57de8c8d369389e55/client.lua#L1100).

**To Reproduce**
1. Equip any weapon
2. Load weapon with its preferred ammo type
3. Fire weapon and observe recoil
4. As you are firing the final round in the current magazine, observe lack of recoil

**Expected behavior**
As a player is firing a weapon, they would experience the same amount of recoil on every shot, including the final round in a magazine.

**Screenshots**
[Recoil gif](https://i.imgur.com/7xkVtac.gifv)

**Additional context**
N/A

**Comment by thelindat** [comment]
This was there to prevent disarming when running out of ammo, but I don't even believe that's necessary anymore? Need to confirm.

**Comment by jag3dagster** [comment]
Hm, looks like that does still occur without the code there. Is that a native GTA behavior to disarm once a weapon is empty with no ammo in reserves?

**Comment by thelindat** [comment]
Yes. 90% of the "bugs" people report are just GTA behaviour.

**Comment by jag3dagster** [comment]
Based on [this](https://forum.cfx.re/t/setweaponsnoautoswap-not-working/4873685/3) post from the forums, that function call may be dependent on not using [SetPedCanSwitchWeapon](https://github.com/overextended/ox_inventory/blob/0b9bfcdcde95212a84b7fd004f7f6854eae2dd53/modules/utils/client.lua#L89) which effectively sets Ped Config Flag 48.

Removing that call to SetPedCanSwitchWeapon appears to keep the weapon in hand after shooting the final shot. It appears that with this [DisableControlAction](https://github.com/overextended/ox_inventory/blob/0b9bfcdcde95212a84b7fd004f7f6854eae2dd53/client.lua#L1064) call, the user is still unable to open their weapon wheel. I'm unsure if there are other repercussions of not flipping that flag that you may be more aware of?
