### ISSUE TITLE
Can't withdraw/deposit items via jobscreator stash

### ISSUE THREAD

**Issue by Asuraeuw** [overextended/ox_inventory#900]
Hello,
my problem is that everytime i try to deposit an item into the stash i get an error code in my Console.
See error on Screenshot:

![Screenshot_1](https://user-images.githubusercontent.com/115834376/195928261-08a20a7c-27e2-440b-9139-e288ce41ec60.png)

**Comment by thelindat** [comment]
Don't know what "jobscreator" is but if it's using default esx inventory menu then that isn't my problem.

**Comment by Asuraeuw** [comment]
It is not using esx_inventory and it is compatible with ox_inventory, but i can't find a solution.

**Comment by DokaDoka** [comment]
ask the job creator creator creator not us

**Comment by Asuraeuw** [comment]
The Error Code shows nothing from the jobcreator. What should i show them?
