### ISSUE TITLE
Cant Open Inventory if someone was in the stash and crashed

### ISSUE THREAD

**Issue by FuZZED105** [overextended/ox_inventory#903]
**Describe the bug**
If a player opens a stash and crashes or closes their game when inside the stash, no players are able to open that stash as it still thinks that someone is inside the stash.

**To Reproduce**
1. Go into a stash
3. Close your game when inside the stash
4. Load back into the server and try and open the stash

**Expected behavior**
When player closes game inside a stash it should make them leave the stash so other players can access

**Comment by thelindat** [comment]
This is already a thing.

**Comment by thelindat** [comment]
Also don't bother posting issues when you're just going to vanish.
https://github.com/overextended/ox_inventory/issues/886
