### ISSUE TITLE
Stuck Inventory

### ISSUE THREAD

**Issue by Steviol** [overextended/ox_inventory#905]
https://youtube.com/clip/UgkxVR5M1BnwElOWNgWMW4IhFmlw9x29a5x4

**Comment by Steviol** [comment]
sometimes when inventory is closed, camera will going blur, and he cannot open again the inventory. there is no error in the console btw

**Comment by thelindat** [comment]
"sometimes" is not a repro.

**Comment by Steviol** [comment]
> "sometimes" is not a repro.

i mean its not often, so this happens when someone drop the item to the ground

**Comment by thelindat** [comment]
this solves everything

**Comment by thelindat** [comment]
i might be able to solve world hunger now that i have this clip

**Comment by Steviol** [comment]
my english is bad, so i might help you with giving some clip for this details. sorry if you are being offended

**Comment by Steviol** [comment]
> i'm so sorry but still not fixed, when someone drop any item to the ground too fast, inventory will reappear and if try to force close inventory, cursor will stay and he/she cannot open inventory again

*this bugs triggered when someone drop any items and drop id is not already generated but he/she too fast close the inventory and the inventory opened again when drop id is generated this is where stuck inventory happen

**Comment by Steviol** [comment]
thanks!
