### ISSUE TITLE
client = { add... Bug for items purchased from stores

### ISSUE THREAD

**Issue by Testaross** [overextended/ox_inventory#907]
**Describe the bug**
Morning,I have stumbled upon a bug when using the add and remove function in the item.lua while purchasing from a store

**To Reproduce**
put this item into your items.lua
```	
['largebag'] = {
		label = 'Large Duffle Bag',
		weight = 220,
		stack = false,
		consume = 0,
		client = {
			add = function(total)
				if total > 0 then
					print('Add')
					SetPedComponentVariation(PlayerPedId(-1), 5, 82, 0, 0);
				end
			end,
	
			remove = function(total)
				if total < 1 then
				print('Remove')
					SetPedComponentVariation(PlayerPedId(-1), 5, 0, 0, 0);
				end
			end
		}
	},
```

add the item to a store in shops.lua, any store is just fine 
```
{ name = 'largebag', price = 300 },
```

Purchase the item, notice no print or change to ped
**Expected behavior**
Bag placed on ped, print of  'Add' in the client console

**Additional context**
Function would help for tutorial showing how easy it is to create container scripts in the inventory, because why are people charging for built in functionality

**Comment by thelindat** [comment]
Try the following (replace the existing nuicallback).
```lua
RegisterNUICallback('buyItem', function(data, cb)
	local response, data, message = lib.callback.await('ox_inventory:buyItem', 100, data)

	if data then
		updateInventory({[data[1]] = data[2]}, data[4])
		SendNUIMessage({ action = 'refreshSlots', data = data[3] and {{item = data[2]}, {item = data[3], inventory = 'shop'}} or {item = data[2]}})
	end

	if message then
		lib.notify(message)
	end

	cb(response)
end)
```

**Comment by thelindat** [comment]
Used water because why not. Should act as you'd expect now?
https://user-images.githubusercontent.com/65407488/196638515-7daa71ea-a6b0-484f-8507-b6b6d681fee3.mp4

**Comment by Testaross** [comment]
Just tested thank you!
