### ISSUE TITLE
dumpster

### ISSUE THREAD

**Issue by FittedLabs** [overextended/ox_inventory#911]
added ammo(ammo-9, ect ect) to the dumpers and nothing shows in the dumpers after adding new items. i put back the defult items then it starts working

**Comment by Rione21** [comment]
what file name for edit loot dumpster/vehicle?

**Comment by FittedLabs** [comment]
all the small ammo that ix comes  with. ammo-9,45,44,38 ect ect

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/197401424-0dc11424-1b56-4f5a-924f-00e911603a38.png)
Stop wasting my time.

**Comment by FittedLabs** [comment]
you dont have to be rude, just because its working for u its not for me. u
can help me find out why..
