### ISSUE TITLE
consumable dont work

### ISSUE THREAD

**Issue by FittedLabs** [overextended/ox_inventory#912]
my food items dont work and bandages. the items are in the item lua also. the water gets me stuck in animation and other items dont let me pop the inventory back up again, i have to die or f8 to make it work again,

**Comment by FittedLabs** [comment]
or if playing, after while no foods work at all then other days things start to work

**Comment by thelindat** [comment]
Exact same as #913 and just spam nonsense.

**Comment by FittedLabs** [comment]
my consumables dont work. why you very rude and ask me questions or summit
videos
