### ISSUE TITLE
attachments

### ISSUE THREAD

**Issue by FittedLabs** [overextended/ox_inventory#913]
adding a attachment . flashlight spicifly will stop things from happening. i cant punch, open inventory ect

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/197400915-b724c82b-8e68-434b-8f9c-dfd7ef6b5e3d.png)
Works fine.

Considering you're having a number of random issues perhaps you need to consider something _else_ causing it.
I can reproduce the "issue" by removing the web directory from ox_lib, so going to go out on a very short limb and say you ignore the blatant error about the UI not loading.
