### ISSUE TITLE
new export

### ISSUE THREAD

**Issue by TrymTube** [overextended/ox_inventory#920]
I want my policejob to have preconfigured trunk items

I'd like to see a export to add trunk or glovebox items to a vehicle when it is bought.

**Comment by N-fire** [comment]
You already have addItem for that, but you need to open the trunk first to create the inventory.

**Comment by TrymTube** [comment]
addItem doesnt work for me. I've tried but there should be a new export which created the trunk for the inventory

**Comment by iSentrie** [comment]
> you need to open the trunk first
that's the issue, this limits scripting capabilities from adding items on vehicle purchase
