### ISSUE TITLE
Can't use long weapons as passenger in vehicles

### ISSUE THREAD

**Issue by zZOGZz** [overextended/ox_inventory#921]
**Describe the bug**
Trying to use weapons in a helicopter but seems like it doesnt work with the new update 2.14.0 and 2.14.1

**To Reproduce**
1. Spawn a helicopte, buzzard2 for example
2. Make sure you have a long weapon in the inventory, weapon_heavysniper for example
3. Switch to the passenger seat or the back seats
4. Try to take the weapon out
5. See error

**Expected behavior**
In the past version 2.13.2 it worked.

**Comment by thelindat** [comment]
How many times do I need to screenshot myself holding and shooting a firearm from a helicopter?

**Comment by thelindat** [comment]
Congratulations on recording a video of default gta behaviour.

**Comment by N-fire** [comment]
Everything work corectly just like gta
