### ISSUE TITLE
weapon lisense notification translation for 'nil'

### ISSUE THREAD

**Issue by nemaDev** [overextended/ox_inventory#922]
There is a problem with the translation of the gun license notification for example this one, this has happened with the latest update of ox_inventory please if you can check what is happening <3
![image](https://user-images.githubusercontent.com/28969108/197622512-21ac1a72-2611-490b-a8a7-0f1274e89fc4.png)

I don't know if there are more problems similar to this one

**Comment by FAr18** [comment]
Actually, it's a bug of ox_lib, and it's fixed in the new [commit](https://github.com/overextended/ox_lib/commit/03dcf14f7e6abf857fa6370432bce0f2df207a96).

**Comment by nemaDev** [comment]
thanks, it's fixed <3

**Comment by iSentrie** [comment]
close issue then
