### ISSUE TITLE
Open trunk for specific vanilla vehicles

### ISSUE THREAD

**Issue by iSentrie** [overextended/ox_inventory#924]
Trunk (backdoors) doesn't open on these vehicles:
`buritto`
`buritto2`
`buritto3`
`buritto4`
`buritto5`
`gburitto`
`gburitto2`
`boxville`
`boxville2`
`boxville3`
`boxville4`
`boxville5` (no trunk at all)
`pony`
`pony2`
`rumpo`
`rumpo2`
`speedo`
`speedo2`
`speedo4`
`youga`
`youga3`

**Comment by LukeWasTakenn** [comment]
You can set a bone index for them which when you are near will open the trunk

https://github.com/overextended/ox_inventory/blob/main/data/vehicles.lua#L89-L91
