### ISSUE TITLE
Exports to disable or not inventory for player

### ISSUE THREAD

**Issue by Cyril-Beeckman** [overextended/ox_inventory#928]
**Is your feature request related to a problem? Please describe.**
When player is handcuffed for example, he doesn't have to open his inventory

**Describe the solution you'd like**
Add export like 
`exports.ox_inventory:setInventoryDisabled(true)`
`exports.ox_inventory:setInventoryDisabled(false)`

**Describe alternatives you've considered**
Without to modify sources of inventory and rebuild, we can't disallow a player to open inventory

**Comment by thelindat** [comment]
```lua
LocalPlayer.state.invBusy = true
```
