### ISSUE TITLE
Weapons bug

### ISSUE THREAD

**Issue by syn1xx** [overextended/ox_inventory#933]
when I take a weapon out of inventory it automatically saves instantly

Video: https://streamable.com/otws7m
this happens to all players

**Comment by thelindat** [comment]
when I take a weapon out of inventory it automatically is in my hand

**Comment by syn1xx** [comment]
> when I take a weapon out of inventory it automatically is in my hand

not for me

**Comment by thelindat** [comment]
> when I take a weapon out of inventory it automatically saves instantly
> 
> Video: https://streamable.com/otws7m this happens to all players

not for me

**Comment by paiyaa** [comment]
Hey, thelindat… kindly look into these videos..

https://youtu.be/iFlYHuuKxKs

https://youtu.be/Uyl7q3lPfYo

Plz read the description too
