### ISSUE TITLE
Holster automatically during firing a weapon

### ISSUE THREAD

**Issue by karthik-pitchai03** [overextended/ox_inventory#936]
**Describe the bug**
While shooting any weapon it automatically get holstered and need to take weapon again to shoot

**To Reproduce**
1. Fire using ap-pistol
2. Fire continuously 
3. Weapon holsters
4. No error on both server and client

**Expected behavior**
Weapons should not holster while continuous firing, Like we have a median of 140 players it happens to everyone please have a look into it 

**Screenshots**
Video Proof
https://www.youtube.com/watch?v=Uyl7q3lPfYo&ab_channel=TEST
https://www.youtube.com/watch?v=iFlYHuuKxKs&ab_channel=TEST

**Comment by jpetriejr** [comment]
I've encountered this as well just playing by myself.  My configuration has reloading set to manual reload, but it seems to happen when you run out of ammo, but not every time.

**Comment by thelindat** [comment]
You experience it, so you can go ahead and fix it; because this "issue" is default GTA behaviour and both my own workaround and the more-recent cfx native stop it.
