### ISSUE TITLE
on qb the ox inventory is not working because of one problem

### ISSUE THREAD

**Issue by Jackpoter135** [overextended/ox_inventory#937]
======================================================================
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:279: attempt to perform arithmetic on a nil value (field 'count')
======================================================================
[ script:ox_inventory] > SlotWeight (@ox_inventory/modules/inventory/server.lua:279)
[ script:ox_inventory] > setPlayerInventory (@ox_inventory/server.lua:43)
[ script:ox_inventory] > setupPlayer (@ox_inventory/modules/bridge/qb/server.lua:46)
[ script:ox_inventory] > fn (@ox_inventory/modules/bridge/qb/server.lua:97)
[ script:ox_inventory] > <unknown> (@oxmysql/dist/build.js:22440)
[ script:ox_inventory] > processTicksAndRejections (node:internal/process/task_queues:96)
[ script:ox_inventory] > async rawExecute (@oxmysql/dist/build.js:22393)
======================================================================

**Comment by thelindat** [comment]
You didn't convert your inventory data.
