### ISSUE TITLE
Vending machine doesn't work

### ISSUE THREAD

**Issue by Azakyel** [overextended/ox_inventory#943]
i can't tell why, but when i want to buy something in a vending machine, nothing happen. i can't open the machine inventory, same for all props .. and no error in console

**Comment by thelindat** [comment]
Are you using a targeting resource?

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/200497529-6ae96fa8-8124-4a3c-bbda-77d01030eaa7.png)
Confirmed working..
