### ISSUE TITLE
Improvement needs for items

### ISSUE THREAD

**Issue by 442516** [overextended/ox_inventory#947]
I would like to say why can't I improve on the item customization I personally think that I can add a table called OXitem in the database because I find the inventory customization items too cumbersome and too cumbersome. Why can't I customize everything in the database? I think this can be improved. Because you can fully integrate into the database to complete. Include weight. You will definitely ask me what to do with the original item table? In fact, you can choose to use it, or you can choose not to. I know this will go through a lot of changes. But I also want to make this change, I personally think it is very easy and saves things. Every time I customize an item it takes a long time. Hope to see my suggestion, thank you.I think it's good for everyone to be able to customize items more easily

**Comment by thelindat** [comment]
> Why can't I customize everything in the database?

Many items include data that can't be represented in a database or JSON format, functions being the most obvious. Using a database would also require a lot more data to be sent over a net event (enough to block the network thread, in some cases) when setting up the inventory.
