### ISSUE TITLE
Cant open peoples inventory

### ISSUE THREAD

**Issue by FuZZED105** [overextended/ox_inventory#948]
**Describe the bug**
When doing /viewinv, the inventory will open for a second the close, when I try and open it, I get a notification saying the inventory is not available.

**To Reproduce**
1. Do /viewinv [Player ID]

**Expected behavior**
It should have opened the players inventory

**Comment by thelindat** [comment]
Just ran /viewinv and it works fine.
![image](https://user-images.githubusercontent.com/65407488/201519186-7669c64c-8101-4afd-9996-a5009f1683d3.png)
