### ISSUE TITLE
Some Stash or Shop bug since last update

### ISSUE THREAD

**Issue by frazz1234** [overextended/ox_inventory#949]
**Describe the bug**
Its like the stash or the shop is busy and can<t open. No error F8
I didnt change my data since 3 month and everhting working well. 
since last update 2.15.0, got this bug. 

**To Reproduce**

https://www.youtube.com/watch?v=nLnNc7ilEx8

**Expected behavior**
(https://www.youtube.com/watch?v=nLnNc7ilEx8)

**Screenshots**

https://www.youtube.com/watch?v=nLnNc7ilEx8

**Additional context**

https://www.youtube.com/watch?v=nLnNc7ilEx8

**Comment by thelindat** [comment]
Videos aren't "steps to reproduce" and adding the same link to _every single section_ really tempts me to just close this without saying a word.
