### ISSUE TITLE
ox_inventory qbcore

### ISSUE THREAD

**Issue by cummins24v2** [overextended/ox_inventory#951]
i tried to use ox inventory and i couldnt get it to work i want to revert back to my old inventory and now it wont work after i done convertinvertory qb

**Comment by thelindat** [comment]
> i tried to use ox inventory and i couldnt get it to work

Ok.

> i want to revert back to my old inventory and now it wont work after i done convertinvertory qb

Did you not think about backing up your data and/or using a test server?

**Comment by cummins24v2** [comment]
so there not a way to revert i didnt think it was gonna mess up my old inventory

**Comment by thelindat** [comment]
> so there not a way to revert i didnt think it was gonna mess up my old inventory

qb support is still experimental and untested in every conceivable way. Issues with _conversion_ were only just resolved and there's still many other things that need to be looked into.

I can't be held responsible if you tried to set this stuff up on a live server / database and something went wrong; that's what development servers are for. And no, there's no "conversion reversion".
