### ISSUE TITLE
Ox inventory convert with existing data

### ISSUE THREAD

**Issue by SKITTLE6969** [overextended/ox_inventory#954]
Im trying to convert an existing database to ox inventory and getting this error any idea why?

![image](https://user-images.githubusercontent.com/92496158/201024530-630a896d-264c-446e-9528-c6e721286891.png)

**Comment by thelindat** [comment]
> any idea why?

No, because I don't use qb, I don't have a database filled with random potentially broken/invalid data (thanks to qb's awful db structure), and I don't particularly want to acquire and debug this issue.

**Comment by SKITTLE6969** [comment]
I'm trying to integrate a existing DB to QBOX actually not a QB-Core 
not a qb fan after all

**Comment by thelindat** [comment]
Still the same thing and not something for me to fix, but rather a qb(ox) user.

**Comment by SKITTLE6969** [comment]
aite noted thanks for your time ;)

**Comment by thelindat** [comment]
@SKITTLE6969 Copy over the new contents of convert.lua and try again.

**Comment by SKITTLE6969** [comment]
> @SKITTLE6969 Copy over the new contents of convert.lua and try again.

Bruhh working smooth af!!! Arigathoooooooo nyaa :D
