### ISSUE TITLE
Datadog log and evidence log

### ISSUE THREAD

**Issue by akiilles05** [overextended/ox_inventory#962]
Hi!
I have a problem when I go to logs option not showing logging information in datadog website. 
And how to logging police evidence in discord?

**Comment by akiilles05** [comment]
![image](https://user-images.githubusercontent.com/112715362/201462921-016378a4-b6e0-4e84-bf88-7115437db8f3.png)

**Comment by thelindat** [comment]
Set the api key and datadog server convars, perform an action that sends a log; it'll start showing logs instead of that setup page.

> in discord?

you don't
