### ISSUE TITLE
pcall function error

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_inventory#963]
**Describe the bug**
An error outputs when you don't have `consume = 0` on items apparently? As you can read in the thread [here](https://discord.com/channels/813030955598086174/1037631310627348580/1037631310627348580). 

**To Reproduce**
1. Use an item that has no `consume = 0`
2. The error will output.

**Expected behavior**
I'm not sure, but it says it's nil for money, etc. or anything without the `consume = 0`? Does everything need it now?

**Screenshots**
```lua
[  script:es_extended] SCRIPT ERROR: @es_extended/server/functions.lua:252: attempt to index a nil value (field 'Items')
[  script:es_extended] > ref (@es_extended/server/functions.lua:252)
[  script:es_extended] > [global chunk] (@ox_inventory/server.lua:254)
[  script:es_extended] > handler (@ox_lib/callback/server.lua:75)
```

**Additional context**
Latest version 2.16.2.

**Comment by thelindat** [comment]
I'm _soooo_ glad I bothered writing this comment for people to ignore.
https://github.com/overextended/ox_inventory/blob/main/server.lua#L248-L254
