### ISSUE TITLE
problem with the inventory in qb server

### ISSUE THREAD

**Issue by Jackpoter136** [overextended/ox_inventory#965]
Hello can someone help me i just setup my qb server and then when i put the latest version of the inventory in my qb server it shows me error and the inventory is not working 

Here is the error:
![Екранна снимка (211)](https://user-images.githubusercontent.com/117999118/201489398-f6198203-6c1f-404d-b8da-ad3f4baa36f1.png)

Here is my config.cfg
![Екранна снимка (213)](https://user-images.githubusercontent.com/117999118/201489402-462f914e-017a-414f-89e9-373735cd6953.png)

This is new version of qb made by my txadmin by default and the only change that i make was putting the ox inventory and delete the qb-inventory (default qb inventory)

**Comment by thelindat** [comment]
@Jackpoter136 Can you send me the contents of your player's inventory column (from MySQL)?
Seems something weird is happening during auto-conversion.

**Comment by Jackpoter136** [comment]
ok

**Comment by Jackpoter136** [comment]
![Екранна снимка (216)](https://user-images.githubusercontent.com/117999118/201658566-674d9f32-4b50-40d6-a09f-c5ce1e8fe407.png)
is that it?

**Comment by thelindat** [comment]
No, you need to copy the inventory column from the players column. And I do mean _copy_, not screenshot.

**Comment by Jackpoter136** [comment]
k

**Comment by Jackpoter136** [comment]
(89, 'WRW30617', 1, 'license:2b464d37733ca4718b2ba440c0a03702e0d5edbe', 'TheNightMareBg', '{"cash":500,"crypto":0,"bank":5140}', '{"backstory":"A a","lastname":"N","gender":0,"cid":1,"nationality":"Bulgaria","account":"US01QBCore4919316285","firstname":"N","phone":"8146582414","birthdate":"01/11/00"}', '{"grade":{"name":"Freelancer","level":0},"name":"unemployed","label":"Civilian","isboss":false,"payment":10,"type":"none","onduty":true}', '{"grade":{"name":"none","level":0},"isboss":false,"name":"none","label":"No Gang Affiliaton"}', '{"x":457.71429443359377,"y":-997.068115234375,"z":31.6556396484375}', '{"attachmentcraftingrep":0,"criminalrecord":{"hasRecord":false},"ishandcuffed":false,"thirst":54.40000000000003,"bloodtype":"AB+","callsign":"NO CALLSIGN","phonedata":{"InstalledApps":[],"SerialNumber":37600224},"isdead":false,"licences":{"driver":true,"business":false,"weapon":false},"hunger":49.59999999999996,"jobrep":{"hotdog":0,"taxi":0,"trucker":0,"tow":0},"stress":0,"tracker":false,"fitbit":[],"inlaststand":true,"injail":0,"commandbinds":[],"walletid":"QB-52148486","jailitems":[],"status":[],"inside":{"apartment":[]},"dealerrep":0,"craftingrep":0,"phone":[],"armor":0,"fingerprint":"Yc049g97Joh2055"}', '[{"amount":1,"name":"id_card","info":{"firstname":"N","lastname":"N","nationality":"Bulgaria","birthdate":"01/11/00","citizenid":"WRW30617","gender":0},"type":"item","slot":1},{"amount":1,"name":"phone","info":[],"type":"item","slot":2},{"amount":1,"name":"driver_license","info":{"firstname":"N","type":"Class C Driver License","lastname":"N","birthdate":"01/11/00"},"type":"item","slot":3},{"amount":1,"name":"weapon_snowball","info":{"quality":100,"serie":"03lRu4ka331fwUw"},"type":"weapon","slot":4},{"amount":1,"name":"weapon_sniperrifle","info":{"serie":"15RPt2cr351IwQV","quality":100,"ammo":0},"type":"weapon","slot":5},{"amount":1,"name":"weapon_snowball","info":{"quality":100,"serie":"05ITe9dd152xQWJ"},"type":"weapon","slot":6}]', '2022-11-14 12:17:48');

**Comment by Jackpoter136** [comment]
here the file from my data

**Comment by Jackpoter136** [comment]
here from my players data
[players.zip](https://github.com/overextended/ox_inventory/files/10002904/players.zip)

**Comment by Jackpoter136** [comment]
if you wan't you can try make new qb default server from the txadmin on localhost and will show you the same error that happened to me

**Comment by Jackpoter136** [comment]
so when someone make a new qb server you have default inventory right?
so when the player join the server and use the default inventory and then close his server to replace with the ox inventory the same error is showing

**Comment by Jackpoter136** [comment]
idk why this is happening but the inventory is fixed if you delete the players data if you where using others inventorys before

**Comment by thelindat** [comment]
Just replace `modules/bridge/qb/server.lua` with this.

https://raw.githubusercontent.com/overextended/ox_inventory/main/modules/bridge/qb/server.lua
