### ISSUE TITLE
In the parameter of AddTextEntry, entry key does not support all languages.

### ISSUE THREAD

**Issue by FAr18** [overextended/ox_inventory#970]
As the title states, using a localized string as an `entry key` will cause some locales blip name empty.

`AddTextEntry(entryKey --[[ string ]], entryText --[[ string ]])`

**Comment by FAr18** [comment]
Sorry I can't describe the problem well with my poor English.

First, my main problem is that the parameter `entryKey` of `AddTextEntry` can only use Latin letters and some symbols. When `entryKey` contains non-Latin letters(such as Chinese, Korean, Russian), it cannot be parsed/converted correctly.
Second, this also happens with the blip name of the shop.

**Comment by dingyu1126** [comment]
yep，me too ,didn't show Chinese name

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/commit/c29ef9a16f357c740f7e66a4d6a2154fc1b5457e

I could only get Latin and Cyrillic characters to display for the label; could just be version differences though - let me know.

**Comment by dingyu1126** [comment]
> Tested and it works great. I can display Chinese correctly. also tested some settings and found no other issues.

but how do u do this? my shop blip name always empty
