### ISSUE TITLE
Change inventory interaction key.

### ISSUE THREAD

**Issue by Br4inFish** [overextended/ox_inventory#973]
Hey!

I've tried to change the inventory key From F1 to K for example.
But it doesn't work, since the K is used to open /trunk.

Is there a way to only use K & TAB  for inventory and not F1 ?

**Comment by N-fire** [comment]
No why do you think there is multiple key bind, maybe because they do different thing.

**Comment by Br4inFish** [comment]
> No why do you think there is multiple key bind, maybe because they do different thing.

Simple question, thanks for replyin jeez
