### ISSUE TITLE
Disable short bindkeys 1-5

### ISSUE THREAD

**Issue by xDredar** [overextended/ox_inventory#974]
How to disable the short binds, only temporary?
I have try it with
https://overextended.github.io/docs/ox_inventory/Functions/Client/Utils/weaponWheel/
but it works only for weapons and not for items.
Exist a export where you can turn it off and on?

**Comment by N-fire** [comment]
You can set the statebag invBusy to true but this will disable the whole inventory.
May I suggest you to ask in the discord next time.

**Comment by xDredar** [comment]
I cant join the Discord.
The link from the Overextended website are invalid.

**Comment by N-fire** [comment]
You've probably got banned by warden, you should make an appeal on their discord
