### ISSUE TITLE
Items bugs  when add items in items.lua

### ISSUE THREAD

**Issue by DemirYaman** [overextended/ox_inventory#978]
**Describe the bug**
we have a problem , when we want to load an item on SQL and then we want to restart the Sever, the following is the problem: at items.lua is loaded the new item but the old item what were already loaded comes no comma added and at the last item of the new item from SQL also comes a comma added, but actually that should be just gone

**To Reproduce**
0. insert items in sql 
1. Go to 'items.lua'
2. Scroll down to last item,
4. you can see comma added and have to not added

**Expected behavior**
Each item in the table should be followed by a comma, and the last item should not have a comma because it causes an error.
**Screenshots**
![image](https://user-images.githubusercontent.com/118282761/202824975-de79a7b5-88b8-4e92-805f-68b6253e63b4.png)

**Additional context**
no other context

**Comment by thelindat** [comment]
> Each item in the table should be followed by a comma

yes

> the last item should not have a comma because it causes an error

no
