### ISSUE TITLE
QTarget / Target selection (2.17.1)

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_inventory#979]
**Describe the bug**
If you don't have `ox_target` and using `qtarget` the crafting bench does not work, returns an error.

**To Reproduce**
1. Don't use `ox_target`.
2. Attempt to start the resource (says targeting is false).
> targeting resource is not loaded - it should start before ox_inventory
3. Crafting bench returns an error on client because it attempts to use the export.

**Expected behavior**
Ability to use qtarget (even though it's not _recommended_), and targeting properly.

**Screenshots**
None.

**Additional context**
https://github.com/overextended/ox_inventory/blob/45ad082c33856c358dc769c320db83030ed4bec8/modules/init.lua#L138-L148

**Possible solution**
Not sure if this is the proper way you want it done, but this way works.
```lua
if shared.target then
	local ox_target = GetResourceState('ox_target')
	local qtarget = GetResourceState('qtarget')

	if not ox_target:find('start') and not qtarget:find('start') then
		shared.target = false
		return shared.warning('targeting resource is not loaded - it should start before ox_inventory')
	end

	shared.target = ox_target ~= 'missing' and 'ox_target' or 'qtarget'
end
```

**Comment by thelindat** [comment]
> returns an error on client because it attempts to use the export

and yet no error has been shared

**Comment by PoorLatency** [comment]
> > returns an error on client because it attempts to use the export
> 
> and yet no error has been shared

My fault..
![Error](https://i.imgur.com/jc6HcZQ.png)

**Comment by thelindat** [comment]
```lua
if shared.target then
	local ox_target = GetResourceState('ox_target'):find('start')
	local qtarget = GetResourceState('qtarget'):find('start')

	if not ox_target and not qtarget then
		shared.target = false
		return shared.warning('targeting resource is not loaded - it should start before ox_inventory')
	end

	shared.target = ox_target and 'ox_target' or 'qtarget'
end
```

**Comment by PoorLatency** [comment]
That works, thanks kind sir. 🤠
