### ISSUE TITLE
INVENTORY DOSEN'T WORK IF I PUT OX TARGET

### ISSUE THREAD

**Issue by hasidu** [overextended/ox_inventory#980]
**Describe the bug**
After i installed inventory v2.17.0 and for the target system i select ox_target 
the inventory doesn't work it give me this error

if turn off ox_target and turn on qtarget the inventory work fine

**Screenshots**
![Immagine 2022-11-19 012953](https://user-images.githubusercontent.com/72035642/202828974-cdae002d-af0d-4130-b65c-6f050a1134fd.png)

**Comment by hasidu** [comment]
Anyone ?

**Comment by thelindat** [comment]
_You_ added a shop that doesn't have the proper fields.

**Comment by hasidu** [comment]
Fixed issue thank you
