### ISSUE TITLE
Crafting (qtarget)

### ISSUE THREAD

**Issue by PoorLatency** [overextended/ox_inventory#981]
**Describe the bug**
When you press `E` in the crafting area with qtarget (not ox) it returns an error.

**To Reproduce**
1. Enable qtarget (not ox_target, know its not recommended).
2. Press `E` in the crafting point.
3. It will say the inventory isn't accessible.

**Expected behavior**
The mastermind crafting bench should open.

**Additional context**
```lua
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/crafting/server.lua:57: attempt to index a boolean value (local 'inv')
[ script:ox_inventory] > callbackResponse (@ox_lib/callback/server.lua:59)
[ script:ox_inventory] > handler (@ox_lib/callback/server.lua:75)
[ script:ox_inventory] 
```

**Comment by thelindat** [comment]
> It will say the inventory isn't accessible.

no

`SCRIPT ERROR: @ox_inventory/modules/crafting/server.lua:57: attempt to index a boolean value (local 'inv')`

The player's inventory is open but apparently the target inventory is invalid; an actual repro for this would be nice. And do keep in mind that having qtarget, for crafting, is the same as having targeting disabled - and it opens _just fine_ on my end.

**Comment by PoorLatency** [comment]
Well, it says the inventory isn't accessible even `/viewinv [id]` doesn't work either on version `2.17.2`.

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/202833451-327c424e-1a65-4756-9c11-c80453140b6e.png)

**Comment by PoorLatency** [comment]
What happened was I closed a store, then tried to use the crafting.

**Comment by sfxcustoms** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/77953089/202845620-e7cd1030-bcd1-49e3-bbcf-7906899a6c58.png)

**Comment by DyroS3** [comment]
> 

yep me too

**Comment by thelindat** [comment]
Presumably resolved.
