### ISSUE TITLE
NUI error, item data undefined

### ISSUE THREAD

**Issue by Steviol** [overextended/ox_inventory#986]
**Describe the bug**
Inventory stuck, all picture gone and cannot using/give all item and NUI error for all script because of this (need re-login to fix this), random triggered when someone is too long in the server

**Screenshots**
![image](https://user-images.githubusercontent.com/29462114/203138591-3ecdf056-93c7-487d-8eec-26880b391337.png)
![image](https://user-images.githubusercontent.com/29462114/203138615-cef95307-8776-410f-b1f6-f920ede0317d.png)
![image](https://user-images.githubusercontent.com/29462114/203140474-3798c2c6-80dd-42f8-bf27-5bc09042b185.png)

**Comment by thelindat** [comment]
Does that mean you found the cause or what

**Comment by Steviol** [comment]
> Does that mean you found the cause or what

i thought it was because of the inventory script, but it wasn't because all the nui were showing together at the time of this error
here is the main problem
https://github.com/citizenfx/fivem/issues/1711
