### ISSUE TITLE
Error i can't open trunk random vehicle

### ISSUE THREAD

**Issue by Shadyyy1** [overextended/ox_inventory#987]
[]()
![image](https://user-images.githubusercontent.com/118849857/203402795-5113345a-568c-42d1-ada5-4ea8d02a3b28.png)

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/204647436-f0c5ea96-8789-4d10-a7ab-bd3a237103ec.png)

4 months, neat.
