### ISSUE TITLE
SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:1728: attempt to index a nil value (local 'data')

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_inventory#990]
since the update to the latest version we have this problem 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/35350615/203657067-7aa199f0-e3bd-4b3a-ace6-a740d5f9a20a.png">

**Comment by thelindat** [comment]
https://github.com/overextended/ox_inventory/blob/main/modules/inventory/server.lua#L1728

Would mean somebody is trying to give an item from a slot that's empty.
