### ISSUE TITLE
"UNDEFINED" Item Interactions

### ISSUE THREAD

**Issue by Unavarage** [overextended/ox_inventory#993]
After using any item an "UNDEFINED" text shows up on the top of the consumed item

**To Reproduce**
1. Go to 'Your Inventory'
2. Click on 'Any food'
3. See error

**Expected behavior**
I would expect to have some text like used or deleted
(These are the actions that gets described as "UNDEFINED")
https://prnt.sc/1RJcgPS9ZiAu

**Screenshots**
https://prnt.sc/lbNref6xcK8S

**Comment by thelindat** [comment]
Either locales aren’t loaded or it’s referencing the wrong variable. If you built it yourself previously then you need to do so again.

**Comment by Unavarage** [comment]
> Either locales aren’t loaded or it’s referencing the wrong variable. If you built it yourself previously then you need to do so again.

Actually it's a clean install of the latest version, I don't know I specified only in server.cfg to setr ox:locales"hu", it is possibile that I don't know where to write "setr ox:locale" as the documentation says. Could you help me?

**Comment by Naomi-Kali** [comment]
Hey Problem fixed "added" -> "ui_added"

**Comment by Unavarage** [comment]
I already set it to ui_added :/
https://prnt.sc/DV8NF2cYpai1

**Comment by Unavarage** [comment]
> Hey Problem fixed "added" -> "ui_added"

I already set it to ui_added :/
https://prnt.sc/DV8NF2cYpai1

**Comment by Unavarage** [comment]
> Hey Problem fixed "added" -> "ui_added"

Thanks for the help I found it, so whenever it gets an update I need to manually change the locales so it will continue to work, hope they fix-it later on so I don't need to rewrite it or somebody else for their language.

**Comment by Naomi-Kali** [comment]
> > Hey Problem fixed "added" -> "ui_added"
> 
> Thanks for the help I found it, so whenever it gets an update I need to manually change the locales so it will continue to work, hope they fix-it later on so I don't need to rewrite it or somebody else for their language.

Semmi probléma ezért vagyunk itt! ;)
