### ISSUE TITLE
Item data is undefined (CEF crash / memory leak)

### ISSUE THREAD

**Issue by ProjectRogueRP** [overextended/ox_inventory#995]
**Describe the bug**
Im getting a global issue reported by players where they are reporting that they are randomly just getting their inventory scuffed. No errros, no nothing. Just breaks. The images disappear, they cant use or do anything with their inventory. They simply just disconnect and then it fixes it. Any issues what could be causing this issue? Randomly started happening around the time the crafting was introduced? I also asked a couple other server owners, and they said they were experiencing this as well, using ox_inventory. Im just baffled that I dont see any forum post about this yet, as its been happening for a bit now. Any ideas, recommendations, or even right directions to test, im willing to do them! Thanks guys

PLAYERS REPORT:
“whenever i hang out in the city for a few hours my inventory just turns into this and doesnt let me use any items or interact with anything in the city as soon as i see this. if i dont open my inventory i can still use the "front pockets" and interact with things around the city but as soon as i open it and see this its done. There is no clear indicator on when it happens other than opening them and seeing this”. 
![problem22](https://user-images.githubusercontent.com/83529694/204153099-8999fddd-5f3a-4927-bed4-f192809a1db7.png)

**To Reproduce**
Im unsure, but was asked by Luke to open this on github!

**Expected behavior**
For it not break while they are playing

**Screenshots**
![problem22](https://user-images.githubusercontent.com/83529694/204153091-5c288447-ff63-4422-8ea1-546ae3da6fba.png)

**Comment by ProjectRogueRP** [comment]
@LukeWasTakenn

**Comment by fivemservergg** [comment]
I have the same problem, is there a way to solve it?
Other scripts related to the UI will also have problems when the inventory is reset.

**Comment by Smailas01** [comment]
I have same problem any fixs ?

**Comment by thelindat** [comment]
> I have same problem any fixs ?

> but so far people have reported that xsound is causing a memory leak or something.

![image](https://user-images.githubusercontent.com/65407488/204964566-5e8db60b-0dba-4281-8510-914dc9d7147e.png)
![image](https://user-images.githubusercontent.com/65407488/204964593-b2eca6c0-2500-467e-875d-3bba814b1c9f.png)
![image](https://user-images.githubusercontent.com/65407488/204964732-43c21e3c-d32f-44bc-9e81-825d7d20cc88.png)
![image](https://user-images.githubusercontent.com/65407488/204964812-a2d62583-2737-4f27-8fd1-ae8feb572899.png)
![image](https://user-images.githubusercontent.com/65407488/204964789-94c8521e-dd94-49a8-9fd7-561a148027e9.png)

https://github.com/overextended/ox_inventory/issues/986

**Comment by ProjectRogueRP** [comment]
Hi there. So in more testing, I was hoping xsound was going to be the issue breaker! However, I have disabled all scripts using xsound along with the xsound resource, and the UI is still crashing! I just figured I would give the report that its still happening, even without xsound! So my only thought now, is that it has be the inventory or a FiveM Update messed something up. Im not sure! 

![image](https://user-images.githubusercontent.com/83529694/205472503-dcbe3040-8d07-4cae-9d24-715aea95dde7.png)

![image](https://user-images.githubusercontent.com/83529694/205472523-83242577-9b19-402a-a74f-6b391c137d3b.png)

![image](https://user-images.githubusercontent.com/83529694/205472533-f5ea9160-1ed8-4552-aec9-a8a4803dd62e.png)

![image](https://user-images.githubusercontent.com/83529694/205472544-9bf4c9e7-d64d-4ab1-984e-63962df8566a.png)

**Comment by thelindat** [comment]
>I have disabled all scripts using xsound along with the xsound resource, and the UI is still crashing! I just figured I would give the report that its still happening, even without xsound!
>  
> ![image](https://user-images.githubusercontent.com/83529694/205472544-9bf4c9e7-d64d-4ab1-984e-63962df8566a.png)

Why is xsound mentioned in the console if it's disabled?

**Comment by ProjectRogueRP** [comment]
I updated xSound. Not a single issue for like 3 days. Today, we are right back to square one, and its happening again. Not sure what to do at this point but just disable xsound all together, which sucks cause thats how we play all our music at our bars, clubs, cars, businesses, etc.
![bug](https://user-images.githubusercontent.com/83529694/206823046-3cb6cf9c-0276-401c-aff8-03546770f3a6.png)

**Comment by thelindat** [comment]
Haven't seen anybody mention this in a month so I'll just assume whatever it was has been resolved elsewhere.

**Comment by thelindat** [comment]
_Apparently_ lb-phone had a memory leak, and three people have reported that updating it resolved this issue.

**Comment by Flek26** [comment]
I have this same issue. We Dont use lb-phone
